### ISSUE TITLE
Install fails when using external storage and commenting data_volume

### ISSUE THREAD

**Issue by hrak** [goharbor/harbor#10260]
**Expected behavior and actual behavior:**
The installation guide states about `data_volume`:

> You can optionally configure external storage, in which case disable this option and enable `storage_service`.

I configured external storage so uncommented `storage_service` and commented `data_volume`. The installer fails with the following error:

```
root@harbor:~/harbor# ./install.sh --with-clair --with-chartmuseum

[Step 0]: checking if docker is installed ...

Note: docker version: 19.03.5

[Step 1]: checking docker-compose is installed ...

Note: docker-compose version: 1.25.0


[Step 2]: preparing environment ...

[Step 3]: preparing harbor configs ...
prepare base dir is set to /root/harbor
Unable to find image 'goharbor/prepare:v1.10.0' locally
v1.10.0: Pulling from goharbor/prepare
b950b5dd94ab: Pull complete
0acfdc1f2dfc: Pull complete
fd741c339942: Pull complete
dc5f326adae3: Pull complete
6c159c23a3a1: Pull complete
d08ec21dd899: Pull complete
245c8635bc17: Pull complete
Digest: sha256:261640c817df8b8a9daa7f88da93bf2b045defdba26ad08720085ea334c62a4e
Status: Downloaded newer image for goharbor/prepare:v1.10.0
Traceback (most recent call last):
  File "main.py", line 72, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 34, in main
    config_dict = parse_yaml_config(conf, with_notary=with_notary, with_clair=with_clair, with_chartmuseum=with_chartmuseum)
  File "/usr/src/app/utils/configs.py", line 183, in parse_yaml_config
    config_dict['data_volume'] = configs['data_volume']
KeyError: 'data_volume'
```

**Steps to reproduce the problem:**
comment out `data_volume` and uncomment/configure `storage_service` and run installer

**Versions:**
Please specify the versions of following systems.

- harbor version: [v1.10.0]
- docker engine version: [19.03.5]
- docker-compose version: [1.25.0]

**Additional context:**

relevant sections of harbor.yml:

```
# The default data volume
data_volume:

# Harbor Storage settings by default is using /data dir on local filesystem
# Uncomment storage_service setting If you want to using external storage
storage_service:
#   # ca_bundle is the path to the custom root ca certificate, which will be injected into the truststore
#   # of registry's and chart repository's containers.  This is usually needed when the user hosts a internal storage with self signed certificate.
#   ca_bundle:

#   # storage backend, default is filesystem, options include filesystem, azure, gcs, s3, swift and oss
#   # for more info about this configuration please refer https://docs.docker.com/registry/configuration/
#   filesystem:
#     maxthreads: 100
#   # set disable to true when you want to disable registry redirect
#   redirect:
#     disabled: false
  s3:
    accesskey: dfsdfds
    secretkey: sdfsdf
    region: default
    regionendpoint: https://cloudstorage.example.com
    bucket: harbor
    encrypt: false
    secure: true
    v4auth: true
    chunksize: 5242880
    rootdirectory: /
```

**Comment by hrak** [comment]
This is mostly a documentation issue, because the data directory is still needed for the database, charts, redis etc. so disabling it is not going to work.

**Comment by reasonerjt** [comment]
@hrak could you give us suggestion wrt how the doc should be updated?  Or write up a PR?

**Comment by cjsanchez** [comment]
I'm running into this issue right now. My harbor configurations for the storage service is essentially the same as @hrak. Does anyone know how to solve this? Currently trying on v1.10.17

**Comment by UmanGarbag** [comment]
I have the same issue, could someone please update the documentation in order to provider usage of storage_service for aws and azure backend ?
