### ISSUE TITLE
Harbor returns 401 with Docker BuildKit 

### ISSUE THREAD

**Issue by eroji** [goharbor/harbor#10386]
I am testing docker build with BuildKit. The Dockerfile is a multi-stage using base images from public repos I have configured in Harbor. The only change I made to the Dockerfile after enabling BuildKit is adding a `RUN --mount-type=cache` so that the Maven build cache can be saved to speed up for later build. Before enabling BuildKit, everything works fine. Docker is able to pull down all the base images needed. However, after enabling BuildKit, the build is failing with Harbor returning 401. Docker also logs the errors are 403s when pulling the base images.

Harbor Core
```
2019/12/31 17:49:09 [D] [server.go:2774] |   10.1.131.206| 401 |   4.089799ms|   match| GET      /v2/   r:/v2/*
2019/12/31 17:49:10 [D] [server.go:2774] |   10.1.131.206| 200 |  24.498045ms|   match| GET      /service/token   r:/service/token
2019/12/31 17:49:10 [D] [server.go:2774] |   10.1.131.206| 200 |   4.120089ms|   match| HEAD     /v2/   r:/v2/*
2019/12/31 17:49:11 [D] [server.go:2774] |    10.1.131.33| 200 |   1.799942ms|   match| GET      /api/ping   r:/api/ping
2019/12/31 17:49:14 [D] [server.go:2774] |   10.1.131.206| 401 |   4.211535ms|   match| GET      /v2/   r:/v2/*
2019/12/31 17:49:14 [D] [server.go:2774] |   10.1.131.206| 200 |  64.820175ms|   match| GET      /service/token   r:/service/token
2019/12/31 17:49:14 [D] [server.go:2774] |   10.1.131.206| 200 |   8.106133ms|   match| GET      /v2/   r:/v2/*
2019/12/31 17:49:15 [D] [server.go:2774] |   10.1.131.206| 401 |    3.63903ms|   match| HEAD     /v2/library/openjdk/manifests/8u232-jre-stretch   r:/v2/*
2019/12/31 17:49:15 [C] [panic.go:522] the request url is  /service/token
2019/12/31 17:49:15 [C] [panic.go:522] Handler crashed with error '_xsrf' argument missing from POST
2019/12/31 17:49:15 [C] [panic.go:522] /usr/local/go/src/runtime/panic.go:522
2019/12/31 17:49:15 [C] [panic.go:522] /harbor/src/vendor/github.com/astaxie/beego/context/context.go:80
2019/12/31 17:49:15 [C] [panic.go:522] /harbor/src/vendor/github.com/astaxie/beego/context/context.go:164
2019/12/31 17:49:15 [C] [panic.go:522] /harbor/src/vendor/github.com/astaxie/beego/controller.go:649
2019/12/31 17:49:15 [C] [panic.go:522] /harbor/src/vendor/github.com/astaxie/beego/router.go:788
2019/12/31 17:49:15 [C] [panic.go:522] /usr/local/go/src/net/http/server.go:2774
2019/12/31 17:49:15 [C] [panic.go:522] /usr/local/go/src/net/http/server.go:1878
2019/12/31 17:49:15 [C] [panic.go:522] /usr/local/go/src/runtime/asm_amd64.s:1337
2019/12/31 17:49:15 [D] [server.go:2774] |   10.1.131.206| 401 |   4.155078ms|   match| HEAD     /v2/library/openjdk/manifests/8u232-jre-stretch   r:/v2/*
2019/12/31 17:49:15 [C] [panic.go:522] the request url is  /service/token
2019/12/31 17:49:15 [C] [panic.go:522] Handler crashed with error '_xsrf' argument missing from POST
2019/12/31 17:49:15 [C] [panic.go:522] /usr/local/go/src/runtime/panic.go:522
2019/12/31 17:49:15 [C] [panic.go:522] /harbor/src/vendor/github.com/astaxie/beego/context/context.go:80
2019/12/31 17:49:15 [C] [panic.go:522] /harbor/src/vendor/github.com/astaxie/beego/context/context.go:164
2019/12/31 17:49:15 [C] [panic.go:522] /harbor/src/vendor/github.com/astaxie/beego/controller.go:649
2019/12/31 17:49:15 [C] [panic.go:522] /harbor/src/vendor/github.com/astaxie/beego/router.go:788
2019/12/31 17:49:15 [C] [panic.go:522] /usr/local/go/src/net/http/server.go:2774
2019/12/31 17:49:15 [C] [panic.go:522] /usr/local/go/src/net/http/server.go:1878
2019/12/31 17:49:15 [C] [panic.go:522] /usr/local/go/src/runtime/asm_amd64.s:1337
```

Docker
```
Dec 31 09:49:16 builder dockerd: time="2019-12-31T09:49:16.003263183-08:00" level=debug msg="new ref for local: ytvwrl2w1h1c2yw1uhonrt54j"
Dec 31 09:49:16 builder dockerd: time="2019-12-31T09:49:16.003755389-08:00" level=debug msg="diffcopy took: 211.995µs"
Dec 31 09:49:16 builder dockerd: time="2019-12-31T17:49:16Z" level=error msg="fatal error: rpc error: code = Unknown desc = failed to build LLB: failed to load cache key: failed to fetch oauth token: unexpected status: 403 Forbidden"
Dec 31 09:49:16 builder dockerd: panic: rpc error: code = Unknown desc = failed to build LLB: failed to load cache key: failed to fetch oauth token: unexpected status: 403 Forbidden
Dec 31 09:49:16 builder dockerd: goroutine 1 [running]:
Dec 31 09:49:16 builder dockerd: main.main()
Dec 31 09:49:16 builder dockerd: /src/frontend/dockerfile/cmd/dockerfile-frontend/main.go:26 +0x34f
Dec 31 09:49:16 builder dockerd: time="2019-12-31T09:49:16.056023409-08:00" level=warning msg="grpc: addrConn.createTransport failed to connect to { 0  <nil>}. Err :connection error: desc = \"transport: Error while dialing only one connection allowed\". Reconnecting..." module=grpc
```

**Comment by stonezdj** [comment]
The _xsrf token was disabled for url /service/token recently.
see https://github.com/goharbor/harbor/issues/10305
