### ISSUE TITLE
Scan job may be panic after upgrading from version less than 1.10

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#10657]
log:

```go
Feb  6 03:32:29 172.24.0.1 jobservice[10088]: 2020-02-06T03:32:29Z [ERROR] [/jobservice/runner/redis.go:89]: Job 'IMAGE_SCAN:48b62e2874a67580cf04ab4f' exit with error: runtime error: interface conversion: interface {} is nil, not string; stack: goroutine 134 [running]:
Feb  6 03:32:29 172.24.0.1 jobservice[10088]: github.com/goharbor/harbor/src/jobservice/runner.(*RedisJob).Run.func2(0xc0002097c8, 0xc0002ff200)
Feb  6 03:32:29 172.24.0.1 jobservice[10088]: #011/harbor/src/jobservice/runner/redis.go:122 +0xb5
Feb  6 03:32:29 172.24.0.1 jobservice[10088]: panic(0x148f8e0, 0xc000395e30)
Feb  6 03:32:29 172.24.0.1 jobservice[10088]: #011/usr/local/go/src/runtime/panic.go:679 +0x1b2
Feb  6 03:32:29 172.24.0.1 jobservice[10088]: github.com/goharbor/harbor/src/pkg/scan.(*Job).Run(0x24425a0, 0x1918ee0, 0xc00015a0f0, 0xc000394cc0, 0xc00015a0f0, 0x0)
Feb  6 03:32:29 172.24.0.1 jobservice[10088]: #011/harbor/src/pkg/scan/job.go:124 +0x7a2
Feb  6 03:32:29 172.24.0.1 jobservice[10088]: github.com/goharbor/harbor/src/jobservice/runner.(*RedisJob).Run(0xc0002fd350, 0xc0002ff200, 0x0, 0x0)
Feb  6 03:32:29 172.24.0.1 jobservice[10088]: #011/harbor/src/jobservice/runner/redis.go:187 +0x96b
Feb  6 03:32:29 172.24.0.1 jobservice[10088]: github.com/goharbor/harbor/src/jobservice/worker/cworker.(*basicWorker).registerJob.func2(0xc0002ff200, 0x241af40, 0xc000209838)
Feb  6 03:32:29 172.24.0.1 jobservice[10088]: #011/harbor/src/jobservice/worker/cworker/c_worker.go:418 +0x34
Feb  6 03:32:29 172.24.0.1 jobservice[10088]: github.com/gocraft/work.runJob.func1(0x165d399, 0x10)
Feb  6 03:32:29 172.24.0.1 jobservice[10088]: #011/harbor/src/vendor/github.com/gocraft/work/run.go:31 +0x513
Feb  6 03:32:29 172.24.0.1 jobservice[10088]: github.com/goharbor/harbor/src/jobservice/worker/cworker.(*workerContext).logJob(0x24425a0, 0xc0002ff200, 0xc00015a050, 0x0, 0x0)
Feb  6 03:32:29 172.24.0.1 jobservice[10088]: #011/harbor/src/jobservice
```
probabely missing auth type

**Comment by steven-zou** [comment]
Based on the influence of this issue (legacy job will be failed, new scan jobs will be ok), it's not a blocked issue.
