### ISSUE TITLE
Sometimes test case for job server failed or timeout.

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#10711]
```
2020-02-12T05:33:37.0095701Z 05:33:37 === RUN TestHookAgentTestSuite/TestRetryAndPopMin
2020-02-12T05:33:37.0106409Z 05:33:37 --- FAIL: TestHookAgentTestSuite (0.02s)
2020-02-12T05:33:37.0118508Z 05:33:37 --- FAIL: TestHookAgentTestSuite/TestEventSending (0.01s)
2020-02-12T05:33:37.0131687Z 05:33:37 suite.go:62: test panicked: runtime error: invalid memory address or nil pointer dereference
2020-02-12T05:33:37.0144761Z 05:33:37 goroutine 8 [running]:
2020-02-12T05:33:37.0177911Z 05:33:37 runtime/debug.Stack(0xc00009b6c8, 0xc43ec0, 0x1222ec0)
2020-02-12T05:33:37.0192325Z 05:33:37 /opt/hostedtoolcache/go/1.13.4/x64/src/runtime/debug/stack.go:24 +0xab
2020-02-12T05:33:37.0247096Z 05:33:37 github.com/goharbor/harbor/src/vendor/github.com/stretchr/testify/suite.failOnPanic(0xc000494000)
2020-02-12T05:33:37.0260842Z 05:33:37 /home/runner/work/harbor/src/github.com/goharbor/harbor/src/vendor/github.com/stretchr/testify/suite/suite.go:62 +0x6a
2020-02-12T05:33:37.0275196Z 05:33:37 panic(0xc43ec0, 0x1222ec0)
2020-02-12T05:33:37.0338868Z 05:33:37 /opt/hostedtoolcache/go/1.13.4/x64/src/runtime/panic.go:679 +0x1b2
2020-02-12T05:33:37.0379019Z 05:33:37 github.com/goharbor/harbor/src/jobservice/hook.(*HookAgentTestSuite).checkStatus(0xc00029a780)
2020-02-12T05:33:37.0397103Z 05:33:37 /home/runner/work/harbor/src/github.com/goharbor/harbor/src/jobservice/hook/hook_agent_test.go:170 +0x3f0
2020-02-12T05:33:37.0409712Z 05:33:37 github.com/goharbor/harbor/src/jobservice/hook.(*HookAgentTestSuite).TestEventSending(0xc00029a780)
2020-02-12T05:33:37.0419408Z 05:33:37 /home/runner/work/harbor/src/github.com/goharbor/harbor/src/jobservice/hook/hook_agent_test.go:132 +0x366
2020-02-12T05:33:37.0429066Z 05:33:37 reflect.Value.call(0xc0003f0d20, 0xc000011710, 0x13, 0xce2609, 0x4, 0xc00009bec0, 0x1, 0x1, 0xc0000fa020, 0x7f7690100860, ...)
2020-02-12T05:33:37.0439542Z 05:33:37 /opt/hostedtoolcache/go/1.13.4/x64/src/reflect/value.go:460 +0x62b
2020-02-12T05:33:37.0450685Z 05:33:37 reflect.Value.Call(0xc0003f0d20, 0xc000011710, 0x13, 0xc00009bec0, 0x1, 0x1, 0xf4, 0x11dbadc, 0x11dbadc)
2020-02-12T05:33:37.0461462Z 05:33:37 /opt/hostedtoolcache/go/1.13.4/x64/src/reflect/value.go:321 +0xd4
2020-02-12T05:33:37.0474326Z 05:33:37 github.com/goharbor/harbor/src/vendor/github.com/stretchr/testify/suite.Run.func2(0xc000494000)
2020-02-12T05:33:37.0486300Z 05:33:37 /home/runner/work/harbor/src/github.com/goharbor/harbor/src/vendor/github.com/stretchr/testify/suite/suite.go:133 +0x324
2020-02-12T05:33:37.0495333Z 05:33:37 testing.tRunner(0xc000494000, 0xc000472000)
2020-02-12T05:33:37.0507027Z 05:33:37 /opt/hostedtoolcache/go/1.13.4/x64/src/testing/testing.go:909 +0x19a
2020-02-12T05:33:37.0518551Z 05:33:37 created by testing.(*T).Run
2020-02-12T05:33:37.0529564Z 05:33:37 /opt/hostedtoolcache/go/1.13.4/x64/src/testing/testing.go:960 +0x652
2020-02-12T05:33:37.0541784Z 05:33:37 --- PASS: TestHookAgentTestSuite/TestEventSendingError (0.00s)
```

```
04:16:28 2020/02/13 04:16:28 Load 1 periodic job policies
04:18:12 coverage: 45.5% of statements in github.com/goharbor/harbor/src/jobservice/worker/cworker, github.com/goharbor/harbor/src/jobservice/common/rds, github.com/goharbor/harbor/src/jobservice/common/utils, github.com/goharbor/harbor/src/jobservice/env, github.com/goharbor/harbor/src/jobservice/errs, github.com/goharbor/harbor/src/jobservice/job, github.com/goharbor/harbor/src/jobservice/lcm, github.com/goharbor/harbor/src/jobservice/logger, github.com/goharbor/harbor/src/jobservice/period, github.com/goharbor/harbor/src/jobservice/runner, github.com/goharbor/harbor/src/jobservice/worker
04:18:12 panic: test timed out after 10m0s
04:18:12
04:18:12 goroutine 55 [running]:
04:18:12 testing.(*M).startAlarm.func1()
04:18:12 /home/travis/.gimme/versions/go1.13.4.linux.amd64/src/testing/testing.go:1377 +0x11c
04:18:12 created by time.goFunc
04:18:12 /home/travis/.gimme/versions/go1.13.4.linux.amd64/src/time/sleep.go:168 +0x52
04:18:12
04:18:12 goroutine 1 [chan receive, 10 minutes]:
04:18:12 testing.(*T).Run(0xc0000d1d00, 0xcf5b35, 0x14, 0xd18900, 0x0)
04:18:12 /home/travis/.gimme/versions/go1.13.4.linux.amd64/src/testing/testing.go:961 +0x68a
04:18:12 testing.runTests.func1(0xc0000d1d00)
04:18:12 /home/travis/.gimme/versions/go1.13.4.linux.amd64/src/testing/testing.go:1202 +0xa7
04:18:12 testing.tRunner(0xc0000d1d00, 0xc000191cd8)
04:18:12 /home/travis/.gimme/versions/go1.13.4.linux.amd64/src/testing/testing.go:909 +0x19a
04:18:12 testing.runTests(0xc0002e3680, 0x123eb00, 0x3, 0x3, 0x0)
04:18:12 /home/travis/.gimme/versions/go1.13.4.linux.amd64/src/testing/testing.go:1200 +0x522
04:18:12 testing.(*M).Run(0xc0002c7700, 0x0)
04:18:12 /home/travis/.gimme/versions/go1.13.4.linux.amd64/src/testing/testing.go:1117 +0x300
04:18:12 main.main()
04:18:12 _testmain.go:212 +0x348
04:18:12
04:18:12 goroutine 7 [chan receive, 10 minutes]:
04:18:12 testing.(*T).Run(0xc0000d1e00, 0xbc72e1, 0xb, 0xc0000dca80, 0xc0000d1e01)
04:18:12 /home/travis/.gimme/versions/go1.13.4.linux.amd64/src/testing/testing.go:961 +0x68a
04:18:12 github.com/goharbor/harbor/src/vendor/github.com/stretchr/testify/suite.runTests(0xdec8e0, 0xc0000d1e00, 0xc0002cb5c0, 0x7, 0x8)
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/stretchr/testify/suite/suite.go:151 +0xe4
04:18:12 github.com/goharbor/harbor/src/vendor/github.com/stretchr/testify/suite.Run(0xc0000d1e00, 0xddf280, 0xc00035a000)
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/stretchr/testify/suite/suite.go:138 +0x68c
04:18:12 github.com/goharbor/harbor/src/jobservice/worker/cworker.TestCWorkerTestSuite(0xc0000d1e00)
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/jobservice/worker/cworker/c_worker_test.go:101 +0x5f
04:18:12 testing.tRunner(0xc0000d1e00, 0xd18900)
04:18:12 /home/travis/.gimme/versions/go1.13.4.linux.amd64/src/testing/testing.go:909 +0x19a
04:18:12 created by testing.(*T).Run
04:18:12 /home/travis/.gimme/versions/go1.13.4.linux.amd64/src/testing/testing.go:960 +0x652
04:18:12
04:18:12 goroutine 23 [select]:
04:18:12 github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*worker).loop(0xc0002cb200)
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/worker.go:106 +0x1ff
04:18:12 created by github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*worker).start
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/worker.go:78 +0x51
04:18:12
04:18:12 goroutine 26 [select]:
04:18:12 github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*worker).loop(0xc0002cb500)
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/worker.go:106 +0x1ff
04:18:12 created by github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*worker).start
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/worker.go:78 +0x51
04:18:12
04:18:12 goroutine 11 [select]:
04:18:12 github.com/goharbor/harbor/src/jobservice/period.(*enqueuer).loop(0xc0001e8300)
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/jobservice/period/enqueuer.go:88 +0x310
04:18:12 created by github.com/goharbor/harbor/src/jobservice/period.(*enqueuer).start
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/jobservice/period/enqueuer.go:71 +0x69
04:18:12
04:18:12 goroutine 12 [chan receive, 10 minutes]:
04:18:12 github.com/goharbor/harbor/src/jobservice/worker/cworker.(*basicWorker).Start.func1(0xc000348310)
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/jobservice/worker/cworker/c_worker.go:142 +0xed
04:18:12 created by github.com/goharbor/harbor/src/jobservice/worker/cworker.(*basicWorker).Start
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/jobservice/worker/cworker/c_worker.go:136 +0x467
04:18:12
04:18:12 goroutine 25 [select]:
04:18:12 github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*observer).loop(0xc0003480e0)
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/observer.go:130 +0x2b8
04:18:12 created by github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*observer).start
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/observer.go:81 +0x4d
04:18:12
04:18:12 goroutine 30 [select]:
04:18:12 github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*worker).loop(0xc0002cb380)
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/worker.go:106 +0x1ff
04:18:12 created by github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*worker).start
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/worker.go:78 +0x51
04:18:12
04:18:12 goroutine 32 [select]:
04:18:12 github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*observer).loop(0xc0003481c0)
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/observer.go:130 +0x2b8
04:18:12 created by github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*observer).start
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/observer.go:81 +0x4d
04:18:12
04:18:12 goroutine 51 [select]:
04:18:12 github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*observer).loop(0xc0003482a0)
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/observer.go:130 +0x2b8
04:18:12 created by github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*observer).start
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/observer.go:81 +0x4d
04:18:12
04:18:12 goroutine 28 [select]:
04:18:12 github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*worker).loop(0xc0002cb2c0)
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/worker.go:106 +0x1ff
04:18:12 created by github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*worker).start
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/worker.go:78 +0x51
04:18:12
04:18:12 goroutine 38 [select]:
04:18:12 github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*workerPoolHeartbeater).loop(0xc0002ae1b0)
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/heartbeater.go:78 +0x169
04:18:12 created by github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*workerPoolHeartbeater).start
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/heartbeater.go:65 +0x4d
04:18:12
04:18:12 goroutine 39 [select]:
04:18:12 github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*requeuer).loop(0xc0001e8a80)
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/requeuer.go:71 +0x1ce
04:18:12 created by github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*requeuer).start
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/requeuer.go:50 +0x4d
04:18:12
04:18:12 goroutine 40 [select]:
04:18:12 github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*requeuer).loop(0xc0001e8c00)
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/requeuer.go:71 +0x1ce
04:18:12 created by github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*requeuer).start
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/requeuer.go:50 +0x4d
04:18:12
04:18:12 goroutine 41 [select, 10 minutes]:
04:18:12 github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*deadPoolReaper).loop(0xc000292a00)
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/dead_pool_reaper.go:57 +0x193
04:18:12 created by github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*deadPoolReaper).start
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/dead_pool_reaper.go:43 +0x4d
04:18:12
04:18:12 goroutine 42 [select]:
04:18:12 github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*periodicEnqueuer).loop(0xc0001e8c60)
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/periodic_enqueuer.go:70 +0x1ca
04:18:12 created by github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*periodicEnqueuer).start
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/periodic_enqueuer.go:49 +0x4d
04:18:12
04:18:12 goroutine 52 [select]:
04:18:12 github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*observer).loop(0xc000348150)
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/observer.go:130 +0x2b8
04:18:12 created by github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*observer).start
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/observer.go:81 +0x4d
04:18:12
04:18:12 goroutine 43 [select, 5 minutes]:
04:18:12 github.com/goharbor/harbor/src/jobservice/worker/cworker.(*reaper).start.func1(0xc000292320)
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/jobservice/worker/cworker/reaper.go:59 +0x2ce
04:18:12 created by github.com/goharbor/harbor/src/jobservice/worker/cworker.(*reaper).start
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/jobservice/worker/cworker/reaper.go:51 +0x69
04:18:12
04:18:12 goroutine 53 [select]:
04:18:12 github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*observer).loop(0xc000348230)
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/observer.go:130 +0x2b8
04:18:12 created by github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*observer).start
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/observer.go:81 +0x4d
04:18:12
04:18:12 goroutine 33 [select]:
04:18:12 github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*worker).loop(0xc0002cb440)
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/worker.go:106 +0x1ff
04:18:12 created by github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*worker).start
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/worker.go:78 +0x51
04:18:12
04:18:12 goroutine 69 [select]:
04:18:12 github.com/goharbor/harbor/src/jobservice/worker/cworker.(*CWorkerTestSuite).TestStopJob(0xc00035a000)
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/jobservice/worker/cworker/c_worker_test.go:196 +0x492
04:18:12 reflect.Value.call(0xc000444fc0, 0xc0000100f0, 0x13, 0xcecfca, 0x4, 0xc000067ec0, 0x1, 0x1, 0xc000118250, 0xc000118250, ...)
04:18:12 /home/travis/.gimme/versions/go1.13.4.linux.amd64/src/reflect/value.go:460 +0x62b
04:18:12 reflect.Value.Call(0xc000444fc0, 0xc0000100f0, 0x13, 0xc000067ec0, 0x1, 0x1, 0xf4, 0x11ee605, 0x11ee605)
04:18:12 /home/travis/.gimme/versions/go1.13.4.linux.amd64/src/reflect/value.go:321 +0xd4
04:18:12 github.com/goharbor/harbor/src/vendor/github.com/stretchr/testify/suite.Run.func2(0xc00036e800)
04:18:12 /home/travis/gopath/src/github.com/goharbor/harbor/src/vendor/github.com/stretchr/testify/suite/suite.go:133 +0x324
04:18:12 testing.tRunner(0xc00036e800, 0xc0000dca80)
04:18:12 /home/travis/.gimme/versions/go1.13.4.linux.amd64/src/testing/testing.go:909 +0x19a
04:18:12 created by testing.(*T).Run
04:18:12 /home/travis/.gimme/versions/go1.13.4.linux.amd64/src/testing/testing.go:960 +0x652
04:18:12 FAIL github.com/goharbor/harbor/src/jobservice/worker/cworker 600.039s
04:18:12 FAIL
```

**Comment by renmaosheng** [comment]
Weiwei, is this specific for 2.0 or previous release as well? thanks.

**Comment by heww** [comment]
> Weiwei, is this specific for 2.0 or previous release as well? thanks.

These problems only happend sometimes, I have the impression that the timeout problem also happend before but not always happend.

**Comment by steven-zou** [comment]
One more:
```
2020-02-26T08:49:29.5653996Z 08:49:29 === RUN TestCWorkerTestSuite
2020-02-26T08:49:29.5688951Z 08:49:29 2020-02-26T08:49:29Z [INFO] [/github.com/goharbor/harbor/src/common/dao/testutils.go:72]: POSTGRES_HOST: 10.1.0.4, POSTGRES_USR: postgres, POSTGRES_PORT: 5432, POSTGRES_PWD: root123
2020-02-26T08:49:29.5689935Z 08:49:29 2020-02-26T08:49:29Z [INFO] [/github.com/goharbor/harbor/src/common/dao/testutils.go:82]: initializing database: type-PostgreSQL host-10.1.0.4 port-5432 databse-registry sslmode-"disable"
2020-02-26T08:49:29.5776689Z 08:49:29 2020-02-26T08:49:29Z [INFO] [/github.com/goharbor/harbor/src/common/dao/pgsql.go:119]: Upgrading schema for pgsql ...
2020-02-26T08:49:29.5799965Z 08:49:29 2020-02-26T08:49:29Z [INFO] [/github.com/goharbor/harbor/src/common/dao/pgsql.go:122]: No change in schema, skip.
2020-02-26T08:49:29.5815132Z 08:49:29 2020/02/26 08:49:29 Register job *cworker.fakeJob with name fake_job
2020-02-26T08:49:29.5827754Z 08:49:29 2020/02/26 08:49:29 Register job *cworker.fakeLongRunJob with name fake_long_run_job
2020-02-26T08:49:29.5864029Z 08:49:29 2020/02/26 08:49:29 Scheduler: periodic enqueuer is started
2020-02-26T08:49:29.5880037Z 08:49:29 2020/02/26 08:49:29 Load 0 periodic job policies
2020-02-26T08:49:29.5919795Z 08:49:29 2020/02/26 08:49:29 Basic worker is started
2020-02-26T08:49:29.5948833Z 08:49:29 2020/02/26 08:49:29 Reaper is started
2020-02-26T08:49:29.5972618Z 08:49:29 === RUN TestCWorkerTestSuite/TestEnqueueJob
2020-02-26T08:49:29.6041744Z 08:49:29 === RUN TestCWorkerTestSuite/TestEnqueuePeriodicJob
2020-02-26T08:49:30.4216851Z 08:49:29 2020/02/26 08:49:29 Scheduled execution for periodic job fake_job:22f9b8a22c0a07b94b51a397 at 1582707070
2020-02-26T08:49:30.4217823Z 08:49:29 === RUN TestCWorkerTestSuite/TestEnqueueUniqueJob
2020-02-26T08:49:30.4217993Z 08:49:29 === RUN TestCWorkerTestSuite/TestRegisterJobs
2020-02-26T08:49:30.4218163Z 08:49:29 === RUN TestCWorkerTestSuite/TestScheduleJob
2020-02-26T08:49:30.4218324Z 08:49:29 === RUN TestCWorkerTestSuite/TestStopJob
2020-02-26T08:49:30.4218782Z 08:49:29 2020/02/26 08:49:29 Job incoming: {"name":"fake_job","id":"20ae2ce4bb8c8ac9ecfc3151","t":1582706969,"args":null}
2020-02-26T08:49:30.4218983Z 08:49:29 2020/02/26 08:49:29 Job incoming: {"name":"fake_long_run_job","id":"2890e9c18716ba2c54007565","t":1582706969,"args":null}
2020-02-26T08:49:30.4219173Z 08:49:29 2020/02/26 08:49:29 Job incoming: {"name":"fake_job","id":"08d0c9b878efe6640e6a5660","t":1582706969,"args":null,"unique":true}
2020-02-26T08:49:30.4219339Z 08:49:29 ==================
2020-02-26T08:49:30.4219482Z 08:49:29 WARNING: DATA RACE
2020-02-26T08:49:30.4219674Z 08:49:29 Read at 0x00c00042aa70 by goroutine 35:
2020-02-26T08:49:30.4219814Z 08:49:29 github.com/goharbor/harbor/src/jobservice/runner.(*RedisJob).Run()
2020-02-26T08:49:30.4219998Z 08:49:29 /home/runner/work/harbor/src/github.com/goharbor/harbor/src/jobservice/runner/redis.go:163 +0xb14
2020-02-26T08:49:30.4220183Z 08:49:29 github.com/goharbor/harbor/src/jobservice/worker/cworker.(*basicWorker).registerJob.func2()
2020-02-26T08:49:30.4220374Z 08:49:29 /home/runner/work/harbor/src/github.com/goharbor/harbor/src/jobservice/worker/cworker/c_worker.go:418 +0x71
2020-02-26T08:49:30.4220533Z 08:49:29 github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.runJob.func1()
2020-02-26T08:49:30.4220716Z 08:49:29 /home/runner/work/harbor/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/run.go:31 +0xae1
2020-02-26T08:49:30.4220895Z 08:49:29 github.com/goharbor/harbor/src/jobservice/worker/cworker.(*workerContext).logJob()
2020-02-26T08:49:30.4221077Z 08:49:29 /home/runner/work/harbor/src/github.com/goharbor/harbor/src/jobservice/worker/cworker/c_worker.go:76 +0x1ae
2020-02-26T08:49:30.4221242Z 08:49:29 runtime.call64()
2020-02-26T08:49:30.4221377Z 08:49:29 /opt/hostedtoolcache/go/1.13.4/x64/src/runtime/asm_amd64.s:540 +0x3a
2020-02-26T08:49:30.4221534Z 08:49:29 reflect.Value.Call()
2020-02-26T08:49:30.4221683Z 08:49:29 /opt/hostedtoolcache/go/1.13.4/x64/src/reflect/value.go:321 +0xd3
2020-02-26T08:49:30.4221854Z 08:49:29 github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.runJob.func1()
2020-02-26T08:49:30.4222016Z 08:49:29 /home/runner/work/harbor/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/run.go:23 +0x3ce
2020-02-26T08:49:30.4222529Z 08:49:29 github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.runJob()
2020-02-26T08:49:30.4222707Z 08:49:29 /home/runner/work/harbor/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/run.go:51 +0x3b3
2020-02-26T08:49:30.4222880Z 08:49:29 github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*worker).processJob()
2020-02-26T08:49:30.4223061Z 08:49:29 /home/runner/work/harbor/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/worker.go:198 +0x47a
2020-02-26T08:49:30.4223224Z 08:49:29 github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*worker).loop()
2020-02-26T08:49:30.4223399Z 08:49:29 /home/runner/work/harbor/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/worker.go:119 +0x376
2020-02-26T08:49:30.4223566Z 08:49:29
2020-02-26T08:49:30.4223716Z 08:49:29 Previous write at 0x00c00042aa70 by goroutine 49:
2020-02-26T08:49:30.4223858Z 08:49:29 github.com/goharbor/harbor/src/jobservice/runner.(*RedisJob).Run()
2020-02-26T08:49:30.4224033Z 08:49:29 /home/runner/work/harbor/src/github.com/goharbor/harbor/src/jobservice/runner/redis.go:164 +0x1179
2020-02-26T08:49:30.4224212Z 08:49:29 github.com/goharbor/harbor/src/jobservice/worker/cworker.(*basicWorker).registerJob.func2()
2020-02-26T08:49:30.4224387Z 08:49:29 /home/runner/work/harbor/src/github.com/goharbor/harbor/src/jobservice/worker/cworker/c_worker.go:418 +0x71
2020-02-26T08:49:30.4224560Z 08:49:29 github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.runJob.func1()
2020-02-26T08:49:30.4224802Z 08:49:29 /home/runner/work/harbor/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/run.go:31 +0xae1
2020-02-26T08:49:30.4224971Z 08:49:29 github.com/goharbor/harbor/src/jobservice/worker/cworker.(*workerContext).logJob()
2020-02-26T08:49:30.4225198Z 08:49:29 /home/runner/work/harbor/src/github.com/goharbor/harbor/src/jobservice/worker/cworker/c_worker.go:76 +0x1ae
2020-02-26T08:49:30.4225361Z 08:49:29 runtime.call64()
2020-02-26T08:49:30.4225514Z 08:49:29 /opt/hostedtoolcache/go/1.13.4/x64/src/runtime/asm_amd64.s:540 +0x3a
2020-02-26T08:49:30.4225708Z 08:49:29 reflect.Value.Call()
2020-02-26T08:49:30.4225997Z 08:49:29 /opt/hostedtoolcache/go/1.13.4/x64/src/reflect/value.go:321 +0xd3
2020-02-26T08:49:30.4226164Z 08:49:29 github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.runJob.func1()
2020-02-26T08:49:30.4226340Z 08:49:29 /home/runner/work/harbor/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/run.go:23 +0x3ce
2020-02-26T08:49:30.4226496Z 08:49:29 github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.runJob()
2020-02-26T08:49:30.4226667Z 08:49:29 /home/runner/work/harbor/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/run.go:51 +0x3b3
2020-02-26T08:49:30.4226844Z 08:49:29 github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*worker).processJob()
2020-02-26T08:49:30.4227025Z 08:49:29 /home/runner/work/harbor/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/worker.go:198 +0x47a
2020-02-26T08:49:30.4227200Z 08:49:29 github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*worker).loop()
2020-02-26T08:49:30.4227361Z 08:49:29 /home/runner/work/harbor/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/worker.go:119 +0x376
2020-02-26T08:49:30.4227521Z 08:49:29
2020-02-26T08:49:30.4227664Z 08:49:29 Goroutine 35 (running) created at:
2020-02-26T08:49:30.4227821Z 08:49:29 github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*worker).start()
2020-02-26T08:49:30.4227986Z 08:49:29 /home/runner/work/harbor/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/worker.go:78 +0x50
2020-02-26T08:49:30.4228143Z 08:49:29
2020-02-26T08:49:30.4228286Z 08:49:29 Goroutine 49 (running) created at:
2020-02-26T08:49:30.4228446Z 08:49:29 github.com/goharbor/harbor/src/vendor/github.com/gocraft/work.(*worker).start()
2020-02-26T08:49:30.4228603Z 08:49:29 /home/runner/work/harbor/src/github.com/goharbor/harbor/src/vendor/github.com/gocraft/work/worker.go:78 +0x50
2020-02-26T08:49:30.4228760Z 08:49:29 ==================
2020-02-26T08:49:30.4229645Z 08:49:29 2020/02/26 08:49:29 Job 'fake_job:08d0c9b878efe6640e6a5660' exit with success
2020-02-26T08:49:30.4230078Z 08:49:29 2020/02/26 08:49:29 Job 'fake_job:20ae2ce4bb8c8ac9ecfc3151' exit with success
2020-02-26T08:49:30.4230239Z 08:49:30 === RUN TestCWorkerTestSuite/TestWorkerStats
2020-02-26T08:49:30.4230377Z 08:49:30 2020/02/26 08:49:30 Scheduler: periodic enqueuer is stopped
2020-02-26T08:49:30.4230542Z 08:49:30 2020/02/26 08:49:30 Reaper is stopped
2020-02-26T08:49:32.6083377Z 08:49:32 2020/02/26 08:49:32 Job fake_long_run_job:2890e9c18716ba2c54007565 is stopped
2020-02-26T08:49:32.6098605Z 08:49:32 2020/02/26 08:49:32 Basic worker is stopped
2020-02-26T08:49:32.6143989Z 08:49:32 --- FAIL: TestCWorkerTestSuite (3.05s)
2020-02-26T08:49:32.6222130Z 08:49:32 --- PASS: TestCWorkerTestSuite/TestEnqueueJob (0.00s)
2020-02-26T08:49:32.6240897Z 08:49:32 --- PASS: TestCWorkerTestSuite/TestEnqueuePeriodicJob (0.00s)
2020-02-26T08:49:32.6258149Z 08:49:32 --- PASS: TestCWorkerTestSuite/TestEnqueueUniqueJob (0.00s)
2020-02-26T08:49:32.6276883Z 08:49:32 --- PASS: TestCWorkerTestSuite/TestRegisterJobs (0.00s)
2020-02-26T08:49:32.6291462Z 08:49:32 --- PASS: TestCWorkerTestSuite/TestScheduleJob (0.00s)
2020-02-26T08:49:32.6305402Z 08:49:32 --- FAIL: TestCWorkerTestSuite/TestStopJob (0.50s)
```

**Comment by steven-zou** [comment]
Fixed. Close the issue now.
