### ISSUE TITLE
used ceph as storge,but cann't gc

### ISSUE THREAD

**Issue by jinjie2088** [goharbor/harbor#11067]
**Version:**
```
 goharbor/nginx-photon:v1.8.2                       
 goharbor/harbor-jobservice:v1.8.2                  
 goharbor/harbor-portal:v1.8.2                      
 goharbor/harbor-core:v1.8.2                        
 goharbor/harbor-registryctl:v1.8.2                 
 goharbor/registry-photon:v2.7.1-patch-2819-v1.8.2  
 goharbor/harbor-log:v1.8.2                         
```
**Ceph version**
```
[root@host-10-0-228-151 ~]# ceph version
ceph version 13.2.6 (7b695f835b03642f85998b2ae7b6dd093d9fbce4) mimic (stable)
```
**In registryctl run:**
```
sudo -E -u \#10000 registry garbage-collect --delete-untagged=true /etc/registry/config.yml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc51d8d]

goroutine 1 [running]:
github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).doWalk.func1(0xc00014f180, 0xc00002eb01, 0xc0004f56e8)
	/go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:973 +0x9d
github.com/docker/distribution/vendor/github.com/aws/aws-sdk-go/service/s3.(*S3).ListObjectsV2PagesWithContext(0xc00040a1e8, 0x7f18b4935268, 0xc0002491f0, 0xc00050a3c0, 0xc0004f57e8, 0x0, 0x0, 0x0, 0x1, 0x2)
	/go/src/github.com/docker/distribution/vendor/github.com/aws/aws-sdk-go/service/s3/api.go:4198 +0x111
github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).doWalk(0xc00014f100, 0xff4d80, 0xc000249110, 0xc0004f58a8, 0xc0004168d1, 0x2f, 0x0, 0x0, 0xc00040dd20, 0x0, ...)
	/go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:971 +0x3a1
github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).Walk(0xc00014f100, 0xff4d80, 0xc000249110, 0xc0004199a0, 0x20, 0xc00040dd20, 0x2, 0x0)
	/go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:919 +0x160
github.com/docker/distribution/registry/storage/driver/base.(*Base).Walk(0xc000409400, 0xff4d80, 0xc000249110, 0xc0004199a0, 0x20, 0xc00040dd20, 0x0, 0x0)
	/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go:239 +0x234
github.com/docker/distribution/registry/storage.(*registry).Enumerate(0xc0002490a0, 0xff4ac0, 0xc0000b5350, 0xc00002eac0, 0x0, 0x0)
	/go/src/github.com/docker/distribution/registry/storage/catalog.go:67 +0xe3
github.com/docker/distribution/registry/storage.MarkAndSweep(0xff4ac0, 0xc0000b5350, 0x1000c20, 0xc000409400, 0xff6c80, 0xc0002490a0, 0x100, 0xff6c80, 0xc0002490a0)
	/go/src/github.com/docker/distribution/registry/storage/garbagecollect.go:40 +0x1e7
github.com/docker/distribution/registry.glob..func3(0x171eca0, 0xc00040c7c0, 0x1, 0x2)
	/go/src/github.com/docker/distribution/registry/root.go:80 +0x48a
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x171eca0, 0xc00040c6e0, 0x2, 0x2, 0x171eca0, 0xc00040c6e0)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x191
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x171efe0, 0xc0004f5f88, 0xc00003a0b8)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0x2f4
main.main()
	/go/src/github.com/docker/distribution/cmd/registry/main.go:23 +0x2d
```

**Configure file:**
```
root [ /harbor ]#  sudo -E -u \#10000 cat /etc/registry/config.yml
version: 0.1
log:
  level: info
  fields:
    service: registry
storage:
  cache:
    layerinfo: redis
  s3:
    accesskey: 2OGVK419CIG370TGIMPW
    secretkey: djq3FUukIa7hoTDrCTC6TbD1vl36K0TaYPg0RNTh
    region: zh
    regionendpoint: http://10.0.228.151:7480
    bucket: startimes
    rootdirectory: /registry-local
  maintenance:
    uploadpurging:
      enabled: false
  delete:
    enabled: true
redis:
  addr: 10.0.228.151:6379
  password:
  db: 1
http:
  addr: :5000
  secret: placeholder
  debug:
    addr: localhost:5001
auth:
  token:
    issuer: harbor-token-issuer
    realm: https://registry-local.startimes.me/service/token
    rootcertbundle: /etc/registry/root.crt
    service: harbor-registry
validation:
  disabled: true
notifications:
  endpoints:
  - name: harbor
    disabled: false
    url: http://core:8080/service/notifications
    timeout: 3000ms
    threshold: 5
    backoff: 1s
compatibility:
  schema1:
    enabled: true
```
how to delele the images on ceph?

**Comment by reasonerjt** [comment]
Looks like there is compatibility issue with the driver and ceph storage, and this commit fixed it:

https://github.com/docker/distribution/commit/0a1e4a57e241ac320b613a7d055ce166c9bb65f1

@wy65701436 could you check if this commit is contained in recent releases?

**Comment by wy65701436** [comment]
I have already cherry-pick the fix into distribution v2.7 release branch, it could be in the v2.7.2. I'll keep updating.

**Comment by odeng888** [comment]
What version number is v2.7.2 ？

**Comment by odeng888** [comment]
When to release v2.7.2？

**Comment by wy65701436** [comment]
I cannot tell as it has to be confirmed with distribution maintainer.

**Comment by odeng888** [comment]
When can this problem be solved?

**Comment by odeng888** [comment]
There are still problems
