### ISSUE TITLE
Harbor-core pods are failing 

### ISSUE THREAD

**Issue by Pradyumnakashyap** [goharbor/harbor#11181]
Running on a Kubernetes cluster v1.12 using helm charts.
The other pods are working as expected but the harbor-core pods are failing with the core main.go throwing an index out of range error.
Was working when i checked last time around. Please Advice.

Please find below pod logs for the failed pod -

kubectl logs harbor-harbor-core-d4bb5b9d4-bdtb6
2020-03-20T13:13:06Z [INFO] [/replication/adapter/native/adapter.go:42]: the factory for adapter docker-registry registered
2020-03-20T13:13:06Z [INFO] [/replication/adapter/harbor/adapter.go:40]: the factory for adapter harbor registered
2020-03-20T13:13:06Z [INFO] [/replication/adapter/dockerhub/adapter.go:25]: Factory for adapter docker-hub registered
2020-03-20T13:13:06Z [INFO] [/replication/adapter/huawei/huawei_adapter.go:27]: the factory of Huawei adapter was registered
2020-03-20T13:13:06Z [INFO] [/replication/adapter/googlegcr/adapter.go:29]: the factory for adapter google-gcr registered
2020-03-20T13:13:06Z [INFO] [/replication/adapter/awsecr/adapter.go:47]: the factory for adapter aws-ecr registered
2020-03-20T13:13:06Z [INFO] [/replication/adapter/azurecr/adapter.go:15]: Factory for adapter azure-acr registered
2020-03-20T13:13:06Z [INFO] [/replication/adapter/aliacr/adapter.go:26]: the factory for adapter ali-acr registered
2020-03-20T13:13:06Z [INFO] [/replication/adapter/jfrog/adapter.go:30]: the factory of jfrog artifactory adapter was registered
2020-03-20T13:13:06Z [INFO] [/replication/adapter/quayio/adapter.go:34]: the factory of Quay.io adapter was registered
2020-03-20T13:13:06Z [INFO] [/replication/adapter/helmhub/adapter.go:30]: the factory for adapter helm-hub registered
2020-03-20T13:13:06Z [INFO] [/replication/adapter/gitlab/adapter.go:19]: the factory for adapter gitlab registered
2020-03-20T13:13:06Z [INFO] [/core/controllers/base.go:289]: Config path: /etc/core/app.conf
2020-03-20T13:13:06Z [INFO] [/core/main.go:177]: initializing configurations...
2020-03-20T13:13:06Z [INFO] [/core/config/config.go:100]: key path: /etc/core/key
2020-03-20T13:13:06Z [INFO] [/core/config/config.go:73]: init secret store
2020-03-20T13:13:06Z [INFO] [/core/config/config.go:76]: init project manager based on deploy mode
2020-03-20T13:13:06Z [INFO] [/core/config/config.go:145]: initializing the project manager based on local database...
2020-03-20T13:13:06Z [INFO] [/core/main.go:181]: configurations initialization completed
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/goharbor/harbor/src/core/config.ExtURL(0x1746be0, 0xc00055c390, 0x19834af, 0x8)
/harbor/src/core/config/config.go:257 +0x152
github.com/goharbor/harbor/src/core/service/token.InitCreators()
/harbor/src/core/service/token/creator.go:53 +0x17c
main.main()
/harbor/src/core/main.go:182 +0x1e2

**Comment by reasonerjt** [comment]
looks like the `ExtURL` you set is invalid, what did you set in values.yaml?

**Comment by Pradyumnakashyap** [comment]
# If Harbor is deployed behind the proxy, set it as the URL of proxy
    externalURL: https://192.168.39.106:30003 

- The above externalURL comprises of the IP Address of the node I am running it on and the port 30003 for type "nodePort" to access with https.

**Comment by Pradyumnakashyap** [comment]
@reasonerjt  could you please Advice ?

**Comment by Pradyumnakashyap** [comment]
Nevermind i fixed it.
