### ISSUE TITLE
Cannot generate certificates with my own CA

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#11325]
Generate a CA, put it in the directory `/path/to/internal/tls/cert` and run the following command:
```
root@kube-worker:~# docker run -v /:/hostfs goharbor/prepare:dev gencert -p /path/to/internal/tls/cert
Check openssl ...
start generate internal tls certs
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/app/commands/gencerts.py", line 26, in gencert
    shell_stat = check_call([gen_tls_script, days], stdout=PIPE, stderr=STDOUT, cwd=path)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[PosixPath('/usr/src/app/scripts/gencert.sh'), '365']' returned non-zero exit status 1.
```

**Comment by ywk253100** [comment]
Closing as this is caused by wrong operation
