### ISSUE TITLE
Trivy adapter random failed in CI/Nightly

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#11373]
There are two cases for scan artifacts in APITEST, but it will random failed in CI/Nightly. And the following is the logs of trivy adapter when scan failed.

```
Mar 30 01:56:30 172.18.0.1 trivy-adapter[10914]: {"built_at":"2020-03-26T09:42:06Z","commit":"cf232c467f424d905e727862e5d84023fe043359","level":"info","msg":"Starting harbor-scanner-trivy","time":"2020-03-30T01:56:30Z","version":"0.7.0"}
Mar 30 02:06:04 172.18.0.1 trivy-adapter[10914]: {"exit_code":2,"level":"error","msg":"Running trivy failed","std_out":"unexpected fault address 0x7f32b2c2b008\nfatal error: fault\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f32b2c2b008 pc=0x78cf17]\n\ngoroutine 1 [running]:\nruntime.throw(0x11bd2f1, 0x5)\n\t/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc0004b7668 sp=0xc0004b7638 pc=0x42e6f2\nruntime.sigpanic()\n\t/usr/local/go/src/runtime/signal_unix.go:401 +0x3de fp=0xc0004b7698 sp=0xc0004b7668 pc=0x44321e\ngithub.com/etcd-io/bbolt.(*freelist).read(0xc00013b400, 0x7f32b2c2b000)\n\t/go/pkg/mod/github.com/etcd-io/bbolt@v1.3.3/freelist.go:265 +0x37 fp=0xc0004b7728 sp=0xc0004b7698 pc=0x78cf17\ngithub.com/etcd-io/bbolt.(*DB).loadFreelist.func1()\n\t/go/pkg/mod/github.com/etcd-io/bbolt@v1.3.3/db.go:316 +0xcf fp=0xc0004b7760 sp=0xc0004b7728 pc=0x79719f\nsync.(*Once).doSlow(0xc0001c2568, 0xc0004b7810)\n\t/usr/local/go/src/sync/once.go:66 +0xe3 fp=0xc0004b7800 sp=0xc0004b7760 pc=0x4788e3\nsync.(*Once).Do(...)\n\t/usr/local/go/src/sync/once.go:57\ngithub.com/etcd-io/bbolt.(*DB).loadFreelist(0xc0001c2400)\n\t/go/pkg/mod/github.com/etcd-io/bbolt@v1.3.3/db.go:309 +0x6a fp=0xc0004b7830 sp=0xc0004b7800 pc=0x7881da\ngithub.com/etcd-io/bbolt.Open(0xc000038360, 0x26, 0xc000000180, 0x1c12aa0, 0x0, 0x203000, 0x203000)\n\t/go/pkg/mod/github.com/etcd-io/bbolt@v1.3.3/db.go:286 +0x35d fp=0xc0004b7918 sp=0xc0004b7830 pc=0x787c8d\ngithub.com/aquasecurity/trivy-db/pkg/db.Init(0x7fffbfcc8b81, 0x1a, 0x20, 0x18)\n\t/go/pkg/mod/github.com/aquasecurity/trivy-db@v0.0.0-20200318223623-7d3e67b057d4/pkg/db/db.go:68 +0x13c fp=0xc0004b7980 sp=0xc0004b7918 pc=0x79c92c\ngithub.com/aquasecurity/trivy/internal.showVersion(0x7fffbfcc8b81, 0x1a, 0x7fffbfcc8ba5, 0x4, 0x141acf0, 0x5, 0x1441be0, 0xc0000ae008)\n\t/home/circleci/project/internal/app.go:252 +0x50 fp=0xc0004b7b58 sp=0xc0004b7980 pc=0xef3a20\ngithub.com/aquasecurity/trivy/internal.NewApp.func1(0xc0000a5e40)\n\t/home/circleci/project/internal/app.go:188 +0xe7 fp=0xc0004b7bb8 sp=0xc0004b7b58 pc=0xef42c7\ngithub.com/urfave/cli.ShowVersion(...)\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.1/help.go:213\ngithub.com/urfave/cli.(*App).Run(0xc00024e000, 0xc0000b0120, 0x6, 0x6, 0x0, 0x0)\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.1/app.go:238 +0x9a1 fp=0xc0004b7f00 sp=0xc0004b7bb8 pc=0x7e6b81\nmain.main()\n\t/home/circleci/project/cmd/trivy/main.go:18 +0x6f fp=0xc0004b7f60 sp=0xc0004b7f00 pc=0xef48cf\nruntime.main()\n\t/usr/local/go/src/runtime/proc.go:203 +0x21e fp=0xc0004b7fe0 sp=0xc0004b7f60 pc=0x43008e\nruntime.goexit()\n\t/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0004b7fe8 sp=0xc0004b7fe0 pc=0x45b801\n\ngoroutine 13 [syscall]:\nos/signal.signal_recv(0x0)\n\t/usr/local/go/src/runtime/sigqueue.go:147 +0x9c\nos/signal.loop()\n\t/usr/local/go/src/os/signal/signal_unix.go:23 +0x22\ncreated by os/signal.init.0\n\t/usr/local/go/src/os/signal/signal_unix.go:29 +0x41\n","time":"2020-03-30T02:06:04Z"}
Mar 30 02:06:04 172.18.0.1 trivy-adapter[10914]: {"error":"running trivy: exit status 2: unexpected fault address 0x7f32b2c2b008\nfatal error: fault\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f32b2c2b008 pc=0x78cf17]\n\ngoroutine 1 [running]:\nruntime.throw(0x11bd2f1, 0x5)\n\t/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc0004b7668 sp=0xc0004b7638 pc=0x42e6f2\nruntime.sigpanic()\n\t/usr/local/go/src/runtime/signal_unix.go:401 +0x3de fp=0xc0004b7698 sp=0xc0004b7668 pc=0x44321e\ngithub.com/etcd-io/bbolt.(*freelist).read(0xc00013b400, 0x7f32b2c2b000)\n\t/go/pkg/mod/github.com/etcd-io/bbolt@v1.3.3/freelist.go:265 +0x37 fp=0xc0004b7728 sp=0xc0004b7698 pc=0x78cf17\ngithub.com/etcd-io/bbolt.(*DB).loadFreelist.func1()\n\t/go/pkg/mod/github.com/etcd-io/bbolt@v1.3.3/db.go:316 +0xcf fp=0xc0004b7760 sp=0xc0004b7728 pc=0x79719f\nsync.(*Once).doSlow(0xc0001c2568, 0xc0004b7810)\n\t/usr/local/go/src/sync/once.go:66 +0xe3 fp=0xc0004b7800 sp=0xc0004b7760 pc=0x4788e3\nsync.(*Once).Do(...)\n\t/usr/local/go/src/sync/once.go:57\ngithub.com/etcd-io/bbolt.(*DB).loadFreelist(0xc0001c2400)\n\t/go/pkg/mod/github.com/etcd-io/bbolt@v1.3.3/db.go:309 +0x6a fp=0xc0004b7830 sp=0xc0004b7800 pc=0x7881da\ngithub.com/etcd-io/bbolt.Open(0xc000038360, 0x26, 0xc000000180, 0x1c12aa0, 0x0, 0x203000, 0x203000)\n\t/go/pkg/mod/github.com/etcd-io/bbolt@v1.3.3/db.go:286 +0x35d fp=0xc0004b7918 sp=0xc0004b7830 pc=0x787c8d\ngithub.com/aquasecurity/trivy-db/pkg/db.Init(0x7fffbfcc8b81, 0x1a, 0x20, 0x18)\n\t/go/pkg/mod/github.com/aquasecurity/trivy-db@v0.0.0-20200318223623-7d3e67b057d4/pkg/db/db.go:68 +0x13c fp=0xc0004b7980 sp=0xc0004b7918 pc=0x79c92c\ngithub.com/aquasecurity/trivy/internal.showVersion(0x7fffbfcc8b81, 0x1a, 0x7fffbfcc8ba5, 0x4, 0x141acf0, 0x5, 0x1441be0, 0xc0000ae008)\n\t/home/circleci/project/internal/app.go:252 +0x50 fp=0xc0004b7b58 sp=0xc0004b7980 pc=0xef3a20\ngithub.com/aquasecurity/trivy/internal.NewApp.func1(0xc0000a5e40)\n\t/home/circleci/project/internal/app.go:188 +0xe7 fp=0xc0004b7bb8 sp=0xc0004b7b58 pc=0xef42c7\ngithub.com/urfave/cli.ShowVersion(...)\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.1/help.go:213\ngithub.com/urfave/cli.(*App).Run(0xc00024e000, 0xc0000b0120, 0x6, 0x6, 0x0, 0x0)\n\t/go/pkg/mod/github.com/urfave/cli@v1.22.1/app.go:238 +0x9a1 fp=0xc0004b7f00 sp=0xc0004b7bb8 pc=0x7e6b81\nmain.main()\n\t/home/circleci/project/cmd/trivy/main.go:18 +0x6f fp=0xc0004b7f60 sp=0xc0004b7f00 pc=0xef48cf\nruntime.main()\n\t/usr/local/go/src/runtime/proc.go:203 +0x21e fp=0xc0004b7fe0 sp=0xc0004b7f60 pc=0x43008e\nruntime.goexit()\n\t/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0004b7fe8 sp=0xc0004b7fe0 pc=0x45b801\n\ngoroutine 13 [syscall]:\nos/signal.signal_recv(0x0)\n\t/usr/local/go/src/runtime/sigqueue.go:147 +0x9c\nos/signal.loop()\n\t/usr/local/go/src/os/signal/signal_unix.go:23 +0x22\ncreated by os/signal.init.0\n\t/usr/local/go/src/os/signal/signal_unix.go:29 +0x41\n","level":"error","msg":"Error while retrieving vulnerability DB version","time":"2020-03-30T02:06:04Z"}
```

**Comment by danielpacak** [comment]
We fixed it in https://github.com/aquasecurity/trivy/commit/1bc02f9f6a098f68b502f00f593b6021b12aac42 Just waiting for new release of Trivy to bump it up in Makefile.

**Comment by reasonerjt** [comment]
Let's make sure this is merged by 15th Apr
