### ISSUE TITLE
Get core panic when to trigger a docker-registry replication

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#11854]
### [steps]

- add a docker-registry endpoint

- add a docker-registry replication rule

![image](https://user-images.githubusercontent.com/2841473/81326287-2f543f80-90cc-11ea-8087-95e820bc27be.png)

After triggering a replication, I got the core panic.

### [logs]
```
ch|#033[97;46m POST    #033[0m /service/notifications/jobs/replication/task/12   r:/service/notifications/jobs/replication/task/:id([0-9]+)
May  7 17:31:56 192.168.144.1 core[19235]: panic: runtime error: index out of range [1] with length 1
May  7 17:31:56 192.168.144.1 core[19235]: 
May  7 17:31:56 192.168.144.1 core[19235]: goroutine 148 [running]:
May  7 17:31:56 192.168.144.1 core[19235]: github.com/goharbor/harbor/src/controller/event/handler/webhook/artifact.getMetadataFromResource(...)
May  7 17:31:56 192.168.144.1 core[19235]: #011/harbor/src/controller/event/handler/webhook/artifact/replication.go:205
May  7 17:31:56 192.168.144.1 core[19235]: github.com/goharbor/harbor/src/controller/event/handler/webhook/artifact.constructReplicationPayload(0xc00021d000, 0xc0004b4e28, 0xc0004b4e18, 0x203000, 0x203000)
May  7 17:31:56 192.168.144.1 core[19235]: #011/harbor/src/controller/event/handler/webhook/artifact/replication.go:112 +0x1762
May  7 17:31:56 192.168.144.1 core[19235]: github.com/goharbor/harbor/src/controller/event/handler/webhook/artifact.(*ReplicationHandler).Handle(0x308daa0, 0x19845a0, 0xc00021d000, 0xc000143500, 0x7feb5f77d460)
May  7 17:31:56 192.168.144.1 core[19235]: #011/harbor/src/controller/event/handler/webhook/artifact/replication.go:40 +0x7b
May  7 17:31:56 192.168.144.1 core[19235]: github.com/goharbor/harbor/src/pkg/notifier.(*NotificationWatcher).Notify.func1.1(0x208fd00, 0x308daa0, 0x0, 0x1d11279, 0xb, 0x19845a0, 0xc00021d000)
May  7 17:31:56 192.168.144.1 core[19235]: #011/harbor/src/pkg/notifier/notifier.go:200 +0xba
May  7 17:31:56 192.168.144.1 core[19235]: created by github.com/goharbor/harbor/src/pkg/notifier.(*NotificationWatcher).Notify.func1
May  7 17:31:56 192.168.144.1 core[19235]: #011/harbor/src/pkg/notifier/notifier.go:194 +0xac


```

### [Root cause]
After have a debug, it should be caused by https://github.com/goharbor/harbor/blob/master/src/controller/event/handler/webhook/artifact/replication.go#L205

### [Workaround]
Disable webhook in the system configuration page.

**Comment by wy65701436** [comment]
close it per PR: https://github.com/goharbor/harbor/pull/11863.
