### ISSUE TITLE
Internal TLS not working when tutorial followed 2.0.0

### ISSUE THREAD

**Issue by kuburoman** [goharbor/harbor#11934]
**Expected behavior and actual behavior:**
Expected is that Harbor started and is running properly
Actual is that nginx-photon is constantly restarted and rest of pod reports errors. 

**Steps to reproduce the problem:**
Followed all the steps of tutorial to deploy Harbor with internal tls enabled. In steps there is written to run command `docker run -v /:/hostfs goharbor/prepare:v2.0 gencert -p /path/to/internal/tls/cert` but version should be `v2.0.0`. Installation does not show any errors.

 

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.0.0
- docker engine version: 19.03.1
- docker-compose version: 1.25.5

**Additional context:**

- **Log files:**
- proxy.log
```
May 14 12:24:07 172.18.0.1 proxy[60892]: 2020/05/14 10:24:07 [emerg] 1#0: SSL_CTX_load_verify_locations("/harbor_cust_cert/harbor_internal_ca.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/harbor_cust_cert/harbor_internal_ca.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib)
May 14 12:24:07 172.18.0.1 proxy[60892]: nginx: [emerg] SSL_CTX_load_verify_locations("/harbor_cust_cert/harbor_internal_ca.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/harbor_cust_cert/harbor_internal_ca.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib)
May 14 12:24:07 172.18.0.1 proxy[60892]: 2020/05/14 10:24:07 [emerg] 1#0: SSL_CTX_load_verify_locations("/harbor_cust_cert/harbor_internal_ca.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/harbor_cust_cert/harbor_internal_ca.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib)
May 14 12:24:07 172.18.0.1 proxy[60892]: nginx: [emerg] SSL_CTX_load_verify_locations("/harbor_cust_cert/harbor_internal_ca.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/harbor_cust_cert/harbor_internal_ca.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib)`
```

- core.log 
```
May 14 12:24:04 172.18.0.1 core[60892]: Appending trust CA to ca-bundle ...
May 14 12:24:04 172.18.0.1 core[60892]:  /harbor_cust_cert/core.crt Appended ...
May 14 12:24:04 172.18.0.1 core[60892]: CA appending is Done.
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [INFO] [/controller/artifact/processor/processor.go:58]: the processor to process media type application/vnd.oci.image.index.v1+json registered
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [INFO] [/controller/artifact/processor/processor.go:58]: the processor to process media type application/vnd.docker.distribution.manifest.list.v2+json registered
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [INFO] [/controller/artifact/processor/processor.go:58]: the processor to process media type application/vnd.docker.distribution.manifest.v1+prettyjws registered
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [INFO] [/controller/artifact/processor/processor.go:58]: the processor to process media type application/vnd.oci.image.config.v1+json registered
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [INFO] [/controller/artifact/processor/processor.go:58]: the processor to process media type application/vnd.docker.container.image.v1+json registered
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [INFO] [/controller/artifact/processor/processor.go:58]: the processor to process media type application/vnd.cncf.helm.config.v1+json registered
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [INFO] [/controller/artifact/processor/processor.go:58]: the processor to process media type application/vnd.cnab.manifest.v1 registered
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [INFO] [/replication/adapter/native/adapter.go:36]: the factory for adapter docker-registry registered
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [INFO] [/replication/adapter/harbor/adaper.go:31]: the factory for adapter harbor registered
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [INFO] [/replication/adapter/dockerhub/adapter.go:25]: Factory for adapter docker-hub registered
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [INFO] [/replication/adapter/huawei/huawei_adapter.go:27]: the factory of Huawei adapter was registered
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [INFO] [/replication/adapter/googlegcr/adapter.go:29]: the factory for adapter google-gcr registered
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [INFO] [/replication/adapter/awsecr/adapter.go:47]: the factory for adapter aws-ecr registered
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [INFO] [/replication/adapter/azurecr/adapter.go:15]: Factory for adapter azure-acr registered
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [INFO] [/replication/adapter/aliacr/adapter.go:31]: the factory for adapter ali-acr registered
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [INFO] [/replication/adapter/jfrog/adapter.go:30]: the factory of jfrog artifactory adapter was registered
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [INFO] [/replication/adapter/quayio/adapter.go:38]: the factory of Quay.io adapter was registered
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [INFO] [/replication/adapter/helmhub/adapter.go:30]: the factory for adapter helm-hub registered
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [INFO] [/replication/adapter/gitlab/adapter.go:17]: the factory for adapter gitlab registered
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [ERROR] [/common/config/manager.go:118]: loadSystemConfigFromEnv failed, config item, key: clair_db_port,  err: strconv.Atoi: parsing "": invalid syntax
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [INFO] [/core/controllers/base.go:299]: Config path: /etc/core/app.conf
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [INFO] [/core/main.go:111]: initializing configurations...
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [INFO] [/core/config/config.go:83]: key path: /etc/core/key
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [ERROR] [/common/config/manager.go:118]: loadSystemConfigFromEnv failed, config item, key: clair_db_port,  err: strconv.Atoi: parsing "": invalid syntax
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [INFO] [/core/config/config.go:60]: init secret store
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [INFO] [/core/config/config.go:63]: init project manager
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [INFO] [/core/config/config.go:95]: initializing the project manager based on local database...
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [INFO] [/core/main.go:113]: configurations initialization completed
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [INFO] [/common/dao/base.go:84]: Registering database: type-PostgreSQL host-postgresql port-5432 databse-registry sslmode-"disable"
May 14 12:24:05 172.18.0.1 core[60892]: 2020-05-14T10:24:05Z [ERROR] [/common/utils/utils.go:102]: failed to connect to tcp://postgresql:5432, retry after 2 seconds :dial tcp 172.18.0.3:5432: connect: connection refused
May 14 12:24:07 172.18.0.1 core[60892]: 2020-05-14T10:24:07Z [ERROR] [/common/utils/utils.go:102]: failed to connect to tcp://postgresql:5432, retry after 2 seconds :dial tcp 172.18.0.3:5432: connect: connection refused
May 14 12:24:09 172.18.0.1 core[60892]: 2020-05-14T10:24:09Z [INFO] [/common/dao/base.go:89]: Register database completed
May 14 12:24:09 172.18.0.1 core[60892]: 2020-05-14T10:24:09Z [INFO] [/common/dao/pgsql.go:118]: Upgrading schema for pgsql ...
May 14 12:24:10 172.18.0.1 core[60892]: 2020-05-14T10:24:10Z [INFO] [/core/main.go:78]: User id: 1 updated its encrypted password successfully.
May 14 12:24:10 172.18.0.1 core[60892]: 2020-05-14T10:24:10Z [INFO] [/core/main.go:198]: Removing Trivy scanner
May 14 12:24:10 172.18.0.1 core[60892]: 2020-05-14T10:24:10Z [INFO] [/core/main.go:220]: Removing Clair scanner
May 14 12:24:10 172.18.0.1 core[60892]: 2020-05-14T10:24:10Z [INFO] [/core/main.go:156]: initializing notification...
May 14 12:24:10 172.18.0.1 core[60892]: 2020-05-14T10:24:10Z [INFO] [/pkg/notification/notification.go:47]: notification initialization completed
May 14 12:24:10 172.18.0.1 core[60892]: 2020-05-14T10:24:10Z [INFO] [/core/main.go:162]: internal TLS enabled, Init TLS ...
May 14 12:24:10 172.18.0.1 core[60892]: 2020-05-14T10:24:10Z [INFO] [/core/main.go:166]: load client key: /etc/harbor/ssl/core.key client cert: /etc/harbor/ssl/core.crt
May 14 12:24:10 172.18.0.1 core[60892]: 2020-05-14T10:24:10Z [INFO] [/core/main.go:175]: Version: v2.0.0, Git commit: 87602132
May 14 12:24:10 172.18.0.1 core[60892]: 2020/05/14 10:24:10.402 #033[1;34m[I]#033[0m [asm_amd64.s:1357]  https server Running on https://:8443
May 14 12:24:16 172.18.0.1 core[60892]: 2020/05/14 10:24:16.445 [server.go:3054]  [HTTP] http: TLS handshake error from 172.18.0.9:36534: remote error: tls: bad certificate
May 14 12:24:29 172.18.0.1 core[60892]: 2020/05/14 10:24:29.470 [server.go:3054]  [HTTP] http: TLS handshake error from 172.18.0.9:36548: remote error: tls: bad certificate
May 14 12:24:34 172.18.0.1 core[60892]: 2020/05/14 10:24:34.778 #033[1;44m[D]#033[0m [transaction.go:62]  |      127.0.0.1|#033[97;42m 200 #033[0m|    304.516µs|   match|#033[97;44m GET     #033[0m /api/v2.0/ping   r:/api/v2.0/ping
May 14 12:24:48 172.18.0.1 core[60892]: 2020/05/14 10:24:48.497 [server.go:3054]  [HTTP] http: TLS handshake error from 172.18.0.9:36598: remote error: tls: bad certificate
May 14 12:25:04 172.18.0.1 core[60892]: 2020/05/14 10:25:04.935 #033[1;44m[D]#033[0m [transaction.go:62]  |      127.0.0.1|#033[97;42m 200 #033[0m|    319.823µs|   match|#033[97;44m GET     #033[0m /api/v2.0/ping   r:/api/v2.0/ping
```

**Comment by kuburoman** [comment]
Without Internal tls Harbor starts as expected.

**Comment by gregorkistler** [comment]
Same here. Jobservice and proxy container ending in a restart loop.

**Comment by reasonerjt** [comment]
@kuburoman 
Did you use `/path/to/internal/tls/cert` in your command?  I believe the doc implies it should be the path on your host to store the generated certificates.

Please attach the command you used to gen the cert and harbor.yml

**Comment by ninjadq** [comment]
/path/to/internal/tls/cert should the same as the value of `internal_tls.dir` in your `harbor.yml`, could you provide your harbor.yml file?

**Comment by kuburoman** [comment]
Command `./install.sh --with-notary --with-clair`.
If installation cant find certificates `/opt/harbor/tls` then it fails with error, but everything looks ok after installation, but every container has error about certificates. 

Harbor.yml (Commented lines removed)
```yml
hostname: k8sharbor

http:
  port: 80

https:
  port: 443
  certificate: /opt/harbor/cert/k8sharbor.crt
  private_key: /opt/harbor/cert/k8sharbor.key

internal_tls:
  enabled: true
  dir: /opt/harbor/tls

harbor_admin_password: Harbor12345

database:
  password: Harbor12345
  max_idle_conns: 50
  max_open_conns: 100

data_volume: /srv/harbor

clair:
  updaters_interval: 12

trivy:
  ignore_unfixed: false
  skip_update: false
  insecure: false

jobservice:
  max_job_workers: 10

notification:
  webhook_job_max_retry: 10

chart:
  absolute_url: disabled

log:
  level: info
  local:
    rotate_count: 50
    rotate_size: 200M
    location: /srv/logs/harbor

_version: 2.0.0

proxy:
  http_proxy:
  https_proxy:
  no_proxy:
  components:
    - core
    - jobservice
    - clair
    - trivy
```

**Comment by ninjadq** [comment]
Based on your configs, you must run `docker run -v /:/hostfs goharbor/prepare:v2.0 gencert -p /opt/harbor/tls` before installation in order to generate certs for harbor components

**Comment by kuburoman** [comment]
> Based on your configs, you must run `docker run -v /:/hostfs goharbor/prepare:v2.0 gencert -p /opt/harbor/tls` before installation in order to generate certs for harbor components

I ran that command before. Content of `/opt/harbor/tls`

```
clair_adapter.crt  harbor_db.csr           job_service.key    registry.crt
clair_adapter.csr  harbor_db.key           notary_server.crt  registry.csr
clair_adapter.key  harbor_internal_ca.crt  notary_server.csr  registryctl.crt
clair.crt          harbor_internal_ca.key  notary_server.key  registryctl.csr
clair.csr          harbor_internal_ca.srl  notary_signer.crt  registryctl.key
clair.key          chartmuseum.crt         notary_signer.csr  registry.key
core.crt           chartmuseum.csr         notary_signer.key  trivy_adapter.crt
core.csr           chartmuseum.key         proxy.crt          trivy_adapter.csr
core.key           job_service.crt         proxy.csr          trivy_adapter.key
harbor_db.crt      job_service.csr         proxy.key
```

Also image `goharbor/prepare:v2.0` does not exist. I ran command: `docker run -v /:/hostfs goharbor/prepare:v2.0.0 gencert -p /opt/harbor/tls`

**Comment by ninjadq** [comment]
the `goharbor/prepare:v2.0.0` is uploaded in docker-hub, if you can access the internet, docker will download it automatically.  And this image also included in your offline tar file. If you can not access the internet, you need to load these images first via command `docker load -i ./harbor*.tar.gz`

**Comment by kuburoman** [comment]
> the `goharbor/prepare:v2.0.0` is uploaded in docker-hub, if you can access the internet, docker will download it automatically. And this image also included in your offline tar file. If you can not access the internet, you need to load these images first via command `docker load -i ./harbor*.tar.gz`

In documentation there is command with docker image `goharbor/prepare:v2.0`. That results in `Error response from daemon: manifest for goharbor/prepare:v2.0 not found: manifest unknown: manifest unknown`. 

I ran command  with docker image `goharbor/prepare:v2.0` that exited correctly and generated certificates. After that I ran command `./install.sh --with-notary --with-clair` that also exited correctly. But then i got error from container logs.

**Comment by kuburoman** [comment]
Also i used offline installer.

**Comment by gregorkistler** [comment]
Could solve it in my case. The container mounted directory `/harbor_cust_cert/` only listed an empty _core.crt_ file which seem to get generated on each docker-compose up.
I've simply copied the `harbor_internal_ca.crt` file (generated via _gencert_) to the hard-coded directory `make/common/config/shared/trust-certificates` and redeployed containers.

Likely something on my end as I run Harbor on aarch64. As this does not work out-of-the-box I use my own script to build related Harbor images, alter some files and do some other stuff.

**Comment by reasonerjt** [comment]
@ninjadq any update?

**Comment by ba-work** [comment]
I hit the exact same issues.

Documentation clearly says `goharbor/prepare:v2.0` but it should say `goharbor/prepare:v2.0.0` (note the extra **.0** at the end)

Evidence: https://hub.docker.com/r/goharbor/prepare/tags?page=1&name=2.0

Also had the same where `harbor_internal_ca.crt` was missing from `./common/config/shared/trust-certificates`. Simple copy from the `internal_tls` location and redeploy fixed it on my end as well. This should probably be done as part of `install.sh`

Another thing I'd like to point out is that a first time install _with_ `internal_tls` is logically impossible if you follow the instructions: You have to run `goharbor/prepare` to get certs before installing, but you have to run the installer to load the image for prepare (see the issue here?). Its easy enough to modify `install.sh` to work around this, but it this should probably just be handled in `install.sh` for the user. (the command is documented why not just run it for the user?).

Maybe internal TLS should be a `--with-internal-tls` flag, rather than a "edit the compose file" setting.

**Comment by ofek** [comment]
@ninjadq Any update on this?

**Comment by jr200** [comment]
I believe this issue still exists in harbor v2.2.0. After enabling internal_tls, and running install.sh, the nginx containers enters a restart loop due to the missing CA at common/config/shared/trust-certificates. Copying the file over solves this problem.

**Comment by lqdflying** [comment]
same as `v2.3.0`, Couldn't they just correct the bug so everyone don't need to search the solution from a closed issues?

> I believe this issue still exists in harbor v2.2.0. After enabling internal_tls, and running install.sh, the nginx containers enters a restart loop due to the missing CA at common/config/shared/trust-certificates. Copying the file over solves this problem.

**Comment by SistemasMicro** [comment]
same as v2.8.0, Couldn't they just correct the bug so everyone don't need to search the solution from a closed issues?

**Comment by vndroid** [comment]
> same as v2.8.0, Couldn't they just correct the bug so everyone don't need to search the solution from a closed issues?

Yeah, it's pretty stupid.

**Comment by AugustasV** [comment]
Still same problem

**Comment by vndroid** [comment]
v2.9 still

**Comment by luckylinux** [comment]
Not sure if related (I was trying with Podman) but I even get a crash during install:

``./prepare
```
prepare base dir is set to /home/podman/containers/local/harbor-online-installer-v2.10.2/harbor
Clearing the configuration file: /config/jobservice/env
Clearing the configuration file: /config/jobservice/config.yml
Clearing the configuration file: /config/log/rsyslog_docker.conf
Clearing the configuration file: /config/log/logrotate.conf
Clearing the configuration file: /config/nginx/nginx.conf
Clearing the configuration file: /config/registryctl/config.yml
Clearing the configuration file: /config/registryctl/env
Clearing the configuration file: /config/db/env
Clearing the configuration file: /config/portal/nginx.conf
Clearing the configuration file: /config/core/env
Clearing the configuration file: /config/core/app.conf
Clearing the configuration file: /config/registry/config.yml
Clearing the configuration file: /config/registry/passwd
Generated configuration file: /config/portal/nginx.conf
Generated configuration file: /config/log/logrotate.conf
Generated configuration file: /config/log/rsyslog_docker.conf
Generated configuration file: /config/nginx/nginx.conf
Generated configuration file: /config/core/env
Generated configuration file: /config/core/app.conf
Generated configuration file: /config/registry/config.yml
Generated configuration file: /config/registryctl/env
Generated configuration file: /config/registryctl/config.yml
Generated configuration file: /config/db/env
Generated configuration file: /config/jobservice/env
Generated configuration file: /config/jobservice/config.yml
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/commands/prepare.py", line 50, in prepare
    prepare_tls(config_dict)
  File "/usr/src/app/utils/internal_tls.py", line 4, in prepare_tls
    config_dict['internal_tls'].validate()
  File "/usr/src/app/models.py", line 102, in validate
    self._check(filename)
  File "/usr/src/app/models.py", line 84, in _check
    if not owner_can_read(path.stat().st_mode):
                          ^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1013, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/data/secret/tls/portal.crt'
```

**Comment by AugustasV** [comment]
> As others have said, installing it with internal_tls enabled: true doesn't work at all using the install.sh.
> 
> -p path should be the same as the one under interal_tls: dir: /wherever/you/want/certs
> 
> 1. docker run -v /:/hostfs goharbor/prepare:v2.10.3 gencert -p /wherever/you/want/certs
> 2. sudo cp  /wherever/you/want/certs/* /wherever_harbor_is/common/config/shared/trust-certificates
> 3. sudo ./install.sh --with-trivy
> 
> This works. So either the internal_tls dir: doesn't do what it's supposed to, or something somewhere is screwed up. But you have to copy the certs to the common/config/shared/trust-certificates folder so that harbor will run.

great insights, hope it will be implemented

**Comment by MaKraMc** [comment]
This still exists in 2.11.1. Thanks for the fix

**Comment by MaKraMc** [comment]
![Image](https://github.com/user-attachments/assets/6ed6897a-bc6e-4259-a3f7-c7b5e394e89e)
This is still relevant

**Comment by beavercunning** [comment]
v2.13.1 is still relevant.
