### ISSUE TITLE
Task for Harbor v1.6.1 generated an exception

### ISSUE THREAD

**Issue by elmundomusical2** [goharbor/harbor#12238]
When a player is on the server, Harbor start to log (VERSION 1.12.2):

`[Harbor] Task #7 for Harbor v1.6.1 generated an exception
 java.lang.BootstrapMethodError: java.lang.NoSuchMethodError:
        at xyz.nkomarn.Harbor.task.Checker.getSleeping(Checker.java:64) ~[?:?]
        at xyz.nkomarn.Harbor.task.Checker.checkWorld(Checker.java:31) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.DistinctOps$1$2.accept(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_251]
        at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:1.8.0_251]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_251]
        at xyz.nkomarn.Harbor.task.Checker.run(Checker.java:27) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:78) ~[CraftTask.class:8d2a711]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:429) [CraftScheduler.class:8d2a711]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:919) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:456) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:864) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:736) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NoSuchMethodError:
        ... 22 more`

**Comment by reasonerjt** [comment]
Could you provide more context and information?  
It seems you are using helm chart to deploy Harbor correct?  It is suggested that you create the issue in https://github.com/goharbor/harbor-helm
