### ISSUE TITLE
get job service UT failure

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#12388]
![image](https://user-images.githubusercontent.com/2841473/86430198-38f0d100-bd24-11ea-9af0-f710dacee34a.png)

**Comment by steven-zou** [comment]
Checked, did not reproduce the failure in local env.

**Comment by heww** [comment]
TestHookAgentTestSuite also will be failed random.

```
2020-08-10T17:19:57.9944983Z 17:19:57 === RUN TestHookAgentTestSuite
2020-08-10T17:19:58.0014982Z 17:19:58 === RUN TestHookAgentTestSuite/TestEventSending
2020-08-10T17:19:58.0091530Z 17:19:58 2020/08/10 17:19:58 trigger: no ack done for event: HookAgentTestSuite
2020-08-10T17:19:58.0125113Z 17:19:58 TestHookAgentTestSuite/TestEventSending: suite.go:63: test panicked: runtime error: invalid memory address or nil pointer dereference
2020-08-10T17:19:58.0168116Z 17:19:58 goroutine 24 [running]:
2020-08-10T17:19:58.0168283Z 17:19:58 runtime/debug.Stack(0xc0004bd5f0, 0xde8400, 0x1515c00)
2020-08-10T17:19:58.0176524Z 17:19:58 /opt/hostedtoolcache/go/1.14.5/x64/src/runtime/debug/stack.go:24 +0xab
2020-08-10T17:19:58.0205941Z 17:19:58 github.com/goharbor/harbor/src/vendor/github.com/stretchr/testify/suite.failOnPanic(0xc000168240)
2020-08-10T17:19:58.0219380Z 17:19:58 /home/runner/work/harbor/harbor/src/github.com/goharbor/harbor/src/vendor/github.com/stretchr/testify/suite/suite.go:63 +0x6a
2020-08-10T17:19:58.0233071Z 17:19:58 panic(0xde8400, 0x1515c00)
2020-08-10T17:19:58.0247391Z 17:19:58 /opt/hostedtoolcache/go/1.14.5/x64/src/runtime/panic.go:975 +0x3e3
2020-08-10T17:19:58.0264499Z 17:19:58 github.com/goharbor/harbor/src/jobservice/hook.(*HookAgentTestSuite).checkStatus(0xc0000783c0)
2020-08-10T17:19:58.0280560Z 17:19:58 /home/runner/work/harbor/harbor/src/github.com/goharbor/harbor/src/jobservice/hook/hook_agent_test.go:171 +0x4c0
2020-08-10T17:19:58.0294640Z 17:19:58 github.com/goharbor/harbor/src/jobservice/hook.(*HookAgentTestSuite).TestEventSending(0xc0000783c0)
2020-08-10T17:19:58.0309111Z 17:19:58 /home/runner/work/harbor/harbor/src/github.com/goharbor/harbor/src/jobservice/hook/hook_agent_test.go:132 +0x366
2020-08-10T17:19:58.0323402Z 17:19:58 reflect.Value.call(0xc0003845a0, 0xc0000106b8, 0x13, 0xe9a8af, 0x4, 0xc0004bde58, 0x1, 0x1, 0xc00045a020, 0x7f6468849880, ...)
2020-08-10T17:19:58.0336772Z 17:19:58 /opt/hostedtoolcache/go/1.14.5/x64/src/reflect/value.go:460 +0x967
2020-08-10T17:19:58.0349927Z 17:19:58 reflect.Value.Call(0xc0003845a0, 0xc0000106b8, 0x13, 0xc0004bde58, 0x1, 0x1, 0x39, 0xbc1, 0x0)
2020-08-10T17:19:58.0363931Z 17:19:58 /opt/hostedtoolcache/go/1.14.5/x64/src/reflect/value.go:321 +0xd4
2020-08-10T17:19:58.0379432Z 17:19:58 github.com/goharbor/harbor/src/vendor/github.com/stretchr/testify/suite.Run.func2(0xc000168240)
2020-08-10T17:19:58.0478009Z 17:19:58 /home/runner/work/harbor/harbor/src/github.com/goharbor/harbor/src/vendor/github.com/stretchr/testify/suite/suite.go:137 +0x373
2020-08-10T17:19:58.0495569Z 17:19:58 testing.tRunner(0xc000168240, 0xc00036aa80)
2020-08-10T17:19:58.0508292Z 17:19:58 /opt/hostedtoolcache/go/1.14.5/x64/src/testing/testing.go:991 +0x1ec
2020-08-10T17:19:58.0522259Z 17:19:58 created by testing.(*T).Run
2020-08-10T17:19:58.0537692Z 17:19:58 /opt/hostedtoolcache/go/1.14.5/x64/src/testing/testing.go:1042 +0x661
2020-08-10T17:19:58.0554109Z 17:19:58 === RUN TestHookAgentTestSuite/TestEventSendingError
2020-08-10T17:19:58.0588328Z 17:19:58 2020/08/10 17:19:58 Send hook event 'HookAgentTestSuite' to 'http://domian.com' failed with error: internal server error: for testing; push hook event to the queue for retrying later
2020-08-10T17:19:58.0602395Z 17:19:58 === RUN TestHookAgentTestSuite/TestRetryAndPopMin
2020-08-10T17:19:58.0617561Z 17:19:58 --- FAIL: TestHookAgentTestSuite (0.02s)
2020-08-10T17:19:58.0629393Z 17:19:58 --- FAIL: TestHookAgentTestSuite/TestEventSending (0.01s)
2020-08-10T17:19:58.0642650Z 17:19:58 --- PASS: TestHookAgentTestSuite/TestEventSendingError (0.00s)
2020-08-10T17:19:58.0654296Z 17:19:58 --- PASS: TestHookAgentTestSuite/TestRetryAndPopMin (0.01s)
2020-08-10T17:19:58.0665065Z 17:19:58 === RUN TestHookClientTestSuite
2020-08-10T17:19:58.0679109Z 17:19:58 === RUN TestHookClientTestSuite/TestHookClient
2020-08-10T17:19:58.0693673Z 17:19:58 === RUN TestHookClientTestSuite/TestReportStatusFailed
2020-08-10T17:19:58.0705393Z 17:19:58 --- PASS: TestHookClientTestSuite (0.01s)
2020-08-10T17:19:58.0716989Z 17:19:58 --- PASS: TestHookClientTestSuite/TestHookClient (0.00s)
2020-08-10T17:19:58.0728094Z 17:19:58 --- PASS: TestHookClientTestSuite/TestReportStatusFailed (0.00s)
2020-08-10T17:19:58.0744685Z 17:19:58 FAIL
```
