### ISSUE TITLE
prepare - location of server certificate files

### ISSUE THREAD

**Issue by BernardTsai** [goharbor/harbor#12435]
**Expected behavior and actual behavior:**

Expecting to successfully install harbor (v2.0.1) when following the installation instructions: 

  https://goharbor.io/docs/2.0.0/install-config/

Preparation step leads to an error that certificates could not be found.

**Steps to reproduce the problem:**

In step:

   https://goharbor.io/docs/2.0.0/install-config/configure-https/

Invoking the prepare script (v2.0.1) leads to the error message:

> prepare base dir is set to /root/harbor/harbor
Clearing the configuration file: /config/log/logrotate.conf
Clearing the configuration file: /config/log/rsyslog_docker.conf
Generated configuration file: /config/log/logrotate.conf
Generated configuration file: /config/log/rsyslog_docker.conf
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/app/commands/prepare.py", line 47, in prepare
    prepare_nginx(config_dict)
  File "/usr/src/app/utils/nginx.py", line 23, in prepare_nginx
    render_nginx_template(config_dict)
  File "/usr/src/app/utils/nginx.py", line 56, in render_nginx_template
    prepare_nginx_certs(config_dict['cert_key_path'], config_dict['cert_path'])
  File "/usr/src/app/utils/nginx.py", line 42, in prepare_nginx_certs
    shutil.copy2(host_ngx_cert_key_path, real_key_path)
  File "/usr/lib/python3.6/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/hostfs/etc/dockers/cert.d/....

It seems that the script is making use of a strange file location: /etc/dockers/cert.d

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.0.1]
- docker engine version: [19.03.12]
- docker-compose version: [1.26.2]

**Comment by BernardTsai** [comment]
This was a misconfiguration on my side.
