### ISSUE TITLE
Error while installing goharbor v2.0.1

### ISSUE THREAD

**Issue by EmPRio93** [goharbor/harbor#12520]
Hi! I'm trying to make a clean online installation, that's what i get from ./prepare 

Traceback (most recent call last):
  File "main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/app/commands/prepare.py", line 79, in prepare
    prepare_docker_compose(config_dict, with_clair, with_trivy, with_notary, with_chartmuseum)
  File "/usr/src/app/utils/docker_compose.py", line 25, in prepare_docker_compose
    'log_location': configs['log_location'],
KeyError: 'log_location'

In the harbor.yaml 
log:
  level: info
  rotate_count: 50
  rotate_size: 200M
  location: /var/log/harbor

**Comment by ninjadq** [comment]
could you provide your log in `harbor.yml` with the correct format?

**Comment by EmPRio93** [comment]
log:
  # options are debug, info, warning, error, fatal
  level: info
  # Log files are rotated log_rotate_count times before being removed. If count is 0, old versions are removed rather than rotated.
  rotate_count: 50
  # Log files are rotated only if they grow bigger than log_rotate_size bytes. If size is followed by k, the size is assumed to be in kilobytes. 
  # If the M is used, the size is in megabytes, and if G is used, the size is in gigabytes. So size 100, size 100k, size 100M and size 100G 
  # are all valid.
  rotate_size: 200M
  # The directory on your host that store log
  location: /var/log/harbor

**Comment by EmPRio93** [comment]
Hi, i have fixed the problem. It's was my error in the log config.

**Comment by koalp** [comment]
How have you solved the problem ? I can't find out why the key isn't recognized, even when I add a "log_location" entry in the `harbor.yml` file.
