### ISSUE TITLE
Unable to run replication task

### ISSUE THREAD

**Issue by MaxRink** [goharbor/harbor#12575]
**Expected behavior and actual behavior:**
Im trying to run an replication task agains k8s.gcr.io to fetch the following images: 
{kube-apiserver,kube-controller-manager,kube-scheduler,kube-proxy,pause,etcd,coredns}
Instead of an running job i get an Harbor core restart and Nullpointer panic

```
==> /var/log/harbor/core.log <==
Jul 25 00:32:36 172.28.0.1 core[1641]: 2020/07/24 22:32:36.924 #033[1;44m[D]#033[0m [middleware.go:52]  |      127.0.0.1|#033[97;42m 200 #033[0m|     175.27µs|   match|#033[97;44m GET     #033[0m /api/version   r:/api/version
Jul 25 00:32:36 172.28.0.1 core[1641]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 25 00:32:36 172.28.0.1 core[1641]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xb5cdbc]
Jul 25 00:32:36 172.28.0.1 core[1641]:
Jul 25 00:32:36 172.28.0.1 core[1641]: goroutine 4586 [running]:
Jul 25 00:32:36 172.28.0.1 core[1641]: github.com/goharbor/harbor/src/pkg/registry/auth.(*authorizer).Modify(0xc0009b0d70, 0xc000e6bd00, 0x0, 0x0)
Jul 25 00:32:36 172.28.0.1 core[1641]: #011/harbor/src/pkg/registry/auth/authorizer.go:73 +0x5c
Jul 25 00:32:36 172.28.0.1 core[1641]: github.com/goharbor/harbor/src/pkg/registry.(*client).do(0xc000871c80, 0xc000e6bd00, 0x0, 0x0, 0x0)
Jul 25 00:32:36 172.28.0.1 core[1641]: #011/harbor/src/pkg/registry/client.go:511 +0x596
Jul 25 00:32:36 172.28.0.1 core[1641]: github.com/goharbor/harbor/src/pkg/registry.(*client).listTags(0xc000871c80, 0xc00079eba0, 0x27, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
Jul 25 00:32:36 172.28.0.1 core[1641]: #011/harbor/src/pkg/registry/client.go:224 +0xd5
Jul 25 00:32:36 172.28.0.1 core[1641]: github.com/goharbor/harbor/src/pkg/registry.(*client).ListTags(0xc000871c80, 0xc00048acad, 0x7, 0x0, 0xc000861b02, 0x0, 0x7fde88081320, 0xc0015825e8)
Jul 25 00:32:36 172.28.0.1 core[1641]: #011/harbor/src/pkg/registry/client.go:200 +0x147
Jul 25 00:32:36 172.28.0.1 core[1641]: github.com/goharbor/harbor/src/replication/adapter/native.(*Adapter).listArtifacts(0xc00066f5a0, 0xc00048acad, 0x7, 0xc0004941c8, 0x1, 0x1, 0x8, 0xc001582628, 0xc001582708, 0xab5b29, ...)
Jul 25 00:32:36 172.28.0.1 core[1641]: #011/harbor/src/replication/adapter/native/adapter.go:219 +0x63
Jul 25 00:32:36 172.28.0.1 core[1641]: github.com/goharbor/harbor/src/replication/adapter/native.(*Adapter).FetchArtifacts.func1(0xc001582740, 0x1)
Jul 25 00:32:36 172.28.0.1 core[1641]: #011/harbor/src/replication/adapter/native/adapter.go:150 +0x8a
Jul 25 00:32:36 172.28.0.1 core[1641]: github.com/goharbor/harbor/src/common/utils.(*limitedConcurrentRunner).AddTask.func1(0xc0014368a0, 0xc000f18b40)
Jul 25 00:32:36 172.28.0.1 core[1641]: #011/harbor/src/common/utils/passports.go:107 +0xd2
Jul 25 00:32:36 172.28.0.1 core[1641]: created by github.com/goharbor/harbor/src/common/utils.(*limitedConcurrentRunner).AddTask
Jul 25 00:32:36 172.28.0.1 core[1641]: #011/harbor/src/common/utils/passports.go:93 +0x63
Jul 25 00:32:36 172.28.0.1 core[1641]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 25 00:32:36 172.28.0.1 core[1641]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xb5cdbc]
Jul 25 00:32:36 172.28.0.1 core[1641]:
Jul 25 00:32:36 172.28.0.1 core[1641]: goroutine 4584 [running]:
Jul 25 00:32:36 172.28.0.1 core[1641]: github.com/goharbor/harbor/src/pkg/registry/auth.(*authorizer).Modify(0xc0009b0d70, 0xc001060300, 0x0, 0x0)
Jul 25 00:32:36 172.28.0.1 core[1641]: #011/harbor/src/pkg/registry/auth/authorizer.go:73 +0x5c
Jul 25 00:32:36 172.28.0.1 core[1641]: github.com/goharbor/harbor/src/pkg/registry.(*client).do(0xc000871c80, 0xc001060300, 0x0, 0x0, 0x0)
Jul 25 00:32:36 172.28.0.1 core[1641]: #011/harbor/src/pkg/registry/client.go:511 +0x596
Jul 25 00:32:36 172.28.0.1 core[1641]: github.com/goharbor/harbor/src/pkg/registry.(*client).listTags(0xc000871c80, 0xc007953440, 0x25, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
Jul 25 00:32:36 172.28.0.1 core[1641]: #011/harbor/src/pkg/registry/client.go:224 +0xd5
Jul 25 00:32:36 172.28.0.1 core[1641]: github.com/goharbor/harbor/src/pkg/registry.(*client).ListTags(0xc000871c80, 0xc00048aca2, 0x5, 0x1, 0xc0011e1b02, 0x0, 0x7fde8028fe88, 0xc0007065e8)
Jul 25 00:32:36 172.28.0.1 core[1641]: #011/harbor/src/pkg/registry/client.go:200 +0x147
Jul 25 00:32:36 172.28.0.1 core[1641]: github.com/goharbor/harbor/src/replication/adapter/native.(*Adapter).listArtifacts(0xc00066f5a0, 0xc00048aca2, 0x5, 0xc0004941c8, 0x1, 0x1, 0x8, 0xc000706628, 0xc000706708, 0xab5b29, ...)
Jul 25 00:32:36 172.28.0.1 core[1641]: #011/harbor/src/replication/adapter/native/adapter.go:219 +0x63
Jul 25 00:32:36 172.28.0.1 core[1641]: github.com/goharbor/harbor/src/replication/adapter/native.(*Adapter).FetchArtifacts.func1(0xc000706740, 0x1)
Jul 25 00:32:36 172.28.0.1 core[1641]: #011/harbor/src/replication/adapter/native/adapter.go:150 +0x8a
Jul 25 00:32:36 172.28.0.1 core[1641]: github.com/goharbor/harbor/src/common/utils.(*limitedConcurrentRunner).AddTask.func1(0xc0014368a0, 0xc000f18aa0)
Jul 25 00:32:36 172.28.0.1 core[1641]: #011/harbor/src/common/utils/passports.go:107 +0xd2
Jul 25 00:32:36 172.28.0.1 core[1641]: created by github.com/goharbor/harbor/src/common/utils.(*limitedConcurrentRunner).AddTask
Jul 25 00:32:36 172.28.0.1 core[1641]: #011/harbor/src/common/utils/passports.go:93 +0x63
```

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.0.1
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by ywk253100** [comment]
Dup of https://github.com/goharbor/harbor/issues/11939 and already fixed, the fix will be available on 2.0.2
