### ISSUE TITLE
panic pulling artifact

### ISSUE THREAD

**Issue by xtreme-conor-nosal** [goharbor/harbor#12574]
While reviewing logs I saw a panic related to pulling:

```
panic: runtime error: index out of range [0] with length 0

goroutine 613994 [running]:
github.com/goharbor/harbor/src/controller/event/handler/internal.(*Handler).updatePullTime(0xc0000107f8, 0x20c6ca0, 0xc00120fb00, 0xc000447d50)
	/harbor/src/controller/event/handler/internal/artifact.go:70 +0x3cf
github.com/goharbor/harbor/src/controller/event/handler/internal.(*Handler).onPull.func1(0xc0000107f8, 0x20c6ca0, 0xc00120fb00, 0xc000447d50)
	/harbor/src/controller/event/handler/internal/artifact.go:53 +0x49
created by github.com/goharbor/harbor/src/controller/event/handler/internal.(*Handler).onPull
	/harbor/src/controller/event/handler/internal/artifact.go:53 +0x61
```

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.0.1]

**Comment by wy65701436** [comment]
hi @xtreme-conor-nosal are you pull a untagged artifact?

**Comment by xtreme-conor-nosal** [comment]
This is a production harbor instance, I'm not sure what specific action the user may have taken. Is there a specific log entry I could search for to see if an untagged artifact was pulled? Searching the `core` logs for `pull` only returns many instances of `[/pkg/notifier/notifier.go:204]: Handle notification with topic 'PULL_ARTIFACT': &event.PullArtifactEvent{ArtifactEvent:(*event.ArtifactEvent)(0xc0003225b0)}`

**Comment by paulliss** [comment]
Hello.
Got the same on production Harbor instance Version v2.2.2-56d7937f

`2021-08-12T08:39:18Z [DEBUG] [/core/service/token/creator.go:230]: scopes: [repository:data-hub/ngc-nemo:pull]
2021-08-12T08:39:18Z [DEBUG] [/core/service/token/authutils.go:50]: scopes: [repository:data-hub/ngc-nemo:pull]
2021-08-12T08:39:18Z [DEBUG] [/core/service/token/authutils.go:101]: user: galeleytner@xdomain.org, access: &{repository  data-hub/ngc-nemo [pull]}
2021-08-12T08:39:19Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id 9d7623a8-3f16-42a2-a999-7c77b4c4802f to the logger for the request GET /v2/data-hub/ngc-nemo/manifests/sha256:e99e82fb7ed611459d3849a814e1d3c9c60e96183c38d0696f2e3c3472de6b4e
2021-08-12T08:39:19Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:52]: In artifact info middleware, url: /v2/data-hub/ngc-nemo/manifests/sha256:e99e82fb7ed611459d3849a814e1d3c9c60e96183c38d0696f2e3c3472de6b4e
2021-08-12T08:39:19Z [INFO] [/pkg/notifier/notifier.go:204]: Handle notification with Handler 'InternalArtifact' on topic 'PULL_ARTIFACT': ID-12313, Repository-data-hub/ngc-nemo Tags-[] Digest-sha256:e99e82fb7ed611459d3849a814e1d3c9c60e96183c38d0696f2e3c3472de6b4e Operator-galeleytner@xdomain.org OccurAt-2021-08-12 08:39:19
2021-08-12T08:39:19Z [DEBUG] [/controller/event/handler/webhook/artifact/artifact.go:76]: cannot find policy for PULL_ARTIFACT event: ID-12313, Repository-data-hub/ngc-nemo Tags-[] Digest-sha256:e99e82fb7ed611459d3849a814e1d3c9c60e96183c38d0696f2e3c3472de6b4e Operator-galeleytner@xdomain.org OccurAt-2021-08-12 08:39:19
2021-08-12T08:39:19Z [INFO] [/pkg/notifier/notifier.go:204]: Handle notification with Handler 'ArtifactWebhook' on topic 'PULL_ARTIFACT': ID-12313, Repository-data-hub/ngc-nemo Tags-[] Digest-sha256:e99e82fb7ed611459d3849a814e1d3c9c60e96183c38d0696f2e3c3472de6b4e Operator-galeleytner@xdomain.org OccurAt-2021-08-12 08:39:19
2021-08-12T08:39:20Z [INFO] [/pkg/notifier/notifier.go:204]: Handle notification with Handler 'AuditLog' on topic 'PULL_ARTIFACT': ID-12313, Repository-data-hub/ngc-nemo Tags-[] Digest-sha256:e99e82fb7ed611459d3849a814e1d3c9c60e96183c38d0696f2e3c3472de6b4e Operator-galeleytner@xdomain.org OccurAt-2021-08-12 08:39:19`
