### ISSUE TITLE
GitLab Pull Replication Issue

### ISSUE THREAD

**Issue by pcfens** [goharbor/harbor#12825]
I've created a GitLab registry and a pull replication rule, but when I run it the replication, Harbor's core service crashes. Of course it's possible I have something configured wrong (I can't find a lot of documentation on this, but am happy to submit a PR once I have this figured out).

The steps I've followed:
1. Create a registry:
- Provider: Gitlab
- Name: gitlab.example.com
- Endpoint URL: https://gitlab.example.com/
- Access ID: The personal access token associated with my account
- Access Secret: Blank
- Verify Certificate: checked

2. Create a replication rule:
- Name: test-replication
- Replication mode: Pull-based
- Source registry: gitlab.example.com-https://gitlab.example.com
- Source resource filter: it/nix/myproject (I've also tried it/** here)
- Tag: *
- Destination namespace: test
- Trigger Mode: Manual

3. Trigger the rule

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.0.2
- docker engine version: 19.03.12
- docker-compose version: 1.25.5

**Log Files**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xf117c0]

goroutine 152678 [running]:
github.com/goharbor/harbor/src/replication/adapter/gitlab.(*Client).getProjectsByName(0x0, 0xc000ed3f83, 0x3, 0x1, 0x1, 0x1, 0xc000c774a0, 0x5)
	/harbor/src/replication/adapter/gitlab/client.go:103 +0x40
github.com/goharbor/harbor/src/replication/adapter/gitlab.(*adapter).FetchArtifacts(0xc000839630, 0xc000cded20, 0x2, 0x2, 0xc000839630, 0x1, 0x1, 0x1, 0x0)
	/harbor/src/replication/adapter/gitlab/adapter.go:98 +0xada
github.com/goharbor/harbor/src/replication/operation/flow.fetchResources(0x22e0a80, 0xc000839630, 0xc000a289a0, 0x22e0b40, 0xc00061bef0, 0x0, 0x0, 0x0)
	/harbor/src/replication/operation/flow/stage.go:93 +0x633
github.com/goharbor/harbor/src/replication/operation/flow.(*copyFlow).Run(0xc000838e60, 0x0, 0x0, 0x1d9bd00, 0x1da0301, 0xc000838e60)
	/harbor/src/replication/operation/flow/copy.go:58 +0x601
github.com/goharbor/harbor/src/replication/operation/flow.(*controller).Start(0x33ce678, 0x22a8fc0, 0xc000838e60, 0xc0008eec60, 0x0, 0x0)
	/harbor/src/replication/operation/flow/controller.go:36 +0x39
github.com/goharbor/harbor/src/replication/operation.(*controller).StartReplication.func1(0xc00017be80, 0xb, 0xc000a289a0, 0x0)
	/harbor/src/replication/operation/controller.go:95 +0x1b7
created by github.com/goharbor/harbor/src/replication/operation.(*controller).StartReplication
	/harbor/src/replication/operation/controller.go:90 +0x167
```

I tried a little bit of local debugging by adding
```go
	fmt.Printf("%s", c.url)
	fmt.Printf("%s", name)
```
to the top of the [getProjectsByName](https://github.com/goharbor/harbor/blob/master/src/replication/adapter/gitlab/client.go#L101-L108) method. After adding the two lines it appears that things are crashing when `c.url` is referenced, so I suspect I've either mis-configured something, but can't seem to find where.

**Comment by d2dyno** [comment]
I have this issue still on 2.1.0-rc2

**Comment by pcfens** [comment]
Unfortunately I'm still having this issue in 2.0.3 as well. When I run the manual replication with the same settings as above I get

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xf149d0]

goroutine 1737 [running]:
github.com/goharbor/harbor/src/replication/adapter/gitlab.(*Client).getProjectsByName(0x0, 0xc000b399a3, 0x10, 0x1, 0xffffffffffffffff, 0x10, 0xc000ccde40, 0x4)
	/harbor/src/replication/adapter/gitlab/client.go:103 +0x40
github.com/goharbor/harbor/src/replication/adapter/gitlab.(*adapter).searchByPattern(0xc0009a9220, 0xc000b399a0, 0x1e, 0x40b2fd, 0x1e60560, 0xb15370)
	/harbor/src/replication/adapter/gitlab/adapter.go:194 +0x3e7
github.com/goharbor/harbor/src/replication/adapter/gitlab.(*adapter).FetchArtifacts(0xc0009a9220, 0xc001005a90, 0x2, 0x2, 0xc0009a9220, 0x1, 0x1, 0x1, 0x0)
	/harbor/src/replication/adapter/gitlab/adapter.go:96 +0xdd
github.com/goharbor/harbor/src/replication/operation/flow.fetchResources(0x22e7ea0, 0xc0009a9220, 0xc00084ec60, 0x22e7f60, 0xc000fee720, 0x0, 0x0, 0xc0000bf970)
	/harbor/src/replication/operation/flow/stage.go:93 +0x633
github.com/goharbor/harbor/src/replication/operation/flow.(*copyFlow).Run(0xc0009a8c80, 0x0, 0x0, 0x1da1ba0, 0x2289301, 0xc0009a8c80)
	/harbor/src/replication/operation/flow/copy.go:58 +0x601
github.com/goharbor/harbor/src/replication/operation/flow.(*controller).Start(0x33d8738, 0x22b0340, 0xc0009a8c80, 0x44f567, 0x0, 0xc001066178)
	/harbor/src/replication/operation/flow/controller.go:36 +0x39
github.com/goharbor/harbor/src/replication/operation.(*controller).StartReplication.func1(0xc000797500, 0x1, 0xc00084ec60, 0x0)
	/harbor/src/replication/operation/controller.go:95 +0x1b7
created by github.com/goharbor/harbor/src/replication/operation.(*controller).StartReplication
	/harbor/src/replication/operation/controller.go:90 +0x167
```
