### ISSUE TITLE
Version 2.1.0 USES external storage to report errors

### ISSUE THREAD

**Issue by system51** [goharbor/harbor#13172]
I follow the instructions in the official website to close `data_volume` But there was an error。I'm like an NFS server for storage

```
# The default data volume
# data_volume: /data
storage_service:
  filesystem:
    rootdirectory: /harbor_data/registry
    maxthreads: 100
```

```
Clearing the configuration file: /config/jobservice/env
Clearing the configuration file: /config/jobservice/config.yml
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/app/commands/prepare.py", line 39, in prepare
    config_dict = parse_yaml_config(conf, with_notary=with_notary, with_clair=with_clair, with_trivy=with_trivy, with_chartmuseum=with_chartmuseum)
  File "/usr/src/app/utils/configs.py", line 179, in parse_yaml_config
    config_dict['data_volume'] = configs['data_volume']
KeyError: 'data_volume'
```

**Comment by bitsf** [comment]
don't close data_volume, just add new storage_service

**Comment by system51** [comment]
@bitsf  An error occurred, as below

```
Sep 28 13:45:32 172.28.0.1 registry[89126]: time="2020-09-28T05:45:32.053623118Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code=unknown err.detail="filesystem: mkdir /harbor_data: permission denied" err.message="unknown error" go.version=go1.14.7 http.request.host=images.harbor.com http.request.id=f0ad01e6-6f2b-4943-a3d6-455d26327259 http.request.method=POST http.request.remoteaddr=10.15.1.6 http.request.uri="/v2/linux-test/nginx/blobs/uploads/" http.request.useragent="docker/19.03.12 go/go1.13.10 git-commit/48a66213fe kernel/4.18.0-147.el8.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.12 \(linux\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=4.679346ms http.response.status=500 http.response.written=152 vars.name="linux-test/nginx" 
```

**Comment by ninjadq** [comment]
please check you have the right privileges to create dir and files

**Comment by system51** [comment]
@ninjadq I have set the permissions to 777

**Comment by ninjadq** [comment]
This seems a permission issue on NFS side. Could you double check the NFS configs

**Comment by system51** [comment]
@ninjadq Do I need to enable external storage parameters when I use NFS as storage?

```
# The default data volume
data_volume: /harbor_data
#storage_service:
#  filesystem:
#    rootdirectory: /harbor_data
#    maxthreads: 100
```

```
[root@k8s-m2 harbor]# df -hT
Filesystem             Type      Size  Used Avail Use% Mounted on
devtmpfs               devtmpfs  3.8G     0  3.8G   0% /dev
tmpfs                  tmpfs     3.9G     0  3.9G   0% /dev/shm
tmpfs                  tmpfs     3.9G  410M  3.5G  11% /run
tmpfs                  tmpfs     3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/sda3              xfs        31G  7.2G   24G  24% /
/dev/sdb               xfs        60G  461M   60G   1% /data
/dev/sda1              ext4      976M  132M  778M  15% /boot
10.15.1.5:/data/images nfs4       60G  816M   60G   2% /harbor_data
```

I use this configuration service everything is normal

**Comment by geewhizsmith** [comment]
Hello, I had the same or a very similar problem, and have an explanation and steps to make it work.

The "install.sh" and "prepare" or the templates they use do not account for the
setting of a "rootdirectory", and so no "volume" is set in "docker-compose.yml"
to enable the setting to work.

To make it work with my setup I did this...

    1) configure "rootdirectory" to point to my mounted NFS storage:
        harbor.yml
            storage_service:
              filesystem:
                rootdirectory: /mnt/storage/harbor-registry
                maxthreads: 100

    2) run the installation script and shut the installation down (it was running but could not store files)
        sudo ./install.sh
        sudo docker compose down --volumes

    3) add configuration for the volume (and make a backup of the file in case somebody ran the base "install.sh")
        sudo vi docker-compose.yml
            services:
              registry:
                volumes:
                  - /mnt/storage/harbor-registry:/mnt/storage/harbor-registry
        sudo cp docker-compose.yml docker-compose.yml-EDITED_BACKUP

    4) and start it again
        sudo docker compose up --detach

And in my README for the service, I put a warning on the restart notes:

    diff docker-compose.yml docker-compose.yml-EDITED_BACKUP || echo "WARNING:  docker-compose.yml does is different from docker-compose.yml-EDITED_BACKUP"
    sudo docker compose down --volumes
    sudo docker compose up --detach

I am going to open a new issue, but I wanted to drop this comment on a number of
threads where other people might find it while tring to do a fix of their own.
