### ISSUE TITLE
Build from source code failed

### ISSUE THREAD

**Issue by LasseChi** [goharbor/harbor#13319]
**Expected behavior and actual behavior:**
When I run the command: make install, an error occurs in the 21st step of building the portal image, the error is as follows:
```
21/33 : RUN node --max_old_space_size=2048 'node_modules/@angular/cli/bin/ng' build --prod
 ---> Running in 5598aa8fee82
Option "lazy" is deprecated: Use 'inject' option with 'false' value instead.
Option "lazy" is deprecated: Use 'inject' option with 'false' value instead.
Compiling @angular/core : es2015 as esm2015
Compiling @angular/animations : es2015 as esm2015
Compiling @angular/animations/browser : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @ngx-translate/core : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling ngx-cookie : module as esm5
Compiling @angular/router : es2015 as esm2015
Compiling @angular/platform-browser/animations : es2015 as esm2015
Compiling @clr/angular : es2015 as esm2015
Compiling ngx-markdown : es2015 as esm2015
Compiling @ngx-translate/http-loader : es2015 as esm2015

ERROR in main.a57710ccdc3ac09e60e0.js from Terser
Error: Call retries were exceeded
    at ChildProcessWorker.initialize (/build_dir/node_modules/jest-worker/build/workers/ChildProcessWorker.js:193:21)
    at ChildProcessWorker._onExit (/build_dir/node_modules/jest-worker/build/workers/ChildProcessWorker.js:274:12)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)

chunk {} runtime.acf0dec4155e77772545.js (runtime) 1.45 kB [entry] [rendered]
chunk {1} dark-theme.css (dark-theme) 387 kB [initial] [rendered]
chunk {2} light-theme.css (light-theme) 517 kB [initial] [rendered]
chunk {3} main.a57710ccdc3ac09e60e0.js (main) 11.2 MB [initial] [rendered]
chunk {4} polyfills-es5.5b991c65805c64109f17.js (polyfills-es5) 82.9 kB [initial] [rendered]
chunk {5} styles.4a59a77b36322bddab82.css (styles) 660 kB [initial] [rendered]
chunk {scripts} scripts.bd8f7597c29e5618bc28.js (scripts) 969 kB [entry] [rendered]
Date: 2020-10-21T02:53:21.109Z - Hash: 84d33a9f9af9522a047f - Time: 178497ms
The command '/bin/sh -c node --max_old_space_size=2048 'node_modules/@angular/cli/bin/ng' build --prod' returned a non-zero code: 1
make[1]: *** [_build_portal] Error 1
make: *** [build] Error 2

```

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.1.0
- docker engine version: 19.03.12
- docker-compose version: 1.26.2
- go version: 1.15
- OS: osx catalina 10.15.7

**Comment by AllForNothing** [comment]
@LasseChi It seems the NG building process is running out of memery , see https://github.com/angular/angular-cli/issues/16515
Try modifying  "RUN node --max_old_space_size=2048 'node_modules/@angular/cli/bin/ng' build --prod"  to "RUN node --max_old_space_size=4096 'node_modules/@angular/cli/bin/ng' build --prod"  in ./make/photon/portal/Dockerfile
and see if it works for you

**Comment by LasseChi** [comment]
@AllForNothing  
I modified the Dockerfile according to your suggestion. I tried `--max_old_space_size=4096` and `--max_old_space_size=6144`. The test result still failed to create, and the same error was reported.

The `node --max_old_space_size=2048 'node_modules/@angular/cli/bin/ng' build --prod` command can be executed normally in the ./src/portal directory. 
I tried to comment out the following lines in ./make/photon/portal/Dockerfile,
```
......
ENV NPM_CONFIG_REGISTRY=${npm_registry}
#(Execute these three commands in the local ./src/portal directory)
#RUN npm install --unsafe-perm
#RUN npm run generate-build-timestamp
#RUN node --max_old_space_size=6144 'node_modules/@angular/cli/bin/ng' build --prod

FROM ${harbor_base_namespace}/harbor-portal-base:${harbor_base_image_version}
......
```
Then go back to the root directory and execute `make install`. Finally, Harbor was successfully created and can run normally

**Comment by AllForNothing** [comment]
@LasseChi  I'm closing it.  Please open another issue if  you have any questions.

**Comment by lmdkfs** [comment]
The same problem i encountered.
```
Done.
building portal container for photon...
/usr/local/bin/docker build --build-arg harbor_base_image_version=dev --build-arg harbor_base_namespace=goharbor --build-arg npm_registry=https://registry.npmjs.org -f /Users/zhuruiqing/data/go-projects/harbor/make/photon/portal/Dockerfile -t goharbor/harbor-portal:dev .
[+] Building 125.6s (22/29)
 => [internal] load .dockerignore                                                                                                                                                                                                                        0.0s
[+] Building 125.7s (22/29)
[+] Building 255.3s (23/29)
 => [internal] load .dockerignore                                                                                                                                                                                                                        0.0s
 => => transferring context: 34B                                                                                                                                                                                                                         0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                     0.0s
 => => transferring dockerfile: 1.89kB                                                                                                                                                                                                                   0.0s
 => [internal] load metadata for docker.io/goharbor/harbor-portal-base:dev                                                                                                                                                                               7.3s
 => [internal] load metadata for docker.io/library/node:10.15.0                                                                                                                                                                                          7.2s
 => [nodeportal 1/17] FROM docker.io/library/node:10.15.0@sha256:c9a51b7f2f3774f39058bb436ed62d66f415f32b9386e5c35c3fb4854722ed84                                                                                                                        0.0s
 => [internal] load build context                                                                                                                                                                                                                        0.3s
 => => transferring context: 4.33MB                                                                                                                                                                                                                      0.3s
 => [stage-1 1/7] FROM docker.io/goharbor/harbor-portal-base:dev@sha256:ba61ba5becffc6ab24c39f5505515f05bbd42a9f5e6b0b2ea76d3d05543697f4                                                                                                                 0.0s
 => CACHED [nodeportal 2/17] WORKDIR /build_dir                                                                                                                                                                                                          0.0s
 => CACHED [nodeportal 3/17] RUN apt-get update     && apt-get install -y --no-install-recommends python-yaml=3.12-1                                                                                                                                     0.0s
 => CACHED [nodeportal 4/17] COPY src/portal/package.json /build_dir                                                                                                                                                                                     0.0s
 => CACHED [nodeportal 5/17] COPY src/portal/package-lock.json /build_dir                                                                                                                                                                                0.0s
 => CACHED [nodeportal 6/17] COPY src/portal/scripts /build_dir                                                                                                                                                                                          0.0s
 => CACHED [nodeportal 7/17] COPY ./api/v2.0/legacy_swagger.yaml /build_dir/swagger.yaml                                                                                                                                                                 0.0s
 => CACHED [nodeportal 8/17] COPY ./api/v2.0/swagger.yaml /build_dir/swagger2.yaml                                                                                                                                                                       0.0s
 => CACHED [nodeportal 9/17] COPY ./api/swagger.yaml /build_dir/swagger3.yaml                                                                                                                                                                            0.0s
 => CACHED [nodeportal 10/17] RUN python -c 'import sys, yaml, json; y=yaml.load(sys.stdin.read()); print json.dumps(y)' < swagger.yaml > swagger.json                                                                                                   0.0s
 => CACHED [nodeportal 11/17] RUN python -c 'import sys, yaml, json; y=yaml.load(sys.stdin.read()); print json.dumps(y)' < swagger2.yaml > swagger2.json                                                                                                 0.0s
 => CACHED [nodeportal 12/17] RUN python -c 'import sys, yaml, json; y=yaml.load(sys.stdin.read()); print json.dumps(y)' < swagger3.yaml > swagger3.json                                                                                                 0.0s
 => CACHED [nodeportal 13/17] COPY ./LICENSE /build_dir                                                                                                                                                                                                  0.0s
 => CACHED [nodeportal 14/17] COPY src/portal /build_dir                                                                                                                                                                                                 0.0s
 => CACHED [nodeportal 15/17] RUN npm install --unsafe-perm                                                                                                                                                                                              0.0s
 => CACHED [nodeportal 16/17] RUN npm run generate-build-timestamp                                                                                                                                                                                       0.0s
 => ERROR [nodeportal 17/17] RUN node --max_old_space_size=4096 'node_modules/@angular/cli/bin/ng' build --prod                                                                                                                                        247.5s
------
 > [nodeportal 17/17] RUN node --max_old_space_size=4096 'node_modules/@angular/cli/bin/ng' build --prod:
#23 8.805 Browserslist: caniuse-lite is outdated. Please run next command `npm update`
#23 247.2 Killed
------
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c node --max_old_space_size=4096 'node_modules/@angular/cli/bin/ng' build --prod]: runc did not terminate sucessfully
make[1]: *** [_build_portal] Error 1
make: *** [build] Error 2
```

I tried to comment out the following lines in ./make/photon/portal/Dockerfile, according to @LasseCh method，but Encountered the following problems：

```
 => ERROR [stage-1 2/7] COPY --from=nodeportal /build_dir/dist /usr/share/nginx/html                                                                                                                                                                     0.0s
------
 > [stage-1 2/7] COPY --from=nodeportal /build_dir/dist /usr/share/nginx/html:
------
failed to solve with frontend dockerfile.v0: failed to build LLB: failed to compute cache key: "/build_dir/dist" not found: not found
make[1]: *** [_build_portal] Error 1
make: *** [build] Error 2
```

how to resolve.

**Comment by LasseChi** [comment]
@lmdkfs Your compilation error and mine are caused by different reasons, so you can’t solve it with my solution
Duplicate of

**Comment by lmdkfs** [comment]
> @lmdkfs Your compilation error and mine are caused by different reasons, so you can’t solve it with my solution
Many thanks, i should create new issue.
