### ISSUE TITLE
Core container crashing when GitLab replication rule is run

### ISSUE THREAD

**Issue by jsolbrig** [goharbor/harbor#13366]
I have a self-hosted gitlab instance from which I would like to pull docker images. I am able to create a replication endpoint pointing to my gitlab instance. Using a username and personal access token as credentials, the endpoint shows that it is "healthy" and when I run a connection test, it succeeds. 

I can also create a replication rule with a manual trigger, but it does not appear to work. Instead, when I run the rule the `core` container crashes with a segfault. I have tried creating this rule with `name` and `tag` unspecified, set explicitly to wildcards `**`, and set to explicit values. In each instance, the rule is created and shows as "enabled". When I trigger the rule, however, I get a 502 error in the Harbor interface. This is because the `core` container crashes.

**Note that the traceback differs based on whether I'm using wildcards or explicitly defining `name` and `tag`.**

**When using wildcards, the log output from the core container ends with:**

```
2020-10-27T01:18:37Z [INFO] [/replication/registry/healthcheck.go:60]: Start regular health check for registries with interval 5m0s
2020-10-27T01:18:40Z [WARNING] [/replication/adapter/gitlab/client.go:77]: Schemas [] are unsupported
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xfb09d0]

goroutine 378 [running]:
github.com/goharbor/harbor/src/replication/adapter/gitlab.(*Client).getProjectsByName(0x0, 0xc000ee052d, 0xb, 0x1, 0x0, 0x2, 0xc0008c3920, 0x3)
	/harbor/src/replication/adapter/gitlab/client.go:103 +0x40
github.com/goharbor/harbor/src/replication/adapter/gitlab.(*adapter).searchByPattern(0xc0003f9ef0, 0xc00049e760, 0x1c, 0x40b70d, 0x1f67680, 0xbb13a0)
	/harbor/src/replication/adapter/gitlab/adapter.go:171 +0x184
github.com/goharbor/harbor/src/replication/adapter/gitlab.(*adapter).FetchArtifacts(0xc0003f9ef0, 0xc000bbc980, 0x2, 0x2, 0xc0003f9ef0, 0x1, 0x1, 0x1, 0x0)
	/harbor/src/replication/adapter/gitlab/adapter.go:96 +0xdd
github.com/goharbor/harbor/src/replication/operation/flow.fetchResources(0x24f7f00, 0xc0003f9ef0, 0xc000859a20, 0x24f7fc0, 0xc000924130, 0x0, 0x0, 0x0)
	/harbor/src/replication/operation/flow/stage.go:93 +0x633
github.com/goharbor/harbor/src/replication/operation/flow.(*copyFlow).Run(0xc0006b8140, 0x0, 0x0, 0x1eb7e80, 0x1, 0xc0006b8140)
	/harbor/src/replication/operation/flow/copy.go:58 +0x601
github.com/goharbor/harbor/src/replication/operation/flow.(*controller).Start(0x36d0528, 0x24bfae0, 0xc0006b8140, 0x0, 0x0, 0x0)
	/harbor/src/replication/operation/flow/controller.go:36 +0x39
github.com/goharbor/harbor/src/replication/operation.(*controller).StartReplication.func1(0xc000b38300, 0x9, 0xc000859a20, 0x0)
	/harbor/src/replication/operation/controller.go:90 +0x1a0
created by github.com/goharbor/harbor/src/replication/operation.(*controller).StartReplication
	/harbor/src/replication/operation/controller.go:85 +0x167
```

**When using a two-level (i.e. `group/repo`) path for `name`, the log output from the `core` container ends with:**

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xfb09d0]

goroutine 2296 [running]:
github.com/goharbor/harbor/src/replication/adapter/gitlab.(*Client).getProjectsByName(0x0, 0xc000ccec68, 0x9, 0x1, 0x0, 0x1, 0xc0005ca660, 0x2)
	/harbor/src/replication/adapter/gitlab/client.go:103 +0x40
github.com/goharbor/harbor/src/replication/adapter/gitlab.(*adapter).searchByPattern(0xc0009ba1e0, 0xc000cb0320, 0x11, 0x40b70d, 0x1f67680, 0xbb13a0)
	/harbor/src/replication/adapter/gitlab/adapter.go:171 +0x184
github.com/goharbor/harbor/src/replication/adapter/gitlab.(*adapter).FetchArtifacts(0xc0009ba1e0, 0xc000682850, 0x2, 0x2, 0xc0009ba1e0, 0x1, 0x1, 0x1, 0x0)
	/harbor/src/replication/adapter/gitlab/adapter.go:96 +0xdd
github.com/goharbor/harbor/src/replication/operation/flow.fetchResources(0x24f7f00, 0xc0009ba1e0, 0xc001344370, 0x24f7fc0, 0xc0005325d0, 0x0, 0x0, 0x0)
	/harbor/src/replication/operation/flow/stage.go:93 +0x633
github.com/goharbor/harbor/src/replication/operation/flow.(*copyFlow).Run(0xc000cd7400, 0x0, 0x0, 0x1eb7e80, 0x1, 0xc000cd7400)
	/harbor/src/replication/operation/flow/copy.go:58 +0x601
github.com/goharbor/harbor/src/replication/operation/flow.(*controller).Start(0x36d0528, 0x24bfae0, 0xc000cd7400, 0xc000e0e150, 0x0, 0x0)
	/harbor/src/replication/operation/flow/controller.go:36 +0x39
github.com/goharbor/harbor/src/replication/operation.(*controller).StartReplication.func1(0xc000bf61c0, 0xf, 0xc001344370, 0x0)
	/harbor/src/replication/operation/controller.go:90 +0x1a0
created by github.com/goharbor/harbor/src/replication/operation.(*controller).StartReplication
	/harbor/src/replication/operation/controller.go:85 +0x167
```

I just barely know a little golang, but from the time I've spent starting at the code, it looks like the same error is occurring in two functions. I think that in `replication/adapter/gitlab/client.go` on lines [94](https://github.com/goharbor/harbor/blob/ce21e134ed87bd42a7e429d8a0b0d7d7fe065fa0/src/replication/adapter/gitlab/client.go#L94) and [103](https://github.com/goharbor/harbor/blob/ce21e134ed87bd42a7e429d8a0b0d7d7fe065fa0/src/replication/adapter/gitlab/client.go#L103), `c.url` is set to `nul` for some reason.

**Expected behavior and actual behavior:**
Replication should be possible when properly configured.

**Steps to reproduce the problem:**
1. Stand up an instance of Harbor (I'm doing this via the v1.5.0 helm chart in kubernetes).
1. Set up a self-served instance of gitlab.
2. Create a project under any group/name.
3. Upload a docker image to the project's docker registry.
4. Add the gitlab instance as an endpoint in Harbor.
5. Add a replication rule for the project.
6. Manually execute the replication rule.

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.1.0]
- helm chart version: [1.5.0]
- kubernetes version: [1.19.0]
- docker engine version: [19.03.13]
- docker-compose version: N/A

**Additional context:**

- **Log files:**
The error appears in the core container. I don't see anything interesting happening anywhere else.

```
> k logs -f -n argocd harbor-harbor-core-6cf849898f-6bzgn
Appending internal tls trust CA to ca-bundle ...
find: /etc/harbor/ssl: No such file or directory
Internal tls trust CA appending is Done.
2020-10-27T01:17:21Z [INFO] [/controller/artifact/annotation/parser.go:71]: the annotation parser to parser artifact annotation version v1alpha1 registered
2020-10-27T01:17:21Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.cncf.helm.config.v1+json registered
2020-10-27T01:17:21Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.cnab.manifest.v1 registered
2020-10-27T01:17:21Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.oci.image.index.v1+json registered
2020-10-27T01:17:21Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.docker.distribution.manifest.list.v2+json registered
2020-10-27T01:17:21Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.docker.distribution.manifest.v1+prettyjws registered
2020-10-27T01:17:21Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.oci.image.config.v1+json registered
2020-10-27T01:17:21Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.docker.container.image.v1+json registered
2020-10-27T01:17:21Z [INFO] [/replication/adapter/native/adapter.go:36]: the factory for adapter docker-registry registered
2020-10-27T01:17:21Z [INFO] [/replication/adapter/harbor/adaper.go:31]: the factory for adapter harbor registered
2020-10-27T01:17:21Z [INFO] [/replication/adapter/dockerhub/adapter.go:25]: Factory for adapter docker-hub registered
2020-10-27T01:17:21Z [INFO] [/replication/adapter/huawei/huawei_adapter.go:27]: the factory of Huawei adapter was registered
2020-10-27T01:17:21Z [INFO] [/replication/adapter/googlegcr/adapter.go:35]: the factory for adapter google-gcr registered
2020-10-27T01:17:21Z [INFO] [/replication/adapter/awsecr/adapter.go:47]: the factory for adapter aws-ecr registered
2020-10-27T01:17:21Z [INFO] [/replication/adapter/azurecr/adapter.go:15]: Factory for adapter azure-acr registered
2020-10-27T01:17:21Z [INFO] [/replication/adapter/aliacr/adapter.go:31]: the factory for adapter ali-acr registered
2020-10-27T01:17:21Z [INFO] [/replication/adapter/jfrog/adapter.go:47]: the factory of jfrog artifactory adapter was registered
2020-10-27T01:17:21Z [INFO] [/replication/adapter/quay/adapter.go:41]: the factory of Quay adapter was registered
2020-10-27T01:17:21Z [INFO] [/replication/adapter/helmhub/adapter.go:30]: the factory for adapter helm-hub registered
2020-10-27T01:17:21Z [INFO] [/replication/adapter/gitlab/adapter.go:17]: the factory for adapter gitlab registered
2020-10-27T01:17:21Z [INFO] [/core/controllers/base.go:299]: Config path: /etc/core/app.conf
2020-10-27T01:17:21Z [INFO] [/core/main.go:162]: initializing configurations...
2020-10-27T01:17:21Z [INFO] [/core/config/config.go:84]: key path: /etc/core/key
2020-10-27T01:17:21Z [INFO] [/core/config/config.go:61]: init secret store
2020-10-27T01:17:21Z [INFO] [/core/config/config.go:64]: init project manager
2020-10-27T01:17:21Z [INFO] [/core/config/config.go:96]: initializing the project manager based on local database...
2020-10-27T01:17:21Z [INFO] [/core/main.go:164]: configurations initialization completed
2020-10-27T01:17:21Z [INFO] [/common/dao/base.go:65]: Registering database: type-PostgreSQL host-harbor-harbor-database port-5432 database-registry sslmode-"disable"
2020-10-27T01:17:21Z [INFO] [/common/dao/base.go:70]: Register database completed
2020-10-27T01:17:21Z [INFO] [/common/dao/pgsql.go:127]: Upgrading schema for pgsql ...
2020-10-27T01:17:21Z [INFO] [/common/dao/pgsql.go:130]: No change in schema, skip.
2020-10-27T01:17:21Z [INFO] [/migration/migration.go:58]: Abstracting artifact data to DB...
2020-10-27T01:17:21Z [INFO] [/migration/migration.go:67]: No need to abstract artifact data. Skip
2020-10-27T01:17:21Z [INFO] [/core/main.go:81]: User id: 1 already has its encrypted password.
2020-10-27T01:17:21Z [INFO] [/chartserver/cache.go:185]: Enable redis cache for chart caching
2020-10-27T01:17:21Z [INFO] [/chartserver/reverse_proxy.go:60]: New chart server traffic proxy with middlewares
2020-10-27T01:17:21Z [INFO] [/core/api/chart_repository.go:613]: API controller for chart repository server is successfully initialized
2020-10-27T01:17:21Z [INFO] [/core/main.go:235]: Registering Trivy scanner
2020-10-27T01:17:21Z [INFO] [/core/main.go:249]: Registering Clair scanner
2020-10-27T01:17:21Z [INFO] [/pkg/scan/init.go:62]: Scanner registration already exists: http://harbor-harbor-trivy:8080
2020-10-27T01:17:21Z [INFO] [/pkg/scan/init.go:62]: Scanner registration already exists: http://harbor-harbor-clair:8080
2020-10-27T01:17:21Z [INFO] [/core/main.go:271]: Setting Trivy as default scanner
2020-10-27T01:17:21Z [INFO] [/pkg/scan/init.go:77]: Skipped setting Trivy as the default scanner. The default scanner is already set to http://harbor-harbor-trivy:8080
2020-10-27T01:17:21Z [INFO] [/core/main.go:202]: initializing notification...
2020-10-27T01:17:21Z [INFO] [/pkg/notification/notification.go:47]: notification initialization completed
2020-10-27T01:17:21Z [INFO] [/core/main.go:221]: Version: v2.1.0, Git commit: a3eca103
2020/10/27 01:17:21.420 [I] [asm_amd64.s:1373]  http server Running on http://:8080
2020-10-27T01:18:37Z [INFO] [/replication/registry/healthcheck.go:60]: Start regular health check for registries with interval 5m0s
2020-10-27T01:18:40Z [WARNING] [/replication/adapter/gitlab/client.go:77]: Schemas [] are unsupported
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xfb09d0]

goroutine 378 [running]:
github.com/goharbor/harbor/src/replication/adapter/gitlab.(*Client).getProjectsByName(0x0, 0xc000ee052d, 0xb, 0x1, 0x0, 0x2, 0xc0008c3920, 0x3)
	/harbor/src/replication/adapter/gitlab/client.go:103 +0x40
github.com/goharbor/harbor/src/replication/adapter/gitlab.(*adapter).searchByPattern(0xc0003f9ef0, 0xc00049e760, 0x1c, 0x40b70d, 0x1f67680, 0xbb13a0)
	/harbor/src/replication/adapter/gitlab/adapter.go:171 +0x184
github.com/goharbor/harbor/src/replication/adapter/gitlab.(*adapter).FetchArtifacts(0xc0003f9ef0, 0xc000bbc980, 0x2, 0x2, 0xc0003f9ef0, 0x1, 0x1, 0x1, 0x0)
	/harbor/src/replication/adapter/gitlab/adapter.go:96 +0xdd
github.com/goharbor/harbor/src/replication/operation/flow.fetchResources(0x24f7f00, 0xc0003f9ef0, 0xc000859a20, 0x24f7fc0, 0xc000924130, 0x0, 0x0, 0x0)
	/harbor/src/replication/operation/flow/stage.go:93 +0x633
github.com/goharbor/harbor/src/replication/operation/flow.(*copyFlow).Run(0xc0006b8140, 0x0, 0x0, 0x1eb7e80, 0x1, 0xc0006b8140)
	/harbor/src/replication/operation/flow/copy.go:58 +0x601
github.com/goharbor/harbor/src/replication/operation/flow.(*controller).Start(0x36d0528, 0x24bfae0, 0xc0006b8140, 0x0, 0x0, 0x0)
	/harbor/src/replication/operation/flow/controller.go:36 +0x39
github.com/goharbor/harbor/src/replication/operation.(*controller).StartReplication.func1(0xc000b38300, 0x9, 0xc000859a20, 0x0)
	/harbor/src/replication/operation/controller.go:90 +0x1a0
created by github.com/goharbor/harbor/src/replication/operation.(*controller).StartReplication
	/harbor/src/replication/operation/controller.go:85 +0x167
```

**Comment by steven-zou** [comment]
Gitlab adapter is contributed by @lxShaDoWxl. Let's see if lxShaDoWxl can help to check this issue.


cc @bitsf

**Comment by steven-zou** [comment]
@jsolbrig 

It seems you have located the root cause of this issue. Is it possible for you to fix this issue?

**Comment by bitsf** [comment]
hi, please upgrade to >2.1.1, this should be fixed

**Comment by jsolbrig** [comment]
@bitsf Are you wanting me to test with 2.1.1 or with an unreleased version? With 2.1.1 I get the same error.

If you would like me to try building the docker image myself, is there a specific commit that I should try building from? It looks like the current master branch's head is failing its CI.

**Comment by jsolbrig** [comment]
I'd be happy to help debug this. I'm just starting to learn golang, but it seems fairly straightforward. Here's the log output from the core container.

```
> k logs -n argocd -f harbor-harbor-core-b7cc79d59-ggbdk
Appending internal tls trust CA to ca-bundle ...
find: /etc/harbor/ssl: No such file or directory
Internal tls trust CA appending is Done.
2020-11-10T17:33:31Z [INFO] [/controller/artifact/annotation/parser.go:71]: the annotation parser to parser artifact annotation version v1alpha1 registered
2020-11-10T17:33:31Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.cncf.helm.config.v1+json registered
2020-11-10T17:33:31Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.cnab.manifest.v1 registered
2020-11-10T17:33:31Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.oci.image.index.v1+json registered
2020-11-10T17:33:31Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.docker.distribution.manifest.list.v2+json registered
2020-11-10T17:33:31Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.docker.distribution.manifest.v1+prettyjws registered
2020-11-10T17:33:31Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.oci.image.config.v1+json registered
2020-11-10T17:33:31Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.docker.container.image.v1+json registered
2020-11-10T17:33:31Z [INFO] [/replication/adapter/native/adapter.go:36]: the factory for adapter docker-registry registered
2020-11-10T17:33:31Z [INFO] [/replication/adapter/harbor/adaper.go:31]: the factory for adapter harbor registered
2020-11-10T17:33:31Z [INFO] [/replication/adapter/dockerhub/adapter.go:25]: Factory for adapter docker-hub registered
2020-11-10T17:33:31Z [INFO] [/replication/adapter/huawei/huawei_adapter.go:27]: the factory of Huawei adapter was registered
2020-11-10T17:33:31Z [INFO] [/replication/adapter/googlegcr/adapter.go:35]: the factory for adapter google-gcr registered
2020-11-10T17:33:31Z [INFO] [/replication/adapter/awsecr/adapter.go:47]: the factory for adapter aws-ecr registered
2020-11-10T17:33:31Z [INFO] [/replication/adapter/azurecr/adapter.go:15]: Factory for adapter azure-acr registered
2020-11-10T17:33:31Z [INFO] [/replication/adapter/aliacr/adapter.go:31]: the factory for adapter ali-acr registered
2020-11-10T17:33:31Z [INFO] [/replication/adapter/jfrog/adapter.go:47]: the factory of jfrog artifactory adapter was registered
2020-11-10T17:33:31Z [INFO] [/replication/adapter/quay/adapter.go:55]: the factory of Quay adapter was registered
2020-11-10T17:33:31Z [INFO] [/replication/adapter/helmhub/adapter.go:30]: the factory for adapter helm-hub registered
2020-11-10T17:33:31Z [INFO] [/replication/adapter/gitlab/adapter.go:17]: the factory for adapter gitlab registered
2020-11-10T17:33:31Z [INFO] [/core/controllers/base.go:299]: Config path: /etc/core/app.conf
2020-11-10T17:33:31Z [INFO] [/core/main.go:162]: initializing configurations...
2020-11-10T17:33:31Z [INFO] [/core/config/config.go:84]: key path: /etc/core/key
2020-11-10T17:33:31Z [INFO] [/core/config/config.go:61]: init secret store
2020-11-10T17:33:31Z [INFO] [/core/config/config.go:64]: init project manager
2020-11-10T17:33:31Z [INFO] [/core/config/config.go:96]: initializing the project manager based on local database...
2020-11-10T17:33:31Z [INFO] [/core/main.go:164]: configurations initialization completed
2020-11-10T17:33:31Z [INFO] [/common/dao/base.go:65]: Registering database: type-PostgreSQL host-harbor-harbor-database port-5432 database-registry sslmode-"disable"
2020-11-10T17:33:31Z [INFO] [/common/dao/base.go:70]: Register database completed
2020-11-10T17:33:31Z [INFO] [/common/dao/pgsql.go:127]: Upgrading schema for pgsql ...
2020-11-10T17:33:31Z [INFO] [/common/dao/pgsql.go:130]: No change in schema, skip.
2020-11-10T17:33:31Z [INFO] [/migration/migration.go:58]: Abstracting artifact data to DB...
2020-11-10T17:33:31Z [INFO] [/migration/migration.go:67]: No need to abstract artifact data. Skip
2020-11-10T17:33:31Z [INFO] [/core/main.go:81]: User id: 1 already has its encrypted password.
2020-11-10T17:33:31Z [INFO] [/chartserver/cache.go:185]: Enable redis cache for chart caching
2020-11-10T17:33:31Z [INFO] [/chartserver/reverse_proxy.go:60]: New chart server traffic proxy with middlewares
2020-11-10T17:33:31Z [INFO] [/core/api/chart_repository.go:613]: API controller for chart repository server is successfully initialized
2020-11-10T17:33:31Z [INFO] [/core/main.go:235]: Registering Trivy scanner
2020-11-10T17:33:31Z [INFO] [/core/main.go:249]: Registering Clair scanner
2020-11-10T17:33:31Z [INFO] [/pkg/scan/init.go:62]: Scanner registration already exists: http://harbor-harbor-trivy:8080
2020-11-10T17:33:31Z [INFO] [/pkg/scan/init.go:62]: Scanner registration already exists: http://harbor-harbor-clair:8080
2020-11-10T17:33:31Z [INFO] [/core/main.go:271]: Setting Trivy as default scanner
2020-11-10T17:33:31Z [INFO] [/pkg/scan/init.go:77]: Skipped setting Trivy as the default scanner. The default scanner is already set to http://harbor-harbor-trivy:8080
2020-11-10T17:33:31Z [INFO] [/core/main.go:202]: initializing notification...
2020-11-10T17:33:31Z [INFO] [/pkg/notification/notification.go:47]: notification initialization completed
2020-11-10T17:33:31Z [INFO] [/core/main.go:221]: Version: v2.1.1, Git commit: 5f52168e
2020/11/10 17:33:31.817 [I] [asm_amd64.s:1373]  http server Running on http://:8080
2020-11-10T17:33:47Z [WARNING] [/core/systeminfo/imagestorage/filesystem/driver.go:51]: The path /data is not found, will return zero value of capacity
2020-11-10T17:33:52Z [ERROR] [/core/api/registry.go:358]: Can't delete registry 1,  1 replication policies use it as source registry
2020-11-10T17:34:10Z [WARNING] [/replication/adapter/gitlab/client.go:77]: Schemas [] are unsupported
2020-11-10T17:34:38Z [INFO] [/replication/registry/healthcheck.go:60]: Start regular health check for registries with interval 5m0s
2020-11-10T17:36:10Z [WARNING] [/core/systeminfo/imagestorage/filesystem/driver.go:51]: The path /data is not found, will return zero value of capacity
2020-11-10T17:39:30Z [WARNING] [/replication/adapter/gitlab/client.go:77]: Schemas [] are unsupported
2020-11-10T17:39:32Z [WARNING] [/replication/adapter/gitlab/client.go:77]: Schemas [] are unsupported
2020-11-10T17:39:38Z [WARNING] [/replication/adapter/gitlab/client.go:77]: Schemas [] are unsupported
2020-11-10T17:40:02Z [WARNING] [/replication/adapter/gitlab/client.go:77]: Schemas [] are unsupported
2020-11-10T17:42:03Z [WARNING] [/replication/adapter/gitlab/client.go:77]: Schemas [] are unsupported
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xfb0c70]

goroutine 2112 [running]:
github.com/goharbor/harbor/src/replication/adapter/gitlab.(*Client).getProjects(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/harbor/src/replication/adapter/gitlab/client.go:94 +0x40
github.com/goharbor/harbor/src/replication/adapter/gitlab.(*adapter).FetchArtifacts(0xc0005fb130, 0x0, 0x0, 0x0, 0xc0005fb130, 0x1, 0x1, 0x1, 0x0)
	/harbor/src/replication/adapter/gitlab/adapter.go:98 +0xa23
github.com/goharbor/harbor/src/replication/operation/flow.fetchResources(0x24f96a0, 0xc0005fb130, 0xc000ce5340, 0x24f9760, 0xc00095b5c0, 0x0, 0x0, 0x44841c)
	/harbor/src/replication/operation/flow/stage.go:93 +0x633
github.com/goharbor/harbor/src/replication/operation/flow.(*copyFlow).Run(0xc000345400, 0x0, 0x0, 0x1eb91a0, 0x40e201, 0xc000345400)
	/harbor/src/replication/operation/flow/copy.go:58 +0x601
github.com/goharbor/harbor/src/replication/operation/flow.(*controller).Start(0x36d2568, 0x24c1240, 0xc000345400, 0xc00071d440, 0xc000948c90, 0x20163c7)
	/harbor/src/replication/operation/flow/controller.go:36 +0x39
github.com/goharbor/harbor/src/replication/operation.(*controller).StartReplication.func1(0xc0008582c0, 0x15, 0xc000ce5340, 0x0)
	/harbor/src/replication/operation/controller.go:90 +0x1a0
created by github.com/goharbor/harbor/src/replication/operation.(*controller).StartReplication
	/harbor/src/replication/operation/controller.go:85 +0x167
```

**Comment by djdembeck** [comment]
I have this issue on 2.1.1 as well. Old issue shouldn't have been closed: https://github.com/goharbor/harbor/issues/12825
