### ISSUE TITLE
Prepare script fails with an error "FileNotFoundError: [Errno 2] No such file or directory"

### ISSUE THREAD

**Issue by allaboutopensource** [goharbor/harbor#13465]
After inserting the SSL certificate using the cert and key parameter in the harbor.yaml file and when i run the prepare script i get this error:

Traceback (most recent call last):
  File "main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/app/commands/prepare.py", line 49, in prepare
    prepare_nginx(config_dict)
  File "/usr/src/app/utils/nginx.py", line 23, in prepare_nginx
    render_nginx_template(config_dict)
  File "/usr/src/app/utils/nginx.py", line 56, in render_nginx_template
    prepare_nginx_certs(config_dict['cert_key_path'], config_dict['cert_path'])
  File "/usr/src/app/utils/nginx.py", line 42, in prepare_nginx_certs
    shutil.copy2(host_ngx_cert_key_path, real_key_path)
  File "/usr/lib/python3.6/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/hostfs/root/certs/abc.key'

SSL certificate paths is : /root/certs/ not sure why is it picking /hostfs/root/certs
I checked the dns setting and they are fine too. Able to restart the harbor service using the docker-compose. 

harbor Version v2.1.1-5f52168e
CentOS Linux release 7.8.2003 (Core)

**Comment by reasonerjt** [comment]
Seems a dup of #13461

**Comment by sahramelissa** [comment]
Hi guys :)

If you look at prepare script you will see 

docker run ... -v /:/hostfs 

change it to docker run ... -v /pathOfYourCert/certs:/hostfs 

That will fix the problem :)

**Comment by paulohleal** [comment]
Hi @sahramelissa, this did not work for me. I am trying to install Harbor v2.3.2.

**Comment by paulohleal** [comment]
I changed the file to: 
docker run ... -v /pathOfYourCert/certs:/hostfs/pathOfYourCert/certs
and it worked for me!

**Comment by jrgongora** [comment]
Hello, I'm having this issue to install Harbor 2.4.1, interestingly,  I was able to install Harbor 1.10 fine and the cert and key were on the exacly same path. I've attempted all solutions proposed on this thread, no luck. Any idea ? Thanks in advance for your time.

The following is the output of /.install.sh

[Step 3]: preparing harbor configs ...
prepare base dir is set to /usr/local/src/harbor
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1062, in main
Clearing the configuration file: /config/portal/nginx.conf
Clearing the configuration file: /config/log/logrotate.conf
Clearing the configuration file: /config/log/rsyslog_docker.conf
Generated configuration file: /config/portal/nginx.conf
Generated configuration file: /config/log/logrotate.conf
Generated configuration file: /config/log/rsyslog_docker.conf
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/app/commands/prepare.py", line 47, in prepare
    prepare_nginx(config_dict)
  File "/usr/src/app/utils/nginx.py", line 23, in prepare_nginx
    render_nginx_template(config_dict)
  File "/usr/src/app/utils/nginx.py", line 56, in render_nginx_template
    prepare_nginx_certs(config_dict['cert_key_path'], config_dict['cert_path'])
  File "/usr/src/app/utils/nginx.py", line 42, in prepare_nginx_certs
    shutil.copy2(host_ngx_cert_key_path, real_key_path)
  File "/usr/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/hostfs/etc/letsencrypt/live/myserver.com/privkey.pem'

This is the section of certs on my harbor.yml file:

# The path of cert and key files for nginx
  certificate: /etc/letsencrypt/live/myserver.com/fullchain.pem
  private_key: /etc/letsencrypt/live/myserver.com/privkey.pem

**Comment by StefanKMF** [comment]
I ran into this issue as well, after much frustration, I determined that it appears to be an issue when docker is installed from snap (how it's installed from Ubuntu live disk).  My workaround was to remove docker from snap (snap remove docker) and then follow the [official docker install instructions](https://docs.docker.com/engine/install/ubuntu/), afterwards I was able to install without modifying the prepare script.

**Comment by HimanshuKapoor328** [comment]
I also have same doubt, but it resolved.....
we need to create a data/cert directory and move our certificate inside that.

And in harbor/prepare add :- 


# Run prepare script
docker run --rm -v $input_dir:/input \
                    -v $data_path:/data \
                    -v $harbor_prepare_path:/compose_location \
                    -v $config_dir:/config \
                    -v /home/ubuntu/data/cert:/hostfs/home/ubuntu/data/cert \
                    --privileged \
                    goharbor/prepare:v2.1.5 prepare $@

**Comment by stonezdj** [comment]
Got the same error when run install, and finally found that there is a directory `/hostfs` already exist in the VM, after remove this directory, install script works.

**Comment by Robbie558** [comment]
We are running v2.5.0 of Harbor on Ubuntu Linux, and faced the same issue when attempting to run the `install.sh` script.  When running the script we would get the error and have the certificates we were providing deleted from the directory passed to the `$data_path` parameter (specifically `/data/secret/cert/`).

```
[Step 4]: preparing harbor configs ...
prepare base dir is set to /etc/harbor/harbor
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 15, in <module>
Clearing the configuration file: /config/log/rsyslog_docker.conf
Clearing the configuration file: /config/log/logrotate.conf
Clearing the configuration file: /config/portal/nginx.conf
Generated configuration file: /config/portal/nginx.conf
Generated configuration file: /config/log/logrotate.conf
Generated configuration file: /config/log/rsyslog_docker.conf
    cli()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/app/commands/prepare.py", line 47, in prepare
    prepare_nginx(config_dict)
  File "/usr/src/app/utils/nginx.py", line 23, in prepare_nginx
    render_nginx_template(config_dict)
  File "/usr/src/app/utils/nginx.py", line 56, in render_nginx_template
    prepare_nginx_certs(config_dict['cert_key_path'], config_dict['cert_path'])
  File "/usr/src/app/utils/nginx.py", line 42, in prepare_nginx_certs
    shutil.copy2(host_ngx_cert_key_path, real_key_path)
  File "/usr/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/hostfs/data/secret/cert/server.key'
```

We were able to trace the issue down to the interpolation of the `$input_dir` variable in the `prepare` [script](https://github.com/goharbor/harbor/blob/v2.5.0/make/prepare#L16-L17).  When this is set to `/etc/harbor/harbor/input` we observed the behaviour described above.  When we removed the trailing `input` directory from the [docker run command](https://github.com/goharbor/harbor/blob/v2.5.0/make/prepare#L54) the script completed successfully.  This configuration of the `$input_dir` variable is still the case in the main branch of the code.

We have been running Harbor for several years but only observed this issue when rebuilding the host, and wiping both the directory passed to `$data_path` parameter as well as the install directory `/etc/harbor/`.

**Comment by dunefro** [comment]
> Run prepare script with the right Path
docker run --rm -v $input_dir:/input
-v $data_path:/data
-v $harbor_prepare_path:/compose_location
-v $config_dir:/config
-v /pathOfYourCert/certs:/hostfs
--privileged
goharbor/prepare:v2.1.5 prepare $@

I was able to resolve the issue with the solution provided by @sahramelissa.
My certs and key files were present in `/dir/certs` and I mounted that directory to `/hostfs` -> `-v /dir/certs:/hostfs`.
In harbor.yml, you just simply need to point to the location of certificates wrt directory `/dir/certs`

**Comment by wy65701436** [comment]
> I ran into this issue as well, after much frustration, I determined that it appears to be an issue when docker is installed from snap (how it's installed from Ubuntu live disk). My workaround was to remove docker from snap (snap remove docker) and then follow the [official docker install instructions](https://docs.docker.com/engine/install/ubuntu/), afterwards I was able to install without modifying the prepare script.

I run into the same issue on an new setup Ubuntu. After remove the docker under` /snap/bin/docker`, and install the official one, it works.

If anyone has the same problem, check whether your docker is installed from **`snap`**.

**Comment by amine7-svg** [comment]
hello harbor community,

I am facing issue while running prepare script using image goharbor/prepare:2.7.3  , could you please help 

harbor@DESKTOP-PF86DVG:~/harbor$ ./prepare
prepare base dir is set to /home/harbor/harbor
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
Clearing the configuration file: /config/portal/nginx.conf
Clearing the configuration file: /config/log/logrotate.conf
Clearing the configuration file: /config/log/rsyslog_docker.conf
Generated configuration file: /config/portal/nginx.conf
Generated configuration file: /config/log/logrotate.conf
Generated configuration file: /config/log/rsyslog_docker.conf
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/app/commands/prepare.py", line 47, in prepare
    prepare_nginx(config_dict)
  File "/usr/src/app/utils/nginx.py", line 23, in prepare_nginx
    render_nginx_template(config_dict)
  File "/usr/src/app/utils/nginx.py", line 56, in render_nginx_template
    prepare_nginx_certs(config_dict['cert_key_path'], config_dict['cert_path'])
  File "/usr/src/app/utils/nginx.py", line 42, in prepare_nginx_certs
    shutil.copy2(host_ngx_cert_key_path, real_key_path)
  File "/usr/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/hostfs/data/cert/harbor.local.key 


I already have certificate file under /data/cert on the host
