### ISSUE TITLE
Installers for 2.0.4 and 1.10.6 broken - read-only file system

### ISSUE THREAD

**Issue by boeboe** [goharbor/harbor#13626]
Please test you installers on the latest releases.... all of them are broken

    ubuntu@operations:/opt/harbor$ ll
    total 48
    drwxr-xr-x 2 ubuntu ubuntu  4096 Nov 27 19:05 ./
    drwxr-xr-x 3 root   root    4096 Nov 27 18:36 ../
    -rw-r--r-- 1 ubuntu ubuntu 11347 Nov 13 08:19 LICENSE
    -rw-r--r-- 1 ubuntu ubuntu  3361 Nov 13 08:19 common.sh
    -rw-rw-r-- 1 ubuntu ubuntu  7838 Nov 27 18:41 harbor.yml
    -rw-r--r-- 1 ubuntu ubuntu  7828 Nov 13 08:19 harbor.yml.tmpl
    -rwxr-xr-x 1 ubuntu ubuntu  2523 Nov 13 08:19 install.sh*
    -rwxr-xr-x 1 ubuntu ubuntu  1868 Nov 27 18:55 prepare*
    ubuntu@operations:/opt/harbor$ ./install.sh

    [Step 0]: checking if docker is installed ...

    Note: docker version: 19.03.11

    [Step 1]: checking docker-compose is installed ...

    Note: docker-compose version: 1.25.5

    [Step 2]: preparing environment ...

    [Step 3]: preparing harbor configs ...
    + [[ -n '' ]]
    +++ dirname ./prepare
    ++ cd .
    ++ pwd -P
    + harbor_prepare_path=/opt/harbor
    + echo 'prepare base dir is set to /opt/harbor'
    prepare base dir is set to /opt/harbor
    + rm -rf /opt/harbor/input
    + mkdir -p /opt/harbor/input
    + input_dir=/opt/harbor/input
    + [[ ! '' =~ ^-- ]]
    + '[' -f '' ']'
    + '[' -f /opt/harbor/harbor.yml ']'
    + cp /opt/harbor/harbor.yml /opt/harbor/input/harbor.yml
    ++ grep '^[^#]*data_volume:' /opt/harbor/input/harbor.yml
    ++ awk '{print $NF}'
    + data_path=/opt/harbor/data
    + previous_secretkey_path=/data/secretkey
    + previous_defaultalias_path=/data/defaultalias
    + '[' -f /data/secretkey ']'
    + '[' -f /data/defaultalias ']'
    + secret_dir=/opt/harbor/data/secret
    + config_dir=/opt/harbor/common/config
    + sudo docker run --rm -v /opt/harbor/input:/input:z -v /opt/harbor/data:/data:z -v /opt/harbor:/compose_location:z -v /opt/harbor/common/config:/config:z -v /:/hostfs:z goharbor/prepare:v2.0.4 prepare
    docker: Error response from daemon: error while creating mount source path '/opt/harbor/input': mkdir /opt/harbor: read-only file system.

I have spend all my afternoon hacking around in the shell scripts and messing with permissions, but besides many issues in them, the docker containers also perform mkdir and other operations which cannot be fixed for an install using the shell scripts.

I followed the official installation, also tried several external websites with installation procedures... really none of them work. If you provide docker containers that also do preparation work, this needs to be documented and a descent walkthrough and install guide goes through this process of directory creation and permission requirements.

Changing to another data dir also does not make it any better:

    ubuntu@operations:/tmp/harbor/harbor$ ./install.sh --with-clair

        [Step 0]: checking if docker is installed ...

        Note: docker version: 19.03.11

        [Step 1]: checking docker-compose is installed ...

        Note: docker-compose version: 1.25.5

        [Step 2]: preparing environment ...

        [Step 3]: preparing harbor configs ...
        + [[ -n '' ]]
        +++ dirname ./prepare
        ++ cd .
        ++ pwd -P
        + harbor_prepare_path=/tmp/harbor/harbor
        + echo 'prepare base dir is set to /tmp/harbor/harbor'
        prepare base dir is set to /tmp/harbor/harbor
        + rm -rf /tmp/harbor/harbor/input
        + mkdir -p /tmp/harbor/harbor/input
        + input_dir=/tmp/harbor/harbor/input
        + [[ ! --with-clair =~ ^-- ]]
        + '[' -f /tmp/harbor/harbor/harbor.yml ']'
        + cp /tmp/harbor/harbor/harbor.yml /tmp/harbor/harbor/input/harbor.yml
        ++ grep '^[^#]*data_volume:' /tmp/harbor/harbor/input/harbor.yml
        ++ awk '{print $NF}'
        + data_path=/home/ubuntu/harbor/data
        + previous_secretkey_path=/data/secretkey
        + previous_defaultalias_path=/data/defaultalias
        + '[' -f /data/secretkey ']'
        + '[' -f /data/defaultalias ']'
        + secret_dir=/home/ubuntu/harbor/data/secret
        + config_dir=/tmp/harbor/harbor/common/config
        + docker run --rm -v /tmp/harbor/harbor/input:/input:z -v /home/ubuntu/harbor/data:/data:z -v /tmp/harbor/harbor:/compose_location:z -v /tmp/harbor/harbor/common/config:/config:z -v /:/hostfs:z goharbor/prepare:v2.0.4 prepare --with-clair
        Traceback (most recent call last):
          File "main.py", line 15, in <module>
            cli()
          File "/usr/lib/python3.6/site-packages/click/core.py", line 829, in __call__
            return self.main(*args, **kwargs)
          File "/usr/lib/python3.6/site-packages/click/core.py", line 782, in main
            rv = self.invoke(ctx)
          File "/usr/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
            return _process_result(sub_ctx.command.invoke(sub_ctx))
          File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
            return ctx.invoke(self.callback, **ctx.params)
          File "/usr/lib/python3.6/site-packages/click/core.py", line 610, in invoke
            return callback(*args, **kwargs)
          File "/usr/src/app/commands/prepare.py", line 38, in prepare
            config_dict = parse_yaml_config(conf, with_notary=with_notary, with_clair=with_clair, with_trivy=with_trivy, with_chartmuseum=with_chartmuseum)
          File "/usr/src/app/utils/configs.py", line 105, in parse_yaml_config
            with open(config_file_path) as f:
        FileNotFoundError: [Errno 2] No such file or directory: '/input/harbor.yml'

    ubuntu@operations:/tmp/harbor/harbor$ ls /tmp/harbor/harbor/input
        harbor.yml

As you can see, the container is mounting `/tmp/harbor/harbor/input:/input:z` and even if the file exists, the container does not find it in his local mount on `/input/harbor.yml`

**Comment by boeboe** [comment]
Fixed by changing folders
