### ISSUE TITLE
The gitlab adapter may panic occasionally

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#14153]
The panic cannot always be reproduced, it occurs occasionally:
```
Feb  3 09:10:34 172.28.0.1 core[2219]: panic: runtime error: invalid memory address or nil pointer dereference
Feb  3 09:10:34 172.28.0.1 core[2219]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xf4862d]
Feb  3 09:10:34 172.28.0.1 core[2219]: 
Feb  3 09:10:34 172.28.0.1 core[2219]: goroutine 1276249 [running]:
Feb  3 09:10:34 172.28.0.1 core[2219]: github.com/goharbor/harbor/src/replication/adapter/gitlab.(*Client).getProjectsByName(0x0, 0xc01d7e334b, 0x10, 0x1, 0xffffffffffffffff, 0x10, 0xc01ecc0090, 0x3)
Feb  3 09:10:34 172.28.0.1 core[2219]: #011/harbor/src/replication/adapter/gitlab/client.go:103 +0x4d
Feb  3 09:10:34 172.28.0.1 core[2219]: github.com/goharbor/harbor/src/replication/adapter/gitlab.(*adapter).getProjectsByPattern(0xc018b0a460, 0xc01d7e3340, 0x1d, 0x203004, 0x203004, 0xc01ec29890)
Feb  3 09:10:34 172.28.0.1 core[2219]: #011/harbor/src/replication/adapter/gitlab/adapter.go:199 +0x4dd
Feb  3 09:10:34 172.28.0.1 core[2219]: github.com/goharbor/harbor/src/replication/adapter/gitlab.(*adapter).FetchArtifacts(0xc018b0a460, 0xc00f449150, 0x1, 0x1, 0xc018b0a460, 0x1, 0x0, 0x1, 0x370c280)
Feb  3 09:10:34 172.28.0.1 core[2219]: #011/harbor/src/replication/adapter/gitlab/adapter.go:96 +0xe5
Feb  3 09:10:34 172.28.0.1 core[2219]: github.com/goharbor/harbor/src/controller/replication/flow.fetchResources(0x26ccec0, 0xc018b0a460, 0xc018f3f810, 0x26ccf80, 0xc01353f6a0, 0x0, 0x0, 0x2167280)
Feb  3 09:10:34 172.28.0.1 core[2219]: #011/harbor/src/controller/replication/flow/stage.go:87 +0x629
Feb  3 09:10:34 172.28.0.1 core[2219]: github.com/goharbor/harbor/src/controller/replication/flow.(*copyFlow).Run(0xc00acd3860, 0x26e3540, 0xc018f52060, 0x2162820, 0x1)
Feb  3 09:10:34 172.28.0.1 core[2219]: #011/harbor/src/controller/replication/flow/copy.go:56 +0x4ce
Feb  3 09:10:34 172.28.0.1 core[2219]: github.com/goharbor/harbor/src/controller/replication/flow.(*controller).Start(0x370c280, 0x26e3540, 0xc018f52060, 0x36a, 0xc018f3f810, 0x0, 0x26e3540, 0xc018f52060)
Feb  3 09:10:34 172.28.0.1 core[2219]: #011/harbor/src/controller/replication/flow/controller.go:50 +0x12f
Feb  3 09:10:34 172.28.0.1 core[2219]: github.com/goharbor/harbor/src/controller/replication.(*controller).Start.func1(0xc0002b1450, 0x36a, 0xc00dbe6840, 0xc018f3f810, 0x0)
Feb  3 09:10:34 172.28.0.1 core[2219]: #011/harbor/src/controller/replication/controller.go:108 +0x23d
Feb  3 09:10:34 172.28.0.1 core[2219]: created by github.com/goharbor/harbor/src/controller/replication.(*controller).Start
Feb  3 09:10:34 172.28.0.1 core[2219]: #011/harbor/src/controller/replication/controller.go:92 +0x1a6
```

**Comment by bitsf** [comment]
at least add a recovery() block
