### ISSUE TITLE
update 1.7.5 to 1.8.5 IsADirectoryError

### ISSUE THREAD

**Issue by meteorlad** [goharbor/harbor#14196]
What can we help you?
I upgraded 1.7.5 to 1.8.5 to throw the following exceptions：

* IsADirectoryError: [Errno 21] Is a directory: **'/config/core/app.conf'**

```
[root@dev-harbor01 harbor]# ./install.sh

[Step 0]: checking installation environment ...

Note: docker version: 19.03.1

Note: docker-compose version: 1.24.1

[Step 1]: loading Harbor images ...
Loaded image: goharbor/redis-photon:v1.8.5
Loaded image: goharbor/clair-photon:v2.0.8-v1.8.5
Loaded image: goharbor/harbor-core:v1.8.5
Loaded image: goharbor/harbor-portal:v1.8.5
Loaded image: goharbor/harbor-log:v1.8.5
Loaded image: goharbor/harbor-db:v1.8.5
Loaded image: goharbor/harbor-jobservice:v1.8.5
Loaded image: goharbor/nginx-photon:v1.8.5
Loaded image: goharbor/chartmuseum-photon:v0.9.0-v1.8.5
Loaded image: goharbor/prepare:v1.8.5
Loaded image: goharbor/harbor-registryctl:v1.8.5
Loaded image: goharbor/registry-photon:v2.7.1-patch-2819-v1.8.5
Loaded image: goharbor/notary-server-photon:v0.6.1-v1.8.5
Loaded image: goharbor/notary-signer-photon:v0.6.1-v1.8.5
Loaded image: goharbor/harbor-migrator:v1.8.5


[Step 2]: preparing environment ...
prepare base dir is set to /data/harbor
Clearing the configuration file: /config/log/logrotate.conf
Clearing the configuration file: /config/nginx/nginx.conf
Clearing the configuration file: /config/core/env
Generated configuration file: /config/log/logrotate.conf
Generated configuration file: /config/nginx/nginx.conf
Generated configuration file: /config/core/env
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 36, in main
    prepare_core(config_dict, with_notary=with_notary, with_clair=with_clair, with_chartmuseum=with_chartmuseum)
  File "/usr/src/app/utils/core.py", line 37, in prepare_core
    xsrf_key=generate_random_string(40))
  File "/usr/src/app/utils/jinja.py", line 8, in render_jinja
    with open(dest, 'w') as f:
IsADirectoryError: [Errno 21] Is a directory: **'/config/core/app.conf'**
```

How should I deal with it？

**Comment by meteorlad** [comment]
The problem has been solved
