### ISSUE TITLE
Failure in Testcase to push CNAB

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#14199]
I started seeing random errors after bump up docker in the CI env:
```
======================================================================
ERROR: test_01_PushBundleByCnab (__main__.TestCNAB)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/drone/tests/apitests/python/library/base.py", line 99, in run_command
    universal_newlines=True)
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['sudo', 'cnab-to-oci', '--log-level', 'debug', 'fixup', './tests/apitests/python/bundle_data/bundle.json', '--target', '10.158.214.19/project-1612146433176/test_cnab:test_cnab_tag', '--bundle', './tests/apitests/python/bundle_data/fixed-bundle.json', '--auto-update-bundle']' returned non-zero exit status 1.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "./tests/apitests/python/test_push_cnab_bundle.py", line 74, in test_01_PushBundleByCnab
    TestCNAB.reference_sha256 = library.cnab.push_cnab_bundle(harbor_server, TestCNAB.user_name, TestCNAB.user_push_cnab_password, "containrrr/watchtower:latest", "kong:latest", target)
  File "/drone/tests/apitests/python/library/cnab.py", line 51, in push_cnab_bundle
    fixed_bundle_file = cnab_fixup_bundle(bundle_file, target, auto_update_bundle = auto_update_bundle)
  File "/drone/tests/apitests/python/library/cnab.py", line 28, in cnab_fixup_bundle
    ret = base.run_command(command)
  File "/drone/tests/apitests/python/library/base.py", line 107, in run_command
    raise Exception('Error: Exited with error code: %s. Output:%s'% (e.returncode, e.output))
Exception: Error: Exited with error code: 1. Output:time="2021-02-01T02:27:14Z" level=debug msg="Fixing up bundle 10.158.214.19/project-1612146433176/test_cnab:test_cnab_tag"
time="2021-02-01T02:27:14Z" level=debug msg="Updating entry in relocation map for \"kong:latest\""
Starting to copy image kong:latest...
Completed image kong:latest copy
time="2021-02-01T02:27:18Z" level=debug msg="Updating entry in relocation map for \"containrrr/watchtower:latest\""
Starting to copy image containrrr/watchtower:latest...
Failed to copy image containrrr/watchtower:latest: failed commit on ref "layer-sha256:8a9c414386aba17a2b5cb431d9219984cc7e6c818a68fc1a190666b698fa0a0f": no response
Error: failed commit on ref "layer-sha256:8a9c414386aba17a2b5cb431d9219984cc7e6c818a68fc1a190666b698fa0a0f": no response
```

**Comment by reasonerjt** [comment]
Need to find the root cause and improve the stability.
