### ISSUE TITLE
Core panic when external redis not fully loaded

### ISSUE THREAD

**Issue by Paul-Michaud** [goharbor/harbor#14221]
Hello,

We are using harbor with an external redis+sentinel cluster, we also have an external postgres.

**Actual behavior**

When we restart all redis+sentinel and harbor servers at the same time (Yes it's not a good idea but we wanted to test)  we can see the following error in the harbor-core logs when it starts : 

**harbor-core.log**
```
2021-02-09T04:02:04.428997+01:00 harbor-core 76c20c006df4 2021-02-09T03:02:04Z [INFO] [/core/main.go:221]: Version: v2.1.2, Git commit: fcc6751d
2021-02-09T04:02:04.433587+01:00 harbor-core 76c20c006df4 redis: 2021/02/09 03:02:04 sentinel.go:329: sentinel: discovered new sentinel="70d4e65a288e002603f84456b3a7af7c0a26f107" for master="harbor_master"
2021-02-09T04:02:04.433676+01:00 harbor-core 76c20c006df4 redis: 2021/02/09 03:02:04 sentinel.go:329: sentinel: discovered new sentinel="fbb9929a9ad398e8ebda1f3ea938dbe87a0443b1" for master="harbor_master"
2021-02-09T04:02:04.433744+01:00 harbor-core 76c20c006df4 redis: 2021/02/09 03:02:04 sentinel.go:329: sentinel: discovered new sentinel="c6562f7ef4f440f80f586e981fa95d5f0353a2a1" for master="harbor_master"
2021-02-09T04:02:04.433824+01:00 harbor-core 76c20c006df4 redis: 2021/02/09 03:02:04 sentinel.go:296: sentinel: new master="harbor_master" addr="10.34.116.88:6379"
2021-02-09T04:02:04.440103+01:00 harbor-core 76c20c006df4 panic: LOADING Redis is loading the dataset in memory
2021-02-09T04:02:04.440196+01:00 harbor-core 76c20c006df4
2021-02-09T04:02:04.440255+01:00 harbor-core 76c20c006df4 goroutine 1 [running]:
2021-02-09T04:02:04.440337+01:00 harbor-core 76c20c006df4 github.com/astaxie/beego.initBeforeHTTPRun()
2021-02-09T04:02:04.440394+01:00 harbor-core 76c20c006df4       /harbor/src/vendor/github.com/astaxie/beego/beego.go:104 +0x20c
2021-02-09T04:02:04.440451+01:00 harbor-core 76c20c006df4 github.com/astaxie/beego.RunWithMiddleWares(0x0, 0x0, 0xc00071fbd0, 0xa, 0xa)
2021-02-09T04:02:04.440506+01:00 harbor-core 76c20c006df4       /harbor/src/vendor/github.com/astaxie/beego/beego.go:77 +0x26
2021-02-09T04:02:04.440573+01:00 harbor-core 76c20c006df4 main.main()
2021-02-09T04:02:04.440631+01:00 harbor-core 76c20c006df4       /harbor/src/core/main.go:222 +0x6a3
```

Redis logs on the first server of the cluster. Logs from other servers are relatively similar. I can provide them if needed.
**Server [REDIS1] redis.log**
```
1245:M 09 Feb 2021 04:02:04.461 * Ready to accept connections
1245:M 09 Feb 2021 04:02:04.989 * Replica [REDIS2]:6379 asks for synchronization
1245:M 09 Feb 2021 04:02:04.989 * Full resync requested by replica [REDIS2]:6379
1245:M 09 Feb 2021 04:02:04.989 * Starting BGSAVE for SYNC with target: disk
1245:M 09 Feb 2021 04:02:04.992 * Background saving started by pid 4418
4418:C 09 Feb 2021 04:02:05.132 * DB saved on disk
4418:C 09 Feb 2021 04:02:05.135 * RDB: 8 MB of memory used by copy-on-write
1245:M 09 Feb 2021 04:02:05.164 * Background saving terminated with success
1245:M 09 Feb 2021 04:02:05.199 * Synchronization with replica  [REDIS2]:6379 succeeded
1245:M 09 Feb 2021 04:02:08.344 * Replica [REDIS3]:6379 asks for synchronization
1245:M 09 Feb 2021 04:02:08.344 * Full resync requested by replica [REDIS3]:6379
1245:M 09 Feb 2021 04:02:08.344 * Starting BGSAVE for SYNC with target: disk
1245:M 09 Feb 2021 04:02:08.347 * Background saving started by pid 4419
4419:C 09 Feb 2021 04:02:08.486 * DB saved on disk
4419:C 09 Feb 2021 04:02:08.488 * RDB: 12 MB of memory used by copy-on-write
1245:M 09 Feb 2021 04:02:08.574 * Background saving terminated with success
1245:M 09 Feb 2021 04:02:08.609 * Synchronization with replica [REDIS3]:6379 succeeded
```

**Expected behavior**
The error `LOADING Redis is loading the dataset in memory` seems to indicate that redis is not yet ready to accept connection. We would expect the core to retry some times for the redis to be ready before panicking.

We could avoid this error by not restarting everything at the same time on our side but since it might be a real issue we made this bug report.

**Steps to reproduce the problem:**
Here is the redis configuration in harbor.yml

```yaml
external_redis:
  # support redis, redis+sentinel
  # host for redis: <host_redis>:<port_redis>
  # host for redis+sentinel:
  #  <host_sentinel1>:<port_sentinel1>,<host_sentinel2>:<port_sentinel2>,<host_sentinel3>:<port_sentinel3>
  host: [REDIS1]:26379,[REDIS2]:26379,[REDIS3]:26379
  password: [REDACTED]
  # sentinel_master_set must be set to support redis+sentinel
  sentinel_master_set: harbor_master
  # db_index 0 is for core, it's unchangeable
  registry_db_index: 1
  jobservice_db_index: 2
  chartmuseum_db_index: 3
  clair_db_index: 4
  trivy_db_index: 5
  idle_timeout_seconds: 30
```

redis and sentinel cofiguration are basics with default values (A bit long so I didn't paste them here, I can do it of needed)

**Versions**

- harbor version: [2.1.2]
- redis version: [5.0.3]

**Additional context**
Once redis+sentinel & harbor started we don't have much keys in redis
```
# redis-cli -h [REDIS1] -a "[REDACTED]" keys "*"  | wc -l
4412
```

**Comment by bitsf** [comment]
redis and db are the dependencies, harbor-core will restart
