### ISSUE TITLE
Webhook Slack JSON is JavaScript, not JSON and can't be parsed by RocketChat, retries forever

### ISSUE THREAD

**Issue by GJKrupa** [goharbor/harbor#14274]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior:**

Rocket.Chat receives a Slack JSON webhook payload and logs the message (albeit empty) to the selected channel. Requests should not retry after a 40x response because it indicates a permanent problem with the request.

**Actual behavior:**

Rocket.Chat responds with a 400 code and fails to process the incoming message (then eventually starts returning 502/504 once a rate limit is reached). The following is logged:

```
rocketchat_1          | SyntaxError: Unexpected token
rocketchat_1          |  in JSON at position 749
rocketchat_1          |     at JSON.parse (<anonymous>)
rocketchat_1          |     at parse (/app/bundle/programs/server/npm/node_modules/meteor/simple_json-routes/node_modules/connect/node_modules/body-parser/lib/types/json.js:88:17)
rocketchat_1          |     at /app/bundle/programs/server/npm/node_modules/meteor/simple_json-routes/node_modules/connect/node_modules/body-parser/lib/read.js:108:18
rocketchat_1          |     at invokeCallback (/app/bundle/programs/server/npm/node_modules/meteor/simple_json-routes/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
rocketchat_1          |     at done (/app/bundle/programs/server/npm/node_modules/meteor/simple_json-routes/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
rocketchat_1          |     at IncomingMessage.onEnd (/app/bundle/programs/server/npm/node_modules/meteor/simple_json-routes/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:308:7)
rocketchat_1          |     at IncomingMessage.emit (events.js:327:22)
rocketchat_1          |     at IncomingMessage.EventEmitter.emit (domain.js:483:12)
rocketchat_1          |     at endReadableNT (_stream_readable.js:1220:12)
rocketchat_1          |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Using tcpdump I can see that the payload contains an un-quoted multi-line string delimited by triple backticks which is valid JavaScript but not valid JSON.

Even after deleting the webhook from Harbor, disabling and re-enabling webhooks globally and re-starting Harbor, it continues re-sending the failed message to the Rocket.Chat endpoint until it receives a 200.

In the end I had to deploy a dummy Python web server in place of Rocket.Chat to accept the message and respond with a 200 code until Harbor eventually stopped re-trying failed requests.

**Steps to reproduce the problem:**

Configure an integration in Rocket.Chat using default parameters
Configure Harbor with a new Slack webhook using the URL of the Rocket.Chat integration
Generate a webhook event, e.g. by completing a scan

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.1.3
- docker engine version: 20.10.3
- docker-compose version: 1.28.4

**Additional context:**

Default harbor.yml

jobservice log:
```
Feb 20 09:41:02 172.18.0.1 jobservice[7342]: 2021-02-20T09:41:02Z [ERROR] [/jobservice/runner/redis.go:206]: slack job(target: https://rocket.MYDOMAIN/hooks/KE8xDcL4o6ufHC7Gr/TOKEN) response code is 400
Feb 20 09:41:03 172.18.0.1 jobservice[7342]: 2021-02-20T09:41:03Z [ERROR] [/jobservice/runner/redis.go:111]: Job 'SLACK:6b2520bfb1a34532b6b2a8a8' exit with error: run error: slack job(target: https://rocket.MYDOMAIN/hooks/KE8xDcL4o6ufHC7Gr/TOKEN) response code is 400
```

**Comment by GJKrupa** [comment]
Example Slack message payload:
```
{
	"blocks": [
		{
            "type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "*Harbor webhook events*"
			}
        },
        {
            "type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "*event_type:* SCANNING_COMPLETED"
			}
        },
        {
            "type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "*occur_at:* <!date^1613812193^{date} at {time}|February 18th, 2014 at 6:39 AM PST>"
			}
        },
        {	"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "*operator:* auto"
			}
		},
        {	"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "*event_data:*"
			}
		},
		{	"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "```{
	\"resources\": [
		{
			\"digest\": \"sha256:6d951c962cdbb23d643362e2096a5c8518e7075a7db6ba96b21b1212dcb5d29a\",
			\"tag\": \"\",
			\"resource_url\": \"harbor.gjk.me.uk/gitlab-sync/bin-of-the-week:\",
			\"scan_overview\": {
				\"application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0\": {
					\"report_id\": \"5376dc18-c192-42c3-b191-5ca10c8c935f\",
					\"scan_status\": \"Success\",
					\"severity\": \"High\",
					\"duration\": 3,
					\"summary\": {
						\"total\": 106,
						\"fixable\": 0,
						\"summary\": {
							\"High\": 5,
							\"Low\": 42,
							\"Medium\": 59
						}
					},
					\"start_time\": \"2021-02-20T09:09:50.381569Z\",
					\"end_time\": \"2021-02-20T09:09:53.647025Z\",
					\"scanner\": {
						\"name\": \"Trivy\",
						\"vendor\": \"Aqua Security\",
						\"version\": \"v0.9.2\"
					},
					\"complete_percent\": 100
				}
			}
		}
	],
	\"repository\": {
		\"name\": \"bin-of-the-week\",
		\"namespace\": \"gitlab-sync\",
		\"repo_full_name\": \"gitlab-sync/bin-of-the-week\",
		\"repo_type\": \"private\"
	}
}```"
			}
		}
    ]}
```

**Comment by GJKrupa** [comment]
What it should look like:
```
{
    "blocks": [
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": "*Harbor webhook events*"
            }
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": "*event_type:* SCANNING_COMPLETED"
            }
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": "*occur_at:* <!date^1613812193^{date} at {time}|February 18th, 2014 at 6:39 AM PST>"
            }
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": "*operator:* auto"
            }
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": "*event_data:*"
            }
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": "```{\n\t\"resources\": [\n\t\t{\n\t\t\t\"digest\": \"sha256:6d951c962cdbb23d643362e2096a5c8518e7075a7db6ba96b21b1212dcb5d29a\",\n\t\t\t\"tag\": \"\",\n\t\t\t\"resource_url\": \"harbor.MYDOMAIN/gitlab-sync/my-image:\",\n\t\t\t\"scan_overview\": {\n\t\t\t\t\"application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0\": {\n\t\t\t\t\t\"report_id\": \"5376dc18-c192-42c3-b191-5ca10c8c935f\",\n\t\t\t\t\t\"scan_status\": \"Success\",\n\t\t\t\t\t\"severity\": \"High\",\n\t\t\t\t\t\"duration\": 3,\n\t\t\t\t\t\"summary\": {\n\t\t\t\t\t\t\"total\": 106,\n\t\t\t\t\t\t\"fixable\": 0,\n\t\t\t\t\t\t\"summary\": {\n\t\t\t\t\t\t\t\"High\": 5,\n\t\t\t\t\t\t\t\"Low\": 42,\n\t\t\t\t\t\t\t\"Medium\": 59\n\t\t\t\t\t\t}\n\t\t\t\t\t},\n\t\t\t\t\t\"start_time\": \"2021-02-20T09:09:50.381569Z\",\n\t\t\t\t\t\"end_time\": \"2021-02-20T09:09:53.647025Z\",\n\t\t\t\t\t\"scanner\": {\n\t\t\t\t\t\t\"name\": \"Trivy\",\n\t\t\t\t\t\t\"vendor\": \"Aqua Security\",\n\t\t\t\t\t\t\"version\": \"v0.9.2\"\n\t\t\t\t\t},\n\t\t\t\t\t\"complete_percent\": 100\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t],\n\t\"repository\": {\n\t\t\"name\": \"my-image\",\n\t\t\"namespace\": \"gitlab-sync\",\n\t\t\"repo_full_name\": \"gitlab-sync/my-image\",\n\t\t\"repo_type\": \"private\"\n\t}\n}```"
            }
        }
    ]
}
```

**Comment by GJKrupa** [comment]
I've tested the same with Slack and I'm seeing the same behaviour:
```
Feb 20 11:48:20 172.18.0.1 jobservice[7342]: 2021-02-20T11:48:20Z [ERROR] [/jobservice/runner/redis.go:206]: webhook job(target: https://hooks.slack.com/services/XXXXX/XXXXX/XXXXX) response code is 400
Feb 20 11:48:20 172.18.0.1 jobservice[7342]: 2021-02-20T11:48:20Z [ERROR] [/jobservice/runner/redis.go:111]: Job 'WEBHOOK:4a9b5addf2c55fd142c8fc7b' exit with error: run error: webhook job(target: https://hooks.slack.com/services/XXXXX/XXXXX/XXXXX) response code is 400
```

**Comment by mmpei** [comment]
1. i think stopping retring when receiving a 4xx response is reasonable. i will check again.
2. now harbor only supports slack but not Rocket.Chat, there needs an adapter.
3. you should delete the job in DB and the task in redis, if you want to stop a task. i remember these is a parameter 'max retry count' in configuration of harbor.  and default value is 10? you can use it.

**Comment by GJKrupa** [comment]
Thanks for that. I'm writing a Rocket.Chat webhook adapter myself (as a webhook pre-processor script) but the incoming data isn't hitting my code at all because it fails JSON parsing inside RC. I could write something to handle the http webhook schema but I'm looking to end up with a single generic handler that converts Slack blocks into RC attachments and isn't specific to Harbor webhooks.

It appears that Slack is a bit more tolerant of non-compliant JSON than it should be (specifically it allows unquoted newlines in the middle of strings). For example the following script:
```
PAYLOAD="{\"channel\": \"#general\", \"username\": \"webhookbot\", \"text\": \"Line1\nLine2\", \"icon_emoji\": \":ghost:\"}"

curl \
    -X POST \
    -H "Content-Type: application/json" \
    --data-raw "${PAYLOAD}" \
    https://hooks.slack.com/services/XXX/XXX/XXXX

echo "${PAYLOAD}" | jq -r
```
The payload is accepted Slack but JQ gives the error:
```
parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 2, column 6
```
