### ISSUE TITLE
Harbor core pod on k8S failing with panic: wrong db field/column name `Status` for model `github.com/goharbor/harbor/src/pkg/reg/dao.Registry`

### ISSUE THREAD

**Issue by bsakweson** [goharbor/harbor#15111]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I expect harbor core to connect, retrieve and update registry database with issues. Currently it is failing with the following error:

```
2021-06-09T20:29:59Z [INFO] [/controller/registry/controller.go:221]: Start regular health check for registries with interval 5m0s
panic: wrong db field/column name `Status` for model `github.com/goharbor/harbor/src/pkg/reg/dao.Registry`

goroutine 118 [running]:
github.com/astaxie/beego/orm.(*dbBase).collectValues(0xc000113290, 0xc0004d1400, 0x234bb60, 0xc001e8c300, 0x199, 0xc001ea4640, 0x1, 0x1, 0x7fac6a570001, 0xc0012abbc8, ...)
	/harbor/src/vendor/github.com/astaxie/beego/orm/db.go:88 +0x8c6
github.com/astaxie/beego/orm.(*dbBase).Update(0xc000113290, 0x28c2fe0, 0xc00084a480, 0xc0004d1400, 0x234bb60, 0xc001e8c300, 0x199, 0x38f0bc0, 0xc001ea4640, 0x1, ...)
	/harbor/src/vendor/github.com/astaxie/beego/orm/db.go:619 +0x1ea
github.com/astaxie/beego/orm.(*orm).Update(0xc0008d9660, 0x20c47a0, 0xc001e8c300, 0xc001ea4640, 0x1, 0x1, 0x0, 0xc0012abe28, 0xf891c7)
	/harbor/src/vendor/github.com/astaxie/beego/orm/orm.go:237 +0xdb
github.com/goharbor/harbor/src/pkg/reg/dao.(*dao).Update(0x3946fc0, 0x28aa520, 0xc00024a9f0, 0xc001e8c300, 0xc001ea4640, 0x1, 0x1, 0x1, 0xc001ea4640)
	/harbor/src/pkg/reg/dao/dao.go:101 +0x102
github.com/goharbor/harbor/src/pkg/reg.(*manager).Update(0xc00004f770, 0x28aa520, 0xc00024a9f0, 0xc000fc3130, 0xc001ea4640, 0x1, 0x1, 0x0, 0x0)
	/harbor/src/pkg/reg/manager.go:144 +0xb2
github.com/goharbor/harbor/src/controller/registry.(*controller).StartRegularHealthCheck(0xc0007652f0, 0x28aa520, 0xc00024a9f0, 0xc000053b60, 0xc000053bc0)
	/harbor/src/controller/registry/controller.go:244 +0x268
created by main.main
	/harbor/src/core/main.go:218 +0x60a
```

**Steps to reproduce the problem:**
Install harbor on kubernetes successfull and let it run, monitor the logs.

**Versions:**

- harbor version: [2.2.1]
- docker engine version: [19.3.13]

**Comment by bitsf** [comment]
fresh install or upgrade from which version ?

**Comment by ywk253100** [comment]
@bsakweson seems your harbor deployment isn't a release build. Please use a release build instead
