### ISSUE TITLE
Harbor 2.3.3 installation failed

### ISSUE THREAD

**Issue by thomas-reinhold-de** [goharbor/harbor#15787]
When I install Harbor on MacOS 11.6, I got following message. It seems like the data path which I specified in harbor.yml file is not used correctly.

[Step 4]: preparing harbor configs ...
prepare base dir is set to /Users/me/Runtime/harbor
WARNING:root:WARNING: HTTP protocol is insecure. Harbor will deprecate http protocol in the future. Please make sure to upgrade to https
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
Clearing the configuration file: /config/log/logrotate.conf
Clearing the configuration file: /config/log/rsyslog_docker.conf
Clearing the configuration file: /config/nginx/nginx.conf
Clearing the configuration file: /config/portal/nginx.conf
Generated configuration file: /config/portal/nginx.conf
Generated configuration file: /config/log/logrotate.conf
Generated configuration file: /config/log/rsyslog_docker.conf
Generated configuration file: /config/nginx/nginx.conf
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/app/commands/prepare.py", line 48, in prepare
    prepare_core(config_dict, with_notary=with_notary, with_trivy=with_trivy, with_chartmuseum=with_chartmuseum)
  File "/usr/src/app/utils/core.py", line 17, in prepare_core
    prepare_dir(ca_download_dir, uid=DEFAULT_UID, gid=DEFAULT_GID)
  File "/usr/src/app/utils/misc.py", line 76, in prepare_dir
    absolute_path.mkdir(mode=mode, parents=True)
  File "/usr/lib/python3.9/pathlib.py", line 1312, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 1] Operation not permitted: '/data/ca_download'

Following is the part of my Harbo config file.

`data_volume: /var/data/harbor`

I don't setup storage_service section. Based on my understanding, if the storage_service section is disabled, the path of data should be setup with the value of data_value setting. I have no idea why this issue happened.

**Comment by thomas-reinhold-de** [comment]
I changed paths both of data and log to user home. It works.
