### ISSUE TITLE
tracing can not normally export data via Jaeger agent mode

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#15826]
Below is my configuration for trace
```
trace:
  enabled: true
  # set sample_rate to 1 if you wanna sampling 100% of trace data; set 0.5 if you wanna sampling 50% of trace data, and so forth
  sample_rate: 1
  # # namespace used to differenciate different harbor services
  # namespace:
  # # attributes is a key value dict contains user defined attributes used to initialize trace provider
  # attributes:
  #   application: harbor
  jaeger:
#    endpoint: http://xx.xxx.xxx.xxx:14268/api/traces
#    username:
#    password:
    agent_host: xx.xxx.xxx.xxx
    agent_port: 6832
```

```
5cbc674cf4e9   jaegertracing/all-in-one:1.23          "/go/bin/all-in-one-…"   8 hours ago      Up 8 hours                5775/udp, 0.0.0.0:14250->14250/tcp, 0.0.0.0:14268->14268/tcp, 6831-6832/udp, 5778/tcp, 0.0.0.0:16686->16686/tcp   jaeger
```
When I start the harbor with the above configuration.
tracing can not normally export data via Jaeger agent mode.

**Comment by YangJiao0817** [comment]
I use jaegertracing/all-in-one: 1.27 is normal

**Comment by QiuToo** [comment]
> 我使用 jaegertracing/all-in-one: 1.27 是正常的

我在配置Jaeger时也遇到了这个问题，我遇到了以下问题，希望获得您的帮助：


[root@harbor-lidabai harbor]# ./prepare 
prepare base dir is set to /app/harbor
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/app/commands/prepare.py", line 37, in prepare
    config_dict = parse_yaml_config(conf, with_notary=with_notary, with_trivy=with_trivy, with_chartmuseum=with_chartmuseum)
  File "/usr/src/app/utils/configs.py", line 107, in parse_yaml_config
    configs = yaml.safe_load(f)
  File "/usr/lib/python3.10/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3.10/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3.10/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "/input/harbor.yml", line 217, column 3
expected <block end>, but found '<block mapping start>'
  in "/input/harbor.yml", line 226, column 5

[root@harbor-lidabai harbor]# vim harbor.yml
216 trace:
217   enabled: true
218 #   # set sample_rate to 1 if you wanna sampling 100% of trace data; set 0.5 if you wanna sampling 50% of trace data, and so forth
219   sample_rate: 1
220 #   # # namespace used to differenciate different harbor services
221 #   # namespace:
222 #   # # attributes is a key value dict contains user defined attributes used to initialize trace provider
223 #    attributes:
224 #   #   application: harbor
225 #   # # jaeger should be 1.26 or newer.
226     jaeger:
227 #      endpoint: http://192.168.2.250:14268/api/traces
228 #   #   username:
229 #   #   password:
230       agent_host: 192.168.2.6
231 #   #   # export trace data by jaeger.thrift in compact mode
232       agent_port: 6831
233 #   # otel:
234 #   #   endpoint: hostname:4318
235 #   #   url_path: /v1/traces
236 #   #   compression: false
237 #   #   insecure: true
238 #   #   timeout: 10s
