### ISSUE TITLE
Job "GARBAGE_COLLECTION" exits with runtime error

### ISSUE THREAD

**Issue by TheRealMoP** [goharbor/harbor#15966]
Running "GARBAGE_COLLECTION" job causes following error:

`[ERROR] [/jobservice/runner/redis.go:152]: Run job GARBAGE_COLLECTION:7453ffbe297f716b8bb0bdac error: runtime error: interface conversion: interface {} is nil, not string;`

Error occures everytime scheduled GC job starts and occasionally after manual start.

**Versions:**
- harbor version: v2.3.2

**Log**
```
Nov  5 12:00:00 172.18.0.1 jobservice[459]: 2021-11-05T11:00:00Z [ERROR] [/jobservice/runner/redis.go:152]: Run job GARBAGE_COLLECTION:7453ffbe297f716b8bb0bdac error: runtime error: interface conversion: interface {} is nil, not string; stack: goroutine 85 [running]:
Nov  5 12:00:00 172.18.0.1 jobservice[459]: github.com/goharbor/harbor/src/jobservice/runner.(*RedisJob).Run.func2(0xc000cdb7d0, 0xc0008f6540)
Nov  5 12:00:00 172.18.0.1 jobservice[459]: #011/harbor/src/jobservice/runner/redis.go:150 +0xa5
Nov  5 12:00:00 172.18.0.1 jobservice[459]: panic(0x28b6f40, 0xc0016d5fb0)
Nov  5 12:00:00 172.18.0.1 jobservice[459]: #011/usr/local/go/src/runtime/panic.go:975 +0x47a
Nov  5 12:00:00 172.18.0.1 jobservice[459]: github.com/goharbor/harbor/src/jobservice/job/impl/gc.(*GarbageCollector).parseParams(0xc00151f440, 0xc000ee60c0)
Nov  5 12:00:00 172.18.0.1 jobservice[459]: #011/harbor/src/jobservice/job/impl/gc/garbage_collection.go:116 +0x365
Nov  5 12:00:00 172.18.0.1 jobservice[459]: github.com/goharbor/harbor/src/jobservice/job/impl/gc.(*GarbageCollector).init(0xc00151f440, 0x2eb4460, 0xc0008428c0, 0xc000ee60c0, 0x7, 0x0)
Nov  5 12:00:00 172.18.0.1 jobservice[459]: #011/harbor/src/jobservice/job/impl/gc/garbage_collection.go:109 +0x313
Nov  5 12:00:00 172.18.0.1 jobservice[459]: github.com/goharbor/harbor/src/jobservice/job/impl/gc.(*GarbageCollector).Run(0xc00151f440, 0x2eb4460, 0xc0008428c0, 0xc000ee60c0, 0xc0008428c0, 0x0)
Nov  5 12:00:00 172.18.0.1 jobservice[459]: #011/harbor/src/jobservice/job/impl/gc/garbage_collection.go:151 +0x4d
Nov  5 12:00:00 172.18.0.1 jobservice[459]: github.com/goharbor/harbor/src/jobservice/runner.(*RedisJob).Run(0xc00077b560, 0xc0008f6540, 0x0, 0x0)
Nov  5 12:00:00 172.18.0.1 jobservice[459]: #011/harbor/src/jobservice/runner/redis.go:212 +0xc55
Nov  5 12:00:00 172.18.0.1 jobservice[459]: github.

```

**Comment by wy65701436** [comment]
is it an external redis?

**Comment by TheRealMoP** [comment]
No, there is no external redis. 

Here is the value of _REDIS_URL_REG:
`docker exec harbor-core /bin/bash -c 'echo "${_REDIS_URL_REG}"'
redis://redis:6379/1?idle_timeout_seconds=30`

**Comment by wy65701436** [comment]
is it an fresh install or upgrade from pervious version?

**Comment by baramundi-tweyer** [comment]
It's an upgraded installation and we've used `--with-trivy` (instead of clair).

**Comment by wy65701436** [comment]
@TheRealMoP @baramundi-tweyer we tried to the scenario and cannot reproduce the problem. Can you give more details?

Or is it possible to clean the redis data and try again?

**Comment by baramundi-tweyer** [comment]
How to clean the redis data?

Is it safe to do following without any additional work?
- Stop Harbor using `docker-compose down`
- Drop the volume mounted to `/var/lib/redis`
- Restart Harbor using `docker-compose up -d --force-recreate`

**Comment by baramundi-tweyer** [comment]
@wy65701436 Which further details can help to fix this issue?

**Comment by wy65701436** [comment]
hi, can you try to upgrade to 2.4 then have a try?

**Comment by baramundi-tweyer** [comment]
We've just updated our Harbor installation to the 2.4.1 version .
Unfortunately GC is still broken:

```
2022-02-14T08:19:13Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:301]: delete blob from storage: sha256:e34990d9f8ac513fbc27fbe0d8f1e1360188be6db5425f35c41a79aaa593d94f
2022-02-14T08:19:13Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:319]: delete blob record from database: 100615, sha256:e34990d9f8ac513fbc27fbe0d8f1e1360188be6db5425f35c41a79aaa593d94f
2022-02-14T08:19:13Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:261]: delete the manifest with registry v2 API: Project/Repository, application/vnd.docker.distribution.manifest.v2+json, sha256:c1a8cfa212230e1cb72ea442e4e92f8fa3e8b52876c7b142699d51eb1e8d9446
2022-02-14T08:19:13Z [ERROR] [/jobservice/job/impl/gc/garbage_collection.go:264]: failed to delete manifest with v2 API, Project/Repository, sha256:c1a8cfa212230e1cb72ea442e4e92f8fa3e8b52876c7b142699d51eb1e8d9446, http status code: 500, body: 
2022-02-14T08:19:13Z [ERROR] [/jobservice/job/impl/gc/garbage_collection.go:166]: failed to execute GC job at sweep phase, error: failed to delete manifest with v2 API: Project/Repository, sha256:c1a8cfa212230e1cb72ea442e4e92f8fa3e8b52876c7b142699d51eb1e8d9446: http status code: 500, body: 
```

The failing image is a multi platform image for both Windows and Linux.

**Comment by wy65701436** [comment]
@baramundi-tweyer for the above problem, please provide the registry log for debugging.
