### ISSUE TITLE
Cannot upload a specific image after v2.4.0 upgrade

### ISSUE THREAD

**Issue by meridiana73** [goharbor/harbor#16069]
Hi,

- harbor version: v2.4.0
- docker engine version: Docker version 20.10.6, build 370c289
- docker-compose version: docker-compose version 1.29.2, build 5becea4c
- SO Ubuntu 18.04.5 LTS RAM 32Gb

after performing: docker push XXXXXXXXXXXXXXXX

102e6b5f0969: Pushing [==============>                 ] 620.9MB/2.086GB
Traceback (most recent call last):
File "urllib3/response.py", line 436, in _error_catcher
File "urllib3/response.py", line 518, in read
File "http/client.py", line 457, in read
File "http/client.py", line 491, in readinto
File "http/client.py", line 586, in _readinto_chunked
File "http/client.py", line 554, in _get_chunk_left
File "http/client.py", line 514, in _read_next_chunk_size
File "socket.py", line 589, in readinto
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "bin/docker-compose", line 3, in <module>
File "compose/cli/main.py", line 67, in main
File "compose/cli/main.py", line 126, in perform_command
File "compose/cli/main.py", line 760, in push
File "compose/project.py", line 772, in push
File "compose/service.py", line 1280, in push
File "compose/progress_stream.py", line 109, in get_digest_from_push
File "compose/progress_stream.py", line 22, in stream_output
File "compose/utils.py", line 50, in split_buffer
File "compose/utils.py", line 26, in stream_as_text
File "docker/api/client.py", line 343, in _stream_helper
File "urllib3/response.py", line 540, in read
File "contextlib.py", line 130, in __exit__
File "urllib3/response.py", line 441, in _error_catcher
urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.
[8265] Failed to execute script docker-compose

In the previous Harbor version we dont have any problem with this image and we dont have problems with others. We guess it could be by the size.

We tried:

export DOCKER_CLIENT_TIMEOUT=120
export COMPOSE_HTTP_TIMEOUT=120

and no results.

sudo journalctl -fu docker.service output:

Dec 01 13:09:16 azweutmwac06 dockerd[13229]: time="2021-12-01T13:09:16.650178295Z" level=error msg="Not continuing with push after error: context canceled"

thanks in advance.

Regards

**Comment by wy65701436** [comment]
what's the harbor core/proxy/registry log?

**Comment by meridiana73** [comment]
Hi,

I found the problem. It was a bad configuration of netscaler (publish service).

Everything is fine right now.

Thanks for your answer!
