### ISSUE TITLE
Setting up for new PR; can't run go test on dao package

### ISSUE THREAD

**Issue by nyarly** [goharbor/harbor#16330]
**Expected behavior and actual behavior:**

I'm attempting to follow to the Contributing guide to address issue #8649.

Running `go test -v ./...` in `common/dao` fails like
```
⮀ env POSTGRESQL_HOST=127.0.0.1 POSTGRESQL_USR=postgres POSTGRESQL_PORT=5432 POSTGRESQL_DATABASE=harbor go test -v ./...
 12:09:58 - started
2022-02-04T12:09:59-08:00 [INFO] [/common/dao/dao_test.go:102]: run test cases for database: postgresql
2022-02-04T12:09:59-08:00 [INFO] [/common/dao/testutils.go:74]: POSTGRES_HOST: 127.0.0.1, POSTGRES_USR: postgres, POSTGRES_PORT: 5432, POSTGRES_PWD:
2022-02-04T12:09:59-08:00 [INFO] [/common/dao/testutils.go:84]: initializing database: type-PostgreSQL host-127.0.0.1 port-5432 database-harbor sslmode-"disable"
panic: open /home/judson/dev/YM/harbor/src/common/dao/migrations/postgresql: no such file or directory

goroutine 1 [running]:
github.com/goharbor/harbor/src/common/dao.initDatabaseForTest(0xc00063fdf0)
        /home/judson/dev/YM/harbor/src/common/dao/testutils.go:95 +0x2dc
github.com/goharbor/harbor/src/common/dao.PrepareTestForPostgresSQL()
        /home/judson/dev/YM/harbor/src/common/dao/testutils.go:75 +0x3d6
github.com/goharbor/harbor/src/common/dao.TestMain(0xc00044ae80)
        /home/judson/dev/YM/harbor/src/common/dao/dao_test.go:106 +0x1f2
main.main()
        _testmain.go:53 +0x165
FAIL    github.com/goharbor/harbor/src/common/dao       0.030s
FAIL
```

**Steps to reproduce the problem:**
Clone `goharbor/harbor` fresh.
`cd src/common/dao`
`go test -v ./...`

**Versions:**
Please specify the versions of following systems.

- harbor version: main branch

**Comment by chlins** [comment]
You could try to copy `migrations` folder under `make` to your test folder `/home/judson/dev/YM/harbor/src/common/dao/`.

**Comment by nyarly** [comment]
That gets a little further. It complains that the DB `harbor` doesn't exist; I create that, no problem.

Now it complains that several relations don't exist. I see them mentioned in migrations, but no where are they created, AFAICT.

```
2022-02-07T16:09:29-08:00 [INFO] [/common/dao/dao_test.go:102]: run test cases for database: postgresql
2022-02-07T16:09:29-08:00 [INFO] [/common/dao/testutils.go:74]: POSTGRES_HOST: 127.0.0.1, POSTGRES_USR: postgres, POSTGRES_PORT: 5432, POSTGRES_PWD:
2022-02-07T16:09:29-08:00 [INFO] [/common/dao/testutils.go:84]: initializing database: type-PostgreSQL host-127.0.0.1 port-5432 database-harbor sslmode-"disable"
2022-02-07T16:09:29-08:00 [INFO] [/common/dao/pgsql.go:131]: Upgrading schema for pgsql ...
2022-02-07T16:09:29-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 1/u initial_schema (193.235192ms)
2022-02-07T16:09:29-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 2/u 1.7.0_schema (220.959602ms)
2022-02-07T16:09:29-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 3/u add_replication_op_uuid (231.939509ms)
2022-02-07T16:09:29-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 4/u 1.8.0_schema (286.634137ms)
2022-02-07T16:09:29-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 5/u 1.8.2_schema (299.87702ms)
2022-02-07T16:09:29-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 10/u 1.9.0_schema (420.702546ms)
2022-02-07T16:09:29-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 11/u 1.9.1_schema (450.067998ms)
2022-02-07T16:09:29-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 12/u 1.9.4_schema (460.641837ms)
2022-02-07T16:09:29-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 15/u 1.10.0_schema (560.541806ms)
2022-02-07T16:09:29-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 30/u 2.0.0_schema (637.535599ms)
2022-02-07T16:09:29-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 31/u 2.0.3_schema (654.194888ms)
2022-02-07T16:09:29-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 40/u 2.1.0_schema (548.687021ms)
2022-02-07T16:09:30-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 41/u 2.1.4_schema (531.201375ms)
2022-02-07T16:09:30-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 50/u 2.2.0_schema (584.401278ms)
2022-02-07T16:09:30-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 51/u 2.2.1_schema (542.364348ms)
2022-02-07T16:09:30-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 52/u 2.2.2_schema (540.254037ms)
2022-02-07T16:09:30-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 53/u 2.2.3_schema (439.47657ms)
2022-02-07T16:09:30-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 60/u 2.3.0_schema (423.5894ms)
2022-02-07T16:09:30-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 61/u 2.3.4_schema (429.125795ms)
2022-02-07T16:09:30-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 70/u 2.4.0_schema (366.504715ms)
2022-02-07T16:09:30-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 80/u 2.5.0_schema (311.329797ms)
2022-02-07T16:09:30-08:00 [ERROR] [/common/dao/dao_test.go:58]: pq: relation "project_member" does not exist
2022-02-07T16:09:30-08:00 [ERROR] [/common/dao/dao_test.go:70]: pq: relation "project_member" does not exist
2022-02-07T16:09:30-08:00 [ERROR] [/common/dao/dao_test.go:76]: pq: relation "project" does not exist
2022-02-07T16:09:30-08:00 [ERROR] [/common/dao/dao_test.go:82]: pq: relation "harbor_user" does not exist
2022-02-07T16:09:30-08:00 [ERROR] [/common/dao/dao_test.go:86]: pq: relation "replication_policy" does not exist
2022-02-07T16:09:30-08:00 [ERROR] [/common/dao/dao_test.go:90]: pq: relation "registry" does not exist
```

**Comment by chlins** [comment]
> That gets a little further. It complains that the DB `harbor` doesn't exist; I create that, no problem.
> 
> Now it complains that several relations don't exist. I see them mentioned in migrations, but no where are they created, AFAICT.
> 
> ```
> 2022-02-07T16:09:29-08:00 [INFO] [/common/dao/dao_test.go:102]: run test cases for database: postgresql
> 2022-02-07T16:09:29-08:00 [INFO] [/common/dao/testutils.go:74]: POSTGRES_HOST: 127.0.0.1, POSTGRES_USR: postgres, POSTGRES_PORT: 5432, POSTGRES_PWD:
> 2022-02-07T16:09:29-08:00 [INFO] [/common/dao/testutils.go:84]: initializing database: type-PostgreSQL host-127.0.0.1 port-5432 database-harbor sslmode-"disable"
> 2022-02-07T16:09:29-08:00 [INFO] [/common/dao/pgsql.go:131]: Upgrading schema for pgsql ...
> 2022-02-07T16:09:29-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 1/u initial_schema (193.235192ms)
> 2022-02-07T16:09:29-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 2/u 1.7.0_schema (220.959602ms)
> 2022-02-07T16:09:29-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 3/u add_replication_op_uuid (231.939509ms)
> 2022-02-07T16:09:29-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 4/u 1.8.0_schema (286.634137ms)
> 2022-02-07T16:09:29-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 5/u 1.8.2_schema (299.87702ms)
> 2022-02-07T16:09:29-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 10/u 1.9.0_schema (420.702546ms)
> 2022-02-07T16:09:29-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 11/u 1.9.1_schema (450.067998ms)
> 2022-02-07T16:09:29-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 12/u 1.9.4_schema (460.641837ms)
> 2022-02-07T16:09:29-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 15/u 1.10.0_schema (560.541806ms)
> 2022-02-07T16:09:29-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 30/u 2.0.0_schema (637.535599ms)
> 2022-02-07T16:09:29-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 31/u 2.0.3_schema (654.194888ms)
> 2022-02-07T16:09:29-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 40/u 2.1.0_schema (548.687021ms)
> 2022-02-07T16:09:30-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 41/u 2.1.4_schema (531.201375ms)
> 2022-02-07T16:09:30-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 50/u 2.2.0_schema (584.401278ms)
> 2022-02-07T16:09:30-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 51/u 2.2.1_schema (542.364348ms)
> 2022-02-07T16:09:30-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 52/u 2.2.2_schema (540.254037ms)
> 2022-02-07T16:09:30-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 53/u 2.2.3_schema (439.47657ms)
> 2022-02-07T16:09:30-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 60/u 2.3.0_schema (423.5894ms)
> 2022-02-07T16:09:30-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 61/u 2.3.4_schema (429.125795ms)
> 2022-02-07T16:09:30-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 70/u 2.4.0_schema (366.504715ms)
> 2022-02-07T16:09:30-08:00 [INFO] [/vendor/github.com/golang-migrate/migrate/v4/migrate.go:765]: 80/u 2.5.0_schema (311.329797ms)
> 2022-02-07T16:09:30-08:00 [ERROR] [/common/dao/dao_test.go:58]: pq: relation "project_member" does not exist
> 2022-02-07T16:09:30-08:00 [ERROR] [/common/dao/dao_test.go:70]: pq: relation "project_member" does not exist
> 2022-02-07T16:09:30-08:00 [ERROR] [/common/dao/dao_test.go:76]: pq: relation "project" does not exist
> 2022-02-07T16:09:30-08:00 [ERROR] [/common/dao/dao_test.go:82]: pq: relation "harbor_user" does not exist
> 2022-02-07T16:09:30-08:00 [ERROR] [/common/dao/dao_test.go:86]: pq: relation "replication_policy" does not exist
> 2022-02-07T16:09:30-08:00 [ERROR] [/common/dao/dao_test.go:90]: pq: relation "registry" does not exist
> ```

cc @wy65701436 I think db migration should create these tables automatically?

**Comment by nyarly** [comment]
I see `create table project_member` in `migrations/postgresql/0001_initial_schema.up.sql` so it seems like that should work?

I did a second run (which I should have done sooner...) and get
```
⮀ env POSTGRESQL_HOST=127.0.0.1 POSTGRESQL_USR=postgres POSTGRESQL_PORT=5432 POSTGRESQL_DATABASE=harbor go test -v ./...
 09:57:39 - started
2022-02-17T09:58:02-08:00 [INFO] [/common/dao/dao_test.go:102]: run test cases for database: postgresql
2022-02-17T09:58:02-08:00 [INFO] [/common/dao/testutils.go:74]: POSTGRES_HOST: 127.0.0.1, POSTGRES_USR: postgres, POSTGRES_PORT: 5432, POSTGRES_PWD:
2022-02-17T09:58:02-08:00 [INFO] [/common/dao/testutils.go:84]: initializing database: type-PostgreSQL host-127.0.0.1 port-5432 database-harbor sslmode-"disable"
2022-02-17T09:58:02-08:00 [INFO] [/common/dao/pgsql.go:131]: Upgrading schema for pgsql ...
2022-02-17T09:58:02-08:00 [INFO] [/common/dao/pgsql.go:134]: No change in schema, skip.
2022-02-17T09:58:02-08:00 [ERROR] [/common/dao/dao_test.go:58]: pq: relation "project_member" does not exist
2022-02-17T09:58:02-08:00 [ERROR] [/common/dao/dao_test.go:70]: pq: relation "project_member" does not exist
2022-02-17T09:58:02-08:00 [ERROR] [/common/dao/dao_test.go:76]: pq: relation "project" does not exist
2022-02-17T09:58:02-08:00 [ERROR] [/common/dao/dao_test.go:82]: pq: relation "harbor_user" does not exist
2022-02-17T09:58:02-08:00 [ERROR] [/common/dao/dao_test.go:86]: pq: relation "replication_policy" does not exist
2022-02-17T09:58:02-08:00 [ERROR] [/common/dao/dao_test.go:90]: pq: relation "registry" does not exist
panic: pq: relation "harbor_user" does not exist

goroutine 1 [running]:
github.com/astaxie/beego/orm.(*DB).QueryRow(0xc0005cc018, 0xc000324000, 0x107, 0xc00007c750, 0xc, 0xd, 0xe4)
        /home/judson/dev/YM/harbor/src/vendor/github.com/astaxie/beego/orm/db_alias.go:182 +0xc6
github.com/astaxie/beego/orm.(*dbBase).InsertValue(0xc0001184c0, 0xc66f28, 0xc0005cc018, 0xc000524280, 0x100, 0xc00007c680, 0xc, 0xd, 0xc00007c750, 0xc, ...)
        /home/judson/dev/YM/harbor/src/vendor/github.com/astaxie/beego/orm/db.go:491 +0x6ad
github.com/astaxie/beego/orm.(*dbBase).Insert(0xc0001184c0, 0xc66f28, 0xc0005cc018, 0xc000524280, 0xb63b60, 0xc00007c5b0, 0x199, 0x10169a0, 0x0, 0x0, ...)
        /home/judson/dev/YM/harbor/src/vendor/github.com/astaxie/beego/orm/db.go:382 +0x1ea
github.com/astaxie/beego/orm.(*orm).Insert(0xc0001662a0, 0xac4660, 0xc00007c5b0, 0xc0001662a0, 0x0, 0x0)
        /home/judson/dev/YM/harbor/src/vendor/github.com/astaxie/beego/orm/orm.go:164 +0xd3
github.com/goharbor/harbor/src/pkg/user/dao.(*dao).Create(0x1055498, 0xc61c80, 0xc000346cc0, 0xc00059c300, 0xb713e0, 0xc000346c01, 0xc00059c300)
        /home/judson/dev/YM/harbor/src/pkg/user/dao/dao.go:79 +0x222
github.com/goharbor/harbor/src/pkg/user.(*manager).Create(0xc0004e2290, 0xc61c80, 0xc000346cc0, 0xc00059c300, 0xc000122010, 0xabfaa0, 0x1055498)
        /home/judson/dev/YM/harbor/src/pkg/user/manager.go:148 +0x79
github.com/goharbor/harbor/src/common/dao.testForAll(0xc000472200, 0xc0004d33e0)
        /home/judson/dev/YM/harbor/src/common/dao/dao_test.go:123 +0xfa
github.com/goharbor/harbor/src/common/dao.TestMain(0xc000472200)
        /home/judson/dev/YM/harbor/src/common/dao/dao_test.go:111 +0x1a5
main.main()
        _testmain.go:53 +0x165
FAIL    github.com/goharbor/harbor/src/common/dao       0.065s
FAIL
```

That looks like the schema is _there._ I'll continue to poke at it as I have time, but the recreation seems to be:
* do a clean checkout of harbor
* wipe out your test database
* cd src/common/dao
* `env POSTGRESQL_HOST=127.0.0.1 POSTGRESQL_USR=postgres POSTGRESQL_PORT=5432 POSTGRESQL_DATABASE=harbor go test -v ./...`

As a newcomer to the codebase, it's a lot to try to figure out what else I should be doing?
