### ISSUE TITLE
[Step 4]: preparing harbor configs FAILED with error YAMLLoadWarning

### ISSUE THREAD

**Issue by snehalbiche** [goharbor/harbor#16450]
If you are reporting a problem, please make sure the following information are provided:
while running command sudo ./install.sh --with-notary --with-clair --with-chartmuseum I am getting below exception. 

[Step 4]: preparing harbor configs ...
prepare base dir is set to /home/krachchh/harbor
/usr/src/app/utils/configs.py:100: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  configs = yaml.load(f)
Traceback (most recent call last):
  File "main.py", line 72, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "main.py", line 34, in main
    config_dict = parse_yaml_config(conf, with_notary=with_notary, with_clair=with_clair, with_chartmuseum=with_chartmuseum)
  File "/usr/src/app/utils/configs.py", line 100, in parse_yaml_config
    configs = yaml.load(f)
  File "/usr/lib/python3.6/site-packages/yaml/__init__.py", line 115, in load
    return loader.get_single_data()
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3.6/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3.6/site-packages/yaml/composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "/usr/lib/python3.6/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3.6/site-packages/yaml/parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "/usr/lib/python3.6/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/lib/python3.6/site-packages/yaml/scanner.py", line 224, in fetch_more_tokens
    return self.fetch_alias()
  File "/usr/lib/python3.6/site-packages/yaml/scanner.py", line 607, in fetch_alias
    self.tokens.append(self.scan_anchor(AliasToken))
  File "/usr/lib/python3.6/site-packages/yaml/scanner.py", line 921, in scan_anchor
    % ch, self.get_mark())
yaml.scanner.ScannerError: while scanning an alias
  in "/input/harbor.yml", line 164, column 13
expected alphabetic or numeric character, but found '.'
  in "/input/harbor.yml", line 164, column 14

**Expected behavior and actual behavior:**

Harbor installation completes successfully 

**Steps to reproduce the problem:**

Please provide the steps to reproduce this problem.
1) Install pre-reqs
2) download installer offline zip file 
3) run command "sudo ./install.sh --with-notary --with-clair --with-chartmuseum"

**Versions:**
Please specify the versions of the following systems.

- harbor version: v1.10.10
- docker engine version: 
   Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:36 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

- docker-compose version: 
Docker Compose version v2.2.2

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.

- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by zyyw** [comment]
I saw `_version: 1.10.0`, try to use a new version of harbor, say v2.4.2.
