### ISSUE TITLE
installation error - install.sh exits with python error 

### ISSUE THREAD

**Issue by miconx** [goharbor/harbor#16583]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
sudo ./install.sh should install harbor

**Steps to reproduce the problem:**
execute sudo ./install after downloading and extracting release packages (tried online & offline!) 
both throw the python exception in  the prepare stage

[Step 4]: preparing harbor configs ...
prepare base dir is set to /home/micon/norb_data/norb_data/TEXT_DIVERS/IKB/PROJEKTE/hashicorp/NOMAD/harbor_files/harbor
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/app/commands/prepare.py", line 37, in prepare
    config_dict = parse_yaml_config(conf, with_notary=with_notary, with_trivy=with_trivy, with_chartmuseum=with_chartmuseum)
  File "/usr/src/app/utils/configs.py", line 97, in parse_yaml_config
    configs = yaml.safe_load(f)
  File "/usr/lib/python3.10/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3.10/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3.10/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "/input/harbor.yml", line 5, column 1
expected <block end>, but found '<block mapping start>'
  in "/input/harbor.yml", line 29, column 2

**Versions:**
- harbor version: [2.4.2]
- docker engine version: [20.10.13]
- docker-compose version: [1.29.2]

**Comment by miconx** [comment]
found error in config file
