### ISSUE TITLE
install harbor2.5.0 on centos8,harbor jobservice container always restart

### ISSUE THREAD

**Issue by bodhi-code** [goharbor/harbor#16711]
there are jobservice container logs:
Apr 18 15:02:19 172.26.0.1 jobservice[823]: Appending internal tls trust CA to ca-bundle ...
Apr 18 15:02:19 172.26.0.1 jobservice[823]: find: '/etc/harbor/ssl': No such file or directory
Apr 18 15:02:19 172.26.0.1 jobservice[823]: Internal tls trust CA appending is Done.
Apr 18 15:02:19 172.26.0.1 jobservice[823]: 2022-04-18T07:02:19Z [INFO] [/controller/artifact/annotation/parser.go:71]: the annotation parser to parser artifact annotation version v1alpha1 registered
Apr 18 15:02:19 172.26.0.1 jobservice[823]: 2022-04-18T07:02:19Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.cncf.helm.config.v1+json registered
Apr 18 15:02:19 172.26.0.1 jobservice[823]: 2022-04-18T07:02:19Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.cnab.manifest.v1 registered
Apr 18 15:02:19 172.26.0.1 jobservice[823]: 2022-04-18T07:02:19Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.oci.image.index.v1+json registered
Apr 18 15:02:19 172.26.0.1 jobservice[823]: 2022-04-18T07:02:19Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.docker.distribution.manifest.list.v2+json registered
Apr 18 15:02:19 172.26.0.1 jobservice[823]: 2022-04-18T07:02:19Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.docker.distribution.manifest.v1+prettyjws registered
Apr 18 15:02:19 172.26.0.1 jobservice[823]: 2022-04-18T07:02:19Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.oci.image.config.v1+json registered
Apr 18 15:02:19 172.26.0.1 jobservice[823]: 2022-04-18T07:02:19Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.docker.container.image.v1+json registered
Apr 18 15:02:19 172.26.0.1 jobservice[823]: 2022-04-18T07:02:19Z [INFO] [/pkg/reg/adapter/native/adapter.go:36]: the factory for adapter docker-registry registered
Apr 18 15:02:19 172.26.0.1 jobservice[823]: 2022-04-18T07:02:19Z [INFO] [/pkg/reg/adapter/harbor/adaper.go:31]: the factory for adapter harbor registered
Apr 18 15:02:19 172.26.0.1 jobservice[823]: 2022-04-18T07:02:19Z [INFO] [/pkg/reg/adapter/dockerhub/adapter.go:26]: Factory for adapter docker-hub registered
Apr 18 15:02:19 172.26.0.1 jobservice[823]: 2022-04-18T07:02:19Z [INFO] [/pkg/reg/adapter/huawei/huawei_adapter.go:41]: the factory of Huawei adapter was registered
Apr 18 15:02:19 172.26.0.1 jobservice[823]: 2022-04-18T07:02:19Z [INFO] [/pkg/reg/adapter/googlegcr/adapter.go:35]: the factory for adapter google-gcr registered
Apr 18 15:02:19 172.26.0.1 jobservice[823]: 2022-04-18T07:02:19Z [INFO] [/pkg/reg/adapter/awsecr/adapter.go:43]: the factory for adapter aws-ecr registered
Apr 18 15:02:19 172.26.0.1 jobservice[823]: 2022-04-18T07:02:19Z [INFO] [/pkg/reg/adapter/azurecr/adapter.go:15]: Factory for adapter azure-acr registered
Apr 18 15:02:19 172.26.0.1 jobservice[823]: 2022-04-18T07:02:19Z [INFO] [/pkg/reg/adapter/aliacr/adapter.go:31]: the factory for adapter ali-acr registered
Apr 18 15:02:19 172.26.0.1 jobservice[823]: 2022-04-18T07:02:19Z [INFO] [/pkg/reg/adapter/jfrog/adapter.go:46]: the factory of jfrog artifactory adapter was registered
Apr 18 15:02:19 172.26.0.1 jobservice[823]: 2022-04-18T07:02:19Z [INFO] [/pkg/reg/adapter/quay/adapter.go:54]: the factory of Quay adapter was registered
Apr 18 15:02:19 172.26.0.1 jobservice[823]: 2022-04-18T07:02:19Z [INFO] [/pkg/reg/adapter/helmhub/adapter.go:30]: the factory for adapter helm-hub registered
Apr 18 15:02:19 172.26.0.1 jobservice[823]: 2022-04-18T07:02:19Z [INFO] [/pkg/reg/adapter/gitlab/adapter.go:17]: the factory for adapter gitlab registered
Apr 18 15:02:19 172.26.0.1 jobservice[823]: 2022-04-18T07:02:19Z [INFO] [/pkg/reg/adapter/dtr/adapter.go:22]: the factory of dtr adapter was registered
Apr 18 15:02:19 172.26.0.1 jobservice[823]: 2022-04-18T07:02:19Z [INFO] [/pkg/reg/adapter/artifacthub/adapter.go:30]: the factory for adapter artifact-hub registered
Apr 18 15:02:19 172.26.0.1 jobservice[823]: 2022-04-18T07:02:19Z [INFO] [/pkg/reg/adapter/tencentcr/adapter.go:41]: the factory for adapter tencent-tcr registered
Apr 18 15:02:19 172.26.0.1 jobservice[823]: 2022-04-18T07:02:19Z [INFO] [/pkg/reg/adapter/githubcr/adapter.go:29]: the factory for adapter github-ghcr registered
Apr 18 15:02:19 172.26.0.1 jobservice[823]: 2022-04-18T07:02:19Z [ERROR] [/lib/config/config.go:81]: failed to get config manager
Apr 18 15:02:19 172.26.0.1 jobservice[823]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 18 15:02:19 172.26.0.1 jobservice[823]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x2713fd0]
Apr 18 15:02:19 172.26.0.1 jobservice[823]: goroutine 1 [running]:
Apr 18 15:02:19 172.26.0.1 jobservice[823]: main.main()
Apr 18 15:02:19 172.26.0.1 jobservice[823]: #011/harbor/src/jobservice/main.go:38 +0x70

**Comment by stonezdj** [comment]
could you please try installing it on ubuntu? we didn't verify it on CentOS.

**Comment by bodhi-code** [comment]
I have installed harbor in ubuntu, jobservice container is still still restarts with the same error log
ubuntu version 20.04.4 LTS
docker version 20.10.14

**Comment by phin1x** [comment]
The operating system should not matter because of the container.
Is your database running correctly and can the job service connect to the database container? Part of the configuration is stored in it.

**Comment by jotamartos** [comment]
Hi everyone! 

I just tested the official docker image and got the same error when running the binary. I was expecting the same output the previous version provided but that's not the case. Could you please let me know if that's expected? I can still see the information about how to use the different params in the code 

https://github.com/goharbor/harbor/blob/98e1b82fbfcc0f1ab9673e0911ae937e6a6fca36/src/jobservice/main.go#L41 

```
❯ docker run --rm --entrypoint="/harbor/harbor_jobservice" goharbor/harbor-jobservice:v2.4.2
2022-04-18T15:07:11Z [INFO] [/controller/artifact/annotation/parser.go:71]: the annotation parser to parser artifact annotation version v1alpha1 registered
2022-04-18T15:07:11Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.cncf.helm.config.v1+json registered
2022-04-18T15:07:11Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.cnab.manifest.v1 registered
2022-04-18T15:07:11Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.oci.image.index.v1+json registered
2022-04-18T15:07:11Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.docker.distribution.manifest.list.v2+json registered
2022-04-18T15:07:11Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.docker.distribution.manifest.v1+prettyjws registered
2022-04-18T15:07:11Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.oci.image.config.v1+json registered
2022-04-18T15:07:11Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.docker.container.image.v1+json registered
2022-04-18T15:07:11Z [INFO] [/pkg/reg/adapter/native/adapter.go:36]: the factory for adapter docker-registry registered
2022-04-18T15:07:11Z [INFO] [/pkg/reg/adapter/harbor/adaper.go:31]: the factory for adapter harbor registered
2022-04-18T15:07:11Z [INFO] [/pkg/reg/adapter/dockerhub/adapter.go:26]: Factory for adapter docker-hub registered
2022-04-18T15:07:11Z [INFO] [/pkg/reg/adapter/huawei/huawei_adapter.go:41]: the factory of Huawei adapter was registered
2022-04-18T15:07:11Z [INFO] [/pkg/reg/adapter/googlegcr/adapter.go:35]: the factory for adapter google-gcr registered
2022-04-18T15:07:11Z [INFO] [/pkg/reg/adapter/awsecr/adapter.go:43]: the factory for adapter aws-ecr registered
2022-04-18T15:07:11Z [INFO] [/pkg/reg/adapter/azurecr/adapter.go:15]: Factory for adapter azure-acr registered
2022-04-18T15:07:11Z [INFO] [/pkg/reg/adapter/aliacr/adapter.go:32]: the factory for adapter ali-acr registered
2022-04-18T15:07:11Z [INFO] [/pkg/reg/adapter/jfrog/adapter.go:46]: the factory of jfrog artifactory adapter was registered
2022-04-18T15:07:11Z [INFO] [/pkg/reg/adapter/quay/adapter.go:54]: the factory of Quay adapter was registered
2022-04-18T15:07:11Z [INFO] [/pkg/reg/adapter/helmhub/adapter.go:30]: the factory for adapter helm-hub registered
2022-04-18T15:07:11Z [INFO] [/pkg/reg/adapter/gitlab/adapter.go:17]: the factory for adapter gitlab registered
2022-04-18T15:07:11Z [INFO] [/pkg/reg/adapter/dtr/adapter.go:22]: the factory of dtr adapter was registered
2022-04-18T15:07:11Z [INFO] [/pkg/reg/adapter/artifacthub/adapter.go:30]: the factory for adapter artifact-hub registered
2022-04-18T15:07:11Z [INFO] [/pkg/reg/adapter/tencentcr/adapter.go:41]: the factory for adapter tencent-tcr registered
2022-04-18T15:07:11Z [INFO] [/pkg/reg/adapter/githubcr/adapter.go:29]: the factory for adapter github-ghcr registered
Usage of /harbor/harbor_jobservice:
  -c string
    	Specify the yaml config file path
  -graceful
    	listen on open fd (after forking)
  -socketorder string
    	previous initialization order - used when more than one listener was started

~                                                                                                                                                                                                                                    17:07:11
❯ docker run --rm --entrypoint="/harbor/harbor_jobservice" goharbor/harbor-jobservice:v2.5.0
2022-04-18T15:07:16Z [INFO] [/controller/artifact/annotation/parser.go:71]: the annotation parser to parser artifact annotation version v1alpha1 registered
2022-04-18T15:07:16Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.cncf.helm.config.v1+json registered
2022-04-18T15:07:16Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.cnab.manifest.v1 registered
2022-04-18T15:07:16Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.oci.image.index.v1+json registered
2022-04-18T15:07:16Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.docker.distribution.manifest.list.v2+json registered
2022-04-18T15:07:16Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.docker.distribution.manifest.v1+prettyjws registered
2022-04-18T15:07:16Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.oci.image.config.v1+json registered
2022-04-18T15:07:16Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.docker.container.image.v1+json registered
2022-04-18T15:07:16Z [INFO] [/pkg/reg/adapter/native/adapter.go:36]: the factory for adapter docker-registry registered
2022-04-18T15:07:16Z [INFO] [/pkg/reg/adapter/harbor/adaper.go:31]: the factory for adapter harbor registered
2022-04-18T15:07:16Z [INFO] [/pkg/reg/adapter/dockerhub/adapter.go:26]: Factory for adapter docker-hub registered
2022-04-18T15:07:16Z [INFO] [/pkg/reg/adapter/huawei/huawei_adapter.go:41]: the factory of Huawei adapter was registered
2022-04-18T15:07:16Z [INFO] [/pkg/reg/adapter/googlegcr/adapter.go:35]: the factory for adapter google-gcr registered
2022-04-18T15:07:16Z [INFO] [/pkg/reg/adapter/awsecr/adapter.go:43]: the factory for adapter aws-ecr registered
2022-04-18T15:07:16Z [INFO] [/pkg/reg/adapter/azurecr/adapter.go:15]: Factory for adapter azure-acr registered
2022-04-18T15:07:16Z [INFO] [/pkg/reg/adapter/aliacr/adapter.go:31]: the factory for adapter ali-acr registered
2022-04-18T15:07:16Z [INFO] [/pkg/reg/adapter/jfrog/adapter.go:46]: the factory of jfrog artifactory adapter was registered
2022-04-18T15:07:16Z [INFO] [/pkg/reg/adapter/quay/adapter.go:54]: the factory of Quay adapter was registered
2022-04-18T15:07:16Z [INFO] [/pkg/reg/adapter/helmhub/adapter.go:30]: the factory for adapter helm-hub registered
2022-04-18T15:07:16Z [INFO] [/pkg/reg/adapter/gitlab/adapter.go:17]: the factory for adapter gitlab registered
2022-04-18T15:07:16Z [INFO] [/pkg/reg/adapter/dtr/adapter.go:22]: the factory of dtr adapter was registered
2022-04-18T15:07:16Z [INFO] [/pkg/reg/adapter/artifacthub/adapter.go:30]: the factory for adapter artifact-hub registered
2022-04-18T15:07:16Z [INFO] [/pkg/reg/adapter/tencentcr/adapter.go:41]: the factory for adapter tencent-tcr registered
2022-04-18T15:07:16Z [INFO] [/pkg/reg/adapter/githubcr/adapter.go:29]: the factory for adapter github-ghcr registered
2022-04-18T15:07:16Z [ERROR] [/lib/config/config.go:81]: failed to get config manager
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x2713fd0]

goroutine 1 [running]:
main.main()
	/harbor/src/jobservice/main.go:38 +0x70
```

**Comment by phin1x** [comment]
the harbor components need some environment variables to work properly.

the jobservice uses http to pull its config from the api server. to authenticate the api call, the job service uses a secrets with is provided by the `JOBSERVICE_SECRET` env var. if the env var is not present or emtpy, the rest config manager will not be registered and the job service will crash at start when it tries to load the config.

please ensure that the  `JOBSERVICE_SECRET` is set properly.

**Comment by bodhi-code** [comment]
As phin1x said, I retried again and this time I successfully installed it without the container reboot problem. Previously, due to permission issue, I installed harbor in centos8 container, because I didn't implicitly put the directory of harbor installation location into the docker container, which led to the loss of harbor configuration, and eventually the jobservice container kept restarting.
