### ISSUE TITLE
Exception: no migration path found

### ISSUE THREAD

**Issue by QiuToo** [goharbor/harbor#16812]
在升级harbor 1.10.7到2.0.0过程中，迁移数据时出现以下问题：
[root@harbor01 harbor]# docker run -it --rm  -v /:/hostfs   goharbor/prepare:v2.0.0 migrate   -i /app/harbor-backup-1.10.7/harbor/harbor.yml -o /app/harbor/harbor.yml  -t 2.0.0
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/app/commands/migrate.py", line 37, in migrate
    for m in search(input_version, target):
  File "/usr/src/app/utils/migration.py", line 35, in search
    raise Exception('no migration path found')
Exception: no migration path found

**Comment by chlins** [comment]
You should replace volume /:/hostfs to your real path folder.

**Comment by QiuToo** [comment]
> 

Does "/" here represent the old configuration file and "/hostfs" represent the new configuration file?

**Comment by chlins** [comment]
This migrate script is running in the container, so you need to mount your local path into the container, replace the /hostfs to your local host path, for example: `-v /:/app/harbor-backup-1.10.7/harbor`.

**Comment by QiuToo** [comment]
Thank you very much for your answer. I already know how to solve this problem

**Comment by linjicong** [comment]
> Thank you very much for your answer. I already know how to solve this problem

我也遇到这个问题了,请问你是怎么解决的呢
