### ISSUE TITLE
harbor.yml migration

### ISSUE THREAD

**Issue by inzagod** [goharbor/harbor#17099]
What can we help you?
hi,

i want to migrate harbor 2.4.x to 2.5.1 and i received an error when i want to migrate harbor.yml conf file :

[root@ocphrb01 sources]# docker run -it --rm -v /:/hostfs goharbor/prepare:v2.5.1 migrate -i /harbor/install/harbor/harbor.yml
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/app/commands/migrate.py", line 40, in migrate
    for m in search(input_version, target):
  File "/usr/src/app/utils/migration.py", line 60, in search
    raise MigratioNotFound('no migration path found to target version')
utils.migration.MigratioNotFound: no migration path found to target version

can you help me about this issue ?

thanks a lot 

ludo

**Comment by MinerYang** [comment]
hi @inzagod ,
when you are do the config file migration, pls do not edit this part in your harbor.yml file. If you are migrating from v2.4.x to v2.5.x, keep `_version: 2.4.0`  in your original(v2.4.x) harbor.yml as below.
```
#This attribute is for migrator to detect the version of the .cfg file, DO NOT MODIFY!
_version: 2.4.0
```

Otherwise, could you pls provide your harbor.yml file as long as the steps you have done.
Thx

**Comment by MinerYang** [comment]
And could you also refer to the hint on this issue. 
https://github.com/goharbor/harbor/issues/16812
