### ISSUE TITLE
Same WASM artifacts upload with different tools can't be interchangable 

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#17337]
There are two approaches to push wasm artifact, wasm-to-oci and oras, we found the upload artifacts are not interchangeable.
Pushed same wasm artifact with different tools with different tag
Step 1: push from testdata/hello.wasm with wasm-to-oci
```
wasm-to-oci push testdata/hello.wasm 10.161.139.212/sample/hello_wasm:v1 
```

Step 2: push with oras
```
oras push 10.161.139.212/sample/hello_wasm:v3 hello.wasm --manifest-annotations annotation.json --insecure 
```

Step 3: push with wasm-to-oci in current directory
```
oras push 10.161.139.212/sample/hello_wasm:v3 hello.wasm --manifest-annotations annotation.json --insecure 
```

Expecting the digest of v1, v3, v4 should be identical, but they are different after push.  
<img width="1656" alt="Screen Shot 2022-08-05 at 10 09 23 PM" src="https://user-images.githubusercontent.com/2696760/183095508-ef980d9d-9b90-494a-ad3a-954ab7b4c729.png">

Another issue of interchangeable is that the artifact pushed by oras can't pull by wasm-to-oci
```
➜  testdata git:(main) ✗ wasm-to-oci pull  10.161.139.212/sample/hello_wasm:v3 --out hello.wasm
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/engineerd/wasm-to-oci/pkg/oci.Pull(0x7ffeefbff229, 0x23, 0x7ffeefbff253, 0xa, 0xc0001d0000, 0x11e54e5, 0xc000318500)
	/home/radu/projects/src/github.com/engineerd/wasm-to-oci/pkg/oci/pull.go:24 +0x47c
main.(*pullOptions).run(0xc00031ae40, 0x0, 0x0)
	/home/radu/projects/src/github.com/engineerd/wasm-to-oci/cmd/pull.go:37 +0x74
main.newPullCmd.func1(0xc000334b00, 0xc00031b020, 0x1, 0x3, 0x0, 0x0)
	/home/radu/projects/src/github.com/engineerd/wasm-to-oci/cmd/pull.go:27 +0x50
github.com/spf13/cobra.(*Command).execute(0xc000334b00, 0xc00031aff0, 0x3, 0x3, 0xc000334b00, 0xc00031aff0)
	/home/radu/projects/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000334580, 0xc0001dff68, 0x2, 0x2)
	/home/radu/projects/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/radu/projects/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
	/home/radu/projects/src/github.com/engineerd/wasm-to-oci/cmd/main.go:47 +0x3bc
```

**Comment by YangJiao0817** [comment]
Maybe the digest is different because of the different annotation.json, I use the same annotation.json digest is the same.

**Comment by MinerYang** [comment]
For the second part of the problem, harbor didn't receive the PUT request as demand when we trying to push a second tag to an artifact.  
```
Aug  8 02:27:39 172.31.0.1 proxy[1160666]: 10.202.250.222 - "HEAD /v2/wasm/hello-artifact/manifests/sha256:e49db102e68678dcd27fc5d431794602c18c6ee4f0734332210275e902698838 HT
TP/1.1" 401 0 "-" "oras/0.13.0" 0.002 0.000 .                                                                                                                                 
Aug  8 02:27:39 172.31.0.1 proxy[1160666]: 10.202.250.222 - "GET /service/token?scope=repository%3Awasm%2Fhello-artifact%3Apull&service=harbor-registry HTTP/1.1" 200 973 "-" 
"oras/0.13.0" 0.023 0.024 .                                                                                                                                                   
Aug  8 02:27:39 172.31.0.1 proxy[1160666]: 10.202.250.222 - "HEAD /v2/wasm/hello-artifact/manifests/sha256:e49db102e68678dcd27fc5d431794602c18c6ee4f0734332210275e902698838 HT
TP/1.1" 200 0 "-" "oras/0.13.0" 0.008 0.008 .                                                                                                                                 
Aug  8 02:27:39 172.31.0.1 proxy[1160666]: 2022/08/08 02:27:39 [crit] 8#0: *17454 SSL_read() failed (SSL: error:0A000126:SSL routines::unexpected eof while reading) while kee
palive, client: 10.202.250.222, server: 0.0.0.0:8443                                                                                                                          
Aug  8 02:27:42 172.31.0.1 proxy[1160666]: 127.0.0.1 - "GET / HTTP/1.1" 308 171 "-" "curl/7.83.1" 0.000 - .
```

What we should receive is something like below:
```
Aug  8 02:29:01 172.31.0.1 proxy[1160666]: 10.202.250.222 - "HEAD /v2/wasm/hello-artifact/manifests/sha256:e49db102e68678dcd27fc5d431794602c18c6ee4f0734332210275e902698838 HT
TP/1.1" 401 0 "-" "oras/0.13.0" 0.001 0.000 .                                                                                                                                 
Aug  8 02:29:01 172.31.0.1 proxy[1160666]: 10.202.250.222 - "GET /service/token?scope=repository%3Awasm%2Fhello-artifact%3Apull&service=harbor-registry HTTP/1.1" 200 976 "-" 
"oras/0.13.0" 0.023 0.024 .                                                                                                                                                   
Aug  8 02:29:01 172.31.0.1 proxy[1160666]: 10.202.250.222 - "HEAD /v2/wasm/hello-artifact/manifests/sha256:e49db102e68678dcd27fc5d431794602c18c6ee4f0734332210275e902698838 HT
TP/1.1" 404 0 "-" "oras/0.13.0" 0.003 0.004 .                                                                                                                                 
Aug  8 02:29:01 172.31.0.1 proxy[1160666]: 10.202.250.222 - "HEAD /v2/wasm/hello-artifact/blobs/sha256:a948904f2f0f479b8f8197694b30184b0d2ed1c1cd2a1ec0fb85d299a192a447 HTTP/1
.1" 200 0 "-" "oras/0.13.0" 0.008 0.008 .                                                                                                                                     
Aug  8 02:29:01 172.31.0.1 proxy[1160666]: 10.202.250.222 - "HEAD /v2/wasm/hello-artifact/blobs/sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 HTTP/1
.1" 200 0 "-" "oras/0.13.0" 0.007 0.008 .                                                                                                                                     
Aug  8 02:29:01 172.31.0.1 proxy[1160666]: 10.202.250.222 - "PUT /v2/wasm/hello-artifact/manifests/v3 HTTP/1.1" 401 188 "-" "oras/0.13.0" 0.002 0.004 .                       
Aug  8 02:29:01 172.31.0.1 proxy[1160666]: 10.202.250.222 - "GET /service/token?scope=repository%3Awasm%2Fhello-artifact%3Apull%2Cpush&service=harbor-registry HTTP/1.1" 200 9
76 "-" "oras/0.13.0" 0.022 0.020 .                                                                                                                                            
Aug  8 02:29:01 172.31.0.1 proxy[1160666]: 10.202.250.222 - "PUT /v2/wasm/hello-artifact/manifests/v3 HTTP/1.1" 201 0 "-" "oras/0.13.0" 0.029 0.032 .                         
Aug  8 02:29:01 172.31.0.1 proxy[1160666]: 2022/08/08 02:29:01 [crit] 9#0: *17487 SSL_read() failed (SSL: error:0A000126:SSL routines::unexpected eof while reading) while kee
palive, client: 10.202.250.222, server: 0.0.0.0:8443
```
