### ISSUE TITLE
Harbor Trivy scans not working after upgrade to 2.5.4

### ISSUE THREAD

**Issue by dioguerra** [goharbor/harbor#17610]
Just upgrade cluster from 2.5.1 to 2.5.4 and the Harbor - Trivy integration is not working with all scans failing.

In the trivy pod I have the current output:
``` json
{"built_at":"unknown","commit":"none","level":"info","msg":"Starting harbor-scanner-trivy","time":"2022-09-28T12:40:25Z","version":"dev"}
{"addr":":8080","level":"warning","msg":"Starting API server without TLS","time":"2022-09-28T12:40:25Z"}
{"exit_code":2,"image_ref":"harbor-core:80/myrepo/node@sha256:c14713487576a7d0516960cb2e2715885537828af77f1e8737915b24e3206469","level":"error","msg":"Running trivy failed","std_out":"panic: page 19753 already freed\n\ngoroutine 190 [running]:\ngo.etcd.io/bbolt.(*freelist).free(0xc000151b80, 0x79c21, 0x7fb930e29000)\n\t/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/freelist.go:175 +0x2c8\ngo.etcd.io/bbolt.(*node).spill(0xc0007021c0)\n\t/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/node.go:359 +0x216\ngo.etcd.io/bbolt.(*node).spill(0xc000702150)\n\t/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/node.go:346 +0xaa\ngo.etcd.io/bbolt.(*Bucket).spill(0xc00098e2b8)\n\t/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/bucket.go:570 +0x33f\ngo.etcd.io/bbolt.(*Tx).Commit(0xc00098e2a0)\n\t/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/tx.go:160 +0xe7\ngo.etcd.io/bbolt.(*DB).Update(0x1cb95a0?, 0xc000b7d740)\n\t/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:748 +0xe5\ngithub.com/aquasecurity/fanal/cache.FSCache.PutBlob({0xc001062b40?, {_, _}}, {_, _}, {0x2, {0xc000b5a0a0, 0x47}, {0xc000a12690, 0x47}, ...})\n\t/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220414083417-61bfa9f92483/cache/fs.go:85 +0x1c5\ngithub.com/aquasecurity/fanal/artifact/image.Artifact.inspect.func1({0x2230f10, 0xc000790480}, {0xc00077c5a0, 0x47})\n\t/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220414083417-61bfa9f92483/artifact/image/image.go:161 +0x306\ncreated by github.com/aquasecurity/fanal/artifact/image.Artifact.inspect\n\t/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220414083417-61bfa9f92483/artifact/image/image.go:154 +0x512\n","time":"2022-09-28T12:40:52Z"}
{"error":"running trivy wrapper: running trivy: exit status 2: panic: page 19753 already freed\n\ngoroutine 190 [running]:\ngo.etcd.io/bbolt.(*freelist).free(0xc000151b80, 0x79c21, 0x7fb930e29000)\n\t/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/freelist.go:175 +0x2c8\ngo.etcd.io/bbolt.(*node).spill(0xc0007021c0)\n\t/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/node.go:359 +0x216\ngo.etcd.io/bbolt.(*node).spill(0xc000702150)\n\t/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/node.go:346 +0xaa\ngo.etcd.io/bbolt.(*Bucket).spill(0xc00098e2b8)\n\t/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/bucket.go:570 +0x33f\ngo.etcd.io/bbolt.(*Tx).Commit(0xc00098e2a0)\n\t/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/tx.go:160 +0xe7\ngo.etcd.io/bbolt.(*DB).Update(0x1cb95a0?, 0xc000b7d740)\n\t/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:748 +0xe5\ngithub.com/aquasecurity/fanal/cache.FSCache.PutBlob({0xc001062b40?, {_, _}}, {_, _}, {0x2, {0xc000b5a0a0, 0x47}, {0xc000a12690, 0x47}, ...})\n\t/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220414083417-61bfa9f92483/cache/fs.go:85 +0x1c5\ngithub.com/aquasecurity/fanal/artifact/image.Artifact.inspect.func1({0x2230f10, 0xc000790480}, {0xc00077c5a0, 0x47})\n\t/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220414083417-61bfa9f92483/artifact/image/image.go:161 +0x306\ncreated by github.com/aquasecurity/fanal/artifact/image.Artifact.inspect\n\t/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220414083417-61bfa9f92483/artifact/image/image.go:154 +0x512\n","level":"error","msg":"Scan failed","time":"2022-09-28T12:40:52Z"}
{"error":"running trivy wrapper: running trivy: exit status 2: panic: page 19753 already freed\n\ngoroutine 190 [running]:\ngo.etcd.io/bbolt.(*freelist).free(0xc000151b80, 0x79c21, 0x7fb930e29000)\n\t/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/freelist.go:175 +0x2c8\ngo.etcd.io/bbolt.(*node).spill(0xc0007021c0)\n\t/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/node.go:359 +0x216\ngo.etcd.io/bbolt.(*node).spill(0xc000702150)\n\t/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/node.go:346 +0xaa\ngo.etcd.io/bbolt.(*Bucket).spill(0xc00098e2b8)\n\t/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/bucket.go:570 +0x33f\ngo.etcd.io/bbolt.(*Tx).Commit(0xc00098e2a0)\n\t/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/tx.go:160 +0xe7\ngo.etcd.io/bbolt.(*DB).Update(0x1cb95a0?, 0xc000b7d740)\n\t/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:748 +0xe5\ngithub.com/aquasecurity/fanal/cache.FSCache.PutBlob({0xc001062b40?, {_, _}}, {_, _}, {0x2, {0xc000b5a0a0, 0x47}, {0xc000a12690, 0x47}, ...})\n\t/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220414083417-61bfa9f92483/cache/fs.go:85 +0x1c5\ngithub.com/aquasecurity/fanal/artifact/image.Artifact.inspect.func1({0x2230f10, 0xc000790480}, {0xc00077c5a0, 0x47})\n\t/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220414083417-61bfa9f92483/artifact/image/image.go:161 +0x306\ncreated by github.com/aquasecurity/fanal/artifact/image.Artifact.inspect\n\t/home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20220414083417-61bfa9f92483/artifact/image/image.go:154 +0x512\n","level":"error","msg":"Scan job failed","scan_job_id":"d601f3cc5c5a4e60e49d87f0","time":"2022-09-28T12:40:54Z"}
```

Tried to use Trivy goharbor/trivy-adapter-photon:v2.6.0 and the old one goharbor/trivy-adapter-photon:v2.5.1 with no success.

**Comment by rrgadeev** [comment]
docker-compose down -v
set trivy options
  ignore_unfixed: false
 #  timeout: 15m0s
  skip_update: false
  offline_scan: false
  insecure: false
./prepare  --with-trivy
docker-compose up -d
I have trive running through a proxy, there was a timeout and insecure: true. The packages simply did not reach the proxy, it was not possible to update the vulnerability database.

**Comment by dioguerra** [comment]
This is the data from harbor side:
```
2022-10-06T13:08:18Z [INFO] [/pkg/scan/job.go:385]: {
  "uuid": "6809b473-11fb-11eb-93ee-e6a720a2df22",
  "name": "Trivy",
  "description": "The Trivy scanner adapter",
  "url": "http://harbor-trivy:8080",
  "disabled": false,
  "is_default": true,
  "health": "healthy",
  "auth": "",
  "access_credential": "[HIDDEN]",
  "skip_certVerify": false,
  "use_internal_addr": true,
  "adapter": "Trivy",
  "vendor": "Aqua Security",
  "version": "v0.29.2",
  "create_time": "2020-10-19T13:08:24.486231Z",
  "update_time": "2022-02-23T10:12:32.887639Z"
}
2022-10-06T13:08:18Z [INFO] [/pkg/scan/job.go:385]: {
  "registry": {
    "url": "http://harbor-core:80",
    "authorization": "[HIDDEN]"
  },
  "artifact": {
    "namespace_id": 19,
    "repository": "foo/bar",
    "tag": "v3.13.2",
    "digest": "sha256:b3715c9a19baace7303e35755753bd17225dad877cac28fbea9d876c822fa523",
    "mime_type": "application/vnd.docker.distribution.manifest.v2+json"
  }
}
2022-10-06T13:08:18Z [INFO] [/pkg/scan/job.go:167]: Report mime types: [application/vnd.security.vulnerability.report; version=1.1]
2022-10-06T13:08:18Z [INFO] [/pkg/scan/job.go:222]: Get report for mime type: application/vnd.security.vulnerability.report; version=1.1
2022-10-06T13:08:20Z [INFO] [/pkg/scan/job.go:243]: Report with mime type application/vnd.security.vulnerability.report; version=1.1 is not ready yet, retry after 5 seconds
2022-10-06T13:08:25Z [ERROR] [/pkg/scan/job.go:292]: check scan report with mime type application/vnd.security.vulnerability.report; version=1.1: running trivy wrapper: running trivy: exit status 2: 2022-10-06T13:08:22.232Z	[34mINFO[0m	Vulnerability scanning is enabled
2022-10-06T13:08:22.232Z	[34mINFO[0m	Secret scanning is enabled
2022-10-06T13:08:22.232Z	[34mINFO[0m	If your scanning is slow, please try '--security-checks vuln' to disable secret scanning
2022-10-06T13:08:22.232Z	[34mINFO[0m	Please see also https://aquasecurity.github.io/trivy/v0.29.2/docs/secret/scanning/#recommendation for faster secret detection
panic: page 19753 already freed

goroutine 227 [running]:
go.etcd.io/bbolt.(*freelist).free(0xc000ef6580, 0x8a106, 0x7fe8ae329000)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/freelist.go:175 +0x2c8
go.etcd.io/bbolt.(*node).spill(0xc001023490)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/node.go:359 +0x216
go.etcd.io/bbolt.(*node).spill(0xc001023420)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/node.go:346 +0xaa
go.etcd.io/bbolt.(*Bucket).spill(0xc00087e7f8)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/bucket.go:570 +0x33f
go.etcd.io/bbolt.(*Tx).Commit(0xc00087e7e0)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/tx.go:160 +0xe7
go.etcd.io/bbolt.(*DB).Update(0x3400180?, 0xc00173b730)
	/home/runner/go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:748 +0xe5
github.com/aquasecurity/trivy/pkg/fanal/cache.FSCache.PutBlob({0xc0006b2fc0?, {_, _}}, {_, _}, {0x2, {0xc001510190, 0x47}, {0xc001470280, 0x47}, ...})
	/home/runner/work/trivy/trivy/pkg/fanal/cache/fs.go:85 +0x1c5
github.com/aquasecurity/trivy/pkg/fanal/artifact/image.Artifact.inspect.func1({0x3d63820, 0xc001d5a6c0}, {0xc0014708c0, 0x47})
	/home/runner/work/trivy/trivy/pkg/fanal/artifact/image/image.go:177 +0x3a6
created by github.com/aquasecurity/trivy/pkg/fanal/artifact/image.Artifact.inspect
	/home/runner/work/trivy/trivy/pkg/fanal/artifact/image/image.go:163 +0x532
: general response handler: unexpected status code: 500, expected: 200
```
