### ISSUE TITLE
jobs container can not start , report x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by coachafei** [goharbor/harbor#17679]
What can we help you?
I installed harbor with internal_tls enabled, and get all the internal component certificates by command:
```
docker run -v /data/harbor/tls:/hostfs goharbor/prepare:v2.6.1 gencert -p /internal
```
The installer run successfully, but when I run command `docker-compose ps -a` to check the service then found  jobservice and nginx service always restart. 

`docker logs -f jobservice_container_id` logs shows below:
```
2022-10-22T15:37:16Z [INFO] [/pkg/reg/adapter/quay/adapter.go:54]: the factory of Quay adapter was registered
2022-10-22T15:37:16Z [INFO] [/pkg/reg/adapter/tencentcr/adapter.go:41]: the factory for adapter tencent-tcr registered
2022-10-22T15:37:16Z [INFO] [/pkg/config/rest/rest.go:47]: get configuration from url: https://core:8443/api/v2.0/internalconfig
2022-10-22T15:37:16Z [ERROR] [/pkg/config/rest/rest.go:50]: Failed on load rest config err:Get 
"https://core:8443/api/v2.0/internalconfig": x509: certificate signed by unknown authority, 
url:https://core:8443/api/v2.0/internalconfig
panic: failed to load configuration, error: failed to load rest config

goroutine 1 [running]:
main.main()
	/harbor/src/jobservice/main.go:42 +0x4b9
```
Why the service didn't trust the certificate which was signed by the prepare tool?

**Comment by coachafei** [comment]
I found the reason, because the certificate in common/config/shared/trust-certificates/core.crt which was loaded to ca-bundle by job-service container was a blank file. And I copy one from `tls/internal/core.crt` then jobservice container start successfully.
