### ISSUE TITLE
 Upgrade 1.10.15 to 2.10.0 prepare migrate encounter error external_redis.port

### ISSUE THREAD

**Issue by lklkxcxc** [goharbor/harbor#17837]
I try to upgrade 1.10.15 to 2.10.0 prepare migrate report error:
error log：
```
migrating to version 2.0.0
migrating to version 2.1.0
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/app/commands/migrate.py", line 43, in migrate
    m.migrate(current_input_path, current_output_path)
  File "/usr/src/app/migrations/version_2_1_0/__init__.py", line 30, in migrate
    f.write(tpl.render(**config_dict))
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/src/app/migrations/version_2_1_0/harbor.yml.jinja", line 368, in top-level template code
    host: {{ external_redis.host }}:{{ external_redis.port }}
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'port'
```
old harbor.yml:
```
external_redis:
  host: 192.168.16.131
  port: 6379
  password: 
  # db_index 0 is for core, it's unchangeable
  registry_db_index: 1
  jobservice_db_index: 2
  chartmuseum_db_index: 3
  clair_db_index: 4
```

**Comment by lklkxcxc** [comment]
as a workaround, you can use a newer version of goharbor/prepare:v2.3.0-rc1.
Or you can wait for the stable release like goharbor/prepare:2.2.3 or goharbor/prepare:2.3.0

**Comment by MinerYang** [comment]
Hi @lklkxcxc ,
Could you provide the 1.10 yaml you are using? and btw we don't have version 2.10..0, are you migrate to 2.1.0 official release?

**Comment by lklkxcxc** [comment]
@MinerYang Sorry !  It release is 2.1.0. yaml content:
```
external_redis:
  host: 192.168.1.146
  port: 6379
  password:

**Comment by lklkxcxc** [comment]
Retry prepare migrate before it has did comment redis port .

**Comment by lklkxcxc** [comment]
Retry prepare migrate before it has did comment redis port .

**Comment by lklkxcxc** [comment]
Retry prepare migrate before it has did comment redis port .
