### ISSUE TITLE
docker.errors.APIError: 500 Server Error

### ISSUE THREAD

**Issue by HanGuangyu** [goharbor/harbor#18035]
Hi,

I encountered a strange phenomenon. I can complete the pull operation through the cli, but the python sdk reports an error.

```bash
docker pull hub.chinauos.com/kolla-ustack/uniontechos-source-cron:train
```
cli is OK, I can pull the image.

But if I excuate pull by python sdk, I got error. I'm a newer in this, does anyone know what could be the cause? 

This harbor is a private harbor, but I am not an administrator. I am not sure if it have done any configuration. What configuration may cause this problem?
```python3
>>> import docker
>>> client = docker.from_env()
>>> client.images.pull('hub.chinauos.com/kolla-ustack/uniontechos-source-cron')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.41/images/create?tag=latest&fromImage=hub.chinauos.com%2Fkolla-ustack%2Funiontechos-source-cron

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/docker/models/images.py", line 466, in pull
    repository, tag=tag, stream=True, all_tags=all_tags, **kwargs
  File "/usr/local/lib/python3.7/dist-packages/docker/api/image.py", line 429, in pull
    self._raise_for_status(response)
  File "/usr/local/lib/python3.7/dist-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/usr/local/lib/python3.7/dist-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=latest&fromImage=hub.chinauos.com%2Fkolla-ustack%2Funiontechos-source-cron: Internal Server Error ("Head "https://hub.chinauos.com/v2/kolla-ustack/uniontechos-source-cron/manifests/latest": error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<!DOCTYPE html>\n<html>\n<head>\n<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n<title>403</title>\n<style type=\"text/css\">\nbody {\n    background-color: #f3f3f4;\n    color: #676a6c;\n    height: 100%;\n    font-family: -apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,sans-serif,\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Segoe UI Symbol\";\n}\n\n.middle-box {\n  max-width: 600px;\n  z-index: 100;\n  margin: 0 auto;\n  padding-top: 40px;\n  text-align: center;\n}\n\n.middle-box h1 {\n  font-size: 170px;\n  font-weight: 100;\n  margin-top: 20px;\n  margin-bottom: 10px;\n}\n\n.btn {\n  border-radius: 3px;\n  font-size: inherit;\n  display: inline-block;\n  width: 100px;\n  height: 30px;\n  line-height: 30px;\n  background-color: #1ab394;\n  border-color: #1ab394;\n  color: #fff;\n  cursor: pointer;\n  font-size: 14px;\n}\n\n.btn:hover {\n  background-color: #1c8570;\n}\n\n.btn:active {\n  background-image: none;\n  outline: 0;\n  -webkit-box-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125);\n  box-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125);\n}\n\n.buttons {\n    margin-top: 30px;\n}\n\n</style>\n</head>\n<body>\n    <div class=\"middle-box\">\n        <h1>403</h1>\n        <h3 class=\"font-bold\">Forbidden</h3>\n        <div class=\"error-desc\">因权限问题或行为非法，您的访问被拒绝。</div>\n        <div class=\"buttons\"><a class=\"btn btn-primary\" onclick=\"javascript:history.back()\">返回</a></div>\n    </div>\n</body>\n</html>\n<span style=\"position: absolute;bottom: 0;left: 50%;transform: translate(-50%, 0);\">Request ID:  7182593655883099695</span>"")
```

I will appreciate for any help.

**Comment by Vad1mo** [comment]
you get a 403 error, you you need to set the credentials in the python sdk, which you did for the cli. 

please refer to the python sdk you are using.
