### ISSUE TITLE
Failed to upgrade schema, error: "Dirty database version 100. Fix and force version."

### ISSUE THREAD

**Issue by CoreTechnologyAG** [goharbor/harbor#18034]
**Expected behavior and actual behavior:**
Migrate the database from V2.6.1 to V2.7.0 via helm chart 1.11.0

helm ls -n system-registry before and after upgrade
| Status | NAME | NAMESPACE   | REVISION | UPDATED | STATUS          | CHART                                           | APP VERSION |
| --- | --- | --- |  --- | --- |  --- | --- | --- | 
| **before upgrade**: all container are running | harbor |                                 system-registry        |                 14        |      2022-10-19 10:24:18.6208134 +0200 CEST  |deployed      |  harbor-1.10.1           |                        2.6.1   |   
| **after upgrade**: core/jobservice not running. other kubernetes container are running with 2.7.0 | harbor |                                 system-registry        |                 15        |      2022-10-19 10:24:18.6208134 +0200 CEST  |deployed      |  harbor-1.11.0           |                        2.7.0  | 

**Steps to reproduce the problem:**
- Running v2.6.1
-Helm Upgrade
   helm upgrade harbor harbor/harbor --version 1.11.0 --namespace system-registry -f ./harbor.coreintern.ch/values_ct.yaml
   - value_ct.yaml is the same file

**Versions:**
- harbor version: 2.7.0
- kubernetes: v1.24.8
- postgresql: v15.0.0

-  **Log files:**
**core-Logfiles**

Appending internal tls trust CA to ca-bundle ...
find: '/etc/harbor/ssl': No such file or directory
Internal tls trust CA appending is Done.
2022/12/29 14:01:20.857 [1;44m[D][0m  init global config instance failed. If you do not use this, just ignore it.  open conf/app.conf: no such file or directory
2022-12-29T14:01:20Z [ERROR] [/pkg/registry/client.go:82]: Failed to parse REGISTRY_HTTP_CLIENT_TIMEOUT: strconv.ParseInt: parsing "": invalid syntax, use default value: 30m0s
2022-12-29T14:01:20Z [INFO] [/controller/artifact/annotation/parser.go:71]: the annotation parser to parser artifact annotation version v1alpha1 registered
2022-12-29T14:01:20Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.wasm.config.v1+json registered
2022-12-29T14:01:20Z [ERROR] [/lib/config/config.go:81]: failed to get config manager
2022-12-29T14:01:20Z [ERROR] [/lib/config/config.go:81]: failed to get config manager
2022-12-29T14:01:20Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.cncf.helm.config.v1+json registered
2022-12-29T14:01:20Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.cnab.manifest.v1 registered
2022-12-29T14:01:20Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.oci.image.index.v1+json registered
2022-12-29T14:01:20Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.docker.distribution.manifest.list.v2+json registered
2022-12-29T14:01:20Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.docker.distribution.manifest.v1+prettyjws registered
2022-12-29T14:01:20Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.oci.image.config.v1+json registered
2022-12-29T14:01:20Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.docker.container.image.v1+json registered
2022-12-29T14:01:20Z [INFO] [/pkg/reg/adapter/native/adapter.go:36]: the factory for adapter docker-registry registered
2022-12-29T14:01:20Z [INFO] [/pkg/reg/adapter/aliacr/adapter.go:30]: the factory for adapter ali-acr registered
2022-12-29T14:01:20Z [INFO] [/pkg/reg/adapter/artifacthub/adapter.go:30]: the factory for adapter artifact-hub registered
2022-12-29T14:01:20Z [INFO] [/pkg/reg/adapter/awsecr/adapter.go:44]: the factory for adapter aws-ecr registered
2022-12-29T14:01:20Z [INFO] [/pkg/reg/adapter/azurecr/adapter.go:29]: Factory for adapter azure-acr registered
2022-12-29T14:01:20Z [INFO] [/pkg/reg/adapter/dockerhub/adapter.go:26]: Factory for adapter docker-hub registered
2022-12-29T14:01:20Z [INFO] [/pkg/reg/adapter/dtr/adapter.go:22]: the factory of dtr adapter was registered
2022-12-29T14:01:20Z [INFO] [/pkg/reg/adapter/githubcr/adapter.go:29]: the factory for adapter github-ghcr registered
2022-12-29T14:01:20Z [INFO] [/pkg/reg/adapter/gitlab/adapter.go:18]: the factory for adapter gitlab registered
2022-12-29T14:01:20Z [INFO] [/pkg/reg/adapter/googlegcr/adapter.go:37]: the factory for adapter google-gcr registered
2022-12-29T14:01:20Z [INFO] [/pkg/reg/adapter/harbor/adaper.go:31]: the factory for adapter harbor registered
2022-12-29T14:01:20Z [INFO] [/pkg/reg/adapter/helmhub/adapter.go:30]: the factory for adapter helm-hub registered
2022-12-29T14:01:20Z [INFO] [/pkg/reg/adapter/huawei/huawei_adapter.go:40]: the factory of Huawei adapter was registered
2022-12-29T14:01:20Z [INFO] [/pkg/reg/adapter/jfrog/adapter.go:42]: the factory of jfrog artifactory adapter was registered
2022-12-29T14:01:20Z [INFO] [/pkg/reg/adapter/quay/adapter.go:53]: the factory of Quay adapter was registered
2022-12-29T14:01:20Z [INFO] [/pkg/reg/adapter/tencentcr/adapter.go:41]: the factory for adapter tencent-tcr registered
2022-12-29T14:01:20Z [INFO] [/core/controllers/base.go:159]: Config path: /etc/core/app.conf
2022-12-29T14:01:20Z [INFO] [/core/main.go:138]: initializing cache ...
2022-12-29T14:01:20Z [INFO] [/core/main.go:148]: initializing configurations...
2022-12-29T14:01:20Z [INFO] [/lib/config/systemconfig.go:198]: key path: /etc/core/key
2022-12-29T14:01:20Z [INFO] [/lib/config/config.go:92]: init secret store
2022-12-29T14:01:20Z [INFO] [/core/main.go:150]: configurations initialization completed
2022-12-29T14:01:20Z [INFO] [/common/dao/base.go:67]: Registering database: type-PostgreSQL host-postgresql.system-registry.svc.cluster.local port-5432 database-registry sslmode-"disable"
2022-12-29T14:01:20Z [INFO] [/lib/metric/server.go:23]: Prometheus metric server running on port 8001
2022-12-29T14:01:20Z [INFO] [/common/dao/base.go:72]: Register database completed
2022-12-29T14:01:21Z [INFO] [/common/dao/pgsql.go:135]: **Upgrading schema for pgsql ...**
2022-12-29T14:01:21Z [ERROR] [/common/dao/pgsql.go:140]: **Failed to upgrade schema, error: "Dirty database version 100. Fix and force version."**
2022-12-29T14:01:21Z [FATAL] [/core/main.go:179]: failed to migrate the database, error: Dirty database version 100. Fix and force version.

**jobservice-Logfile**
Appending internal tls trust CA to ca-bundle ...
find: '/etc/harbor/ssl': No such file or directory
Internal tls trust CA appending is Done.
2022-12-29T14:24:33Z [ERROR] [/pkg/registry/client.go:82]: Failed to parse REGISTRY_HTTP_CLIENT_TIMEOUT: strconv.ParseInt: parsing "": invalid syntax, use default value: 30m0s
2022-12-29T14:24:33Z [INFO] [/controller/artifact/annotation/parser.go:71]: the annotation parser to parser artifact annotation version v1alpha1 registered
2022-12-29T14:24:33Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.wasm.config.v1+json registered
2022-12-29T14:24:33Z [ERROR] [/lib/config/config.go:81]: failed to get config manager
2022-12-29T14:24:33Z [ERROR] [/lib/config/config.go:81]: failed to get config manager
2022-12-29T14:24:33Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.cncf.helm.config.v1+json registered
2022-12-29T14:24:33Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.cnab.manifest.v1 registered
2022-12-29T14:24:33Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.oci.image.index.v1+json registered
2022-12-29T14:24:33Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.docker.distribution.manifest.list.v2+json registered
2022-12-29T14:24:33Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.docker.distribution.manifest.v1+prettyjws registered
2022-12-29T14:24:33Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.oci.image.config.v1+json registered
2022-12-29T14:24:33Z [INFO] [/controller/artifact/processor/processor.go:59]: the processor to process media type application/vnd.docker.container.image.v1+json registered
2022/12/29 14:24:33.942 [1;44m[D][0m  init global config instance failed. If you do not use this, just ignore it.  open conf/app.conf: no such file or directory
2022-12-29T14:24:33Z [ERROR] [/pkg/config/manager.go:66]: LoadSystemConfigFromEnv failed, config item, key: postgresql_port,  err: strconv.Atoi: parsing "tcp://10.108.189.105:5432": invalid syntax
2022-12-29T14:24:33Z [ERROR] [/pkg/config/manager.go:66]: LoadSystemConfigFromEnv failed, config item, key: postgresql_port,  err: strconv.Atoi: parsing "tcp://10.108.189.105:5432": invalid syntax
2022-12-29T14:24:33Z [INFO] [/pkg/reg/adapter/native/adapter.go:36]: the factory for adapter docker-registry registered
2022-12-29T14:24:33Z [INFO] [/pkg/reg/adapter/aliacr/adapter.go:30]: the factory for adapter ali-acr registered
2022-12-29T14:24:33Z [INFO] [/pkg/reg/adapter/artifacthub/adapter.go:30]: the factory for adapter artifact-hub registered
2022-12-29T14:24:33Z [INFO] [/pkg/reg/adapter/awsecr/adapter.go:44]: the factory for adapter aws-ecr registered
2022-12-29T14:24:33Z [INFO] [/pkg/reg/adapter/azurecr/adapter.go:29]: Factory for adapter azure-acr registered
2022-12-29T14:24:33Z [INFO] [/pkg/reg/adapter/dockerhub/adapter.go:26]: Factory for adapter docker-hub registered
2022-12-29T14:24:33Z [INFO] [/pkg/reg/adapter/dtr/adapter.go:22]: the factory of dtr adapter was registered
2022-12-29T14:24:33Z [INFO] [/pkg/reg/adapter/githubcr/adapter.go:29]: the factory for adapter github-ghcr registered
2022-12-29T14:24:33Z [INFO] [/pkg/reg/adapter/gitlab/adapter.go:18]: the factory for adapter gitlab registered
2022-12-29T14:24:33Z [INFO] [/pkg/reg/adapter/googlegcr/adapter.go:37]: the factory for adapter google-gcr registered
2022-12-29T14:24:33Z [INFO] [/pkg/reg/adapter/harbor/adaper.go:31]: the factory for adapter harbor registered
2022-12-29T14:24:33Z [INFO] [/pkg/reg/adapter/helmhub/adapter.go:30]: the factory for adapter helm-hub registered
2022-12-29T14:24:33Z [INFO] [/pkg/reg/adapter/huawei/huawei_adapter.go:40]: the factory of Huawei adapter was registered
2022-12-29T14:24:33Z [INFO] [/pkg/reg/adapter/jfrog/adapter.go:42]: the factory of jfrog artifactory adapter was registered
2022-12-29T14:24:33Z [INFO] [/pkg/reg/adapter/quay/adapter.go:53]: the factory of Quay adapter was registered
2022-12-29T14:24:33Z [INFO] [/pkg/reg/adapter/tencentcr/adapter.go:41]: the factory for adapter tencent-tcr registered
2022-12-29T14:24:33Z [ERROR] [/pkg/config/manager.go:66]: LoadSystemConfigFromEnv **failed, config item, key: postgresql_port,  err: strconv.Atoi: parsing "tcp://10.108.189.105:5432": invalid syntax**
2022-12-29T14:24:33Z [INFO] [/pkg/config/rest/rest.go:47]: get configuration from url: http://harbor-core:80/api/v2.0/internalconfig
2022-12-29T14:24:34Z [ERROR] [/pkg/config/rest/rest.go:50]: Failed on load rest config err:Get "http://harbor-core:80/api/v2.0/internalconfig": dial tcp 10.111.253.31:80: connect: connection refused, url:http://harbor-core:80/api/v2.0/internalconfig
panic: failed to load configuration, error: failed to load rest config
goroutine 1 [running]:
main.main()
/harbor/src/jobservice/main.go:42 +0x4b9

**Comment by stonezdj** [comment]
What is the output in postgresql.log in upgrade 

You could update the  schema_migrations and try again.
```
update schema_migrations set version = 90, dirty=false where 1 = 1
```

**Comment by CoreTechnologyAG** [comment]
Thanks for responsing and your support

#### executed Steps:
1. Executed the above sql-script
2. Upgrade helm-chart to 1.11.0
3. Checked pod-logs:
    - postgres: [harborCase18034V1.11.0_postgresql.log](https://github.com/goharbor/harbor/files/10342174/harborCase18034V1.11.0_postgresql.log)
    - harbor-core-* v2.7.0: still same error Failed to upgrade schema, error: "Dirty database version 100. Fix and force version.": [harborCase18034V1.11.0_harborCore.log](https://github.com/goharbor/harbor/files/10342175/harborCase18034V1.11.0_harborCore.log)


#### Rollback steps
1. Rollback again to v2.6.1
    1. scale deployment from harbor-core and harbor-jobservice down to 0
    2.  scale deployment rom harbor-core and harbor-jobservice up to 1
    3. not starting: still same error in harbor-core-log (2 additional log entries) [harborCase18034V1.11.0_postgresqlAfterRollback.log](https://github.com/goharbor/harbor/files/10342209/harborCase18034V1.11.0_postgresqlAfterRollback.log)
2. scale all deployments to 0
3. scale statefulset postgresql to 0
4. restore database
5. scale up to 1 statefulset and deployments again.
6. everything running back on v2.6.1 again.

**Comment by stonezdj** [comment]
In the https://github.com/goharbor/harbor/files/10342174/harborCase18034V1.11.0_postgresql.log, found that sql:
```
delete from artifact_blob afb where not exists (select digest from blob b where b.digest = afb.digest_af);
```
It is a SQL for Harbor 2.8.0, it should not be executed in the upgrade to 2.7.0.

**Comment by CoreTechnologyAG** [comment]
The last SQL-Schema-Upgrade is 0090_2.6.0_schema.up.sql.

If I grep after "delete from artifact_blob" in this migration-folder, I don't find anything.

Where do this "delete"-statement come from. I just upgraded via helm-chart. Can I influence this via the value-File of the helm-chart. I didn't find a option/parameter.

In the tar.gz-file I send you all sql-statements from the migration-folder. 
[harbor_mig_postgresql.gz](https://github.com/goharbor/harbor/files/10371375/harbor_mig_postgresql.gz)

**Comment by stonezdj** [comment]
Current Harbor 2.7.0 doesn't support Postgres 15.
there is an error in postgressql log
```
ERROR:  permission denied for schema public at character 108
```
see: https://www.cybertec-postgresql.com/en/error-permission-denied-schema-public/
Please use postgres 13.4

**Comment by CoreTechnologyAG** [comment]
Thanks for your help.
Oh, I see, 

Is there maybe already a plan to upgrade to postgresql V14 or V15 ;-). Or is this a feature request?

**Comment by baoroushi** [comment]
> What is the output in postgresql.log in upgrade
> 
> You could update the schema_migrations and try again.
> 
> ```
> update schema_migrations set version = 90, dirty=false where 1 = 1
> ```

I hit the same issue, when I fresh install harbor 2.7.0 with helm.  This method can solve my problem. Thank you very much.

**Comment by neha-live** [comment]
> What is the output in postgresql.log in upgrade
> 
> You could update the schema_migrations and try again.
> 
> ```
> update schema_migrations set version = 90, dirty=false where 1 = 1
> ```

I tried this but not helping anyway.. still getting same error

**Comment by neha-live** [comment]
> Thanks for your help. Oh, I see,
> 
> Is there maybe already a plan to upgrade to postgresql V14 or V15 ;-). Or is this a feature request?
I am using v13.4 only but getting internal server error after updating dirty =false and project storage is not showing.
