### ISSUE TITLE
Migrate job during upgrade from 2.6.3 to 2.7.0 fails with 'dict object' has no attribute 'notary_signer"

### ISSUE THREAD

**Issue by 7oku** [goharbor/harbor#18115]
**Expected behavior and actual behavior:**
Migrate should succeed.

**Steps to reproduce the problem:**
Upgrade from 2.6.3 to 2.7.0

**Versions:**
- harbor version: 2.6.3
- docker engine version: 20.10.22
- docker-compose version: v2.14.1

**Additional context:**
The migration job described at [upgrade guide 2.7.0](https://goharbor.io/docs/2.7.0/administration/upgrade/) in _step 6_ fails with a traceback, see logfile.

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
```
hostname: <hostname>

http:
  port: 80

external_url: https://<exturl>
harbor_admin_password: <password>
data_volume: </path/to/harbor-data>

trivy:
  ignore_unfixed: false
  skip_update: false
  offline_scan: false
  insecure: false
jobservice:
  max_job_workers: 10

notification:
  webhook_job_max_retry: 10

chart:
  absolute_url: disabled

log:
  level: info
  local:
    rotate_count: 50
    rotate_size: 200M
    location: /var/log/harbor

_version: 2.6.0

external_database:
  harbor:
    host: <dburl>
    port: 5432
    db_name: <dbname>
    username: <dbuser>
    password: <dbpassword>
    ssl_mode: require
    max_idle_conns: 2
    max_open_conns: 0

proxy:
  http_proxy:
  https_proxy:
  no_proxy:
  components:
    - core
    - jobservice
    - trivy

upload_purging:
  enabled: true
  age: 168h
  interval: 24h
  dryrun: false

cache:
  enabled: false
  expire_hours: 24
```

- **Log files:** You can get them by package the `/var/log/harbor/` .
```
docker run -it --rm -v /:/hostfs goharbor/prepare:v2.7.0 migrate -i /opt/harbor/harbor.yml
migrating to version 2.7.0
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/app/commands/migrate.py", line 43, in migrate
    m.migrate(current_input_path, current_output_path)
  File "/usr/src/app/migrations/version_2_7_0/__init__.py", line 21, in migrate
    f.write(tpl.render(**config_dict))
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/lib/python3.10/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/src/app/migrations/version_2_7_0/harbor.yml.jinja", line 430, in top-level template code
    http_proxy: {{ proxy.http_proxy or ''}}
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'notary_signer'
```

**Comment by zyyw** [comment]
Please refer to this issue:
* https://github.com/goharbor/harbor/issues/18046

Closing it now.
