### ISSUE TITLE
prepare harbor storage_config error

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#18397]
storage_config in harbor.yml
```
storage_service:
  redirect:
    disabled: true
  s3:
    accesskey: xxxxxxx
    secretkey: xxxxxxx
    region: xxxxxxx
    bucket: xxxxxxx
    regionendpoint: xxxxxxx
    secure: xxxxxxx
    v4auth: xxxxxxx
    rootdirectory: xxxxxxx
    chunksize: xxxxxxx
```
`./install.sh --with-notary --with-trivy`
error log
```
[Step 4]: preparing harbor configs ...
prepare base dir is set to /harbor/harbor
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/app/commands/prepare.py", line 35, in prepare
    config_dict = parse_yaml_config(conf, with_notary=with_notary, with_trivy=with_trivy)
  File "/usr/src/app/utils/configs.py", line 213, in parse_yaml_config
    config_dict['storage_redirect_disabled'] = storage_config['redirect']['disable']
KeyError: 'disable'
```
This PR([#14615](https://github.com/goharbor/harbor/pull/14615)) causes this error

**Comment by MinerYang** [comment]
In 2.8 we corrected wording `disabled` to `disable` 
https://docs.docker.com/registry/configuration/#list-of-configuration-options
So if you are installing / upgrade harbor 2.8, please either using the corresponding yaml template file OR by running the script migrate command to get the right file.
https://github.com/goharbor/harbor/blob/deaecf2de544ecf088b8cadfb21f97c45a7f932a/make/harbor.yml.tmpl#L68
https://goharbor.io/docs/2.7.0/administration/upgrade/
```
docker run -it --rm -v /:/hostfs goharbor/prepare:[tag] migrate -i ${path to harbor.yml}
```
