### ISSUE TITLE
Can't use AWS Region us-gov-east-1

### ISSUE THREAD

**Issue by kevinlmadison** [goharbor/harbor#18654]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior** 
I should be able to back up my images in s3.

**Actual behavior:**
```
x k logs -n admin harbor-registry-6d9f84c5b7-tmdhj 
Appending internal tls trust CA to ca-bundle ...
find: '/etc/harbor/ssl': No such file or directory
Internal tls trust CA appending is Done.
time="2023-05-08T15:35:56.140082417Z" level=info msg="debug server listening :8001" 
panic: invalid region provided: us-gov-east-1

goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp({0xf292e8?, 0xc0004b0db0?}, 0xc0003d3800)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:130 +0x23f1
github.com/docker/distribution/registry.NewRegistry({0xf292e8?, 0xc000467fb0?}, 0xc0003d3800)
	/go/src/github.com/docker/distribution/registry/registry.go:161 +0x145
github.com/docker/distribution/registry.glob..func1(0xc000034190?, {0xc0004647e0, 0x1, 0x1})
	/go/src/github.com/docker/distribution/registry/registry.go:119 +0x18f
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x14b3240, {0xc0004647a0?, 0x2?, 0x2?})
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x44f
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x14b33e0)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0xaa
main.main()
	/go/src/github.com/docker/distribution/cmd/registry/main.go:23 +0x25

```

**Steps to reproduce the problem:**
Create necessary components in AWS GovCloud, then install via helm
**Versions:**
Please specify the versions of following systems.
I'm using image tag 2.8.0 for all my images.

**Comment by chlins** [comment]
It seems the region you configured is not supported by the [upstream](https://github.com/distribution/distribution) in current version, you can find out more details from upstream [issue](https://github.com/distribution/distribution/issues/3771).
