### ISSUE TITLE
v2.8.2  prepare 操作，脚本错误 KeyError: 'logger_sweeper_duration' ，请问是什么问题，如何解决？

### ISSUE THREAD

**Issue by xzxiaoshan** [goharbor/harbor#18869]
**Harbor 在部分Linux系统上进行 prepare（版本v2.8.2），出现如下脚本错误，请问是什么问题，如何解决？**

[root@K8s-1 harbor]# ./prepare 
prepare base dir is set to /opt/soft/harbor/harbor
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/app/commands/prepare.py", line 35, in prepare
    config_dict = parse_yaml_config(conf, with_notary=with_notary, with_trivy=with_trivy)
  File "/usr/src/app/utils/configs.py", line 241, in parse_yaml_config
    config_dict['logger_sweeper_duration'] = js_config["logger_sweeper_duration"]
KeyError: 'logger_sweeper_duration'

**Comment by xzxiaoshan** [comment]
自己已经处理好了：原因是 harbor.yml 配置文件没有充分升级，大家如果遇到同类问题可以参考
