### ISSUE TITLE
Harbor Registry Pod ErrorMessage=The account permission has been restricted as account storage usage is over quota.

### ISSUE THREAD

**Issue by sarveswarreddy** [goharbor/harbor#18897]
harbor-registry pod getting to `CrashLoopBackoff` state.

Two different but related error messages from the logs, complains about the storage quota.
Is this the quota on the azure storage account? or project quota? I checked, and confirm that we have not reached the quotas.

Any suggestions how to fix this?

```
registry panic: storage: service returned error: StatusCode=403, ErrorCode=AccountSizeOverQuota, ErrorMessage=The account permission has been restricted as account storage usage is over quota.
```

```
registryctl 2023-07-05T14:06:36Z [ERROR] [/registryctl/config/config.go:63]: failed to load storage driver, err:storage: service returned error: StatusCode=403, ErrorCode=AccountSizeOverQuota, ErrorMessage=The account permission has been restricted as account storage usage is over quota.
```

```
registryctl Appending internal tls trust CA to ca-bundle ...
registryctl Internal tls trust CA /etc/harbor/ssl/registry/ca.crt appended ...
registryctl Internal tls trust CA appending is Done.
registryctl 2023-07-05T14:06:36Z [ERROR] [/registryctl/config/config.go:63]: failed to load storage driver, err:storage: service returned error: StatusCode=403, ErrorCode=AccountSizeOverQuota, ErrorMessage=The account permission has been restricted as account storage usage is over quota.
registryctl RequestId:f8356336-c360-021d-5970-985afa55a28a
registryctl Time:2023-07-05T14:06:36.3821266Z, RequestInitiated=Wed, 05 Jul 2023 14:06:36 GMT, RequestId=f8356336-c360-021d-5970-985afa55a28a, API Version=2018-03-28, QueryParameterName=, QueryParameterValue=
registryctl 2023-07-05T14:06:36Z [FATAL] [/registryctl/main.go:99]: Failed to load configurations with error: storage: service returned error: StatusCode=403, ErrorCode=AccountSizeOverQuota, ErrorMessage=The account permission has been restricted as account storage usage is over quota.
registryctl RequestId:f8356336-c360-021d-5970-985afa55a28a
registryctl Time:2023-07-05T14:06:36.3821266Z, RequestInitiated=Wed, 05 Jul 2023 14:06:36 GMT, RequestId=f8356336-c360-021d-5970-985afa55a28a, API Version=2018-03-28, QueryParameterName=, QueryParameterValue=
Stream closed EOF for harbor/harbor-registry-6556c7bbdb-8jn29 (registryctl)
registry Appending internal tls trust CA to ca-bundle ...
registry Internal tls trust CA /etc/harbor/ssl/registry/ca.crt appended ...
registry Internal tls trust CA appending is Done.
registry time="2023-07-05T14:06:36.121556193Z" level=info msg="debug server listening localhost:5001" 
registry panic: storage: service returned error: StatusCode=403, ErrorCode=AccountSizeOverQuota, ErrorMessage=The account permission has been restricted as account storage usage is over quota.
registry RequestId:daebfd75-d4ed-0746-78f5-0d8a7cb8fff4
registry Time:2023-07-05T14:06:36.1949672Z, RequestInitiated=Wed, 05 Jul 2023 14:06:35 GMT, RequestId=daebfd75-d4ed-0746-78f5-0d8a7cb8fff4, API Version=2016-05-31, QueryParameterName=, QueryParameterValue=
registry 
registry goroutine 1 [running]:
registry github.com/docker/distribution/registry/handlers.NewApp({0xead700, 0xc0003b20c0}, 0xc000371180)
registry     /go/src/github.com/docker/distribution/registry/handlers/app.go:129 +0x2269
registry github.com/docker/distribution/registry.NewRegistry({0xead700, 0xc0000cb6e0}, 0xc000371180)
registry     /go/src/github.com/docker/distribution/registry/registry.go:105 +0x145
registry github.com/docker/distribution/registry.glob..func1(0xc00025fed8, {0xc00009ca10, 0x1, 0x1})
registry     /go/src/github.com/docker/distribution/registry/registry.go:63 +0x194
registry github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x1478100, {0xc00009c9d0, 0x60, 0x2})
registry     /go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x3db
registry github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x14782a0)
registry     /go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0xaa
registry main.main()
registry     /go/src/github.com/docker/distribution/cmd/registry/main.go:23 +0x25
Stream closed EOF for harbor/harbor-registry-6556c7bbdb-8jn29 (registry)
```

**Comment by MinerYang** [comment]
How do you install harbor?(docker compose or harbor-helm)
It is probably a quota issue from your azure storage account, please kindly take a check

**Comment by sarveswarreddy** [comment]
It was indeed a quota issue on azure storage account!
