### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/hostfs/data/cert/harbor.example.com.key' in macOS Catalina

### ISSUE THREAD

**Issue by bennyzx** [goharbor/harbor#18964]
Hi guys, same errors occurred in my macOS Catalina. 
I tried several ways above, but it doesn't still work for me.

Error message, as follows: 

➜  harbor ./prepare  
prepare base dir is set to /Users/zhouxuan/harbor
Clearing the configuration file: /config/log/logrotate.conf
Clearing the configuration file: /config/log/rsyslog_docker.conf
Clearing the configuration file: /config/portal/nginx.conf
Generated configuration file: /config/portal/nginx.conf
Generated configuration file: /config/log/logrotate.conf
Generated configuration file: /config/log/rsyslog_docker.conf
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/app/commands/prepare.py", line 45, in prepare
    prepare_nginx(config_dict)
  File "/usr/src/app/utils/nginx.py", line 23, in prepare_nginx
    render_nginx_template(config_dict)
  File "/usr/src/app/utils/nginx.py", line 56, in render_nginx_template
    prepare_nginx_certs(config_dict['cert_key_path'], config_dict['cert_path'])
  File "/usr/src/app/utils/nginx.py", line 42, in prepare_nginx_certs
    shutil.copy2(host_ngx_cert_key_path, real_key_path)
  File "/usr/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/hostfs/data/cert/harbor.example.com.key'

Can anybody help me out?

**Comment by bennyzx** [comment]
/data/cert is in root directory of my macOS Catalina

file: prepare, modified place:
# Run prepare script
docker run --rm -v $input_dir:/input \
                    -v $data_path:/data \
                    -v $harbor_prepare_path:/compose_location \
                    -v $config_dir:/config \
                    -v /data/cert:/hostfs:z \
                    --privileged \
                    goharbor/prepare:v2.8.2 prepare $@

file: harbor.yml, modified place:
# https related config
https:
  # https port for harbor, default is 443
  port: 9443
  # The path of cert and key files for nginx
  certificate: /data/cert/harbor.example.com.crt
  private_key: /data/cert/harbor.example.com.key

**Comment by bennyzx** [comment]
A quick around is to modify shell script file, prepare,
added: cert_dir=/a/b/data/cert
modified: -v $cert_dir:/hostfs
