### ISSUE TITLE
Installation script aborts - many error messages by run install.sh script and prepare script

### ISSUE THREAD

**Issue by tbartschat** [goharbor/harbor#19108]
Hi all, 

I focused an issue during my harbor offline installation.

OS: 22.04.3 LTS (Jammy Jellyfish)
Harbor Version: 2.8.3
Docker Version: 24.0.5
Docker Compose Version: v2.20.2

Attached you can find my harbor.yml configuration file.

Pleas can someone help me out to solve this issue ? 

I'm getting an error messages during execution of install.sh script, same error occurs by using prepare script. 

[Step 4]: preparing harbor configs ...
prepare base dir is set to /etc/harbor
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/app/commands/prepare.py", line 35, in prepare
    config_dict = parse_yaml_config(conf, with_notary=with_notary, with_trivy=with_trivy)
  File "/usr/src/app/utils/configs.py", line 107, in parse_yaml_config
    configs = yaml.safe_load(f)
  File "/usr/lib/python3.10/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3.10/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3.10/site-packages/yaml/composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "/usr/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3.10/site-packages/yaml/parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "/usr/lib/python3.10/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/lib/python3.10/site-packages/yaml/scanner.py", line 235, in fetch_more_tokens
    return self.fetch_tag()
  File "/usr/lib/python3.10/site-packages/yaml/scanner.py", line 632, in fetch_tag
    self.tokens.append(self.scan_tag())
  File "/usr/lib/python3.10/site-packages/yaml/scanner.py", line 963, in scan_tag
    handle = self.scan_tag_handle('tag', start_mark)
  File "/usr/lib/python3.10/site-packages/yaml/scanner.py", line 1365, in scan_tag_handle
    raise ScannerError("while scanning a %s" % name, start_mark,
yaml.scanner.ScannerError: while scanning a tag
  in "/input/harbor.yml", line 34, column 24
expected '!', but found '@'
  in "/input/harbor.yml", line 34, column 25

[harbor.txt](https://github.com/goharbor/harbor/files/12267758/harbor.txt)

**Comment by tbartschat** [comment]
I solved it ... the issue was the password in the harbor.yml it was starting with a !, looks like it is not valid. After changing password to an other one starting with a character, installation script finished successfully.
