### ISSUE TITLE
harbor prepare v2.9.0 error

### ISSUE THREAD

**Issue by Zheer09** [goharbor/harbor#19520]
How can we help you?
When i try to run prepare for v2.9.0 i get this issue 

Versions:

Python 3.8.10
docker engine 24.0.6
Docker Compose version v2.21.0

```
prepare base dir is set to /etc/harbor
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 15, in <module>
    cli()
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/commands/prepare.py", line 33, in prepare
    config_dict = parse_yaml_config(conf, with_trivy=with_trivy)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/utils/configs.py", line 224, in parse_yaml_config
    config_dict['job_loggers'] = js_config["job_loggers"]
                                 ~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'job_loggers'
```

**Comment by chlins** [comment]
It should be same with https://github.com/goharbor/harbor/issues/19316.
