### ISSUE TITLE
Large Garbage Collections Slow and Can Easily Fail Indefinitely

### ISSUE THREAD

**Issue by isugimpy** [goharbor/harbor#19991]
Apologies for making this a general Issue type, but this isn't exactly a bug, and it isn't exactly a proposal for a feature either.

On very large and high churn Harbor instances, garbage collection can become very slow or reach a point of indefinite failure due to OOM, requiring human intervention.  This intervention may be in the form of adjusting resources, or purging resources from the backing datastore.  Additionally, garbage collection cycles are all-or-nothing, requiring a full pass of marking before any deletion occurs.

Incremental garbage collection which purges chunks at a time rather than needing to do the full mark cycle every time would likely be a decent solution here, but may not be in line with goals of the project.  There are various ways this could be implemented, but I would lean toward a concurrent mark/sweep approach as that'd be the closest to the current implementation.  The run step could begin the mark in a goroutine, pushing chunked results back on a channel, and those chunks could be fed to a number of workers to execute deletion in near-realtime, allowing deletions to occur without collecting the full data.  This would be beneficial from a speed perspective, but also would act as a mechanism to allow for an incomplete GC to be retried with a smaller total dataset, eventually getting fully caught up.

I'm not sure if the maintainers have something else in mind, or if I'm the only one dealing with the level of scale here, but this has been a real pain point that I'd love to see a solution to.

**Comment by isugimpy** [comment]
The instance that spawned this has ~150k artifacts right now across 648 repositories in one project.  Backing datastore is AWS S3, metadata is in AWS Aurora Postgres and AWS Elasticache Redis.

**Comment by wy65701436** [comment]
Have you tried performing multiple deletions, such as setting the number of workers to 5?
BTW, what version of harbor are you using?

**Comment by isugimpy** [comment]
Apologies, I didn't see the reply here until just now.  This is on 2.8.4.  I could likely see about updating us to 2.9.0+ to get the GC changes there, but looking at the code it's not clear if it'd solve the issue we're having.

Can you clarify what you mean about performing multiple deletions?  Our jobservice pods run 10 workers each, but exactly one garbage collection task is running at any given time.  

Since I last posted, we actually let a garbage collection task run for 18 days, only to find the following error happened about an hour ago, leaving us with nothing deleted from the bucket.  We've got ~10TB of data in our actual registry, and ~75TB in the bucket, due to the GC failures just compounding over time.

```
ERROR [/jobservice/runner/redis.go:167]: Run job GARBAGE_COLLECTION:c4bc6b26560c68ef94b423e0 error: runtime error: interface conversion: interface {} is nil, not []uint8; stack: goroutine 74 [running]:
github.com/goharbor/harbor/src/jobservice/runner.(*RedisJob).Run.func2()
	/harbor/src/jobservice/runner/redis.go:165 +0x7b
panic({0x14c0320, 0xc045059710})
	/usr/local/go/src/runtime/panic.go:890 +0x263
github.com/goharbor/harbor/src/jobservice/job.getStatus({0x1933138?, 0xc04517c318?}, {0xc0450cab40?, 0x18?})
	/harbor/src/jobservice/job/tracker.go:619 +0x194
github.com/goharbor/harbor/src/jobservice/job.(*basicTracker).Status(0xc03691c3c0)
	/harbor/src/jobservice/job/tracker.go:193 +0xcf
github.com/goharbor/harbor/src/jobservice/job/impl.(*Context).OPCommand(0xc038b2e3d0?)
	/harbor/src/jobservice/job/impl/context.go:165 +0x26
github.com/goharbor/harbor/src/jobservice/job/impl/gc.(*GarbageCollector).shouldStop(0xc04d648fa0?, {0x1934e90?, 0xc038a4ec80?})
	/harbor/src/jobservice/job/impl/gc/garbage_collection.go:644 +0x27
github.com/goharbor/harbor/src/jobservice/job/impl/gc.(*GarbageCollector).mark(0xc045164f30, {0x1934e90, 0xc038a4ec80})
	/harbor/src/jobservice/job/impl/gc/garbage_collection.go:224 +0x41e
github.com/goharbor/harbor/src/jobservice/job/impl/gc.(*GarbageCollector).Run(0xc045164f30, {0x1934e90, 0xc038a4ec80}, 0x3?)
	/harbor/src/jobservice/job/impl/gc/garbage_collection.go:156 +0x70
github.com/goharbor/harbor/src/jobservice/runner.(*RedisJob).Run(0xc0008e6e10, 0xc00b5d6600)
	/harbor/src/jobservice/runner/redis.go:231 +0x11d8
github.com/goharbor/harbor/src/jobservice/worker/cworker.(*basicWorker).registerJob.func2(0x23ddda0?)
	/harbor/src/jobservice/worker/cworker/c_worker.go:439 +0x25
github.com/gocraft/work.runJob.func1()
	/harbor/src/vendor/github.com/gocraft/work/run.go:31 +0x3f0
github.com/goharbor/harbor/src/jobservice/worker/cworker.(*workerContext).logJob(0x2?, 0xc00b5d6600, 0xc03691c370)
	/harbor/src/jobservice/worker/cworker/c_worker.go:79 +0x136
reflect.Value.call({0x1489320?, 0x1743370?, 0xc00b5d6600?}, {0x169544e, 0x4}, {0xc05b611d48, 0x3, 0x461ea5?})
	/usr/local/go/src/reflect/value.go:586 +0xb0b
reflect.Value.Call({0x1489320?, 0x1743370?, 0xc05b611cd8?}, {0xc05b611d48?, 0x16?, 0x12a8e0?})
	/usr/local/go/src/reflect/value.go:370 +0xbc
github.com/gocraft/work.runJob.func1()
	/harbor/src/vendor/github.com/gocraft/work/run.go:23 +0x215
github.com/gocraft/work.runJob(0xc00b5d6600, {0x1945ac8, 0x14ab100}, {0xc000014270, 0x1, 0x1}, 0xc000528240)
	/harbor/src/vendor/github.com/gocraft/work/run.go:51 +0x22b
github.com/gocraft/work.(*worker).processJob(0xc000792900, 0xc00b5d6600)
	/harbor/src/vendor/github.com/gocraft/work/worker.go:198 +0x20c
github.com/gocraft/work.(*worker).loop(0xc000792900)
	/harbor/src/vendor/github.com/gocraft/work/worker.go:119 +0x1cd
created by github.com/gocraft/work.(*worker).start
	/harbor/src/vendor/github.com/gocraft/work/worker.go:78 +0x5a
ERROR [/jobservice/runner/redis.go:123]: Job 'GARBAGE_COLLECTION:c4bc6b26560c68ef94b423e0' exit with error: runtime error: interface conversion: interface {} is nil, not []uint8; stack: goroutine 74 [running]:
github.com/goharbor/harbor/src/jobservice/runner.(*RedisJob).Run.func2()
	/harbor/src/jobservice/runner/redis.go:165 +0x7b
panic({0x14c0320, 0xc045059710})
	/usr/local/go/src/runtime/panic.go:890 +0x263
github.com/goharbor/harbor/src/jobservice/job.getStatus({0x1933138?, 0xc04517c318?}, {0xc0450cab40?, 0x18?})
	/harbor/src/jobservice/job/tracker.go:619 +0x194
github.com/goharbor/harbor/src/jobservice/job.(*basicTracker).Status(0xc03691c3c0)
	/harbor/src/jobservice/job/tracker.go:193 +0xcf
github.com/goharbor/harbor/src/jobservice/job/impl.(*Context).OPCommand(0xc038b2e3d0?)
	/harbor/src/jobservice/job/impl/context.go:165 +0x26
github.com/goharbor/harbor/src/jobservice/job/impl/gc.(*GarbageCollector).shouldStop(0xc04d648fa0?, {0x1934e90?, 0xc038a4ec80?})
	/harbor/src/jobservice/job/impl/gc/garbage_collection.go:644 +0x27
github.com/goharbor/harbor/src/jobservice/job/impl/gc.(*GarbageCollector).mark(0xc045164f30, {0x1934e90, 0xc038a4ec80})
	/harbor/src/jobservice/job/impl/gc/garbage_collection.go:224 +0x41e
github.com/goharbor/harbor/src/jobservice/job/impl/gc.(*GarbageCollector).Run(0xc045164f30, {0x1934e90, 0xc038a4ec80}, 0x3?)
	/harbor/src/jobservice/job/impl/gc/garbage_collection.go:156 +0x70
github.com/goharbor/harbor/src/jobservice/runner.(*RedisJob).Run(0xc0008e6e10, 0xc00b5d6600)
	/harbor/src/jobservice/runner/redis.go:231 +0x11d8
github.com/goharbor/harbor/src/jobservice/worker/cworker.(*basicWorker).registerJob.func2(0x23ddda0?)
	/harbor/src/jobservice/worker/cworker/c_worker.go:439 +0x25
github.com/gocraft/work.runJob.func1()
	/harbor/src/vendor/github.com/gocraft/work/run.go:31 +0x3f0
github.com/goharbor/harbor/src/jobservice/worker/cworker.(*workerContext).logJob(0x2?, 0xc00b5d6600, 0xc03691c370)
	/harbor/src/jobservice/worker/cworker/c_worker.go:79 +0x136
reflect.Value.call({0x1489320?, 0x1743370?, 0xc00b5d6600?}, {0x169544e, 0x4}, {0xc05b611d48, 0x3, 0x461ea5?})
	/usr/local/go/src/reflect/value.go:586 +0xb0b
reflect.Value.Call({0x1489320?, 0x1743370?, 0xc05b611cd8?}, {0xc05b611d48?, 0x16?, 0x12a8e0?})
	/usr/local/go/src/reflect/value.go:370 +0xbc
github.com/gocraft/work.runJob.func1()
	/harbor/src/vendor/github.com/gocraft/work/run.go:23 +0x215
github.com/gocraft/work.runJob(0xc00b5d6600, {0x1945ac8, 0x14ab100}, {0xc000014270, 0x1, 0x1}, 0xc000528240)
	/harbor/src/vendor/github.com/gocraft/work/run.go:51 +0x22b
github.com/gocraft/work.(*worker).processJob(0xc000792900, 0xc00b5d6600)
	/harbor/src/vendor/github.com/gocraft/work/worker.go:198 +0x20c
github.com/gocraft/work.(*worker).loop(0xc000792900)
	/harbor/src/vendor/github.com/gocraft/work/worker.go:119 +0x1cd
created by github.com/gocraft/work.(*worker).start
	/harbor/src/vendor/github.com/gocraft/work/worker.go:78 +0x5a 
```

**Comment by jwojnarowicz** [comment]
@isugimpy 
We also have problems regarding the use of S3 backend (MinIO in our case). The GC runs very slow even though it stresses Minio's CPUs.
Running 2.10 on Kubernetes so I guess it is still not resolved.

**Comment by isugimpy** [comment]
@stonezdj @wy65701436 Any further thoughts on this?  It's been quite a while with no response and this is still an issue.  Willing to try upgrading to resolve this, but given that our GC runs never make it past the mark stage to actually begin deleting, it doesn't look like an increase in worker counts will actually do anything.  I'd love to find out I'm wrong here, of course, but I'm not seeing any way that the additional workers could help.

Would this project be open to a change to move the mark to be concurrent with sweeping?  I'm sure there are other alternative approaches which could work as well, but that seems like the least intrusive way to deal with this.

**Comment by xianlubird** [comment]
Is there any other way to clean it manually first? We have the same problem now.

**Comment by AllenXu93** [comment]
Same problem in v2.6.0.

**Comment by wy65701436** [comment]
@isugimpy can you show me the output of those keys?

```
hmget {harbor_job_service_namespace}:job_stats:{gc_job_id} status
ttl {harbor_job_service_namespace}:job_stats:{gc_job_id}
```

**Comment by AllenXu93** [comment]
> @isugimpy can you show me the output of those keys?
> 
> ```
> hmget {harbor_job_service_namespace}:job_stats:{gc_job_id} status
> ttl {harbor_job_service_namespace}:job_stats:{gc_job_id}
> ```

In my harbor cluster met the same issue. 

```
hmget {harbor_job_service_namespace}:job_stats:1265a0cfa09fe700cc4a8c71 status
1) "Running"
ttl {harbor_job_service_namespace}:job_stats:1265a0cfa09fe700cc4a8c71
(integer) -1
```

**Comment by AllenXu93** [comment]
> > @isugimpy can you show me the output of those keys?
> > ```
> > hmget {harbor_job_service_namespace}:job_stats:{gc_job_id} status
> > ttl {harbor_job_service_namespace}:job_stats:{gc_job_id}
> > ```
> 
> In my harbor cluster met the same issue.
> 
> ```
> hmget {harbor_job_service_namespace}:job_stats:1265a0cfa09fe700cc4a8c71 status
> 1) "Running"
> ttl {harbor_job_service_namespace}:job_stats:1265a0cfa09fe700cc4a8c71
> (integer) -1
> ```

For now, GC task in redis markd Error and `job_stats` key has a ttl; But in jobserver,  gc task is still running.

> hmget {harbor_job_service_namespace}:job_stats:1265a0cfa09fe700cc4a8c71 status
1) "Error"
> ttl  {harbor_job_service_namespace}:job_stats:1265a0cfa09fe700cc4a8c71
(integer) 594374

**Comment by AllenXu93** [comment]
I think I found the reason.
In my case, 

JobServer will mark job failed after it runs longer than 1 day (by default):

https://github.com/goharbor/harbor/blob/main/src/jobservice/worker/cworker/reaper.go#L182

And then it will mark the job_stats redis val ttl for 1 day.

https://github.com/goharbor/harbor/blob/main/src/jobservice/worker/cworker/reaper.go#L173-L182

So after the job runs for 2 day, the redis val for job stats is expire, then the job will panic because it got nil in :

https://github.com/goharbor/harbor/blob/main/src/jobservice/job/tracker.go#L618-L622

**Comment by jcambronero** [comment]
@AllenXu93 this is a great finding. We're running into this same issue.
I was wondering if as a workaround we could connect to redis and manually extend the key's TTL to prevent this issue, e.g.

```
expire {harbor_job_service_namespace}:job_stats:1265a0cfa09fe700cc4a8c71 999999999
```

However, we're not sure if his could cause other unintended consequences.
Any thoughts on this?

**Comment by AllenXu93** [comment]
> @AllenXu93 this is a great finding. We're running into this same issue. I was wondering if as a workaround we could connect to redis and manually extend the key's TTL to prevent this issue, e.g.
> 
> ```
> expire {harbor_job_service_namespace}:job_stats:1265a0cfa09fe700cc4a8c71 999999999
> ```
> 
> However, we're not sure if his could cause other unintended consequences. Any thoughts on this?

I'm not sure, I think it won't cause other negative impact.
For me , I changed the MaxUpdateDuration, and it work fine.

**Comment by liukch** [comment]
Same issue, I have 1.3TB artifacts waiting for gc in S3 MinIO.
Harbor after run GC job, remark 263K total delete count.
According to `jobservice` logs, every 3mins do one delete for a worker, delete all of them, I need half one year!!!
I don't know how to **speed up the GC progress**, I have CPU and memory resources, but no half of one year time.
Why it is **3mins** do one delete? Where to determine this value? I could not find it.
My version is v2.5.5

some logs here, you can see every 3mins do one delete and the total count:
``` log
harbor-jobservice  | 2024-12-06T02:38:36Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:317]: [8714/263290] delete blob from storage: sha256:dddf1ac728f06bddadcbaf459d68217c3deaad4911c98cc11f5b9c0ee905a240
harbor-jobservice  | 2024-12-06T02:38:37Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:337]: [8714/263290] delete blob record from database: 333996, sha256:dddf1ac728f06bddadcbaf459d68217c3deaad4911c98cc11f5b9c0ee905a240
harbor-jobservice  | 2024-12-06T02:38:37Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:266]: [8715/263290] delete the manifest with registry v2 API: foo/bar, application/vnd.docker.distribution.manifest.list.v2+json, sha256:cc6b72273a914d5296b62be1b2733fe07d2092f06cc5891cce3b29358826ede1
harbor-jobservice  | 2024-12-06T02:41:37Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:280]: [8715/263290] delete manifest from storage: sha256:cc6b72273a914d5296b62be1b2733fe07d2092f06cc5891cce3b29358826ede1
harbor-jobservice  | 2024-12-06T02:41:38Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:299]: [8715/263290] delete artifact trash record from database: 265833, foo/bar, sha256:cc6b72273a914d5296b62be1b2733fe07d2092f06cc5891cce3b29358826ede1
harbor-jobservice  | 2024-12-06T02:41:38Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:317]: [8715/263290] delete blob from storage: sha256:cc6b72273a914d5296b62be1b2733fe07d2092f06cc5891cce3b29358826ede1
harbor-jobservice  | 2024-12-06T02:41:38Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:337]: [8715/263290] delete blob record from database: 333999, sha256:cc6b72273a914d5296b62be1b2733fe07d2092f06cc5891cce3b29358826ede1
harbor-jobservice  | 2024-12-06T02:41:38Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:266]: [8716/263290] delete the manifest with registry v2 API: foo/brz, application/vnd.docker.distribution.manifest.v2+json, sha256:725b1513dbf098f4c322562f0d911d9d8888f323c076f2125199bcce8fd77df5
harbor-jobservice  | 2024-12-06T02:44:39Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:280]: [8716/263290] delete manifest from storage: sha256:725b1513dbf098f4c322562f0d911d9d8888f323c076f2125199bcce8fd77df5
harbor-jobservice  | 2024-12-06T02:44:39Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:299]: [8716/263290] delete artifact trash record from database: 264266, foo/brz, sha256:725b1513dbf098f4c322562f0d911d9d8888f323c076f2125199bcce8fd77df5
harbor-jobservice  | 2024-12-06T02:44:39Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:317]: [8716/263290] delete blob from storage: sha256:725b1513dbf098f4c322562f0d911d9d8888f323c076f2125199bcce8fd77df5
harbor-jobservice  | 2024-12-06T02:44:39Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:337]: [8716/263290] delete blob record from database: 334007, sha256:725b1513dbf098f4c322562f0d911d9d8888f323c076f2125199bcce8fd77df5
harbor-jobservice  | 2024-12-06T02:44:39Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:266]: [8717/263290] delete the manifest with registry v2 API: foo/bar, application/vnd.docker.distribution.manifest.v2+json, sha256:f7d33bcf4fb17e5e5157eacb48726debe480e871d4c3cb6fffcfeb559223a12a
harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:280]: [8717/263290] delete manifest from storage: sha256:f7d33bcf4fb17e5e5157eacb48726debe480e871d4c3cb6fffcfeb559223a12a
harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:299]: [8717/263290] delete artifact trash record from database: 265376, foo/bar, sha256:f7d33bcf4fb17e5e5157eacb48726debe480e871d4c3cb6fffcfeb559223a12a
harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:317]: [8717/263290] delete blob from storage: sha256:f7d33bcf4fb17e5e5157eacb48726debe480e871d4c3cb6fffcfeb559223a12a
harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:337]: [8717/263290] delete blob record from database: 349671, sha256:f7d33bcf4fb17e5e5157eacb48726debe480e871d4c3cb6fffcfeb559223a12a
harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:317]: [8718/263290] delete blob from storage: sha256:9a3cb54a8afe7faac60cc6f0ddb0bae9144233a3d99b5d36f188dd0fda7368fd
harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:337]: [8718/263290] delete blob record from database: 349667, sha256:9a3cb54a8afe7faac60cc6f0ddb0bae9144233a3d99b5d36f188dd0fda7368fd
harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:317]: [8719/263290] delete blob from storage: sha256:c84c3b5faad1d78addef7651c15fbb2c74abf914e104daad48a0d7c0daa383dd
harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:337]: [8719/263290] delete blob record from database: 349666, sha256:c84c3b5faad1d78addef7651c15fbb2c74abf914e104daad48a0d7c0daa383dd
harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:317]: [8720/263290] delete blob from storage: sha256:33edaa58d5505f5a771763fb8e8c068d69515893fce4064b11010785d08c44d2
harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:337]: [8720/263290] delete blob record from database: 349665, sha256:33edaa58d5505f5a771763fb8e8c068d69515893fce4064b11010785d08c44d2
harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:317]: [8721/263290] delete blob from storage: sha256:70632908c70b701383179179f19d64e60750b03ad34df37a0ba834e29c60b6d0
harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:337]: [8721/263290] delete blob record from database: 349668, sha256:70632908c70b701383179179f19d64e60750b03ad34df37a0ba834e29c60b6d0
harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:317]: [8722/263290] delete blob from storage: sha256:23665b9645ee54bdb130a729a4b12e2ca6ef157096a461dea2bc865408df64be
harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:337]: [8722/263290] delete blob record from database: 349669, sha256:23665b9645ee54bdb130a729a4b12e2ca6ef157096a461dea2bc865408df64be
harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:266]: [8723/263290] delete the manifest with registry v2 API: foo/bar, application/vnd.docker.distribution.manifest.list.v2+json, sha256:0920e2390c20ef73e3ebf093731c9700b7d8e93bbfe368ed62a72aa582d84d8f
```

**Comment by AllenXu93** [comment]
> Same issue, I have 1.3TB artifacts waiting for gc in S3 MinIO. Harbor after run GC job, remark 263K total delete count. According to `jobservice` logs, every 3mins do one delete for a worker, delete all of them, I need half one year!!! I don't know how to **speed up the GC progress**, I have CPU and memory resources, but no half of one year time. Why it is **3mins** do one delete? Where to determine this value? I could not find it. My version is v2.5.5
> 
> some logs here, you can see every 3mins do one delete and the total count:
> 
> ```
> harbor-jobservice  | 2024-12-06T02:38:36Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:317]: [8714/263290] delete blob from storage: sha256:dddf1ac728f06bddadcbaf459d68217c3deaad4911c98cc11f5b9c0ee905a240
> harbor-jobservice  | 2024-12-06T02:38:37Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:337]: [8714/263290] delete blob record from database: 333996, sha256:dddf1ac728f06bddadcbaf459d68217c3deaad4911c98cc11f5b9c0ee905a240
> harbor-jobservice  | 2024-12-06T02:38:37Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:266]: [8715/263290] delete the manifest with registry v2 API: foo/bar, application/vnd.docker.distribution.manifest.list.v2+json, sha256:cc6b72273a914d5296b62be1b2733fe07d2092f06cc5891cce3b29358826ede1
> harbor-jobservice  | 2024-12-06T02:41:37Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:280]: [8715/263290] delete manifest from storage: sha256:cc6b72273a914d5296b62be1b2733fe07d2092f06cc5891cce3b29358826ede1
> harbor-jobservice  | 2024-12-06T02:41:38Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:299]: [8715/263290] delete artifact trash record from database: 265833, foo/bar, sha256:cc6b72273a914d5296b62be1b2733fe07d2092f06cc5891cce3b29358826ede1
> harbor-jobservice  | 2024-12-06T02:41:38Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:317]: [8715/263290] delete blob from storage: sha256:cc6b72273a914d5296b62be1b2733fe07d2092f06cc5891cce3b29358826ede1
> harbor-jobservice  | 2024-12-06T02:41:38Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:337]: [8715/263290] delete blob record from database: 333999, sha256:cc6b72273a914d5296b62be1b2733fe07d2092f06cc5891cce3b29358826ede1
> harbor-jobservice  | 2024-12-06T02:41:38Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:266]: [8716/263290] delete the manifest with registry v2 API: foo/brz, application/vnd.docker.distribution.manifest.v2+json, sha256:725b1513dbf098f4c322562f0d911d9d8888f323c076f2125199bcce8fd77df5
> harbor-jobservice  | 2024-12-06T02:44:39Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:280]: [8716/263290] delete manifest from storage: sha256:725b1513dbf098f4c322562f0d911d9d8888f323c076f2125199bcce8fd77df5
> harbor-jobservice  | 2024-12-06T02:44:39Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:299]: [8716/263290] delete artifact trash record from database: 264266, foo/brz, sha256:725b1513dbf098f4c322562f0d911d9d8888f323c076f2125199bcce8fd77df5
> harbor-jobservice  | 2024-12-06T02:44:39Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:317]: [8716/263290] delete blob from storage: sha256:725b1513dbf098f4c322562f0d911d9d8888f323c076f2125199bcce8fd77df5
> harbor-jobservice  | 2024-12-06T02:44:39Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:337]: [8716/263290] delete blob record from database: 334007, sha256:725b1513dbf098f4c322562f0d911d9d8888f323c076f2125199bcce8fd77df5
> harbor-jobservice  | 2024-12-06T02:44:39Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:266]: [8717/263290] delete the manifest with registry v2 API: foo/bar, application/vnd.docker.distribution.manifest.v2+json, sha256:f7d33bcf4fb17e5e5157eacb48726debe480e871d4c3cb6fffcfeb559223a12a
> harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:280]: [8717/263290] delete manifest from storage: sha256:f7d33bcf4fb17e5e5157eacb48726debe480e871d4c3cb6fffcfeb559223a12a
> harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:299]: [8717/263290] delete artifact trash record from database: 265376, foo/bar, sha256:f7d33bcf4fb17e5e5157eacb48726debe480e871d4c3cb6fffcfeb559223a12a
> harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:317]: [8717/263290] delete blob from storage: sha256:f7d33bcf4fb17e5e5157eacb48726debe480e871d4c3cb6fffcfeb559223a12a
> harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:337]: [8717/263290] delete blob record from database: 349671, sha256:f7d33bcf4fb17e5e5157eacb48726debe480e871d4c3cb6fffcfeb559223a12a
> harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:317]: [8718/263290] delete blob from storage: sha256:9a3cb54a8afe7faac60cc6f0ddb0bae9144233a3d99b5d36f188dd0fda7368fd
> harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:337]: [8718/263290] delete blob record from database: 349667, sha256:9a3cb54a8afe7faac60cc6f0ddb0bae9144233a3d99b5d36f188dd0fda7368fd
> harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:317]: [8719/263290] delete blob from storage: sha256:c84c3b5faad1d78addef7651c15fbb2c74abf914e104daad48a0d7c0daa383dd
> harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:337]: [8719/263290] delete blob record from database: 349666, sha256:c84c3b5faad1d78addef7651c15fbb2c74abf914e104daad48a0d7c0daa383dd
> harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:317]: [8720/263290] delete blob from storage: sha256:33edaa58d5505f5a771763fb8e8c068d69515893fce4064b11010785d08c44d2
> harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:337]: [8720/263290] delete blob record from database: 349665, sha256:33edaa58d5505f5a771763fb8e8c068d69515893fce4064b11010785d08c44d2
> harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:317]: [8721/263290] delete blob from storage: sha256:70632908c70b701383179179f19d64e60750b03ad34df37a0ba834e29c60b6d0
> harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:337]: [8721/263290] delete blob record from database: 349668, sha256:70632908c70b701383179179f19d64e60750b03ad34df37a0ba834e29c60b6d0
> harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:317]: [8722/263290] delete blob from storage: sha256:23665b9645ee54bdb130a729a4b12e2ca6ef157096a461dea2bc865408df64be
> harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:337]: [8722/263290] delete blob record from database: 349669, sha256:23665b9645ee54bdb130a729a4b12e2ca6ef157096a461dea2bc865408df64be
> harbor-jobservice  | 2024-12-06T02:47:42Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:266]: [8723/263290] delete the manifest with registry v2 API: foo/bar, application/vnd.docker.distribution.manifest.list.v2+json, sha256:0920e2390c20ef73e3ebf093731c9700b7d8e93bbfe368ed62a72aa582d84d8f
> ```

Same problem. 
I have 400Ti data, 150Ti to gc in my harbor cluster, the GC will run 3-4 mouth. I modify gc code to make it run in parallel , like https://github.com/goharbor/harbor/pull/16211 , gc finish in 2 week.

**Comment by lalit5082** [comment]
We are running Harbor v2.13.2 with a local disk backend and are planning to run a garbage collection on approximately 31,800 blobs / 5,164 manifests (~344 GiB).

Before proceeding, I want to confirm:

  1. Is this issue still present in v2.13.2, or has it been resolved?
  2. Are there any recommended workarounds or configurations to prevent GC from failing/hanging at this scale?
  3. Is there a known safe way to resume a failed GC run, or does it need to be restarted from scratch?
  4. Based on our scale (~31,800 blobs, 344 GiB, local disk backend), is there a rough estimate of how long GC should take to complete successfully?
Any guidance from the team or community on running large GC jobs reliably would be appreciated. Thanks!
