### ISSUE TITLE
jobservice fails immediately when core is not available 

### ISSUE THREAD

**Issue by kavyavvv** [goharbor/harbor#20053]
om url: https://core:8443/api/v2.0/internalconfig
2024-02-27T16:16:45.107176010+05:30 stdout F 2024-02-27T10:46:45Z [ERROR] [/pkg/config/rest/rest.go:50]: Failed on load rest config err:Get "https://core:8443/api/v2.0/internalconfig": dial tcp xx.xx.0.32:8443: connect: connection refused, url:https://core:8443/api/v2.0/internalconfig
2024-02-27T16:16:45.109314037+05:30 stderr F panic: failed to load configuration, error: failed to load rest config
2024-02-27T16:16:45.109314037+05:30 stderr F
2024-02-27T16:16:45.109314037+05:30 stderr F goroutine 1 [running]:
2024-02-27T16:16:45.109314037+05:30 stderr F main.main()
2024-02-27T16:16:45.109314037+05:30 stderr P    /harbor/src/jobservice/main.go:44 +
2024-02-27T16:16:45.109325624+05:30 stderr F 0x3ae
2024-02-27T16:47:26.590776314+05

what could be the reason for this failure ?

what is is the dependency of these containers with each other ?

**Comment by MinerYang** [comment]
Please provide your harbor-core, harbor-db, harbor-redis logs

**Comment by microyahoo** [comment]
hi @kavyavvv, as log shows, jobservice will load internal config from core via [http request](https://github.com/goharbor/harbor/blob/69fc957d7e8745474169f9a2df78d869be8d4650/src/pkg/config/rest/rest.go#L48), which will panic if some error met.

**Comment by kavyavvv** [comment]
> hi @kavyavvv, as log shows, jobservice will load internal config from core via [http request](https://github.com/goharbor/harbor/blob/69fc957d7e8745474169f9a2df78d869be8d4650/src/pkg/config/rest/rest.go#L48), which will panic if some error met.

yes but the core was not completely up by that time , so the job service fails immediately without even waiting for some time
