### ISSUE TITLE
harbor stops working core and jobservice pod are crashloopbackoff and error out

### ISSUE THREAD

**Issue by rajatrj16** [goharbor/harbor#20823]
Hi, I have suddenly got harbor stops working core and jobservice pod are crashloopbackoff and error out.

**Core**: I'm getting error for not be able to connect to redis but its up and running.
```
core 2024-08-08T06:01:05Z [ERROR] [/lib/cache/cache.go:124]: failed to ping redis://master.production.exxxxq.cache.amazonaws.com:6379/0?idle_timeout_seconds=30, retry after 10s : read tcp 100.xx.xx.115:46178->10.xx.xx.198:6379: i/o timeout
core 2024-08-08T06:01:53Z [FATAL] [/core/main.go:156]: failed to initialize cache: retry timeout: read tcp 100.xx.xx.115:46178->10.xx.xx.198:6379: i/o timeout
```
**jobservice**: is not able to comminate to core
```
harbor-registry-jobservice-5d9fc5b9b9-xnqjs 2024-08-08T06:04:45Z [INFO] [/pkg/config/rest/rest.go:47]: get configuration from url: [http://harbor-registry-core:80/api/v2.0/internalconfig](http://harbor-registry-core/api/v2.0/internalconfig)
harbor-registry-jobservice-5d9fc5b9b9-xnqjs 2024-08-08T06:04:45Z [ERROR] [/pkg/config/rest/rest.go:50]: Failed on load rest config err:http error: code 503, message no healthy upstream, url:[http://harbor-registry-core:80/api/v2.0/internalconfig](http://harbor-registry-core/api/v2.0/internalconfig)
harbor-registry-jobservice-5d9fc5b9b9-xnqjs panic: failed to load configuration, error: failed to load rest config                                                                    
harbor-registry-jobservice-5d9fc5b9b9-xnqjs                                                                                                                                                 
harbor-registry-jobservice-5d9fc5b9b9-xnqjs goroutine 1 [running]:                                                                                                                          
harbor-registry-jobservice-5d9fc5b9b9-xnqjs main.main()                                                                                                                                     
harbor-registry-jobservice-5d9fc5b9b9-xnqjs     /harbor/src/jobservice/main.go:46 +0x3ae
```
![image](https://github.com/user-attachments/assets/b206442d-fa19-4a63-8c7c-7499504c5000)

**Comment by chlins** [comment]
Please check the network connectivity between harbor core and redis, jobservice depends on core, so core crash may cause jobservice also crash.
