### ISSUE TITLE
panic: nil pointer dereference when failed to scan out the quota records from redis

### ISSUE THREAD

**Issue by microyahoo** [goharbor/harbor#21045]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.
```console
 84 2024-10-14T19:12:57Z [ERROR] [/pkg/task/dao/execution.go:452]: failed to scan the outdate executions, error: dial tcp 10.246.4.112:6379: i/o timeout
 85 2024-10-14T19:13:20Z [INFO] [/lib/config/userconfig.go:256]: skip_update_pull_time:false
 86 2024-10-14T19:14:08Z [ERROR] [/controller/quota/controller.go:125]: failed to scan out the quota records from redis
 87 panic: runtime error: invalid memory address or nil pointer dereference
 88 [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x102b5f3]
 89 
 90 goroutine 468 [running]:
 91 github.com/goharbor/harbor/src/controller/quota.flushQuota({0x29605e0, 0xc000ea0420})
 92         /harbor/src/controller/quota/controller.go:128 +0x93
 93 github.com/goharbor/harbor/src/lib/gtask.(*Pool).doTask(0x3bea520, {0x29605e0, 0xc000ea0420}, 0xc000c15c30)
 94         /harbor/src/lib/gtask/pool.go:84 +0xeb
 95 created by github.com/goharbor/harbor/src/lib/gtask.(*Pool).Start in goroutine 1
 96         /harbor/src/lib/gtask/pool.go:70 +0xbe
```
https://github.com/goharbor/harbor/blob/main/src/controller/quota/controller.go#L123-L128

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.
1. set redis as quota update provider
2. failed to connect redis

**Versions:**
Please specify the versions of following systems.

- harbor version: [x.x.x]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by microyahoo** [comment]
//assign @microyahoo
