### ISSUE TITLE
Harbor bug deleting projects

### ISSUE THREAD

**Issue by andres06-hub** [goharbor/harbor#21098]
**Expected behavior and actual behavior:**
Hi, I get this error when we try to delete a project in harbor, always I want to delete a project I get
 this error, is it because of the used version?
 
 Someone please give me a hand, thanks.
 
 
**Steps to reproduce the problem:**

Error:
```
2024-10-25T20:18:05Z [INFO] [/controller/event/handler/internal/project.go:42]: delete project id: 174

panic: interface conversion: interface {} is nil, not string


goroutine 1656 [running]:

github.com/goharbor/harbor/src/controller/retention.(*defaultController).DeleteRetention(0xc000490f00, {0x2f46dc8, 0xc000c6de90}, 0x96)

	/harbor/src/controller/retention/controller.go:208 +0x145

github.com/goharbor/harbor/src/controller/retention.(*defaultController).DeleteRetentionByProject(0xc000490f00, {0x2f46dc8, 0xc000c6de90}, 0xae)

	/harbor/src/controller/retention/controller.go:446 +0x1c5
```

**Versions:**
- harbor version: [1.15.1]

**Comment by stonezdj** [comment]
Maybe caused by this code:
https://github.com/goharbor/harbor/blob/de281220b52ecd1427b5c0505ea71d7cdc547c11/src/controller/retention/controller.go#L206

**Comment by andres06-hub** [comment]
I can solved the issue adding to the request the fields `extras": "{\"untagged\":true}` and `"cron": "0 0 0 * * *"`

All this in the creation of the retention (policy)

PUT - `https://$HOST/api/v2.0/retentions/81`

example:
``` json
{
    "algorithm": "or",
    "id": 81,
    "rules": [
        {
            "disabled": false,
            "action": "retain",
            "scope_selectors": {
                "repository": [
                    {
                        "kind": "doublestar",
                        "decoration": "repoMatches",
                        "pattern": "**"
                    }
                ]
            },
            "tag_selectors": [
                {
                    "kind": "doublestar",
                    "decoration": "matches",
                    "pattern": "**",
                    "extras": "{\"untagged\":true}"
                }
            ],
            "params": {
                "nDaysSinceLastPull": 3
            },
            "template": "nDaysSinceLastPull"
        }
    ],
    "scope": {
        "level": "project",
        "ref": 84
    },
    "trigger": {
        "kind": "Schedule",
        "settings": {
            "cron": "0 0 0 * * *",
            "next_scheduled_time": "2024-10-30T00:00:00.000Z"
        }
    }
}
```
