### ISSUE TITLE
Crash registry container

### ISSUE THREAD

**Issue by DimiDr0l** [goharbor/harbor#21172]
If you are reporting a problem, please make sure the following information are provided:

**Steps to reproduce the problem:**
Clean install

**Versions:**
k8s:
Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.27.16

- helm chart version: [1.15.1]

**Additional context:**

```
time="2024-11-12T10:25:15.60349416Z" level=info msg="PurgeUploads starting: olderThan=2024-11-05 10:25:15.603374032 +0000 UTC m=-603359.994052969, actuallyDelete=true"
panic: runtime error: index out of range [0] with length 0

goroutine 42 [running]:
github.com/docker/distribution/registry/storage.getOutstandingUploads.func1({0xf33148, 0xc0004cb780})
	/go/src/github.com/docker/distribution/registry/storage/purgeuploads.go:73 +0x55e
github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).doWalk.func1(0xc000354680, 0x30?)
	/go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:1023 +0x622
github.com/docker/distribution/vendor/github.com/aws/aws-sdk-go/service/s3.(*S3).ListObjectsV2PagesWithContext(0xc00038c9b0, {0x7fece3fbbc88, 0xc00031e0e0}, 0xc00039c870, 0xc0002a7a18, {0x0, 0x0, 0x0})
	/go/src/github.com/docker/distribution/vendor/github.com/aws/aws-sdk-go/service/s3/api.go:4198 +0x174
github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).doWalk(0xc00046f600, {0xf33458, 0xc00031e000}, 0xc00011eb00, {0xc00032c331, 0x20}, {0xf26d78, 0x1}, 0xc0003c4b70)
	/go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:982 +0x34e
github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).Walk(0xc00046f600, {0xf33458, 0xc00031e000}, {0xc0001a4300, 0x20}, 0xc0003c4b70)
	/go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:930 +0x148
github.com/docker/distribution/registry/storage/driver/base.(*Base).Walk(0xc0004ce0f0, {0xf32ea8?, 0xc0004b8140?}, {0xc0001a4300, 0x20}, 0xc0003c4b70)
	/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go:239 +0x243
github.com/docker/distribution/registry/storage.getOutstandingUploads({0xf32ea8, 0xc0004b8140}, {0xf3a170, 0xc0004ce0f0})
	/go/src/github.com/docker/distribution/registry/storage/purgeuploads.go:70 +0x1d8
github.com/docker/distribution/registry/storage.PurgeUploads({0xf32ea8, 0xc0004b8140}, {0xf3a170, 0xc0004ce0f0}, {0xc1c29a82e3f6c1d0, 0xfffddb3f4de1fe97, 0x1509000}, 0x1)
	/go/src/github.com/docker/distribution/registry/storage/purgeuploads.go:34 +0x116
github.com/docker/distribution/registry/handlers.startUploadPurger.func1()
	/go/src/github.com/docker/distribution/registry/handlers/app.go:1112 +0x33f
created by github.com/docker/distribution/registry/handlers.startUploadPurger in goroutine 1
	/go/src/github.com/docker/distribution/registry/handlers/app.go:1100 +0x2ebtime="2024-11-12T10:25:15.60349416Z" level=info msg="PurgeUploads starting: olderThan=2024-11-05 10:25:15.603374032 +0000 UTC m=-603359.994052969, actuallyDelete=true"
panic: runtime error: index out of range [0] with length 0

goroutine 42 [running]:
github.com/docker/distribution/registry/storage.getOutstandingUploads.func1({0xf33148, 0xc0004cb780})
	/go/src/github.com/docker/distribution/registry/storage/purgeuploads.go:73 +0x55e
github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).doWalk.func1(0xc000354680, 0x30?)
	/go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:1023 +0x622
github.com/docker/distribution/vendor/github.com/aws/aws-sdk-go/service/s3.(*S3).ListObjectsV2PagesWithContext(0xc00038c9b0, {0x7fece3fbbc88, 0xc00031e0e0}, 0xc00039c870, 0xc0002a7a18, {0x0, 0x0, 0x0})
	/go/src/github.com/docker/distribution/vendor/github.com/aws/aws-sdk-go/service/s3/api.go:4198 +0x174
github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).doWalk(0xc00046f600, {0xf33458, 0xc00031e000}, 0xc00011eb00, {0xc00032c331, 0x20}, {0xf26d78, 0x1}, 0xc0003c4b70)
	/go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:982 +0x34e
github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).Walk(0xc00046f600, {0xf33458, 0xc00031e000}, {0xc0001a4300, 0x20}, 0xc0003c4b70)
	/go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:930 +0x148
github.com/docker/distribution/registry/storage/driver/base.(*Base).Walk(0xc0004ce0f0, {0xf32ea8?, 0xc0004b8140?}, {0xc0001a4300, 0x20}, 0xc0003c4b70)
	/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go:239 +0x243
github.com/docker/distribution/registry/storage.getOutstandingUploads({0xf32ea8, 0xc0004b8140}, {0xf3a170, 0xc0004ce0f0})
	/go/src/github.com/docker/distribution/registry/storage/purgeuploads.go:70 +0x1d8
github.com/docker/distribution/registry/storage.PurgeUploads({0xf32ea8, 0xc0004b8140}, {0xf3a170, 0xc0004ce0f0}, {0xc1c29a82e3f6c1d0, 0xfffddb3f4de1fe97, 0x1509000}, 0x1)
	/go/src/github.com/docker/distribution/registry/storage/purgeuploads.go:34 +0x116
github.com/docker/distribution/registry/handlers.startUploadPurger.func1()
	/go/src/github.com/docker/distribution/registry/handlers/app.go:1112 +0x33f
created by github.com/docker/distribution/registry/handlers.startUploadPurger in goroutine 1
	/go/src/github.com/docker/distribution/registry/handlers/app.go:1100 +0x2eb
```

**Comment by MinerYang** [comment]
Hi @DimiDr0l ,

Could you reproduce this issue at you side?
