### ISSUE TITLE
should change data direcotry can be configurable 

### ISSUE THREAD

**Issue by yixingjia** [goharbor/harbor#2617]
1> compile latest harbor code 
2> will report 

Traceback (most recent call last):
  File "/Users/admin/Documents/goworkspace/src/github.com/vmware/harbor/make/prepare", line 156, in <module>
    secret_key = get_secret_key(secretkey_path)
  File "/Users/admin/Documents/goworkspace/src/github.com/vmware/harbor/make/prepare", line 43, in get_secret_key
    secret_key = _get_secret(path, "secretkey") 
  File "/Users/admin/Documents/goworkspace/src/github.com/vmware/harbor/make/prepare", line 60, in _get_secret
    os.makedirs(folder, mode=0600)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/data'

The reason is that my home directory don't have /data directory.
but the certificate  file need to place to that directory
ssl_cert = /data/cert/server.crt
ssl_cert_key = /data/cert/server.key

Ideally we should set those directory as configurable . or create the certificate file in current directory which can avoid the possible permission issue.

Beside that we should separate the sensitive data with others
eg. password, certs, keys should separate the generally data files.

**Comment by reasonerjt** [comment]
This has been fix in v1.8 after introduction of `harbor.yaml` and rework of the prepare process.
