### ISSUE TITLE
ValueError: Timeout value connect was Timeout(connect=60, read=60, total=None), but it must be an int or float

### ISSUE THREAD

**Issue by meteorlad** [goharbor/harbor#5461]
Version:
centos 7.5
docker-ce-18.03.1.ce-1.el7.centos.x86_64
docker-compose-1.21.2
urllib3-1.23
requests-2.18.4

error log:

```
[root@harbor harbor]# ./install.sh

[Step 0]: checking installation environment ...

Note: docker version: 18.03.1

Note: docker-compose version: 1.21.2

[Step 1]: loading Harbor images ...
Loaded image: vmware/registry-photon:v2.6.2-v1.5.2
Loaded image: vmware/photon:1.0
Loaded image: vmware/mariadb-photon:v1.5.2
Loaded image: vmware/harbor-log:v1.5.2
Loaded image: vmware/nginx-photon:v1.5.2
Loaded image: vmware/notary-signer-photon:v0.5.1-v1.5.2
Loaded image: vmware/postgresql-photon:v1.5.2
Loaded image: vmware/harbor-db:v1.5.2
Loaded image: vmware/harbor-jobservice:v1.5.2
Loaded image: vmware/clair-photon:v2.0.4-v1.5.2
Loaded image: vmware/harbor-adminserver:v1.5.2
Loaded image: vmware/harbor-ui:v1.5.2
Loaded image: vmware/redis-photon:v1.5.2
Loaded image: vmware/notary-server-photon:v0.5.1-v1.5.2
Loaded image: vmware/harbor-migrator:v1.5.0


[Step 2]: preparing environment ...
Clearing the configuration file: ./common/config/log/logrotate.conf
Clearing the configuration file: ./common/config/jobservice/env
Clearing the configuration file: ./common/config/jobservice/config.yml
Clearing the configuration file: ./common/config/nginx/nginx.conf
Clearing the configuration file: ./common/config/ui/private_key.pem
Clearing the configuration file: ./common/config/ui/env
Clearing the configuration file: ./common/config/ui/app.conf
Clearing the configuration file: ./common/config/db/env
Clearing the configuration file: ./common/config/adminserver/env
Clearing the configuration file: ./common/config/registry/root.crt
Clearing the configuration file: ./common/config/registry/config.yml
loaded secret from file: /data/secretkey
Generated configuration file: ./common/config/nginx/nginx.conf
Generated configuration file: ./common/config/adminserver/env
Generated configuration file: ./common/config/ui/env
Generated configuration file: ./common/config/registry/config.yml
Generated configuration file: ./common/config/db/env
Generated configuration file: ./common/config/jobservice/env
Generated configuration file: ./common/config/jobservice/config.yml
Generated configuration file: ./common/config/log/logrotate.conf
Generated configuration file: ./common/config/jobservice/config.yml
Generated configuration file: ./common/config/ui/app.conf
Generated certificate, key file: ./common/config/ui/private_key.pem, cert file: ./common/config/registry/root.crt
The configuration files are ready, please use docker-compose to start the service.


[Step 3]: checking existing instance of Harbor ...
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 71, in main
    command()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 124, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 41, in project_from_options
    compatibility=options.get('--compatibility'),
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 126, in get_project
    project_name, config_data, client, environment.get('DOCKER_DEFAULT_PLATFORM')
  File "/usr/lib/python2.7/site-packages/compose/project.py", line 96, in from_config
    service_networks = get_networks(service_dict, networks)
  File "/usr/lib/python2.7/site-packages/compose/network.py", line 320, in get_networks
    networks[network.true_name] = netdef
  File "/usr/lib/python2.7/site-packages/compose/network.py", line 125, in true_name
    self._set_legacy_flag()
  File "/usr/lib/python2.7/site-packages/compose/network.py", line 146, in _set_legacy_flag
    data = self.inspect(legacy=True)
  File "/usr/lib/python2.7/site-packages/compose/network.py", line 106, in inspect
    return self.client.inspect_network(self.legacy_full_name)
  File "/usr/lib/python2.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/api/network.py", line 211, in inspect_network
    res = self._get(url, params=params)
  File "/usr/lib/python2.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 198, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 515, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 582, in urlopen
    timeout_obj = self._get_timeout(timeout)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 309, in _get_timeout
    return Timeout.from_float(timeout)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 154, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 97, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 127, in _validate_timeout
    "int or float." % (name, value))
ValueError: Timeout value connect was Timeout(connect=60, read=60, total=None), but it must be an int or float.


[Step 4]: starting Harbor ...
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 71, in main
    command()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 124, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 41, in project_from_options
    compatibility=options.get('--compatibility'),
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 126, in get_project
    project_name, config_data, client, environment.get('DOCKER_DEFAULT_PLATFORM')
  File "/usr/lib/python2.7/site-packages/compose/project.py", line 96, in from_config
    service_networks = get_networks(service_dict, networks)
  File "/usr/lib/python2.7/site-packages/compose/network.py", line 320, in get_networks
    networks[network.true_name] = netdef
  File "/usr/lib/python2.7/site-packages/compose/network.py", line 125, in true_name
    self._set_legacy_flag()
  File "/usr/lib/python2.7/site-packages/compose/network.py", line 146, in _set_legacy_flag
    data = self.inspect(legacy=True)
  File "/usr/lib/python2.7/site-packages/compose/network.py", line 106, in inspect
    return self.client.inspect_network(self.legacy_full_name)
  File "/usr/lib/python2.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/api/network.py", line 211, in inspect_network
    res = self._get(url, params=params)
  File "/usr/lib/python2.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 198, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 515, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 582, in urlopen
    timeout_obj = self._get_timeout(timeout)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 309, in _get_timeout
    return Timeout.from_float(timeout)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 154, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 97, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 127, in _validate_timeout
    "int or float." % (name, value))
ValueError: Timeout value connect was Timeout(connect=60, read=60, total=None), but it must be an int or float.
```

**Comment by meteorlad** [comment]
harbor.v1.5.2

**Comment by reasonerjt** [comment]
The error is not in Harbor, it's from docker-compose, seems it's because your docker daemon is not responding.

**Comment by meteorlad** [comment]
Can you help me see where the problem is？

```
[root@harbor harbor]# docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
vmware/redis-photon           v1.5.2              e8ec8e42d3cf        2 weeks ago         264MB
vmware/clair-photon           v2.0.4-v1.5.2       b9090d2b9af5        2 weeks ago         358MB
vmware/notary-server-photon   v0.5.1-v1.5.2       86aa90a8796d        2 weeks ago         266MB
vmware/notary-signer-photon   v0.5.1-v1.5.2       75e32a61968d        2 weeks ago         264MB
vmware/registry-photon        v2.6.2-v1.5.2       254f767d3375        2 weeks ago         253MB
vmware/nginx-photon           v1.5.2              cd19d787004d        2 weeks ago         190MB
vmware/harbor-log             v1.5.2              3f14dfecc3f5        2 weeks ago         255MB
vmware/harbor-jobservice      v1.5.2              e450c47fd1f0        2 weeks ago         249MB
vmware/harbor-ui              v1.5.2              a942b187d9a4        2 weeks ago         267MB
vmware/harbor-adminserver     v1.5.2              aff987dfb2a4        2 weeks ago         238MB
vmware/harbor-db              v1.5.2              1c40f4189ef7        2 weeks ago         581MB
vmware/mariadb-photon         v1.5.2              a11e91908b72        2 weeks ago         581MB
vmware/postgresql-photon      v1.5.2              ca22b1070233        2 weeks ago         276MB
vmware/photon                 1.0                 9e2c9d5f44ef        5 weeks ago         130MB
vmware/harbor-migrator        v1.5.0              466c57ab0dc3        3 months ago        1.16GB
[root@harbor harbor]# systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2018-08-02 11:30:08 CST; 2min 49s ago
     Docs: https://docs.docker.com
 Main PID: 24314 (dockerd)
    Tasks: 23
   Memory: 55.9M
   CGroup: /system.slice/docker.service
           ├─24314 /usr/bin/dockerd
           └─24321 docker-containerd --config /var/run/docker/containerd/containerd.toml

Aug 02 11:30:08 harbor.local dockerd[24314]: time="2018-08-02T11:30:08+08:00" level=info msg="containerd successfully booted in 0.007269s" module=containerd
Aug 02 11:30:08 harbor.local dockerd[24314]: time="2018-08-02T11:30:08.273000753+08:00" level=info msg="[graphdriver] using prior storage driver: overlay2"
Aug 02 11:30:08 harbor.local dockerd[24314]: time="2018-08-02T11:30:08.432009206+08:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Aug 02 11:30:08 harbor.local dockerd[24314]: time="2018-08-02T11:30:08.433713113+08:00" level=info msg="Loading containers: start."
Aug 02 11:30:08 harbor.local dockerd[24314]: time="2018-08-02T11:30:08.630208873+08:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a ...erred IP address"
Aug 02 11:30:08 harbor.local dockerd[24314]: time="2018-08-02T11:30:08.700032120+08:00" level=info msg="Loading containers: done."
Aug 02 11:30:08 harbor.local dockerd[24314]: time="2018-08-02T11:30:08.764468110+08:00" level=info msg="Docker daemon" commit=9ee9f40 graphdriver(s)=overlay2 version=18.03.1-ce
Aug 02 11:30:08 harbor.local dockerd[24314]: time="2018-08-02T11:30:08.764650693+08:00" level=info msg="Daemon has completed initialization"
Aug 02 11:30:08 harbor.local dockerd[24314]: time="2018-08-02T11:30:08.782850382+08:00" level=info msg="API listen on /var/run/docker.sock"
Aug 02 11:30:08 harbor.local systemd[1]: Started Docker Application Container Engine.
Hint: Some lines were ellipsized, use -l to show in full.
[root@harbor harbor]# ps -ef|grep docker
root     24314     1  6 11:30 ?        00:00:10 /usr/bin/dockerd
root     24321 24314  0 11:30 ?        00:00:00 docker-containerd --config /var/run/docker/containerd/containerd.toml
root     24571 13667  0 11:33 pts/1    00:00:00 grep --color=auto docker
```
