### ISSUE TITLE
ldap_url

### ISSUE THREAD

**Issue by zhoud9012** [goharbor/harbor#5541]
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/configparser.py", line 789, in get
    value = d[option]
  File "/usr/local/python3/lib/python3.6/collections/__init__.py", line 885, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/local/python3/lib/python3.6/collections/__init__.py", line 877, in __missing__
    raise KeyError(key)
KeyError: 'ldap_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./prepare", line 123, in <module>
    ldap_url = rcp.get("configuration", "ldap_url")
  File "/usr/local/python3/lib/python3.6/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'ldap_url' in section: 'configuration'

**Comment by steven-zou** [comment]
@zhoud9012 

Could you please confirm if the ldap_url existing in the harbor.cfg file?

e.g.:
`ldap_url = ldaps://ldap.mydomain.com`

**Comment by zhoud9012** [comment]
It is now like this 

e.g.:
ldap_url = ldaps://ldap.mydomain.com

Traceback (most recent call last):
  File "./prepare", line 109, in <module>
    validate(rcp, args)
  File "./prepare", line 37, in validate
    project_creation = rcp.get("configuration", "project_creation_restriction")
  File "/usr/local/python3/lib/python3.6/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'project_creation_restriction' in section: 'configuration'

**Comment by steven-zou** [comment]
@zhoud9012 

The root cause might be differences of function rcp in different python versions. You can try a lower version like 3.0 or 2.7 to see if it does work. 

If it is caused by the python version, you can try to fix it and raise PR to merge the code back to harbor repo.

**Comment by clouderati** [comment]
Hi @zhoud9012 – were you able to try with Python v2.7? Please let us know. Thanks!
