### ISSUE TITLE
harbor upgrade directly from v1.1.1 to v1.5.0

### ISSUE THREAD

**Issue by fenghui2013** [goharbor/harbor#5736]
I am using harbor v1.1.1 and I want to upgrade to v1.5.0. Upgrading directly from v1.1.1 to v1.5.0(skip v1.2.0 v1.3.0 v1.4.0) is OK?

**Comment by wy65701436** [comment]
it's ok to upgrade from v1.1.1 to v1.5.0, but please read carefully about the migration guide.

https://github.com/goharbor/harbor/blob/release-1.5.0/docs/migration_guide.md

**Comment by fenghui2013** [comment]
I was upgrading harbor using the command below, but it just upgrade to v1.4.0.

```
docker run -it --rm -e DB_USR=root -e DB_PWD=root123 -v /data/database:/var/lib/mysql -v /root/harbor_test/harbor/harbor.cfg:/harbor-migration/harbor-cfg/harbor.cfg vmware/harbor-migrator:v1.5.0 up
```

error logs:

```
Please backup before upgrade, 
Enter y to continue updating or n to abort: y
Trying to start mysql server...
Waiting for MySQL start...
2018-08-27  9:33:11 139820744288192 [Note] mysqld (mysqld 10.2.14-MariaDB) starting as process 8 ...
2018-08-27  9:33:11 139820744288192 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2018-08-27  9:33:11 139820744288192 [Note] InnoDB: Uses event mutexes
2018-08-27  9:33:11 139820744288192 [Note] InnoDB: Compressed tables use zlib 1.2.8
2018-08-27  9:33:11 139820744288192 [Note] InnoDB: Number of pools: 1
2018-08-27  9:33:11 139820744288192 [Note] InnoDB: Using SSE2 crc32 instructions
2018-08-27  9:33:11 139820744288192 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
2018-08-27  9:33:11 139820744288192 [Note] InnoDB: Completed initialization of buffer pool
2018-08-27  9:33:11 139819749459712 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2018-08-27  9:33:11 139820744288192 [Note] InnoDB: Highest supported file format is Barracuda.
2018-08-27  9:33:12 139820744288192 [Note] InnoDB: Upgrading redo log: 2*50331648 bytes; LSN=1913436
2018-08-27  9:33:12 139820744288192 [Note] InnoDB: Starting to delete and rewrite log files.
2018-08-27  9:33:12 139820744288192 [Note] InnoDB: Setting log file ./ib_logfile101 size to 50331648 bytes
2018-08-27  9:33:12 139820744288192 [Note] InnoDB: Setting log file ./ib_logfile1 size to 50331648 bytes
2018-08-27  9:33:12 139820744288192 [Note] InnoDB: Renaming log file ./ib_logfile101 to ./ib_logfile0
2018-08-27  9:33:12 139820744288192 [Note] InnoDB: New log files created, LSN=1913436
2018-08-27  9:33:12 139820744288192 [Note] InnoDB: 128 out of 128 rollback segments are active.
2018-08-27  9:33:12 139820744288192 [Note] InnoDB: Creating sys_virtual system tables.
2018-08-27  9:33:12 139820744288192 [Note] InnoDB: Creating shared tablespace for temporary tables
2018-08-27  9:33:12 139820744288192 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2018-08-27  9:33:12 139820744288192 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2018-08-27  9:33:12 139820744288192 [Note] InnoDB: Waiting for purge to start
2018-08-27  9:33:12 139820744288192 [Note] InnoDB: 5.7.21 started; log sequence number 1913436
2018-08-27  9:33:12 139818918975232 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2018-08-27  9:33:12 139818918975232 [Note] InnoDB: Cannot open '/var/lib/mysql/ib_buffer_pool' for reading: No such file or directory
2018-08-27  9:33:12 139820744288192 [Note] Plugin 'FEEDBACK' is disabled.
2018-08-27  9:33:12 139820744288192 [Note] Server socket created on IP: '::'.
2018-08-27  9:33:12 139820744288192 [ERROR] Missing system table mysql.roles_mapping; please run mysql_upgrade to create it
2018-08-27  9:33:12 139820744288192 [ERROR] Incorrect definition of table mysql.event: expected column 'sql_mode' at position 14 to have type set('REAL_AS_FLOAT','PIPES_AS_CONCAT','ANSI_QUOTES','IGNORE_SPACE','IGNORE_BAD_TABLE_OPTIONS','ONLY_FULL_GROUP_BY','NO_UNSIGNED_SUBTRACTION','NO_DIR_IN_CREATE','POSTGRESQL','ORACLE','MSSQL','DB2','MAXDB','NO_KEY_OPTIONS','NO_TABLE_OPTIONS','NO_FIELD_OPTIONS','MYSQL323','MYSQL40','ANSI','NO_AUTO_VALUE_ON_ZERO','NO_BACKSLASH_ESCAPES','STRICT_TRANS_TABLES','STRICT_ALL_TABLES','NO_ZERO_IN_DATE','NO_ZERO_DATE','INVALID_DATES','ERROR_FOR_DIVISION_BY_ZERO','TRADITIONAL','NO_AUTO_CREATE_USER','HIGH_NOT_PRECEDENCE','NO_ENGINE_SUBSTITUTION','PAD_CHAR_TO_FULL_LENGTH'), found type set('REAL_AS_FLOAT','PIPES_AS_CONCAT','ANSI_QUOTES','IGNORE_SPACE','NOT_USED','ONLY_FULL_GROUP_BY','NO_UNSIGNED_SUBTRACTION','NO_DIR_IN_CREATE','POSTGRESQL','ORACLE','MSSQL','DB2','MAXDB','NO_KEY_OPTIONS','NO_TABLE_OPTIONS','NO_FIELD_OPTIONS','MYSQL323','MYSQL40','ANSI','NO_AUTO_VALUE_ON_ZERO','NO_BACKSLASH_ESCAPES','STRICT_TRANS_TABLES','STRICT_A
2018-08-27  9:33:12 139820744288192 [ERROR] mysqld: Event Scheduler: An error occurred when initializing system tables. Disabling the Event Scheduler.
2018-08-27  9:33:12 139820581795584 [Warning] Failed to load slave replication state from table mysql.gtid_slave_pos: 1146: Table 'mysql.gtid_slave_pos' doesn't exist
2018-08-27  9:33:12 139820744288192 [Note] Reading of all Master_info entries succeded
2018-08-27  9:33:12 139820744288192 [Note] Added new Master_info '' to hash table
2018-08-27  9:33:12 139820744288192 [Note] mysqld: ready for connections.
Version: '10.2.14-MariaDB'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  Source distribution
Version is not specified. Default version is head.
Performing upgrade head...
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
0.4.0
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 0.4.0 -> 1.2.0, 0.4.0 to 1.2.0
/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py:507: Warning: (1146L, "Table 'mysql.column_stats' doesn't exist")
  cursor.execute(statement, parameters)
/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py:507: Warning: (1146L, "Table 'mysql.index_stats' doesn't exist")
  cursor.execute(statement, parameters)
INFO  [alembic.runtime.migration] Running upgrade 1.2.0 -> 1.3.0, 1.2.0 to 1.3.0
INFO  [alembic.runtime.migration] Running upgrade 1.3.0 -> 1.4.0, 1.3.0 to 1.4.0
INFO  [alembic.runtime.migration] Running upgrade 1.4.0 -> 1.5.0, 1.4.0 to 1.5.0
Traceback (most recent call last):
  File "/usr/bin/alembic", line 9, in <module>
    load_entry_point('alembic==0.9.9', 'console_scripts', 'alembic')()
  File "/usr/lib/python2.7/site-packages/alembic/config.py", line 486, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/lib/python2.7/site-packages/alembic/config.py", line 480, in main
    self.run_cmd(cfg, options)
  File "/usr/lib/python2.7/site-packages/alembic/config.py", line 463, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/usr/lib/python2.7/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/usr/lib/python2.7/site-packages/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/lib/python2.7/site-packages/alembic/util/compat.py", line 141, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "/harbor-migration/db/migration_harbor/env.py", line 85, in <module>
    run_migrations_online()
  File "/harbor-migration/db/migration_harbor/env.py", line 80, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/lib/python2.7/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/lib/python2.7/site-packages/alembic/runtime/migration.py", line 330, in run_migrations
    step.migration_fn(**kw)
  File "/harbor-migration/db/migration_harbor/versions/1_5_0.py", line 74, in upgrade
    op.add_column('img_scan_job', sa.Column('job_uuid', sa.String(64)))
  File "<string>", line 8, in add_column
  File "<string>", line 3, in add_column
  File "/usr/lib/python2.7/site-packages/alembic/operations/ops.py", line 1565, in add_column
    return operations.invoke(op)
  File "/usr/lib/python2.7/site-packages/alembic/operations/base.py", line 319, in invoke
    return fn(self, operation)
  File "/usr/lib/python2.7/site-packages/alembic/operations/toimpl.py", line 123, in add_column
    schema=schema
  File "/usr/lib/python2.7/site-packages/alembic/ddl/impl.py", line 172, in add_column
    self._exec(base.AddColumn(table_name, column, schema=schema))
  File "/usr/lib/python2.7/site-packages/alembic/ddl/impl.py", line 118, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
    compiled
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1060, "Duplicate column name 'job_uuid'") [SQL: u'ALTER TABLE img_scan_job ADD COLUMN job_uuid VARCHAR(64)'] (Background on this error at: http://sqlalche.me/e/e3q8)
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
1.4.0
Upgrade performed.
```

**What happened?**
