### ISSUE TITLE
update 1.5.2 to 1.6.0 Fail.

### ISSUE THREAD

**Issue by paddy235** [goharbor/harbor#5788]
* env:
```
   Static hostname: dockerreg
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 2091b43bc8b3482194b466f9c3081cd6
           Boot ID: 6214219866b24f358b8146315f019607
    Virtualization: vmware
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-693.17.1.el7.x86_64
      Architecture: x86-64



[root@dockerreg harbor]# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 16
Server Version: 17.05.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.17.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.639GiB
Name: dockerreg




```
* run cmd :  

```
docker run -it --rm \
-e DB_USR=root -e DB_PWD=xxxxx  \
-v /webserver/harbor/database:/var/lib/mysql \
-v /root/backup/harbor/harbor.cfg:/harbor-migration/harbor-cfg/harbor.cfg \
goharbor/harbor-migrator:v1.6.0 up


```
* result: 
```
PostgreSQL init process complete; ready for start up.

Performing upgrade 1.5.0...
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
1.5.0 (head)
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
1.5.0 (head)
Upgrade performed.
Traceback (most recent call last):
  File "/harbor-migration/db/util/mysql_pgsql_data_converter.py", line 153, in <module>
    convert_registry_db(sys.argv[1], sys.argv[2])
  File "/harbor-migration/db/util/mysql_pgsql_data_converter.py", line 46, in convert_registry_db
    write_insert(pgsql_dump, insert_lines)
  File "/harbor-migration/db/util/mysql_pgsql_data_converter.py", line 132, in write_insert
    pgsql_dump.write("%s\n" % item)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 214-216: ordinal not in range(128)
```

**Comment by wy65701436** [comment]
@paddy235 can you help to check whether you v1.5.2 DB contains Chinese words?

**Comment by paddy235** [comment]
yes,  contains Chinese words

**Comment by wy65701436** [comment]
thanks @paddy235, this PR(https://github.com/goharbor/harbor/pull/5798) is to fix it.

**Comment by paddy235** [comment]
期待发布修复版本

**Comment by wy65701436** [comment]
@paddy235 please use rc3 to verify, this build contains the fix.

**Comment by wy65701436** [comment]
@paddy235 did you try with the latest rc3 release? Or you can pull goharbor/harbor-migrator:v1.6.0 from dockerhub, I have updated it.

**Comment by wy65701436** [comment]
@paddy235 close it as fixed, please use the GA build.
