### ISSUE TITLE
Harbor ui not started in k8s, Always CrashLoopBackOff.

### ISSUE THREAD

**Issue by yjwfn** [goharbor/harbor#6294]
After install Harbor by Helm, I got this error in ui pod: 
```
liuweideMacBook-Pro:harbor-helm yjwfn$ kubectl logs -n harbor harbor-harbor-ui-5c4c6d4f4b-z6hb2
2018-11-17T03:30:32Z [DEBUG] [init.go:37]: topic StartReplication is subscribed
2018-11-17T03:30:32Z [DEBUG] [init.go:37]: topic OnPush is subscribed
2018-11-17T03:30:32Z [DEBUG] [init.go:37]: topic OnDeletion is subscribed
2018-11-17T03:30:32Z [DEBUG] [authenticator.go:126]: Registered authencation helper for auth mode: db_auth
2018-11-17T03:30:32Z [DEBUG] [authenticator.go:126]: Registered authencation helper for auth mode: ldap_auth
2018-11-17T03:30:32Z [DEBUG] [authenticator.go:126]: Registered authencation helper for auth mode: uaa_auth
2018-11-17T03:30:32Z [INFO] Config path: /etc/ui/app.conf
2018-11-17T03:30:32Z [INFO] initializing configurations...
2018-11-17T03:30:32Z [INFO] key path: /etc/ui/key
2018-11-17T03:30:32Z [INFO] initializing client for adminserver http://harbor-harbor-adminserver ...
2018-11-17T03:30:32Z [INFO] initializing the project manager based on local database...
2018-11-17T03:30:32Z [INFO] configurations initialization completed
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/vmware/harbor/src/ui/config.ExtURL(0xcad960, 0xc420396900, 0xda1152, 0x8)
	/go/src/github.com/vmware/harbor/src/ui/config/config.go:287 +0x108
github.com/vmware/harbor/src/ui/service/token.InitCreators()
	/go/src/github.com/vmware/harbor/src/ui/service/token/creator.go:52 +0x1da
main.main()
	/go/src/github.com/vmware/harbor/src/ui/main.go:92 +0x1c0
liuweideMacBook-Pro:harbor-helm yjwfn$
```

This is all pods : 
```
liuweideMacBook-Pro:harbor-helm yjwfn$ kubectl get pods -n harbor
NAME                                           READY   STATUS             RESTARTS   AGE
harbor-harbor-adminserver-78fb996944-hqtt2     1/1     Running            2          9m55s
harbor-harbor-chartmuseum-794d758f67-t7kvv     1/1     Running            0          9m55s
harbor-harbor-clair-78bfc857df-hlhs6           1/1     Running            2          9m55s
harbor-harbor-database-0                       1/1     Running            0          9m55s
harbor-harbor-jobservice-5897b86998-bsk27      1/1     Running            0          9m55s
harbor-harbor-notary-server-68c6b7ccdd-nprtv   1/1     Running            0          9m55s
harbor-harbor-notary-signer-67b6cd84b9-n4cgz   1/1     Running            1          9m55s
harbor-harbor-registry-666f8bd89c-zrkfg        1/1     Running            0          9m55s
harbor-harbor-ui-5c4c6d4f4b-z6hb2              0/1     CrashLoopBackOff   6          9m55s
harbor-redis-master-0                          1/1     Running            0          9m55s
```

For test I have custom some values:  
```
externalURL: harbor-core.rcntech.cn
ingress:
 hosts:
  core: harbor-core.rcntech.cn
  notary: harbor-notary.rcntech.cn
 tls:
  enabled: true 

persistence:
  enabled: false
  resourcePolicy:  ""
redis:
  master:
    persistence:
      enabled: false  
```

**Comment by ywk253100** [comment]
The protocol is needed in externalURL: `externalURL=https://harbor-core.rcntech.cn`.

**Comment by clouderati** [comment]
@yjwfn – can you please confirm @ywk253100's suggestion fixed your issue?

**Comment by yjwfn** [comment]
@ywk253100 @clouderati  Yes, it is working fine. All pods  are running.

**Comment by StodaraHodan** [comment]
Thanks @ywk253100 

I had a similar error from the core pod, https:// added to external url solved it.

```
panic: runtime error: index out of range
goroutine 1 [running]:
github.com/goharbor/harbor/src/core/config.ExtURL(0x16ba980, 0xc000345080, 0x18e2a72, 0x8)
	/harbor/src/core/config/config.go:255 +0x152
github.com/goharbor/harbor/src/core/service/token.InitCreators()
	/harbor/src/core/service/token/creator.go:53 +0x17c
main.main()
	/harbor/src/core/main.go:174 +0x1e2
```
