### ISSUE TITLE
Harbor HA环境下redis认证失败

### ISSUE THREAD

**Issue by acaiblog** [goharbor/harbor#6299]
Harbor版本：v1.5.0
故障说明：
在搭建harbor ha环境中，由于redis cluster设置了password。导致harbor服务无法通过redis认证。测试了下如果对接没有设置password的redis是正常的。
在harbor ha环境中，因为redis配置的原因导致harbor-ui容器异常，
harbor-ui容器日志错误信息：
```
[root@node01 ~]# tailf /var/log/harbor/ui.log 
Nov 19 00:01:56 172.18.0.1 ui[23724]: 2018-11-19T05:01:56Z [INFO] Init proxy
Nov 19 00:01:56 172.18.0.1 ui[23724]: panic: ERR Client sent AUTH, but no password is set
Nov 19 00:01:56 172.18.0.1 ui[23724]: 
Nov 19 00:01:56 172.18.0.1 ui[23724]: goroutine 1 [running]:
Nov 19 00:01:56 172.18.0.1 ui[23724]: github.com/vmware/harbor/src/vendor/github.com/astaxie/beego.initBeforeHTTPRun()
Nov 19 00:01:56 172.18.0.1 ui[23724]: #011/go/src/github.com/vmware/harbor/src/vendor/github.com/astaxie/beego/beego.go:83 +0x111
Nov 19 00:01:56 172.18.0.1 ui[23724]: github.com/vmware/harbor/src/vendor/github.com/astaxie/beego.Run(0x0, 0x0, 0x0)
Nov 19 00:01:56 172.18.0.1 ui[23724]: #011/go/src/github.com/vmware/harbor/src/vendor/github.com/astaxie/beego/beego.go:55 +0x26
Nov 19 00:01:56 172.18.0.1 ui[23724]: main.main()
Nov 19 00:01:56 172.18.0.1 ui[23724]: #011/go/src/github.com/vmware/harbor/src/ui/main.go:156 +0x7f4
```
以下是harbor.cfg配置
```
##### End of Harbor DB configuration#######

#The redis server address. Only needed in HA installation.
#address:port[,weight,password,db_index]
redis_url = 192.168.100.12:6378,100,123456,0

##########Clair DB configuration############
```
想请问一下，如果在redis有访问密码的情况下。在harbor配置文件中应该如何定义呢？

**Comment by KylanZhang** [comment]
我测的是1.5.4版本的，ui这样配置没问题，有问题的是jobservice和registry，jobservice的我修改成
redis://anonymous:password@url:6379/0 这个形式就正常了，但是registry依旧不行。

**Comment by ywk253100** [comment]
Refer to https://github.com/docker/distribution/blob/master/docs/configuration.md#redis to configure the Redis used by registry. 

BTW, the HA solution in Harbor 1.5 has deprecated, the [Harbor chart](https://github.com/goharbor/harbor-helm) is the recommended way.

**Comment by ywk253100** [comment]
Closing as inactivity, feel free to reopen it.
