### ISSUE TITLE
cannot migrate remote db from mysql to Postgresql

### ISSUE THREAD

**Issue by chamhaw** [goharbor/harbor#6709]
My harbor version is 1.4 now and I want to upgrade to 1.7.
I read the migration guide that I need upgrade to 1.6 first.  I pulled the migrate image `goharbor/harbor:v1.6.3` but the database host is hardcoded. 

Didn't you consider a distributed deployment? 
#4878 this issue have been opened for  three quarters.
#6233 this PR have been opened for three months. 
Can any one resolve the problem?

**Comment by chamhaw** [comment]
@wy65701436

**Comment by chamhaw** [comment]
With the MR #6233, I changed the line `PGSQL_USR="postgres" to ` PGSQL_USR=${PGSQL_USR:-"postgres"} `. It seems works. After my migration, I will feed back here.

**Comment by chamhaw** [comment]
I got these errors.
```
TODO: add support for pgsql.
Performing upgrade head...
Traceback (most recent call last):
  File "/usr/bin/alembic", line 9, in <module>
    load_entry_point('alembic==1.0.5', 'console_scripts', 'alembic')()
  File "/usr/lib/python2.7/site-packages/alembic/config.py", line 503, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/lib/python2.7/site-packages/alembic/config.py", line 497, in main
    self.run_cmd(cfg, options)
  File "/usr/lib/python2.7/site-packages/alembic/config.py", line 480, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/usr/lib/python2.7/site-packages/alembic/command.py", line 469, in current
    script.run_env()
  File "/usr/lib/python2.7/site-packages/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/lib/python2.7/site-packages/alembic/util/compat.py", line 198, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "/harbor-migration/db/alembic/postgres/migration_harbor/env.py", line 70, in <module>
    run_migrations_online()
  File "/harbor-migration/db/alembic/postgres/migration_harbor/env.py", line 58, in run_migrations_online
    with connectable.connect() as connection:
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2102, in connect
    return self._connection_cls(self, **kwargs)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 90, in __init__
    if connection is not None else engine.raw_connection()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2188, in raw_connection
    self.pool.unique_connection, _connection)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
    e, dialect, self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
    exc_info
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 342, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 788, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 529, in checkout
    rec = pool._do_get()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1284, in _do_get
    return self._create_connection()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 347, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 474, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 671, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 412, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/lib/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "pgtest"
 (Background on this error at: http://sqlalche.me/e/e3q8)
Traceback (most recent call last):
  File "/usr/bin/alembic", line 9, in <module>
    load_entry_point('alembic==1.0.5', 'console_scripts', 'alembic')()
  File "/usr/lib/python2.7/site-packages/alembic/config.py", line 503, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/lib/python2.7/site-packages/alembic/config.py", line 497, in main
    self.run_cmd(cfg, options)
  File "/usr/lib/python2.7/site-packages/alembic/config.py", line 480, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/usr/lib/python2.7/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/usr/lib/python2.7/site-packages/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/lib/python2.7/site-packages/alembic/util/compat.py", line 198, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "/harbor-migration/db/alembic/postgres/migration_harbor/env.py", line 70, in <module>
    run_migrations_online()
  File "/harbor-migration/db/alembic/postgres/migration_harbor/env.py", line 58, in run_migrations_online
    with connectable.connect() as connection:
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2102, in connect
    return self._connection_cls(self, **kwargs)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 90, in __init__
    if connection is not None else engine.raw_connection()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2188, in raw_connection
    self.pool.unique_connection, _connection)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
    e, dialect, self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
    exc_info
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 342, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 788, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 529, in checkout
    rec = pool._do_get()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1284, in _do_get
    return self._create_connection()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 347, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 474, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 671, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 412, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/lib/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "pgtest"
 (Background on this error at: http://sqlalche.me/e/e3q8)
Traceback (most recent call last):
  File "/usr/bin/alembic", line 9, in <module>
    load_entry_point('alembic==1.0.5', 'console_scripts', 'alembic')()
  File "/usr/lib/python2.7/site-packages/alembic/config.py", line 503, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/lib/python2.7/site-packages/alembic/config.py", line 497, in main
    self.run_cmd(cfg, options)
  File "/usr/lib/python2.7/site-packages/alembic/config.py", line 480, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/usr/lib/python2.7/site-packages/alembic/command.py", line 469, in current
    script.run_env()
  File "/usr/lib/python2.7/site-packages/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/lib/python2.7/site-packages/alembic/util/compat.py", line 198, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "/harbor-migration/db/alembic/postgres/migration_harbor/env.py", line 70, in <module>
    run_migrations_online()
  File "/harbor-migration/db/alembic/postgres/migration_harbor/env.py", line 58, in run_migrations_online
    with connectable.connect() as connection:
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2102, in connect
    return self._connection_cls(self, **kwargs)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 90, in __init__
    if connection is not None else engine.raw_connection()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2188, in raw_connection
    self.pool.unique_connection, _connection)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
    e, dialect, self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
    exc_info
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 342, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 788, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 529, in checkout
    rec = pool._do_get()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1284, in _do_get
    return self._create_connection()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 347, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 474, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 671, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 412, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/lib/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "pgtest"
 (Background on this error at: http://sqlalche.me/e/e3q8)
Upgrade performed.
```
But I got a successful connection to pgsql before these errors happened. 
```
CREATE TABLE
psql (9.6.10, server 9.6.2)
You are now connected to database "registry" as user "pgtest".
```

**Comment by chamhaw** [comment]
I installed v1.6.3, everything is ok but adminserver cannot start.
```
Jan  8 17:13:11 192.168.160.1 adminserver[27751]: 2019-01-08T09:13:11Z [INFO] initializing system configurations...
Jan  8 17:13:11 192.168.160.1 adminserver[27751]: 2019-01-08T09:13:11Z [FATAL] [main.go:46]: failed to initialize the system: unexpected EOF
Jan  8 17:13:18 192.168.160.1 adminserver[27751]: 2019-01-08T09:13:18Z [INFO] initializing system configurations...
Jan  8 17:13:18 192.168.160.1 adminserver[27751]: 2019-01-08T09:13:18Z [FATAL] [main.go:46]: failed to initialize the system: unexpected EOF
Jan  8 17:13:31 192.168.160.1 adminserver[27751]: 2019-01-08T09:13:31Z [INFO] initializing system configurations...
Jan  8 17:13:31 192.168.160.1 adminserver[27751]: 2019-01-08T09:13:31Z [FATAL] [main.go:46]: failed to initialize the system: unexpected EOF
```

**Comment by vasartori** [comment]
seems a auth problem.
`FATAL:  password authentication failed for user "pgtest" (Background on this error at: http://sqlalche.me/e/e3q8) `

I need to take a look on code to try find where the password is defined.
Currently I'm not working with harbor, so I not have so much time to deal with this issue...

**Comment by wy65701436** [comment]
Can you please upload the harbor log after the upgrade?

Yes, the migrator doesn’t support remote DB migration, you have to do it at the node of DB.

**Comment by chamhaw** [comment]
After upgrading, I updated `harbor.cfg` manually to change the db info such as host and password from mysql to pgsql. Then I ran `prepare` and `install.sh` step by step.

It seems that mysql data have already been migrate to pgsql. But a Dirty Database version errors.
```
Jan  9 10:09:37 192.168.240.1 adminserver[27751]: 2019-01-09T02:09:37Z [ERROR] [pgsql.go:118]: Failed to upgrade schema, error: "Dirty database version 1. Fix and force version."
Jan  9 10:09:37 192.168.240.1 adminserver[27751]: 2019-01-09T02:09:37Z [FATAL] [main.go:46]: failed to initialize the system: Dirty database version 1. Fix and force version.
```

[harbor.zip](https://github.com/goharbor/harbor/files/2739115/harbor.zip)

**Comment by wy65701436** [comment]
please refer to the issue https://github.com/goharbor/harbor/issues/6590, and the fix is in the v1.7.1.

**Comment by chamhaw** [comment]
May I upgrade straightly to v1.7.1 now to fix this issue? Current version is v1.6.3 with problems.

**Comment by wy65701436** [comment]
sure, just install the v1.7.1 and migrate your harbor.cfg, from v1.6.3 to v1.7,1, there is no need to migrade DB scheme.

**Comment by chamhaw** [comment]
Finally, I installed a fresh v1.7.1, and migrated data from mysql to pgsql manually with insert sql.
It works now.
**Attention: The harbor authorization api has been refactored. e.g. The api /login changed to /c/login.**

**Comment by reasonerjt** [comment]
Thanks, glad to hear it works.
