### ISSUE TITLE
upgrade issue to v1.7.1 from v1.7.0

### ISSUE THREAD

**Issue by jeon710** [goharbor/harbor#6844]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
3 weeks ago, I setup harbor v1.7.0 by using offline installer.
And then, I tried harbor migration by ferering migration menual.
https://github.com/goharbor/harbor/blob/master/docs/migration_guide.md

But it is not work.

> docker run -it --rm -v /home/obs/harbor_1.7.0/harbor_cfg:/harbor-migration/harbor-cfg/harbor.cfg goharbor/harbor-migrator:v1.7.1 --cfg up
Please backup before upgrade,
Enter y to continue updating or n to abort: y
Traceback (most recent call last):
  File "./migrator.py", line 232, in <module>
    main()
  File "./migrator.py", line 178, in main
    db_migrator = DBMigrator(commandline_input.target_version)
  File "./migrator.py", line 34, in __init__
    conf.write(open(path).read())
IOError: [Errno 21] Is a directory: '/harbor-migration/harbor-cfg/harbor.cfg'

Could you give me advice?

**Steps to reproduce the problem:**

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.7.0]
- docker engine version: [1.13.1]
- docker-compose version: [1.16.1]

**Comment by wy65701436** [comment]
@jeon710 no need to upgrade harbor.cfg from 1.7.0 to 1.7.1.

You just need to install the v1.7.1 with the harbor.cfg of v1.7.0, that all for your upgrade scenario.

**Comment by jeon710** [comment]
Oh, I just executed install.sh on v1.7.1 offline installer and it works.
Thanks :)
