### ISSUE TITLE
core can't start

### ISSUE THREAD

**Issue by ledboot** [goharbor/harbor#6936]
Install harbor complete, The CORE can't start. here is core log:

```
Feb 15 11:01:54 172.18.0.1 core[2046]: 2019-02-15T03:01:54Z [INFO] Config path: /etc/core/app.conf
Feb 15 11:01:54 172.18.0.1 core[2046]: 2019-02-15T03:01:54Z [INFO] initializing configurations...
Feb 15 11:01:54 172.18.0.1 core[2046]: 2019-02-15T03:01:54Z [INFO] key path: /etc/core/key
Feb 15 11:01:54 172.18.0.1 core[2046]: 2019-02-15T03:01:54Z [INFO] initializing client for adminserver http://adminserver:8080 ...
Feb 15 11:01:54 172.18.0.1 core[2046]: 2019-02-15T03:01:54Z [INFO] initializing the project manager based on local database...
Feb 15 11:01:54 172.18.0.1 core[2046]: 2019-02-15T03:01:54Z [INFO] configurations initialization completed
Feb 15 11:01:54 172.18.0.1 core[2046]: 2019-02-15T03:01:54Z [INFO] Registering database: type-PostgreSQL host-100.69.237.13 port-7666 databse-registry sslmode-"disable"
Feb 15 11:01:54 172.18.0.1 core[2046]: [ORM]2019/02/15 03:01:54 Detect DB timezone: PRC open /usr/local/go/lib/time/zoneinfo.zip: no such file or directory
Feb 15 11:01:54 172.18.0.1 core[2046]: 2019-02-15T03:01:54Z [INFO] Register database completed
Feb 15 11:01:54 172.18.0.1 core[2046]: 2019-02-15T03:01:54Z [INFO] User id: 1 already has its encrypted password.
Feb 15 11:01:54 172.18.0.1 core[2046]: 2019-02-15T03:01:54Z [INFO] Because SYNC_REGISTRY set false , no need to sync registry
Feb 15 11:01:54 172.18.0.1 core[2046]: 2019-02-15T03:01:54Z [INFO] Init proxy
Feb 15 11:01:54 172.18.0.1 core[2046]: panic: ERR invalid password
Feb 15 11:01:54 172.18.0.1 core[2046]:
Feb 15 11:01:54 172.18.0.1 core[2046]: goroutine 1 [running]:
Feb 15 11:01:54 172.18.0.1 core[2046]: github.com/goharbor/harbor/src/vendor/github.com/astaxie/beego.initBeforeHTTPRun()
Feb 15 11:01:54 172.18.0.1 core[2046]: #011/go/src/github.com/goharbor/harbor/src/vendor/github.com/astaxie/beego/beego.go:83 +0x111
Feb 15 11:01:54 172.18.0.1 core[2046]: github.com/goharbor/harbor/src/vendor/github.com/astaxie/beego.Run(0x0, 0x0, 0x0)
Feb 15 11:01:54 172.18.0.1 core[2046]: #011/go/src/github.com/goharbor/harbor/src/vendor/github.com/astaxie/beego/beego.go:55 +0x26
Feb 15 11:01:54 172.18.0.1 core[2046]: main.main()
Feb 15 11:01:54 172.18.0.1 core[2046]: #011/go/src/github.com/goharbor/harbor/src/core/main.go:156 +0x877
```

i don't know what password it mean:

```
panic: ERR invalid password
```

i find the source code, and set `admin_initial_password` into this file`common/templates/core/env`

```
func InitialAdminPassword() (string, error) {
	cfg, err := mg.Get()
	if err != nil {
		return "", err
	}
	return utils.SafeCastString(cfg[common.AdminInitialPassword]), nil
}
```
`common/templates/core/env`:

```
LOG_LEVEL=debug
CONFIG_PATH=/etc/core/app.conf
CORE_SECRET=$core_secret
JOBSERVICE_SECRET=$jobservice_secret
ADMINSERVER_URL=$adminserver_url
UAA_CA_ROOT=/etc/core/certificates/uaa_ca.pem
_REDIS_URL=$redis_host:$redis_port,100,$redis_password
SYNC_REGISTRY=false
CHART_CACHE_DRIVER=$chart_cache_driver
_REDIS_URL_REG=$redis_url_reg
ADMIN_INITIAL_PASSWORD=Harbor12345
```

reinstall harbor, the problem can not be fix.

**Comment by ledboot** [comment]
redis password invalid .
