### ISSUE TITLE
1.7.4 offline invalid username and password

### ISSUE THREAD

**Issue by Ad-Vitam** [goharbor/harbor#7196]
On a fresh install with harbor-offline-installer-v1.7.4.tgz

When i try to login : invalid username and password

harbor-jobservice and harbor-core restart every 60s
I dont understand why, have you some idea ?

```
# docker ps
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS                          PORTS                                                              NAMES
e454a8a58caf        goharbor/nginx-photon:v1.7.4             "nginx -g 'daemon ofâ¦"   About an hour ago   Up About an hour (healthy)      0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:4443->4443/tcp   nginx
30f646c03cda        goharbor/harbor-portal:v1.7.4            "nginx -g 'daemon ofâ¦"   About an hour ago   Up About an hour (healthy)      80/tcp                                                             harbor-portal
d48cc99d791d        goharbor/harbor-jobservice:v1.7.4        "/harbor/start.sh"       About an hour ago   Up 32 seconds                                                                                      harbor-jobservice
c0fc24120529        goharbor/harbor-core:v1.7.4              "/harbor/start.sh"       About an hour ago   Restarting (2) 23 seconds ago                                                                      harbor-core
262fd2004c5f        goharbor/registry-photon:v2.6.2-v1.7.4   "/entrypoint.sh /etcâ¦"   About an hour ago   Up About an hour (healthy)      5000/tcp                                                           registry
824191db7fa4        goharbor/harbor-adminserver:v1.7.4       "/harbor/start.sh"       About an hour ago   Up About an hour (healthy)                                                                         harbor-adminserver
7088adb95713        goharbor/harbor-registryctl:v1.7.4       "/harbor/start.sh"       About an hour ago   Up About an hour (healthy)                                                                         registryctl
4926e231ae35        goharbor/harbor-db:v1.7.4                "/entrypoint.sh postâ¦"   About an hour ago   Up About an hour (healthy)      5432/tcp                                                           harbor-db
d21221269283        goharbor/redis-photon:v1.7.4             "docker-entrypoint.sâ¦"   About an hour ago   Up About an hour                6379/tcp                                                           redis
6a602ce0d2fe        goharbor/harbor-log:v1.7.4               "/bin/sh -c /usr/locâ¦"   About an hour ago   Up About an hour (unhealthy)    127.0.0.1:1514->10514/tcp                                          harbor-log
```

```
# cat /var/log/harbor/core.log
Mar 21 16:37:35 172.18.0.1 core[9097]: 2019-03-21T15:37:35Z [INFO] Config path: /etc/core/app.conf
Mar 21 16:37:35 172.18.0.1 core[9097]: 2019-03-21T15:37:35Z [INFO] initializing configurations...
Mar 21 16:37:35 172.18.0.1 core[9097]: 2019-03-21T15:37:35Z [INFO] key path: /etc/core/key
Mar 21 16:37:35 172.18.0.1 core[9097]: 2019-03-21T15:37:35Z [INFO] initializing client for adminserver http://adminserver:8080 ...
Mar 21 16:37:35 172.18.0.1 core[9097]: 2019-03-21T15:37:35Z [INFO] initializing the project manager based on local database...
Mar 21 16:37:35 172.18.0.1 core[9097]: 2019-03-21T15:37:35Z [INFO] configurations initialization completed
Mar 21 16:37:35 172.18.0.1 core[9097]: 2019-03-21T15:37:35Z [INFO] Registering database: type-PostgreSQL host-postgresql port-5432 databse-registry sslmode-"disable"
Mar 21 16:37:35 172.18.0.1 core[9097]: 2019-03-21T15:37:35Z [INFO] Register database completed
Mar 21 16:37:35 172.18.0.1 core[9097]: 2019-03-21T15:37:35Z [INFO] User id: 1 already has its encrypted password.
Mar 21 16:37:35 172.18.0.1 core[9097]: 2019-03-21T15:37:35Z [INFO] Because SYNC_REGISTRY set false , no need to sync registry
Mar 21 16:37:35 172.18.0.1 core[9097]: 2019-03-21T15:37:35Z [INFO] Init proxy
Mar 21 16:37:35 172.18.0.1 core[9097]: panic: ERR Client sent AUTH, but no password is set
Mar 21 16:37:35 172.18.0.1 core[9097]:
Mar 21 16:37:35 172.18.0.1 core[9097]: goroutine 1 [running]:
Mar 21 16:37:35 172.18.0.1 core[9097]: github.com/goharbor/harbor/src/vendor/github.com/astaxie/beego.initBeforeHTTPRun()
Mar 21 16:37:35 172.18.0.1 core[9097]: #011/go/src/github.com/goharbor/harbor/src/vendor/github.com/astaxie/beego/beego.go:83 +0x111
Mar 21 16:37:35 172.18.0.1 core[9097]: github.com/goharbor/harbor/src/vendor/github.com/astaxie/beego.Run(0x0, 0x0, 0x0)
Mar 21 16:37:35 172.18.0.1 core[9097]: #011/go/src/github.com/goharbor/harbor/src/vendor/github.com/astaxie/beego/beego.go:55 +0x26
Mar 21 16:37:35 172.18.0.1 core[9097]: main.main()
Mar 21 16:37:35 172.18.0.1 core[9097]: #011/go/src/github.com/goharbor/harbor/src/core/main.go:156 +0x877


```

```
#cat /var/log/harbor/jobservice.log
Mar 21 16:38:36 172.18.0.1 jobservice[9097]: 2019-03-21T15:38:36Z [ERROR] [context.go:86]: Job context initialization error: Get http://core:8080/api/configs: dial tcp: lookup core on 127.0.0.11:53: server misbehaving
Mar 21 16:38:36 172.18.0.1 jobservice[9097]: 2019-03-21T15:38:36Z [FATAL] [bootstrap.go:79]: Failed to initialize job context: job context initialization error: Get http://core:8080/api/configs: dial tcp: lookup core on 127.0.0.11:53: server misbehaving (5 times tried)
Mar 21 16:38:38 172.18.0.1 jobservice[9097]: 2019-03-21T15:38:38Z [INFO] 0 outdated log entries are sweepped by sweeper *sweeper.FileSweeper
Mar 21 16:38:38 172.18.0.1 jobservice[9097]: 2019-03-21T15:38:38Z [ERROR] [context.go:86]: Job context initialization error: Get http://core:8080/api/configs: dial tcp: lookup core on 127.0.0.11:53: server misbehaving
Mar 21 16:38:38 172.18.0.1 jobservice[9097]: 2019-03-21T15:38:38Z [INFO] Retry in 9 seconds
Mar 21 16:38:47 172.18.0.1 jobservice[9097]: 2019-03-21T15:38:47Z [ERROR] [context.go:86]: Job context initialization error: Get http://core:8080/api/configs: dial tcp: lookup core on 127.0.0.11:53: server misbehaving
Mar 21 16:38:47 172.18.0.1 jobservice[9097]: 2019-03-21T15:38:47Z [INFO] Retry in 13 seconds
Mar 21 16:39:00 172.18.0.1 jobservice[9097]: 2019-03-21T15:39:00Z [ERROR] [context.go:86]: Job context initialization error: Get http://core:8080/api/configs: dial tcp: lookup core on 127.0.0.11:53: server misbehaving
Mar 21 16:39:00 172.18.0.1 jobservice[9097]: 2019-03-21T15:39:00Z [INFO] Retry in 19 seconds
Mar 21 16:39:19 172.18.0.1 jobservice[9097]: 2019-03-21T15:39:19Z [ERROR] [context.go:86]: Job context initialization error: Get http://core:8080/api/configs: dial tcp: lookup core on 127.0.0.11:53: server misbehaving
Mar 21 16:39:19 172.18.0.1 jobservice[9097]: 2019-03-21T15:39:19Z [INFO] Retry in 29 seconds

```

```
# docker version
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:34:04 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```
  
  
```
# docker-compose version
docker-compose version 1.24.0-rc1, build 0f3d4dda
docker-py version: 3.7.0
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

```
# cat /etc/debian_version
9.8
```

**Comment by reasonerjt** [comment]
This error looks like an error from redis: 
`panic: ERR Client sent AUTH, but no password is set`

Did you customize the settings in redis?

**Comment by Ad-Vitam** [comment]
ok i see my mistake....
In harbor.cfg i have change the db_password for security reason and i do the same for redis_password.

Doing a fresh install changing db_password only is good, harbor login work well
Thanks for your support
i close the issue.
