### ISSUE TITLE
Unable to set external DB in harbor.yml

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#7531]
I uncomment the external_database, and add my DB settings. But get the following errors when to execute prepare.

`Traceback (most recent call last):
  File "main.py", line 62, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 31, in main
    config_dict = parse_yaml_config(conf)
  File "/usr/src/app/utils/configs.py", line 155, in parse_yaml_config
    config_dict['db_user'] = db_configs['username']
KeyError: 'username'`

**Comment by ninjadq** [comment]
fixed in #7591
