### ISSUE TITLE
./install.sh harbor error

### ISSUE THREAD

**Issue by HanaForward** [goharbor/harbor#7991]
[root@harbor]# python -V
Python 2.7.5

[root@harbor]# ./install.sh

[Step 0]: checking installation environment ...

Note: docker version: 18.09.6

Note: docker-compose version: 1.24.0

[Step 1]: preparing environment ...
prepare base dir is set to /root/harbor
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 31, in main
    config_dict = parse_yaml_config(conf)
  File "/usr/src/app/utils/configs.py", line 55, in parse_yaml_config
    configs = yaml.load(f)
  File "/usr/lib/python3.6/site-packages/yaml/__init__.py", line 73, in load
    return loader.get_single_data()
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3.6/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3.6/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python3.6/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3.6/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/lib/python3.6/site-packages/yaml/scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "/usr/lib/python3.6/site-packages/yaml/scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/usr/lib/python3.6/site-packages/yaml/scanner.py", line 292, in stale_possible_simple_keys
    "could not find expected ':'", self.get_mark())
yaml.scanner.ScannerError: while scanning a simple key
  in "/input/harbor.yml", line 8, column 1
could not find expected ':'
  in "/input/harbor.yml", line 9, column 3

**Comment by HanaForward** [comment]
[root@harbor]# docker-compose -v
docker-compose version 1.24.0, build 0aa59064

**Comment by HanaForward** [comment]
[root@harbor]# docker -v
Docker version 18.09.6, build 481bc77156

**Comment by HanaForward** [comment]
i know the error

**Comment by sikujua** [comment]
How was this resolved

**Comment by jakubpartyka** [comment]
> i know the error

Apparently, it's a good thing to share with others what was causing the error once you locate it.

**Comment by HanaForward** [comment]
@jakubpartyka 
i forgot it。。。。

**Comment by HanaForward** [comment]
From the error report, there should be a problem with the configuration file
