### ISSUE TITLE
Job service runtime error Help

### ISSUE THREAD

**Issue by SweeXordious** [goharbor/harbor#8355]
Hello,

while i was trying the [jobservice](https://github.com/goharbor/harbor/tree/master/src/jobservice), i build it using the command `go build -a -o jobservice` then export the _CORE_SECRET_ using `export CORE_SECRET=authorization_Token_I_Got_From_ApiExplorer` then when i run `./jobservice -c config.yml` i get the following errors:

`panic: runtime error: index out of range`

`goroutine 1 [running]:`

`github.com/goharbor/harbor/src/common/utils/log.line(0x4, 0x25, 0xc00015bf08)`

	`/home/a/go/harbor-master/src/common/utils/log/logger.go:282 +0x1cf`

`github.com/goharbor/harbor/src/common/utils/log.(*Logger).getLine(...)`

	`/home/a/go/harbor-master/src/common/utils/log/logger.go:221`

`github.com/goharbor/harbor/src/common/utils/log.(*Logger).Infof(0xc000084080, 0x1480335, 0x25, 0xc00015bf08, 0x1, 0x1)`

	`/home/a/go/harbor-master/src/common/utils/log/logger.go:162 +0x1be`

`github.com/goharbor/harbor/src/common/utils/log.Infof(...)`

	`/home/a/go/harbor-master/src/common/utils/log/logger.go:241`

`github.com/goharbor/harbor/src/replication/adapter/native.init.0()`

	`/home/a/go/harbor-master/src/replication/adapter/native/adapter.go:42 +0x13c`

I've made no changes to the code or anything, i was just trying to get familiar with it.
Im using go 1.12.7 with GOPATH set to `/home/a/go`.

**Comment by SweeXordious** [comment]
I got past this using the following:
1) changed line 282 of `src/common/utils/log/logger.go` from `file=l[1]` to `file=l[0]`. Seems like it was searching for some file that didnt exist.
2) did the following exports:
- `export JOBSERVICE_SECRET=Key_From_API_Explorer`. I took the key from the requests : `curl -H "authorization: Basic Key"` on the API explorer after logging in as admin.
- `export CORE_URL="http://url_of_harbor_without_the_"/"_in_the_end"`, because iam using the http configuration.. i had to change that in the `config.yml` of JobServices as well.


Now, when i run `./jobservice -c config.yml -alsologtostderr` im stuck with this:

`2019-07-22T07:48:38-07:00 [INFO] [/home/a/go/harbor-master/src/common/config/store/driver/rest.go:24]: get configuration from url: http://192.168.252.141/api/internal/configurations`

`2019-07-22T07:48:38-07:00 [ERROR] [/home/a/go/harbor-master/src/common/config/store/driver/rest.go:27]: Failed on load rest config err:http error: code 401, message {"code":401,"message":"UnAuthorized"}, url:http://192.168.252.141/api/internal/configurations`

`2019-07-22T07:48:38-07:00 [ERROR] [/home/a/go/harbor-master/src/jobservice/job/impl/context.go:70]: Job context initialization error: failed to load rest config`

**Comment by SweeXordious** [comment]
After commenting some authentication/loading/verifications... code, i ended up seeing logs similar to those of `/etc/log/harbor/jobservices.log` which means i was trying to run a service that's already up ... 

Now i know that `make all` runs it automatically, Why do i always end up getting the `404 Not found` response whenever i make an api call as specified in [jobservices](https://github.com/goharbor/harbor/tree/master/src/jobservice) ?
