### ISSUE TITLE
Chartmuseum panic causes replication failure

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#8543]
When replicating all charts from Helm Hub to Harbor(thousands of tasks), some of the tasks failed with error:
```
2019-08-02T04:02:04Z [ERROR] [/replication/transfer/chart/transfer.go:138]: failed to check the existence of chart stable/prometheus-operator:2.1.6 on the destination registry: http error: code 500, message {"code":500,"message":"Internal Server Error"}
```

Checking the log of core, got error:
```
Aug  1 21:02:04 192.168.16.1 core[1188]: 2019-08-02T04:02:04Z [ERROR] [/common/api/base.go:195]: fail to get chart version: get content failed: send request GET /api/stable/charts/prometheus-operator/2.1.6 failed: Get http://chartmuseum:9999/api/stable/charts/prometheus-operator/2.1.6: dial tcp 192.168.64.3:9999: connect: connection refused
Aug  1 21:02:04 192.168.16.1 core[1188]: 2019-08-02T04:02:04Z [ERROR] [/common/api/base.go:228]: 
Aug  1 21:02:04 192.168.16.1 core[1188]: 2019-08-02T04:02:04Z [ERROR] [/common/api/base.go:68]: GET /api/chartrepo/stable/charts/prometheus-operator/2.1.6 failed with error: {"code":500,"message":"Internal Server Error"}
```

Checking the logs of chartmuseum, found that it panic and restarted. Got error:
```
Aug  1 21:02:04 192.168.16.1 chartmuseum[1188]: panic: Key "requestid" does not exist
Aug  1 21:02:04 192.168.16.1 chartmuseum[1188]: 
Aug  1 21:02:04 192.168.16.1 chartmuseum[1188]: goroutine 44274 [running]:
Aug  1 21:02:04 192.168.16.1 chartmuseum[1188]: github.com/gin-gonic/gin.(*Context).MustGet(...)
Aug  1 21:02:04 192.168.16.1 chartmuseum[1188]: #011/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/context.go:217
Aug  1 21:02:04 192.168.16.1 chartmuseum[1188]: helm.sh/chartmuseum/pkg/chartmuseum/logger.transformLogcArgs(0xc00bcd2000, 0xc0061545d0, 0x29, 0xc0079e8a00, 0x2, 0x2, 0xc0079e8a00, 0xc000044046, 0xe, 0xc0003e6e00, ...)
Aug  1 21:02:04 192.168.16.1 chartmuseum[1188]: #011/go/src_code/pkg/chartmuseum/logger/logger.go:122 +0x36e
Aug  1 21:02:04 192.168.16.1 chartmuseum[1188]: helm.sh/chartmuseum/pkg/chartmuseum/logger.(*Logger).Debugc(0xc0003f6158, 0xc00bcd2000, 0x157a297, 0x21, 0xc0079e8a00, 0x2, 0x2)
Aug  1 21:02:04 192.168.16.1 chartmuseum[1188]: #011/go/src_code/pkg/chartmuseum/logger/logger.go:96 +0x6d
Aug  1 21:02:04 192.168.16.1 chartmuseum[1188]: helm.sh/chartmuseum/pkg/chartmuseum/logger.(*Logger).ContextLoggingFn.func1(0x155575e, 0x5, 0x157a297, 0x21, 0xc0079e8a00, 0x2, 0x2)
Aug  1 21:02:04 192.168.16.1 chartmuseum[1188]: #011/go/src_code/pkg/chartmuseum/logger/logger.go:83 +0x1d8
Aug  1 21:02:04 192.168.16.1 chartmuseum[1188]: helm.sh/chartmuseum/pkg/chartmuseum/server/multitenant.(*MultiTenantServer).saveStatefile(0xc0004010e0, 0xc00741e7c0, 0xc00610f549, 0x6, 0xc01ffac000, 0x403396, 0x470000)
Aug  1 21:02:04 192.168.16.1 chartmuseum[1188]: #011/go/src_code/pkg/chartmuseum/server/multitenant/index.go:94 +0x1b8
Aug  1 21:02:04 192.168.16.1 chartmuseum[1188]: created by helm.sh/chartmuseum/pkg/chartmuseum/server/multitenant.(*MultiTenantServer).getIndexFile
Aug  1 21:02:04 192.168.16.1 chartmuseum[1188]: #011/go/src_code/pkg/chartmuseum/server/multitenant/index.go:80 +0x729
```

**Comment by ywk253100** [comment]
After hacking the chartmuseum to get rid of the panic error and re-run the replication, got a lot of timeout errors as below:
```
Aug  8 23:55:59 172.28.0.1 core[1188]: 2019-08-09T06:55:59Z [ERROR] [/common/api/base.go:195]: fail to get chart version: get content failed: send request GET /api/stable/charts/prometheus/8.4.2 failed: Get http://chartmuseum:9999/api/stable/charts/prometheus/8.4.2: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

The root cause in the Harbor side is the default timeout(10 seconds) is too short, set it to 0(means no timeout) can fix it. So maybe we should consider to longer the timeout.

**Comment by ywk253100** [comment]
@reasonerjt The chart replication works well when not replicate so many charts(thousands of charts)

**Comment by reasonerjt** [comment]
@ywk253100 let's open an issue to chartmuseum and see what Josh thinks about it.

**Comment by duyanghao** [comment]
So the problem seems to be `chartmuseum`, right?
I create a relevant [issue](https://github.com/helm/chartmuseum/issues/266) in chartmuseum.

**Comment by kycheng** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

I had a similar problem, but not the same one.

harbor 2.6.4

```
113 {"L":"INFO","T":"2023-06-13T10:23:01.825Z","M":"[109] Request served","path":"/project-0325/index.yaml","comment":"","clientIP":"10.51.0.236","method":"GET","statusCode    ":200,"latency":"8.968067ms","reqID":"d39efdb4-7502-4f73-a278-afedc28cae50"}
114 {"L":"INFO","T":"2023-06-13T10:23:01.826Z","M":"[110] Request served","path":"/project-0328/index.yaml","comment":"","clientIP":"10.51.0.236","method":"GET","statusCode    ":200,"latency":"9.312801ms","reqID":"49b86c82-026f-4798-b68f-0165830dba42"}
115 {"L":"INFO","T":"2023-06-13T10:23:01.826Z","M":"[111] Request served","path":"/project-0707/index.yaml","comment":"","clientIP":"10.51.0.236","method":"GET","statusCode    ":200,"latency":"2.975355ms","reqID":"09eefde9-866c-48f0-b185-4bb647c914b6"}
116 fatal error: concurrent map read and map write
117
118 goroutine 228 [running]:
119 helm.sh/chartmuseum/pkg/chartmuseum/server/multitenant.(*MultiTenantServer).getChartList(0xc000c540d0, 0xc000d12900?, {0xc000d015c5, 0xc})
120     /go/src_code/pkg/chartmuseum/server/multitenant/cache.go:97 +0x87
121 helm.sh/chartmuseum/pkg/chartmuseum/server/multitenant.(*MultiTenantServer).getIndexFile(0xc000c540d0, 0xc000d12900, {0xc000d015c5, 0xc})
122     /go/src_code/pkg/chartmuseum/server/multitenant/index.go:45 +0xb8
123 helm.sh/chartmuseum/pkg/chartmuseum/server/multitenant.(*MultiTenantServer).getIndexFileRequestHandler(0xc000c540d0, 0xc0006b6100)
124     /go/src_code/pkg/chartmuseum/server/multitenant/handlers.go:100 +0x85
125 helm.sh/chartmuseum/pkg/chartmuseum/router.(*Router).rootHandler(0xc000623600, 0xc0006b6100)
126     /go/src_code/pkg/chartmuseum/router/router.go:249 +0x25e
127 github.com/gin-gonic/gin.(*Context).Next(...)
128     /go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168
129 github.com/zsais/go-gin-prometheus.(*Prometheus).HandlerFunc.func1(0xc0006b6100)
130     /go/pkg/mod/github.com/zsais/go-gin-prometheus@v0.1.0/middleware.go:364 +0xd5
131 github.com/gin-gonic/gin.(*Context).Next(...)
132     /go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168
133 github.com/gin-contrib/size.RequestSizeLimiter.func1(0xc0006b6100)
134     /go/pkg/mod/github.com/gin-contrib/size@v0.0.0-20220102055520-f75bacbc2df3/size.go:88 +0xca
135 github.com/gin-gonic/gin.(*Context).Next(...)
136     /go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168
137 helm.sh/chartmuseum/pkg/chartmuseum/router.requestWrapper.func1(0xc0006b6100)
138     /go/src_code/pkg/chartmuseum/router/middleware.go:48 +0x186
139 github.com/gin-gonic/gin.(*Context).Next(...)
140     /go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168
141 github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1(0xc0006b6100)
142     /go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/recovery.go:99 +0x82
143 github.com/gin-gonic/gin.(*Context).Next(...)
144     /go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168
145 github.com/gin-gonic/gin.serveError(0xc0006b6100, 0x194, {0x4231240, 0x12, 0x12})
146     /go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:591 +0x4d
147 github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0001036c0, 0xc0006b6100)
148     /go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:584 +0x485
149 github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0001036c0, {0x3189538?, 0xc000c90fc0}, 0xc000c85600)
150     /go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:511 +0x1d2
151 net/http.serverHandler.ServeHTTP({0xc000aea990?}, {0x3189538, 0xc000c90fc0}, 0xc000c85600)
152     /usr/local/go/src/net/http/server.go:2947 +0x30c
153 net/http.(*conn).serve(0xc00054a280, {0x318af80, 0xc000c51890})
154     /usr/local/go/src/net/http/server.go:1991 +0x607
155 created by net/http.(*Server).Serve
156     /usr/local/go/src/net/http/server.go:3102 +0x4db
```
