### ISSUE TITLE
harbor-migrator 从 1.7.x 升级 1.9.x 时模板有问题

### ISSUE THREAD

**Issue by abel533** [goharbor/harbor#9146]
由于 1.7.x 版本的 harbar.cfg 中不存在下面的相关的配置:
```yml
chart:
  absolute_url: disabled
```

从 1.7.x 升级到 1.8.0 时正常，在从 1,8.0 升级 1.9.0 时，由于 https://github.com/goharbor/harbor/blob/master/tools/migration/cfg/migrator_1_9_0/harbor.yml.jinja 模板中使用了 chart 导致升级失败。

解决办法，在升级到 1.8.0 时，https://github.com/goharbor/harbor/blob/master/tools/migration/cfg/migrator_1_8_0/harbor.yml.jinja 增加上面的默认配置。

**Comment by zhaowencheng1991** [comment]
当从 1.7.x 按照你的方法升级到，1.8.3之后，修改该完：

chart:
  absolute_url: disabled

然后在从1.8.3 升级到1.9.0 ，harbor.yml 也能够正常执行，但是在执行 install.sh 时，会报如下错误：

Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 36, in main
    prepare_nginx(config_dict)
  File "/usr/src/app/utils/nginx.py", line 23, in prepare_nginx
    render_nginx_template(config_dict)
  File "/usr/src/app/utils/nginx.py", line 56, in render_nginx_template
    prepare_nginx_certs(config_dict['cert_key_path'], config_dict['cert_path'])
  File "/usr/src/app/utils/nginx.py", line 42, in prepare_nginx_certs
    shutil.copy2(host_ngx_cert_key_path, real_key_path)
  File "/usr/lib/python3.6/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/hostfs/data/cert/x.pf.abc.com.key'


“ hostfs ” 似乎是1.9.0 新增的。 请问是否遇到？

**Comment by abel533** [comment]
升级到1.9.x失败，我目前只升级到了1.8.x

**Comment by abel533** [comment]
1.9.0 已经升级成功，需要自己手动在 1.8.x 添加上面的 `chart`.

**Comment by yke007** [comment]
18.0升级到1.9.0

执行docker run -it --rm -v /data/my__backup_harbor_1.8.0/harbor/harbor.yml:/harbor-migration/harbor-cfg/harbor.yml goharbor/harbor-migrator:v1.9.0 --cfg up
Please backup before upgrade,
Enter y to continue updating or n to abort: y
The path of the migrated harbor.cfg is not set, the input file will be overwritten.
Command for config file migration: python ./cfg/run.py --input /harbor-migration/harbor-cfg/harbor.yml
input version: 1.8.0, migrator chain: ['1.9.0']
migrating to version 1.9.0
Traceback (most recent call last):
  File "./cfg/run.py", line 70, in <module>
    main()
  File "./cfg/run.py", line 46, in main
    m.migrate(curr_input_path, curr_output_path)
  File "/harbor-migration/cfg/migrator_1_9_0/__init__.py", line 21, in migrate
    f.write(tpl.render(**config_dict))
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/harbor-migration/cfg/migrator_1_9_0/harbor.yml.jinja", line 8, in top-level template code
    {% if http %}
jinja2.exceptions.UndefinedError: 'http' is undefined

**Comment by reasonerjt** [comment]
dup of #9174 .  There's a PR #9806
