### ISSUE TITLE
Unable install harbor with proxy setting

### ISSUE THREAD

**Issue by rocenpe** [goharbor/harbor#9185]
- harbor version: 1.9.0
- docker engine version: 19.03.0
- docker-compose version: 1.24.1

I have problem install harbor 1.9.0 with proxy setting. If I run command sudo ./install.sh --with-clair
I give error:
prepare base dir is set to /home/procen/install/harbor
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 32, in main
    config_dict = parse_yaml_config(conf, with_notary=with_notary, with_clair=with_clair, with_chartmuseum=with_chartmuseum)
  File "/usr/src/app/utils/configs.py", line 66, in parse_yaml_config
    configs = yaml.load(f)
  File "/usr/lib/python3.6/site-packages/yaml/__init__.py", line 73, in load
    return loader.get_single_data()
  File "/usr/lib/python3.6/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3.6/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3.6/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python3.6/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3.6/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/lib/python3.6/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/lib/python3.6/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/lib/python3.6/site-packages/yaml/scanner.py", line 579, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "/input/harbor.yml", line 160, column 13
I am sending my harbor.yml attached
[harbor.zip](https://github.com/goharbor/harbor/files/3636955/harbor.zip)
Thank you for your help.
Blessing,
Petr

**Comment by pleasanceccdc** [comment]
your yml file is invalid you need a space after http_proxy: and https_proxy:

`  http_proxy: http://192.168.253.128:5865
  https_proxy: http://192.168.253.128:5865`

**Comment by rocenpe** [comment]
Hello Thomas,
thank you for your help. You are right, my mistake.
Blessings,
Petr
