### ISSUE TITLE
Upgrade 1.8.2 to 1.9.0 privkey error

### ISSUE THREAD

**Issue by CarTerr** [goharbor/harbor#9202]
1. docker run -it --rm -v /home/antony/harbor_back_23.09/harbor.yml:/harbor-migration/harbor-cfg/harbor.yml -v /home/antony/harbor/harbor.yml:/harbor-migration/harbor-cfg-out/harbor.yml goharbor/harbor-migrator:v1.9.0 --cfg up
2. ./install.sh
[Step 0]: checking installation environment ...

Note: docker version: 19.03.2

Note: docker-compose version: 1.24.0

[Step 1]: preparing environment ...
prepare base dir is set to /home/antony/harbor
Clearing the configuration file: /config/log/logrotate.conf
Clearing the configuration file: /config/log/rsyslog_docker.conf
Generated configuration file: /config/log/logrotate.conf
Generated configuration file: /config/log/rsyslog_docker.conf
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 36, in main
    prepare_nginx(config_dict)
  File "/usr/src/app/utils/nginx.py", line 23, in prepare_nginx
    render_nginx_template(config_dict)
  File "/usr/src/app/utils/nginx.py", line 56, in render_nginx_template
    prepare_nginx_certs(config_dict['cert_key_path'], config_dict['cert_path'])
  File "/usr/src/app/utils/nginx.py", line 42, in prepare_nginx_certs
    shutil.copy2(host_ngx_cert_key_path, real_key_path)
  File "/usr/lib/python3.6/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/hostfs/data/cert/privkey.pem'

Section https in harbor.yml
  port: 443
  certificate: /data/cert/cert.pem
  private_key: /data/cert/privkey.pem

certificate and key in /data/cert/ are present

**Comment by ninjadq** [comment]
is there a link in your file path?

**Comment by CarTerr** [comment]
yes, there is a link
```
 ls -l /data/cert/
total 0
lrwxrwxrwx 1 root root 52 июл 15 09:37 cert.pem -> /etc/letsencrypt/live/dc2.srvhub.tools/fullchain.pem
lrwxrwxrwx 1 root root 50 июл 15 09:37 privkey.pem -> /etc/letsencrypt/live/dc2.srvhub.tools/privkey.pem
```

**Comment by CarTerr** [comment]
How to solve it?
In 1.8 it worked
letsencrypt the certificate re-new automatically and changes the name of the files.

**Comment by alexcasutt** [comment]
We have the same issue and also use letsencrypt.
But I also tried it without a link in the path and get the same error..

**Comment by CarTerr** [comment]
I replaced the links with an files
```
ls -l /data/cert/
total 8
-rw-r--r-- 1 root root 3562 сен 26 05:47 cert.pem
-rw------- 1 root root 1704 сен 26 05:48 privkey.pem
```

And get same error
```
prepare base dir is set to /home/antony/harbor
Generated configuration file: /config/log/logrotate.conf
Generated configuration file: /config/log/rsyslog_docker.conf
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 36, in main
    prepare_nginx(config_dict)
  File "/usr/src/app/utils/nginx.py", line 23, in prepare_nginx
    render_nginx_template(config_dict)
  File "/usr/src/app/utils/nginx.py", line 56, in render_nginx_template
    prepare_nginx_certs(config_dict['cert_key_path'], config_dict['cert_path'])
  File "/usr/src/app/utils/nginx.py", line 42, in prepare_nginx_certs
    shutil.copy2(host_ngx_cert_key_path, real_key_path)
  File "/usr/lib/python3.6/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/hostfs/your/private/key/path'
```

**Comment by alexcasutt** [comment]
Hi, it seems that i got a workaround:
Edit the prepare-Script and add on the "docker run"-command the option --privileged.
`# Run prepare script
docker run --rm -v $input_dir:/input:z \
                    **--privileged** \
                    -v $data_path:/data:z \
                    -v $harbor_prepare_path:/compose_location:z \
                    -v $config_dir:/config:z \
                    -v $secret_dir:/secret:z \
                    -v /:/hostfs:z \
                    goharbor/prepare:v1.9.0 $@`

**Comment by CarTerr** [comment]
Thanks alexcasutt. That was very helpful
