### ISSUE TITLE
token auth requires at least one token signing root certificate

### ISSUE THREAD

**Issue by mattcamp** [goharbor/harbor#9250]
I'm attempting to use Harbor 1.9.0 inside a kubernetes cluster with a cert-manager/letsencrypt provided TLS cert which is stored in a secret however the notary-server and registry pods are both failling with message `token auth requires at least one token signing root certificate`.

Harbor was installed via the helm chart. 

values.yaml excerpt:

```
expose:
  type: clusterIP
  tls:
    enabled: true
    secretName: "harbor2-secret"
  ingress:
    hosts:
      core: core.harbor2.my.domain
      notary: notary.harbor2.my.domain
    controller: default
  clusterIP:
    name: harbor
    ports:
      httpPort: 80
      httpsPort: 443
      notaryPort: 4443
```

```
$ kubectl logs harbor2-harbor-notary-server-69894778d-bztnr
2019/09/24 14:25:24 Updating database.
2019/09/24 14:25:24 schema_migrations table does not require update, skip.
no change
notaryserver database migrated to latest version
{"level":"info","msg":"Version: 0.6.1, Git commit: d6e1431f","time":"2019-09-24T14:25:24Z"}
{"level":"info","msg":"Using remote signing service","time":"2019-09-24T14:25:24Z"}
{"level":"info","msg":"Using postgres backend","time":"2019-09-24T14:25:24Z"}
{"level":"info","msg":"Starting Server","time":"2019-09-24T14:25:24Z"}
{"level":"fatal","msg":"token auth requires at least one token signing root certificate","time":"2019-09-24T14:25:24Z"}
```

```
$ kubectl logs harbor2-harbor-registry-dcbcb9d75-pbq4k registry
time="2019-09-24T14:24:59.734439678Z" level=info msg="debug server listening localhost:5001"
time="2019-09-24T14:24:59.735324019Z" level=info msg="configuring endpoint harbor (http://harbor2-harbor-core/service/notifications), timeout=3s, headers=map[]" go.version=go1.11.8 instance.id=f4625998-d315-4884-94f0-bf1f8fbd5f7b service=registry version=v2.7.1
time="2019-09-24T14:24:59.749541951Z" level=info msg="using redis blob descriptor cache" go.version=go1.11.8 instance.id=f4625998-d315-4884-94f0-bf1f8fbd5f7b service=registry version=v2.7.1
panic: unable to configure authorization (token): token auth requires at least one token signing root certificate

goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp(0xff4ac0, 0xc00039ebd0, 0xc00049c000, 0x0)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:313 +0x2a06
github.com/docker/distribution/registry.NewRegistry(0xff4ac0, 0xc00039ebd0, 0xc00049c000, 0xe, 0x0, 0x0)
	/go/src/github.com/docker/distribution/registry/registry.go:105 +0x1dc
github.com/docker/distribution/registry.glob..func1(0x171ee40, 0xc000093d60, 0x1, 0x1)
	/go/src/github.com/docker/distribution/registry/registry.go:63 +0x187
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x171ee40, 0xc000093d20, 0x1, 0x1, 0x171ee40, 0xc000093d20)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x191
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x171efe0, 0xc00024bf88, 0xc000090058)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0x2f4
main.main()
	/go/src/github.com/docker/distribution/cmd/registry/main.go:23 +0x2d
```

```
kubectl get secret harbor2-secret -o yaml
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVrakNDQTNxZ0F3SUJBZ0lRQ2dGQlFnQUFBVk9GYzJvTGhleW5DREFOQmdrcWhraUc5dzBCQVFzRkFEQS8KTVNRd0lnWURWUVFLRXh0RWFXZHBkR0ZzSUZOcFoyNWhkSFZ5WlNCVWNuVnpkQ0JEYnk0eEZ6QVZCZ05WQkFNVApEa1JUVkNCU2IyOTBJRU5CSUZnek1CNFhEVEUyTURNeE56RTJOREEwTmxvWERUSXhNRE14TnpFMk5EQTBObG93ClNqRUxNQWtHQTFVRUJoTUNWVk14RmpBVUJnTlZCQW9URFV4bGRDZHpJRVZ1WTNKNWNIUXhJekFoQmdOVkJBTVQKR2t4bGRDZHpJRVZ1WTNKNWNIUWdRWFYwYUc5eWFYUjVJRmd6TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBbk5NTThGcmxMa2UzY2wwM2c3Tm9ZekRxMXpVbUdTWGh2YjQxOFhDU0w3ZTRTMEVGCnE2bWVOUWhZN0xFcXhHaUhDNlBqZGVUbTg2ZGljYnA1Z1dBZjE1R2FuL1BRZUdkeHlHa09sWkhQL3VhWjZXQTgKU014K3lrMTNFaVNkUnh0YTY3bnNIamNBSEp5c2U2Y0Y2czVLNjcxQjVUYVl1Y3Y5YlR5V2FOOGpLa0tRRElaMApaOGgvcFpxNFVtRVVFejlsNllLSHk5djZEbGIyaG9uemhUK1hocSt3M0JydmF3MlZGbjNFSzZCbHNwa0VObldBCmE2eEs4eHVRU1hndm9wWlBLaUFsS1FUR2RNRFFNYzJQTVRpVkZycW9NN2hEOGJFZnd6Qi9vbmt4RXowdE52amoKL1BJemFyazVNY1d2eEkwTkhXUVdNNnI2aENtMjFBdkEySDNEa3dJREFRQUJvNElCZlRDQ0FYa3dFZ1lEVlIwVApBUUgvQkFnd0JnRUIvd0lCQURBT0JnTlZIUThCQWY4RUJBTUNBWVl3ZndZSUt3WUJCUVVIQVFFRWN6QnhNRElHCkNDc0dBUVVGQnpBQmhpWm9kSFJ3T2k4dmFYTnlaeTUwY25WemRHbGtMbTlqYzNBdWFXUmxiblJ5ZFhOMExtTnYKYlRBN0JnZ3JCZ0VGQlFjd0FvWXZhSFIwY0RvdkwyRndjSE11YVdSbGJuUnlkWE4wTG1OdmJTOXliMjkwY3k5awpjM1J5YjI5MFkyRjRNeTV3TjJNd0h3WURWUjBqQkJnd0ZvQVV4S2V4cEhzc2NmcmI0VXVRZGYvRUZXQ0ZpUkF3ClZBWURWUjBnQkUwd1N6QUlCZ1puZ1F3QkFnRXdQd1lMS3dZQkJBR0MzeE1CQVFFd01EQXVCZ2dyQmdFRkJRY0MKQVJZaWFIUjBjRG92TDJOd2N5NXliMjkwTFhneExteGxkSE5sYm1OeWVYQjBMbTl5WnpBOEJnTlZIUjhFTlRBegpNREdnTDZBdGhpdG9kSFJ3T2k4dlkzSnNMbWxrWlc1MGNuVnpkQzVqYjIwdlJGTlVVazlQVkVOQldETkRVa3d1ClkzSnNNQjBHQTFVZERnUVdCQlNvU21wakJIM2R1dWJST2JlbVJXWHY4Nmpzb1RBTkJna3Foa2lHOXcwQkFRc0YKQUFPQ0FRRUEzVFBYRWZOaldEamRHQlg3Q1ZXK2RsYTVjRWlsYVVjbmU4SWtDSkx4V2g5S0VpazNKSFJSSEdKbwp1TTJWY0dmbDk2UzhUaWhSelp2b3JvZWQ2dGk2V3FFQm10enczV29kYXRnK1Z5T2VwaDRFWXByLzF3WEt0eDgvCndBcEl2SlN3dG1WaTRNRlU1YU1xclNERTZlYTczTWoydGNNeW81ak1kNmptZVdVSEs4c28vam9XVW9IT1Vnd3UKWDRQbzFRWXorM2RzemtEcU1wNGZrbHhCd1hSc1cxMEtYelBNVForc09QQXZleXhpbmRtamtXOGxHeStRc1JsRwpQZlorRzZaNmg3bWplbTBZK2lXbGtZY1Y0UElXTDFpd0JpOHNhQ2JHUzVqTjJwOE0rWCtRN1VOS0VrUk9iM042CktPcWtxbTU3VEgySDNlREpBa1NuaDYvRE5GdTBRZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZkekNDQkYrZ0F3SUJBZ0lTQXduOFF4YU9qR2JRRXlGMGFDcjIrYklVTUEwR0NTcUdTSWIzRFFFQkN3VUEKTUVveEN6QUpCZ05WQkFZVEFsVlRNUll3RkFZRFZRUUtFdzFNWlhRbmN5QkZibU55ZVhCME1TTXdJUVlEVlFRRApFeHBNWlhRbmN5QkZibU55ZVhCMElFRjFkR2h2Y21sMGVTQllNekFlRncweE9UQTVNalF4TVRVM01qWmFGdzB4Ck9URXlNak14TVRVM01qWmFNQjh4SFRBYkJnTlZCQU1URkdoaGNtSnZjakl1YzNCdmEyVmtaWFl1ZUhsNk1JSUIKSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTVjanA5ajhKSG5nODBielBRWXBES3gzawpEMlA1MG50S0RCVS9VZ0psOUVJd1U1Q2dnTXVRNmR1ak01Q0c0OEl4bERWQXlDeGRocnFQb1JiaWJDNHFSVjA1ClNaaFVlTzFrRVlNZEFoR1piTUxUWkpPdTZQclFyVGFUbzJJZFBwMHhXZnVtRXdKUkRtalROem5oc0ZJOXduNE8KRWxpUm5rWkpxZi82R0VDSWVTVksvZWpBZ05vZ2N1M1BJOXZQT0llTVA2dVZHczBZa0VsOCt5SUJ0bHlUZ245RQpqc20rZVNPYTV5VlV4eGxSeGVNcUMrT1FJZHZ0eEtJeXFGd2t1enc4K3hYTjlnUlV1bG9ucmFwYTNFK1JldjhmCk9wSzZ0SVNhUFA0bERPS1ltaXVyekpVc01veFZBRHNXeHNEWitGM3o4bFYzVjVqMnNyNnZPTWJVMEgxbStRSUQKQVFBQm80SUNnRENDQW53d0RnWURWUjBQQVFIL0JBUURBZ1dnTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQgpCZ2dyQmdFRkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUzRwK3hoeWIvR0pTNERGUGhhClJNaVN6a0I2aXpBZkJnTlZIU01FR0RBV2dCU29TbXBqQkgzZHV1YlJPYmVtUldYdjg2anNvVEJ2QmdnckJnRUYKQlFjQkFRUmpNR0V3TGdZSUt3WUJCUVVITUFHR0ltaDBkSEE2THk5dlkzTndMbWx1ZEMxNE15NXNaWFJ6Wlc1agpjbmx3ZEM1dmNtY3dMd1lJS3dZQkJRVUhNQUtHSTJoMGRIQTZMeTlqWlhKMExtbHVkQzE0TXk1c1pYUnpaVzVqCmNubHdkQzV2Y21jdk1EY0dBMVVkRVFRd01DNkNGaW91YUdGeVltOXlNaTV6Y0c5clpXUmxkaTU0ZVhxQ0ZHaGgKY21KdmNqSXVjM0J2YTJWa1pYWXVlSGw2TUV3R0ExVWRJQVJGTUVNd0NBWUdaNEVNQVFJQk1EY0dDeXNHQVFRQgpndDhUQVFFQk1DZ3dKZ1lJS3dZQkJRVUhBZ0VXR21oMGRIQTZMeTlqY0hNdWJHVjBjMlZ1WTNKNWNIUXViM0puCk1JSUJBd1lLS3dZQkJBSFdlUUlFQWdTQjlBU0I4UUR2QUhZQTRtbExyaWJvNlVBSjZJWWJ0anVEMUQ3bi9uU0kKKzZTUEtKTUJuZDN4Mi80QUFBRnRZMWthVFFBQUJBTUFSekJGQWlFQW9oNElZS1dPdDgwYnhFamJBajJMZzlELwp5SzZQUnRvdzRZVzVNK1VxeE40Q0lIRTlZUndlN0ZEYUJXL1JhSnRmdGFzVHBtckd3Q3AyemZlRkcwUm5UYjJWCkFIVUFLVHhSbGxUSU9XVzZxbEQ4V0FmVXQyKy9XSG9wY3R5a3d3ejA1VVZIOUhnQUFBRnRZMWthYkFBQUJBTUEKUmpCRUFpQU1IclFjd0xZbUxiZ29iM21NQUpjbHowVjNqRGxnYzJha1pNN0lVTXpPUXdJZ01KaGlZNkhOeks4NQo0MUxxby95eWNEdkZYQnBmVzhEcDNvTW00SzJzUWtJd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFEK0JmSENvCnNFQmtMd3NSb2FkdndONlVHc1E3a1JRa09kd1AzM1QvdGtJR2Z3NDJNNEE2YTFiaFdBR2t2VFUzWldMR1BxYVQKcXBIaitreTdPZUxqSHlxaWRNNDFaa21TQktnQTJ2am1JNUdiMnhuMzJkenBwZXQ5U3VuazZXdVhEQ1QyNHFLMApjZFBJS0dKQ2ZvVkZ1TTQ2Kzl0THdvNnhUbkptWTQ2WXF2ZjZBb0lhejVXbkFLaWJ1dDUxbDZvTTMvdWJYZW9kCnFUVm8rZTNxSTd3U3JOaUtjdVpReTdvZGlNdmV1UldqVTJjRjQ1eEg5N25RNjcwdVR5ZW5CZm9BNllHbjNnM0MKU3pqR1g1UnZDYmdTUUdvV0JIMXpScUN0aVAzWnVyd0I1WDU1YnBBVUdnaVFZbURLTHlHVXo4WWFJV2lOdUtrNgo2U2paOHN0M2tQcUxQaGs9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVrakNDQTNxZ0F3SUJBZ0lRQ2dGQlFnQUFBVk9GYzJvTGhleW5DREFOQmdrcWhraUc5dzBCQVFzRkFEQS8KTVNRd0lnWURWUVFLRXh0RWFXZHBkR0ZzSUZOcFoyNWhkSFZ5WlNCVWNuVnpkQ0JEYnk0eEZ6QVZCZ05WQkFNVApEa1JUVkNCU2IyOTBJRU5CSUZnek1CNFhEVEUyTURNeE56RTJOREEwTmxvWERUSXhNRE14TnpFMk5EQTBObG93ClNqRUxNQWtHQTFVRUJoTUNWVk14RmpBVUJnTlZCQW9URFV4bGRDZHpJRVZ1WTNKNWNIUXhJekFoQmdOVkJBTVQKR2t4bGRDZHpJRVZ1WTNKNWNIUWdRWFYwYUc5eWFYUjVJRmd6TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBbk5NTThGcmxMa2UzY2wwM2c3Tm9ZekRxMXpVbUdTWGh2YjQxOFhDU0w3ZTRTMEVGCnE2bWVOUWhZN0xFcXhHaUhDNlBqZGVUbTg2ZGljYnA1Z1dBZjE1R2FuL1BRZUdkeHlHa09sWkhQL3VhWjZXQTgKU014K3lrMTNFaVNkUnh0YTY3bnNIamNBSEp5c2U2Y0Y2czVLNjcxQjVUYVl1Y3Y5YlR5V2FOOGpLa0tRRElaMApaOGgvcFpxNFVtRVVFejlsNllLSHk5djZEbGIyaG9uemhUK1hocSt3M0JydmF3MlZGbjNFSzZCbHNwa0VObldBCmE2eEs4eHVRU1hndm9wWlBLaUFsS1FUR2RNRFFNYzJQTVRpVkZycW9NN2hEOGJFZnd6Qi9vbmt4RXowdE52amoKL1BJemFyazVNY1d2eEkwTkhXUVdNNnI2aENtMjFBdkEySDNEa3dJREFRQUJvNElCZlRDQ0FYa3dFZ1lEVlIwVApBUUgvQkFnd0JnRUIvd0lCQURBT0JnTlZIUThCQWY4RUJBTUNBWVl3ZndZSUt3WUJCUVVIQVFFRWN6QnhNRElHCkNDc0dBUVVGQnpBQmhpWm9kSFJ3T2k4dmFYTnlaeTUwY25WemRHbGtMbTlqYzNBdWFXUmxiblJ5ZFhOMExtTnYKYlRBN0JnZ3JCZ0VGQlFjd0FvWXZhSFIwY0RvdkwyRndjSE11YVdSbGJuUnlkWE4wTG1OdmJTOXliMjkwY3k5awpjM1J5YjI5MFkyRjRNeTV3TjJNd0h3WURWUjBqQkJnd0ZvQVV4S2V4cEhzc2NmcmI0VXVRZGYvRUZXQ0ZpUkF3ClZBWURWUjBnQkUwd1N6QUlCZ1puZ1F3QkFnRXdQd1lMS3dZQkJBR0MzeE1CQVFFd01EQXVCZ2dyQmdFRkJRY0MKQVJZaWFIUjBjRG92TDJOd2N5NXliMjkwTFhneExteGxkSE5sYm1OeWVYQjBMbTl5WnpBOEJnTlZIUjhFTlRBegpNREdnTDZBdGhpdG9kSFJ3T2k4dlkzSnNMbWxrWlc1MGNuVnpkQzVqYjIwdlJGTlVVazlQVkVOQldETkRVa3d1ClkzSnNNQjBHQTFVZERnUVdCQlNvU21wakJIM2R1dWJST2JlbVJXWHY4Nmpzb1RBTkJna3Foa2lHOXcwQkFRc0YKQUFPQ0FRRUEzVFBYRWZOaldEamRHQlg3Q1ZXK2RsYTVjRWlsYVVjbmU4SWtDSkx4V2g5S0VpazNKSFJSSEdKbwp1TTJWY0dmbDk2UzhUaWhSelp2b3JvZWQ2dGk2V3FFQm10enczV29kYXRnK1Z5T2VwaDRFWXByLzF3WEt0eDgvCndBcEl2SlN3dG1WaTRNRlU1YU1xclNERTZlYTczTWoydGNNeW81ak1kNmptZVdVSEs4c28vam9XVW9IT1Vnd3UKWDRQbzFRWXorM2RzemtEcU1wNGZrbHhCd1hSc1cxMEtYelBNVForc09QQXZleXhpbmRtamtXOGxHeStRc1JsRwpQZlorRzZaNmg3bWplbTBZK2lXbGtZY1Y0UElXTDFpd0JpOHNhQ2JHUzVqTjJwOE0rWCtRN1VOS0VrUk9iM042CktPcWtxbTU3VEgySDNlREpBa1NuaDYvRE5GdTBRZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBNWNqcDlqOEpIbmc4MGJ6UFFZcERLeDNrRDJQNTBudEtEQlUvVWdKbDlFSXdVNUNnCmdNdVE2ZHVqTTVDRzQ4SXhsRFZBeUN4ZGhycVBvUmJpYkM0cVJWMDVTWmhVZU8xa0VZTWRBaEdaYk1MVFpKT3UKNlByUXJUYVRvMklkUHAweFdmdW1Fd0pSRG1qVE56bmhzRkk5d240T0VsaVJua1pKcWYvNkdFQ0llU1ZLL2VqQQpnTm9nY3UzUEk5dlBPSWVNUDZ1VkdzMFlrRWw4K3lJQnRseVRnbjlFanNtK2VTT2E1eVZVeHhsUnhlTXFDK09RCklkdnR4S0l5cUZ3a3V6dzgreFhOOWdSVXVsb25yYXBhM0UrUmV2OGZPcEs2dElTYVBQNGxET0tZbWl1cnpKVXMKTW94VkFEc1d4c0RaK0YzejhsVjNWNWoyc3I2dk9NYlUwSDFtK1FJREFRQUJBb0lCQUZ4T3JLWHVScVNGMnJESwpyMXQ5eG1QUXV5ZnZtcEVTVS9tc28yWTNibXVFRjFQS2VwK2lweEU2MlVIQ29sMW1TbkptUGlMcnA1cVM0Vlh1CkVvRXd2bXhrK2JsMXh5RlpBK1VCRGFzaUZNY2JNTDVya1Uwb1RLSDRsYkNCbm92anE4cWhDK01CQUR6UW9XREQKRU1XN0UvSkluekNCZ2VYYUNJZVJQQTk0QlJyY3ZFTWU3emxXR3ovYU1KeVVoTmFSL0RQK2lpKytJWjZVeVIvSgpSMDNYOG4wREo4UTBiMitIcWdyS01GYjBua1dCL1hhR0hhOEVUZGZXbjQvK2szYnVvNkpveDF0bzdSVmxnUXlXCkpKeW5kOWphNWFweE9vNlVCaGxGQTlpWkx6WkNoYWFpYlRwVFJOM2hvMUQ1YVkrcDdycmd6blA5OU5vSUxsMnYKMFgvcVI0RUNnWUVBNTRIci9qUjlCMmVLSGhVY0hmV1JOQ1ZkOVpoaWFVSmsvc3doRVZpdHNvekJpSkR5UURkSwpidlpXU3h5V3hLV1dDNUs3Mlg4UGNRWXRKTUxTTlJBQmpEV3BHU05BRnh2ZEtGVDJEc3FodzVIQ3RPT0E2MG9JCnBIeEpXampJMFhGMWhUaWJpLzNIb0tOaElnYXFINmp3UlVnbktERjlLVjc1Zm1ZNGpZandBVkVDZ1lFQS9oaFYKMkhuTXp6MmwxQ3cxK0NoSUg3NVQ1eWJ1ZlBkMmhOayt1N0RNMnF0Q2hvYTdkbnA5STdXNWJobzFWUGc4aFV4TgpsZmppVzR1YlRkV3dCU1RZTTZkaU5QUG5HSTd2SWJxcmw2VVZCS200NVNpckdOeTBhUHpDZVA4TStUYVBsalRXCkRDd3E2M3hjaTZpZU52MGo3c2FvSjlaVy9pR2lQVUsxZmpGVjRTa0NnWUJkRXRLNkJJZ3ZyZVROYTFjK2hEZTQKYXoxM082aDFBUWh4bDhmRG5ZOVh0VmNwZkh5b2JKSTBRajAzUFdzdjdCS0MzSjlCTmVBVFpKUkpyem1yczUrcgpxdmNzOEFzWVAwK09vM201UUtZQVpsMk5NOW5rdm9MeS9qVFBYUHovbDBuVUlZb0hvaVBiNVZOcnhwb20yRmlnCndmMWNIMmxlZEp5QndMOER5QVlWd1FLQmdHWGRHYVVrQnhCWjFYMytqMUJCemRBeisremg5Wi9Sa1FqbkVyZ3AKdzZZeUhBUlVSUmpWT0ErMXpYV3ZPZ3dyVEEvZ0xBWmdkVlpmM0UzU3liTDJOMXBWMHhBSmEyNno5bmZlSHVZMwpQdnJVazVRQ3ZyekQxZXQwMFAyeXVkKzZtTXVOdVBXK1N5S0dnNDlWZEwvMHNaQUt3ZVRlajVkbm9tUE90M1cwCmo0b3BBb0dBWGhPMUoyZVZ2bmFYOERrVUhidWdGc2NmQWRZSWowajVZcmlobks3eEJLS0FCSFh5cUNtN0JUMEwKOGZySWxnNm1IYllHTzRuZHJBTC96bEgrKzBzbTljTmdkYUZaZnJYbHBoQUpaY0hIcC82Ylh3WkI1MURQaGtObgplSkZTSDA1TUNQai83SWpML09MY2hTRFpGYXcwZkhCL2lJdVpEOERRaSt6N2Q3Q2FadWc9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  annotations:
    certmanager.k8s.io/alt-names: '*.harbor2.my.domain,harbor2.my.domain'
    certmanager.k8s.io/certificate-name: harbor2-cert
    certmanager.k8s.io/common-name: harbor2.my.domain
    certmanager.k8s.io/ip-sans: ""
    certmanager.k8s.io/issuer-kind: ClusterIssuer
    certmanager.k8s.io/issuer-name: letsencrypt-prod
  creationTimestamp: "2019-09-24T12:49:45Z"
  labels:
    certmanager.k8s.io/certificate-name: harbor2-cert
  name: harbor2-secret
  namespace: harbor-system
  resourceVersion: "202770"
  selfLink: /api/v1/namespaces/harbor-system/secrets/harbor2-secret
  uid: c93c4619-dec9-11e9-a776-066b56920064
type: kubernetes.io/tls
```

```
$ kubectl describe pod harbor2-harbor-notary-server-69894778d-bztnr
Name:           harbor2-harbor-notary-server-69894778d-bztnr
Namespace:      harbor-system
Priority:       0
Node:           ip-10-64-89-132.eu-west-1.compute.internal/10.64.89.132
Start Time:     Tue, 24 Sep 2019 15:13:38 +0100
Labels:         app=harbor
                chart=harbor
                component=notary-server
                heritage=Tiller
                pod-template-hash=69894778d
                release=harbor2
Annotations:    checksum/secret: f9a13eabc88ef2866ca99a7306e84015f3d2a4f21d963005e29a5281fc15d6c6
                checksum/secret-core: 10d434e6335b885be3d51bad19e53cee2ac6616c19db92cc42d4871ac192ea16
                kubernetes.io/psp: eks.privileged
Status:         Running
IP:             10.64.84.3
Controlled By:  ReplicaSet/harbor2-harbor-notary-server-69894778d
Containers:
  notary-server:
    Container ID:   docker://6dd25630b4ad8f71e885ce168de6fed012878621d049e916f60000e73ee3c7d9
    Image:          goharbor/notary-server-photon:v0.6.1-v1.9.0
    Image ID:       docker-pullable://goharbor/notary-server-photon@sha256:0801efaf39f0b7a6c9bae3eea70fe1b9db2f1d6d4efafbc5356eb4d11fb43109
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 24 Sep 2019 15:30:37 +0100
      Finished:     Tue, 24 Sep 2019 15:30:37 +0100
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 24 Sep 2019 15:25:24 +0100
      Finished:     Tue, 24 Sep 2019 15:25:24 +0100
    Ready:          False
    Restart Count:  8
    Environment:
      MIGRATIONS_PATH:  migrations/server/postgresql
      DB_URL:           postgres://postgres:changeit@harbor2-harbor-database:5432/notaryserver?sslmode=disable
    Mounts:
      /etc/notary/server-config.postgres.json from config (rw,path="server.json")
      /etc/ssl/notary/ca.crt from signer-certificate (rw,path="ca.crt")
      /root.crt from token-service-certificate (rw,path="tls.crt")
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-zjscx (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  harbor2-harbor-notary-server
    Optional:    false
  token-service-certificate:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  harbor2-harbor-core
    Optional:    false
  signer-certificate:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  harbor2-harbor-notary-server
    Optional:    false
  default-token-zjscx:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-zjscx
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                  From                                                 Message
  ----     ------     ----                 ----                                                 -------
  Normal   Scheduled  17m                  default-scheduler                                    Successfully assigned harbor-system/harbor2-harbor-notary-server-69894778d-bztnr to ip-10-64-89-132.eu-west-1.compute.internal
  Normal   Pulled     14m (x5 over 16m)    kubelet, ip-10-64-89-132.eu-west-1.compute.internal  Container image "goharbor/notary-server-photon:v0.6.1-v1.9.0" already present on machine
  Normal   Created    14m (x5 over 16m)    kubelet, ip-10-64-89-132.eu-west-1.compute.internal  Created container notary-server
  Normal   Started    14m (x5 over 16m)    kubelet, ip-10-64-89-132.eu-west-1.compute.internal  Started container notary-server
  Warning  BackOff    114s (x71 over 16m)  kubelet, ip-10-64-89-132.eu-west-1.compute.internal  Back-off restarting failed container
```

**Comment by ywk253100** [comment]
The `expose.tls.secretName` is used for nginx to serve with HTTPS, not for notary and registry. If you want to use your own certificate for notary and registry, you need to set `core.secretName` and `notary. secretName`, or the certificates will be generated automatically

**Comment by mattcamp** [comment]
> The `expose.tls.secretName` is used for nginx to serve with HTTPS, not for notary and registry. If you want to use your own certificate for notary and registry, you need to set `core.secretName` and `notary. secretName`, or the certificates will be generated automatically

Right, that fits with my original understanding of how things fit together.

So assuming I'm not setting `core.secretName` and `notary.secretName` (which I'm not) then why are both services complaining with the error `token auth requires at least one token signing root certificate`? 

I would expect those token signing certs to be auto generated and loaded.
