### ISSUE TITLE
Updating 1.7.4 to 1.9.0 migrate failing on conversion - SOLVED

### ISSUE THREAD

**Issue by andrewjkrull** [goharbor/harbor#9315]
Good day. I am working on upgrading from 1.7.4 to 1.9.0. I have cleaned up my .cfg file to remove all comments and blank lines. I am running the following:

```docker run -it --rm -v /opt/harbor-20190930/harbor.cfg:/harbor-migration/harbor-cfg/harbor.cfg -v /opt/harbor/harbor.yml:/harbor-migration/harbor-cfg-out/harbor.yml goharbor/harbor-migrator:v1.9.0 --cfg up```

this yields:
```Please backup before upgrade, 
Enter y to continue updating or n to abort: y
Command for config file migration: python ./cfg/run.py --input /harbor-migration/harbor-cfg/harbor.cfg --output /harbor-migration/harbor-cfg-out/harbor.yml
Traceback (most recent call last):
  File "./cfg/run.py", line 70, in <module>
    main()
  File "./cfg/run.py", line 24, in main
    input_version = utils.get_conf_version(args.input_path)
  File "/harbor-migration/cfg/utils.py", line 41, in get_conf_version
    return d["_version"]
TypeError: string indices must be integers, not str
[root@host01 harbor]# cat ../harbor-20190930/harbor.cfg 
```

Couple of lines for the .cfg file:

```# cat ../harbor-20190930/harbor.cfg 
_version = 1.7.0
email_password = 
ldap_search_pwd = <something_secret>
clair_db_password = <something_secret>
db_password = <something_secret>
harbor_admin_password = <something_secret>
redis_password = 
uaa_clientsecret = 
...
```

I am not sure what I need to do differently/fix to make this work.

**Comment by andrewjkrull** [comment]
So we got around this with adding the following to the top of the config file:

```[configuration]
_version = 1.7.0
...```

After that we ran into an issue with clair and used the following to get past that:

```https://hub.docker.com/r/thatsk/harbor-migrator/tags```

Using the above we have successfully upgraded from 1.7.4 to 1.9.0 (fingers crossed)
