### ISSUE TITLE
KeyError: 'location' upgrading from 1.8.0 to 1.9.0

### ISSUE THREAD

**Issue by Strum355** [goharbor/harbor#9335]
After running migrator from [here](https://github.com/goharbor/harbor/issues/9174#issuecomment-535889677) (couldn't use official migrator because of [this](https://github.com/goharbor/harbor/issues/9174) still unresolved bug)

harbor.yml:
```
# Log configurations
log:
  # options are debug, info, warning, error, fatal
  level: info
  # configs for logs in local storage
  local:
    # Log files are rotated log_rotate_count times before being removed. If count is 0, old versions are removed rather than rotated.
    rotate_count: 50
    # Log files are rotated only if they grow bigger than log_rotate_size bytes. If size is followed by k, the size is assumed to be in kilobytes.
    # If the M is used, the size is in megabytes, and if G is used, the size is in gigabytes. So size 100, size 100k, size 100M and size 100G
    # are all valid.
    rotate_size: 200M
    # The directory on your host that store log
    location: /var/log/harbor

    # Uncomment following lines to enable external syslog endpoint.
    # external_endpoint:
    #   # protocol used to transmit log to external endpoint, options is tcp or udp
    #   protocol: tcp
    #   # The host of external endpoint
    #   host: localhost
    #   # Port of external endpoint
    #   port: 5140
```

```
[Step 0]: checking installation environment ...

Note: docker version: 19.03.2

Note: docker-compose version: 1.24.1


[Step 1]: preparing environment ...
prepare base dir is set to /netsoc/harbor
Clearing the configuration file: /config/jobservice/config.yml
Clearing the configuration file: /config/jobservice/env
Clearing the configuration file: /config/log/logrotate.conf
Clearing the configuration file: /config/nginx/nginx.conf
Clearing the configuration file: /config/registry/config.yml
Clearing the configuration file: /config/registry/root.crt
Clearing the configuration file: /config/core/env
Clearing the configuration file: /config/core/app.conf
Clearing the configuration file: /config/registryctl/config.yml
Clearing the configuration file: /config/registryctl/env
Clearing the configuration file: /config/db/env
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 31, in main
    config_dict = parse_yaml_config(conf)
  File "/usr/src/app/utils/configs.py", line 186, in parse_yaml_config
    config_dict['log_location'] = log_configs["location"]
KeyError: 'location'
```

**Comment by Strum355** [comment]
`./prepare` was still the old version and was trying to run a 1.8.x image, my bad :)

**Comment by LotteO** [comment]
I get a similar issue while installing harbor 1.8.3.  How can I check if I have the correct ./prepare script and am running the right image?
