### ISSUE TITLE
Harbor 1.9.0 install.sh fail

### ISSUE THREAD

**Issue by thatsk** [goharbor/harbor#9399]
What can we help you?

```BASH
./install.sh --with-notary --with-clair --with-chartmuseum

[Step 0]: checking installation environment ...

Note: docker version: 19.03.3

Note: docker-compose version: 1.24.1


[Step 1]: preparing environment ...
prepare base dir is set to /opt/harbor
Clearing the configuration file: /config/log/logrotate.conf
Clearing the configuration file: /config/log/rsyslog_docker.conf
Clearing the configuration file: /config/nginx/nginx.conf
Clearing the configuration file: /config/core/env
Clearing the configuration file: /config/core/app.conf
Generated configuration file: /config/log/logrotate.conf
Generated configuration file: /config/log/rsyslog_docker.conf
Generated configuration file: /config/nginx/nginx.conf
Generated configuration file: /config/core/env
Generated configuration file: /config/core/app.conf
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 38, in main
    prepare_registry(config_dict)
  File "/usr/src/app/utils/registry.py", line 22, in prepare_registry
    prepare_dir(registry_data_dir, uid=DEFAULT_UID, gid=DEFAULT_GID)
  File "/usr/src/app/utils/misc.py", line 93, in prepare_dir
    absolute_path.chmod(mode)
  File "/usr/lib/python3.6/pathlib.py", line 1264, in chmod
    self._accessor.chmod(self, mode)
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
PermissionError: [Errno 13] Permission denied: '/data/registry'
```

**Comment by thatsk** [comment]
The registry folder is on shared drive not sure is this issue but even if nfs shared folder has 777 permission why its showing permission denied.
```BASH
 df -Th
Filesystem                         Type      Size  Used Avail Use% Mounted on
/dev/mapper/vg-lv_root        xfs        60G  5.6G   54G  10% /
devtmpfs                           devtmpfs  3.9G     0  3.9G   0% /dev
tmpfs                              tmpfs     3.9G   12K  3.9G   1% /dev/shm
tmpfs                              tmpfs     3.9G  8.9M  3.9G   1% /run
tmpfs                              tmpfs     3.9G     0  3.9G   0% /sys/fs/cgroup
tmpfs                              tmpfs     2.0G     0  2.0G   0% /tmp
/dev/sda1                          ext3      488M  116M  347M  26% /boot
/dev/mapper/vg-lv_home        xfs        16G   33M   16G   1% /home
tmpfs                              tmpfs     783M     0  783M   0% /run/user/0
10.170.111.202:/INFRA/registry nfs       669T  345T  311T  53% /data/registry
```
```BASH
ls -ld /data/registry/
drwxrwxrwx 3 10000 10000 24 Oct 14 06:15 /data/registry/
```

**Comment by footlegger** [comment]
In my case it was  showing permission denied because the /data/registry directory was a symbolic link. I had to mount a physical block device on that folder in order to make it work properly.
