### ISSUE TITLE
Harbor upgrade from 1.8.0 to 1.9.0 error

### ISSUE THREAD

**Issue by yke007** [goharbor/harbor#9408]
What can we help you?
The path of the migrated harbor.cfg is not set, the input file will be overwritten.
Command for config file migration: python ./cfg/run.py --input /harbor-migration/harbor-cfg/harbor.yml
input version: 1.8.0, migrator chain: ['1.9.0']
migrating to version 1.9.0
Traceback (most recent call last):
  File "./cfg/run.py", line 70, in <module>
    main()
  File "./cfg/run.py", line 46, in main
    m.migrate(curr_input_path, curr_output_path)
  File "/harbor-migration/cfg/migrator_1_9_0/__init__.py", line 21, in migrate
    f.write(tpl.render(**config_dict))
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/harbor-migration/cfg/migrator_1_9_0/harbor.yml.jinja", line 8, in top-level template code
    {% if http %}
jinja2.exceptions.UndefinedError: 'http' is undefined

**Comment by ninjadq** [comment]
You should set http in your config

**Comment by reasonerjt** [comment]
Will be fixed by #9800
