### ISSUE TITLE
Non-root permission installation failed

### ISSUE THREAD

**Issue by xuexiaoao** [goharbor/harbor#9728]
### I failed to install version 1.9  offline.My account does not have root privileges. How do I install it?
Error message is:
```shell
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 124, in perform_command
  File "compose/cli/command.py", line 64, in project_from_options
  File "compose/cli/command.py", line 139, in get_project
  File "compose/config/config.py", line 404, in load
  File "compose/config/config.py", line 504, in load_services
  File "compose/config/config.py", line 483, in build_services
  File "compose/config/config.py", line 483, in <listcomp>
  File "compose/config/config.py", line 475, in build_service
  File "compose/config/config.py", line 881, in finalize_service
  File "compose/config/config.py", line 681, in resolve_environment
  File "compose/config/environment.py", line 43, in env_vars_from_file
  File "/code/.tox/py37/lib/python3.7/codecs.py", line 904, in open
PermissionError: [Errno 13] Permission denied: '/centos/harbor/common/config/registryctl/env'
```
File permissions is:
```shell
$ ls -alh
total 0
drwxr-xr-x 9 root  root  105 Nov  2 16:16 .
drwxr-xr-x 3 root  root   20 Nov  2 16:16 ..
drwxr-xr-x 3 root  root   53 Nov  2 16:16 core
drwxr-xr-x 2 root  root   17 Nov  2 16:16 db
drwxr-xr-x 2 10000 10000  35 Nov  2 16:16 jobservice
drwxr-xr-x 2 root  root   55 Nov  2 16:16 log
drwxr-xr-x 3 root  root   38 Nov  2 16:16 nginx
drwxr-xr-x 2 root  root   24 Nov  2 16:16 registry
drwxr-xr-x 2 root  root   35 Nov  2 16:16 registryctl

[ registryctl]$ ls -alh
total 8.0K
drwxr-xr-x 2 root root  35 Nov  2 16:16 .
drwxr-xr-x 9 root root 105 Nov  2 16:16 ..
-rw-r--r-- 1 root root 108 Nov  2 16:16 config.yml
-rw-r----- 1 root root  64 Nov  2 16:16 env
```

**Comment by tvvignesh** [comment]
I have the same problem as well. Executing with root permissions worked though.

**Comment by ferrandpaul** [comment]
Hello, I have exactly the same issue, 
[Step 5]: starting Harbor ...
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 125, in perform_command
  File "compose/cli/command.py", line 65, in project_from_options
  File "compose/cli/command.py", line 141, in get_project
  File "compose/config/config.py", line 411, in load
  File "compose/config/config.py", line 511, in load_services
  File "compose/config/config.py", line 490, in build_services
  File "compose/config/config.py", line 490, in <listcomp>
  File "compose/config/config.py", line 482, in build_service
  File "compose/config/config.py", line 888, in finalize_service
  File "compose/config/config.py", line 688, in resolve_environment
  File "compose/config/environment.py", line 43, in env_vars_from_file
  File "/code/.tox/py37/lib/python3.7/codecs.py", line 904, in open
PermissionError: [Errno 13] Permission denied: '/prod/vq/K8S/data/harbor/harbor/common/config/registryctl/env'
[24952] Failed to execute script docker-compose

The problem is coming from the prepare script, it is executed via a docker run command.

Could you find a solution so that we can install it (or simply upgrade the configuration) without being root (I don't and I won't have these kind of access for security reasons)

Thanks a lot

**Comment by xuexiaoao** [comment]
Sorry, there is no other solution, I ended up using root

ferrandpaul <notifications@github.com> 于2020年3月25日周三 下午3:47写道：

**Comment by lhz123** [comment]
This problem is mainly due to insufficient permissions，When installing harbor, just execute the following command：sudo ./install.sh

**Comment by lhz123** [comment]
> Hello, I have exactly the same issue,
> [Step 5]: starting Harbor ...
> Traceback (most recent call last):
> File "bin/docker-compose", line 6, in
> File "compose/cli/main.py", line 72, in main
> File "compose/cli/main.py", line 125, in perform_command
> File "compose/cli/command.py", line 65, in project_from_options
> File "compose/cli/command.py", line 141, in get_project
> File "compose/config/config.py", line 411, in load
> File "compose/config/config.py", line 511, in load_services
> File "compose/config/config.py", line 490, in build_services
> File "compose/config/config.py", line 490, in
> File "compose/config/config.py", line 482, in build_service
> File "compose/config/config.py", line 888, in finalize_service
> File "compose/config/config.py", line 688, in resolve_environment
> File "compose/config/environment.py", line 43, in env_vars_from_file
> File "/code/.tox/py37/lib/python3.7/codecs.py", line 904, in open
> PermissionError: [Errno 13] Permission denied: '/prod/vq/K8S/data/harbor/harbor/common/config/registryctl/env'
> [24952] Failed to execute script docker-compose
> 
> The problem is coming from the prepare script, it is executed via a docker run command.
> 
> Could you find a solution so that we can install it (or simply upgrade the configuration) without being root (I don't and I won't have these kind of access for security reasons)
> 
> Thanks a lot

Zhège wèntí zhǔyào shi quánxiàn bùgòu. Ānzhuāng harbor shí, zhíxíng yǐxià mìnglìng jiù kěyǐle
32 / 5000
翻译结果
This problem is mainly insufficient permissions. When installing harbor, just execute the following command:sudo ./install.sh

**Comment by lhz123** [comment]
> Hello, I have exactly the same issue,
> [Step 5]: starting Harbor ...
> Traceback (most recent call last):
> File "bin/docker-compose", line 6, in
> File "compose/cli/main.py", line 72, in main
> File "compose/cli/main.py", line 125, in perform_command
> File "compose/cli/command.py", line 65, in project_from_options
> File "compose/cli/command.py", line 141, in get_project
> File "compose/config/config.py", line 411, in load
> File "compose/config/config.py", line 511, in load_services
> File "compose/config/config.py", line 490, in build_services
> File "compose/config/config.py", line 490, in
> File "compose/config/config.py", line 482, in build_service
> File "compose/config/config.py", line 888, in finalize_service
> File "compose/config/config.py", line 688, in resolve_environment
> File "compose/config/environment.py", line 43, in env_vars_from_file
> File "/code/.tox/py37/lib/python3.7/codecs.py", line 904, in open
> PermissionError: [Errno 13] Permission denied: '/prod/vq/K8S/data/harbor/harbor/common/config/registryctl/env'
> [24952] Failed to execute script docker-compose
> 
> The problem is coming from the prepare script, it is executed via a docker run command.
> 
> Could you find a solution so that we can install it (or simply upgrade the configuration) without being root (I don't and I won't have these kind of access for security reasons)
> 
> Thanks a lot

This problem is mainly insufficient permissions. When installing harbor, just execute the following command:sudo ./install.sh
