### ISSUE TITLE
Failed to upgrade from V1.5 to V1.6, for the db password 

### ISSUE THREAD

**Issue by okgoba** [goharbor/harbor#9978]
docker run -it --rm -e DB_USR=root -e DB_PWD=Sh3m%oMk  -v /app/harbor_1.5/data/database/:/var/lib/mysql -v /app/harbor_1.5/harbor.cfg:/harbor-migration/harbor-cfg/harbor.cfg -v /app/cfg_bak:/harbor-migration/backup goharbor/harbor-migrator:v1.6.3 up 
Please backup before upgrade, 
Enter y to continue updating or n to abort: y
Trying to start mysql server...
Waiting for MySQL start...
2019-11-24 14:46:06 139747037935552 [Note] mysqld (mysqld 10.2.14-MariaDB) starting as process 13 ...
2019-11-24 14:46:06 139747037935552 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2019-11-24 14:46:06 139747037935552 [Note] InnoDB: Uses event mutexes
2019-11-24 14:46:06 139747037935552 [Note] InnoDB: Compressed tables use zlib 1.2.8
2019-11-24 14:46:06 139747037935552 [Note] InnoDB: Number of pools: 1
2019-11-24 14:46:06 139747037935552 [Note] InnoDB: Using generic crc32 instructions
2019-11-24 14:46:06 139747037935552 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
2019-11-24 14:46:06 139747037935552 [Note] InnoDB: Completed initialization of buffer pool
2019-11-24 14:46:06 139745778706176 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2019-11-24 14:46:06 139747037935552 [Note] InnoDB: Highest supported file format is Barracuda.
2019-11-24 14:46:06 139747037935552 [Note] InnoDB: Starting crash recovery from checkpoint LSN=876346689
2019-11-24 14:46:06 139747037935552 [Note] InnoDB: 128 out of 128 rollback segments are active.
2019-11-24 14:46:06 139747037935552 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2019-11-24 14:46:06 139747037935552 [Note] InnoDB: Creating shared tablespace for temporary tables
2019-11-24 14:46:06 139747037935552 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2019-11-24 14:46:06 139747037935552 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2019-11-24 14:46:06 139747037935552 [Note] InnoDB: Waiting for purge to start
2019-11-24 14:46:06 139747037935552 [Note] InnoDB: 5.7.21 started; log sequence number 876346698
2019-11-24 14:46:06 139744998577920 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2019-11-24 14:46:06 139747037935552 [Note] Plugin 'FEEDBACK' is disabled.
2019-11-24 14:46:06 139747037935552 [Note] Recovering after a crash using tc.log
2019-11-24 14:46:06 139747037935552 [Note] Starting crash recovery...
2019-11-24 14:46:06 139747037935552 [Note] Crash recovery finished.
2019-11-24 14:46:06 139747037935552 [Note] Server socket created on IP: '::'.
2019-11-24 14:46:06 139747037935552 [Note] Reading of all Master_info entries succeded
2019-11-24 14:46:06 139747037935552 [Note] Added new Master_info '' to hash table
2019-11-24 14:46:06 139747037935552 [Note] mysqld: ready for connections.
Version: '10.2.14-MariaDB'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  Source distribution
2019-11-24 14:46:06 139744998577920 [Note] InnoDB: Buffer pool(s) load completed at 191124 14:46:06
Version is not specified. Default version is head.
No directory, logging in with HOME=/
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locales
  COLLATE:  en_US.UTF-8
  CTYPE:    en_US.UTF-8
  MESSAGES: C
  MONETARY: C
  NUMERIC:  C
  TIME:     C
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

No directory, logging in with HOME=/
waiting for server to start....LOG:  database system was shut down at 2019-11-24 14:46:08 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  autovacuum launcher started
LOG:  database system is ready to accept connections
 done
server started
ALTER ROLE

./db/run.sh: ignoring /docker-entrypoint-initdb.d/*

PostgreSQL init process complete; ready for start up.

Performing upgrade 1.5.0...
Traceback (most recent call last):
  File "/usr/bin/alembic", line 9, in <module>
    load_entry_point('alembic==1.0.5', 'console_scripts', 'alembic')()
  File "/usr/lib/python2.7/site-packages/alembic/config.py", line 503, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/lib/python2.7/site-packages/alembic/config.py", line 497, in main
    self.run_cmd(cfg, options)
  File "/usr/lib/python2.7/site-packages/alembic/config.py", line 480, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/usr/lib/python2.7/site-packages/alembic/command.py", line 469, in current
    script.run_env()
  File "/usr/lib/python2.7/site-packages/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/lib/python2.7/site-packages/alembic/util/compat.py", line 198, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "/harbor-migration/db/alembic/mysql/migration_harbor/env.py", line 85, in <module>
    run_migrations_online()
  File "/harbor-migration/db/alembic/mysql/migration_harbor/env.py", line 69, in run_migrations_online
    config.get_section(config.config_ini_section),
  File "/usr/lib/python2.7/site-packages/alembic/config.py", line 217, in get_section
    return dict(self.file_config.items(name))
  File "/usr/lib/python2.7/ConfigParser.py", line 655, in items
    for option in options]
  File "/usr/lib/python2.7/ConfigParser.py", line 691, in _interpolate
    self._interpolate_some(option, L, rawval, section, vars, 1)
  File "/usr/lib/python2.7/ConfigParser.py", line 732, in _interpolate_some
    "'%%' must be followed by '%%' or '(', found: %r" % (rest,))
ConfigParser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%oMk@localhost:3306/registry?unix_socket=/var/run/mysqld/mysqld.sock'

How can I make the password correct? or how can i change the mysql password in V1.5? tks!

**Comment by okgoba** [comment]
Solved
